export const verifiedAt = "2026-08-24";

export const sourceRows = [
  ["src-springfield", "Springfield Museums - hours and admission", "official", "https://springfieldmuseums.org/hours-and-admission/", ["Sunday hours", "five-museum ticket", "adult admission"]],
  ["src-armory", "National Park Service - Springfield Armory hours", "government", "https://www.nps.gov/spar/planyourvisit/hours.htm", ["Sunday operation", "free access", "visitor hours"]],
  ["src-cohoes", "City of Cohoes - Falls View Park", "government", "https://www.cohoes-ny.gov/314/Overlook-Park-Falls-View-Park", ["seasonal hours", "legal overlooks", "riverbed prohibition"]],
  ["src-oakwood", "Oakwood Cemetery Troy - visitor policies and history", "official", "https://www.oakwoodcemetery.org/general-policies", ["daily grounds hours", "active-cemetery etiquette", "visitor rules"]],
  ["src-saratoga-auto", "Saratoga Automobile Museum - plan your visit", "official", "https://www.saratogaautomuseum.org/plan-your-visit", ["October Monday hours", "adult admission", "parking and exhibit-change warning"]],
  ["src-boxing", "International Boxing Hall of Fame - plan your visit", "official", "https://boxhall.wixsite.com/ibhof/plan-your-visit", ["Tuesday hours", "adult admission", "museum location"]],
  ["src-chittenango", "New York State Parks - Chittenango Falls", "government", "https://parks.ny.gov/parks/chittenangofalls/getting-there.aspx", ["sunrise-sunset access", "167-foot waterfall", "trail lengths and seasonal fees"]],
  ["src-anthony", "National Susan B. Anthony Museum & House - visit", "official", "https://susanb.org/hours-admissions-directions/", ["Wednesday hours", "docent-led format", "adult admission"]],
  ["src-mount-hope", "City of Rochester - Mount Hope Cemetery", "government", "https://www.cityofrochester.gov/locations/mount-hope-cemetery", ["seasonal daily hours", "Victorian cemetery history", "Douglass and Anthony graves"]],
  ["src-rmsc", "Rochester Museum & Science Center - hours and admission", "official", "https://rmsc.org/museum-science-center/hours-admission/", ["Wednesday hours", "adult admission", "school-year schedule"]],
  ["src-rmsc-tesla", "RMSC - Electricity Theater", "official", "https://rmsc.org/exhibits/electricity-theater/", ["twin six-foot Tesla coils", "show format", "included admission"]],
  ["src-kazoo", "Original American Kazoo Company", "official", "https://www.edenkazoo.com/", ["Thursday factory operation", "self-guided tour", "make-a-kazoo experience"]],
  ["src-trec", "Pennsylvania DCNR - Tom Ridge Environmental Center", "government", "https://www.pa.gov/agencies/dcnr/recreation/where-to-go/state-parks/find-a-park/presque-isle-state-park/trec", ["October daily hours", "free exhibits", "observation tower"]],
  ["src-erie-maritime", "Erie Maritime Museum - visit", "official", "https://www.eriemaritimemuseum.org/admission", ["museum access", "paid admission", "exact-date confirmation requirement"]],
  ["src-rockhall", "Rock & Roll Hall of Fame - visit", "official", "https://rockhall.com/visit/embed/", ["Friday hours", "adult admission", "visitor planning"]],
  ["src-christmas", "A Christmas Story House - hours and admission", "official", "https://housefromachristmasstory.com/hours-and-admission/", ["daily hours", "guided duration", "ticketing"]],
  ["src-buckland", "Buckland Museum - plan your visit", "official", "https://bucklandmuseum.org/plan-your-visit/", ["admission", "45-minute average visit", "200-plus artifacts"]],
  ["src-sugar", "AEG Presents - Sugar at the Agora", "official-ticketing", "https://cleveland.aegpresents.com/events/detail/?event_id=1300881", ["October 9 2026 date", "7pm doors", "8pm all-ages show"]],
  ["src-crawford", "Western Reserve Historical Society - Cleveland History Center", "official", "https://www.wrhs.org/plan-visit/places-to-visit/cleveland-history-center", ["Friday hours", "Crawford collection", "admission"]],
  ["src-cma", "Cleveland Museum of Art - plan your visit", "official", "https://www.clevelandart.org/plan-your-visit", ["Saturday hours", "free general admission", "visitor access"]],
  ["src-lakeview", "Lake View Cemetery - visitor information", "official", "https://www.lakeviewcemetery.com/", ["public historic landscape", "active-cemetery context", "same-day gate confirmation"]],
  ["src-haserot", "Cleveland Historical - Lake View and Haserot Angel", "university-local-history", "https://clevelandhistorical.org/items/show/76", ["Angel identification", "garden-cemetery history", "visitor context"]],
  ["src-all-saints", "All Saints Greek Orthodox Church Canonsburg", "official-parish", "https://www.allsaintscbg.org/", ["canonical parish", "address", "2026 bulletin and contact channel"]],
  ["src-goarch-pittsburgh", "Greek Orthodox Metropolis of Pittsburgh - communities", "canonical-directory", "https://www.pittsburgh.goarch.org/communities", ["canonical jurisdiction", "Canonsburg parish listing"]],
  ["src-coffee-pot", "VisitPA - Koontz Coffee Pot", "government-tourism", "https://www.visitpa.com/listing/koontz-coffee-pot/1342/", ["1920s roadside structure", "Lincoln Highway context", "exterior visit"]],
  ["src-old-bedford", "Bedford County Chamber - Old Bedford Village", "local-tourism", "https://members.bedfordcountychamber.com/list/member/old-bedford-village-bedford-1492", ["October Sunday hours", "historic village", "seasonal access"]],
  ["src-mack", "Mack Trucks Historical Museum", "official", "https://www.macktruckshistoricalmuseum.org/", ["Monday tour pattern", "reservation-first calendar", "free admission and suggested donation"]],
  ["src-fish-hatchery", "City of Allentown Parks - Fish Hatchery", "government", "https://allentownpa.myrec.com/info/facilities/details.aspx?FacilityID=14801", ["public facility", "exact address", "outdoor access"]],
  ["src-uncle-sam", "Danbury Railway Museum - World's Tallest Uncle Sam", "official", "https://www.danburyrail.org/unclesam", ["38-foot statue", "Great Danbury Fair history", "parking-lot location"]],
  ["src-danbury-fair", "Danbury Fair - hours and services", "official", "https://www.danburyfairmall.com/hours", ["Tuesday mall hours", "carousel service listing", "retail fallback"]],
  ["src-mit", "MIT Museum - admission", "official", "https://mitmuseum.mit.edu/admission-desk/prices", ["adult admission", "science and technology museum", "Cambridge location"]],
  ["src-mit-arts", "MIT Arts - MIT Museum", "official", "https://arts.mit.edu/exhibitions/", ["daily 10-5 hours", "collections", "museum scope"]],
  ["src-harvard", "Harvard Art Museums - visit", "official", "https://harvardartmuseums.org/visit", ["Wednesday hours", "free admission", "Calderwood Courtyard"]],
  ["src-noaa-normals", "NOAA U.S. Climate Normals", "government", "https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals", ["1991-2020 normals methodology"]],
  ["src-osrm", "Open Source Routing Machine", "routing", "https://project-osrm.org/", ["road-network baselines", "no live traffic"]],
  ["src-forum-upstate", "r/upstate_new_york local hidden-gem discussions", "forum", "https://www.reddit.com/r/upstate_new_york/", ["Cazenovia and Chittenango cross-check", "Mount Hope cross-check", "I-90 pacing"]],
  ["src-forum-cleveland", "r/Cleveland local hidden-place discussions", "forum", "https://www.reddit.com/r/Cleveland/", ["Buckland Museum cross-check", "Lake View cross-check", "Cleveland pacing"]]
];

const H = (opens, closes, note, status = "verified-current") => ({ opens, closes, status, note });
const C = (amount, note = "Adult planning price; reconfirm before booking.", status = "verified-current") => ({ amount_per_person: amount, status, note });
const R = (day, replaces, variant, reason) => ({ day, replaces_place_ids: replaces, route_variant_id: variant, reason });
const S = (id, name, kind, city, state, date, summary, why_go, best_for, secondary_for, categories, duration_minutes, source_ids, hours, cost, priority = "anchor", reservation = "none", replacement = null) => ({
  id, name, kind, city, state, visit_date: date, summary, why_go, best_for, secondary_for,
  best_fit_note: `Best for ${best_for.join(" and ")}: ${why_go}`,
  categories, duration_minutes, source_ids, reservation, hours, cost, priority,
  ...(replacement ? { replacement_reason: replacement.reason, replacement } : {}), address: name
});

export const seedPlaces = [
  S("springfield-museums", "Springfield Museums", "five-museum-cultural-campus", "Springfield", "MA", "2026-10-04", "One walkable quadrangle links natural history, American art, regional industry and the Amazing World of Dr. Seuss, so the first day feels like a choose-your-own-adventure rather than one long gallery.", "It lets the four travelers split briefly without splitting the route: Viki can chase visual rooms, Gora can inspect science and industry, and everyone can regroup in the sculpture garden.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "architecture_nature_photogenic", "local_culture"], 180, ["src-springfield"], H("11:00", "17:00", "Sunday hours for the museum campus; the outdoor Seuss garden is free but does not replace late indoor arrival."), C(27.5), "anchor"),
  S("springfield-armory", "Springfield Armory National Historic Site", "industrial-and-firearms-history", "Springfield", "MA", "2026-10-04", "The vast Main Arsenal interprets two centuries of precision manufacturing, labor and weapons development inside the federal armory that helped standardize American industry.", "Gora gets evidence-led industrial history while Viki gets monumental brick architecture; it is a focused alternative to the broader museum campus.", ["gora"], ["viki", "sheluvspaco", "stivka"], ["hidden_history_folklore", "architecture_nature_photogenic", "local_culture"], 120, ["src-armory"], H("09:30", "16:00", "Wednesday-Sunday hours; it closes earlier than the core stop, so it is a preference swap, not a late-arrival rescue."), C(0), "replacement", "none", R(1, ["springfield-museums"], "replacement-d1-springfield-armory", "Use when the group wants one deep industrial story instead of five lighter museums.")),
  S("cohoes-falls", "Cohoes Falls View Park", "urban-waterfall-overlook", "Cohoes", "NY", "2026-10-05", "A 1,000-foot-wide Mohawk River waterfall appears behind an old mill city, combining exposed rock, hydropower history and a short dramatic overlook rather than a strenuous hike.", "It gives Viki a strong landscape-and-infrastructure photo and gives Gora the honest industrial geography behind the Erie Canal corridor.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 70, ["src-cohoes"], H("07:00", "19:30", "Falls View Park is seasonally open through November 1; the year-round upper overlook is the fallback. Never enter the riverbed."), C(0), "anchor"),
  S("oakwood-troy", "Oakwood Cemetery: Uncle Sam Grave & Earl Chapel Grounds", "victorian-cemetery-history", "Troy", "NY", "2026-10-05", "A vast nineteenth-century rural cemetery holds Samuel Wilson's grave—the real meatpacker behind Uncle Sam—plus a Romanesque crematory chapel, waterfalls and long Hudson Valley views.", "This is the buried-history stop: Gora gets the real person behind a national symbol, Viki gets stonework and autumn landscape, and Stivka gets a quiet, respectful setting.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic", "quiet_reset"], 115, ["src-oakwood", "src-forum-upstate"], H("08:00", "19:00", "Daily grounds hours. It is an active cemetery: keep voices low, yield to funerals, use handheld personal photography only and treat chapel interiors as unavailable unless explicitly open."), C(0), "anchor"),
  S("saratoga-auto", "Saratoga Automobile Museum", "automotive-design-museum", "Saratoga Springs", "NY", "2026-10-05", "A restored 1935 state bottling plant now frames rotating automobile exhibitions; the October 2026 headline celebrates 140 years of Mercedes-Benz engineering.", "It is the polished all-weather substitute when the group wants machinery and design more than two outdoor historical landscapes.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["unusual_creative", "architecture_nature_photogenic", "local_culture"], 120, ["src-saratoga-auto"], H("10:00", "17:00", "Open daily in May-October; special events and exhibit changeovers can alter access, so check the museum feed the day before."), C(20), "replacement", "none", R(2, ["cohoes-falls", "oakwood-troy"], "replacement-d2-saratoga-auto", "A single weatherproof design anchor replacing the waterfall-and-cemetery pair.")),
  S("boxing-hof", "International Boxing Hall of Fame", "combat-sport-history-museum", "Canastota", "NY", "2026-10-06", "The sport's international shrine sits in the small town where two residents revived boxing's hall of fame, filling compact galleries with gloves, robes, film and difficult careers.", "This is the route's only sport-forward anchor and it is exactly calibrated for Gora: historical, technical and human rather than an exhausting activity.", ["gora"], ["sheluvspaco", "stivka", "viki"], ["hidden_history_folklore", "local_culture", "unusual_creative"], 120, ["src-boxing"], H("09:30", "17:00", "Weekday hours; leave enough time for the research library and film room if the group gets absorbed."), C(15.5), "anchor"),
  S("chittenango-falls", "Chittenango Falls State Park", "limestone-waterfall-short-walk", "Cazenovia", "NY", "2026-10-06", "A 167-foot waterfall steps over 400-million-year-old bedrock, with a compact gorge trail and footbridge that can deliver a huge fall image without a long hike.", "Viki gets the strongest nature alternative of the first half, while Gora and Stivka get a quiet reset after the Thruway.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "quiet_reset"], 90, ["src-chittenango", "src-forum-upstate"], H(null, null, "Open sunrise to sunset year-round with restrictions. The full gorge has stairs and can be slippery; the top view remains the low-effort option.", "verified-public-space"), C(0, "No October vehicle fee is presently listed; carry a card and reconfirm."), "replacement", "none", R(3, ["boxing-hof"], "replacement-d3-chittenango-falls", "Use when the group needs foliage and open air more than combat-sport history.")),
  S("anthony-house", "National Susan B. Anthony Museum & House", "guided-social-history-house", "Rochester", "NY", "2026-10-07", "A docent-led visit moves through the rooms where Anthony lived, organized and was arrested after voting in 1872, keeping suffrage history grounded in decisions and evidence.", "Gora gets non-sanitized political history, Viki gets an intimate period interior, and the group gets a strong story without a blockbuster crowd.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["hidden_history_folklore", "architecture_nature_photogenic", "local_culture"], 90, ["src-anthony"], H("11:00", "17:00", "Tuesday-Sunday hours; visits are docent-led, so reserve or arrive for an available tour rather than assuming free wandering."), C(20), "anchor", "reserve-recommended"),
  S("mount-hope-rochester", "Mount Hope Cemetery: Douglass & Anthony", "victorian-landscape-and-memory", "Rochester", "NY", "2026-10-07", "America's first municipal Victorian cemetery folds glacial hills, mature trees and elaborate monuments around the graves of Frederick Douglass and Susan B. Anthony.", "The pairing turns a house-museum story into a physical memory landscape and gives all four a quiet, photogenic hour rather than another indoor collection.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 75, ["src-mount-hope", "src-forum-upstate"], H("07:30", "20:00", "October 7 falls within the April 1-October 14 extended grounds schedule. Respect funerals and grave decorations; no staged photo shoot."), C(0), "anchor"),
  S("rmsc-electricity", "RMSC Electricity Theater", "live-tesla-coil-science", "Rochester", "NY", "2026-10-07", "Twin six-foot solid-state Tesla coils throw musical arcs across a dark theater, turning electricity into a controlled live performance inside Rochester's science museum.", "This is Viki's unusual-museum instinct at full voltage and gives Gora a spectacular demonstration with real physics underneath it.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative", "hidden_history_folklore", "local_culture"], 135, ["src-rmsc", "src-rmsc-tesla"], H("09:00", "17:00", "Wednesday school-year museum hours; the Electricity Theater is included, but exact show times must be checked before choosing this swap."), C(23), "replacement", "same-day-show-check", R(4, ["anthony-house", "mount-hope-rochester"], "replacement-d4-rmsc-electricity", "A weatherproof spectacle replacing both quieter history stops when energy or rain calls for one anchor.")),
  S("eden-kazoo", "Original American Kazoo Company Factory & Museum", "working-kazoo-factory", "Eden", "NY", "2026-10-08", "The only metal kazoo factory of its kind in North America still uses belt-driven machinery in an 1890s workshop; a self-guided visit ends by making a playable kazoo.", "This is Route 7's defining hidden gem: strange, inexpensive, mechanical, musical and impossible to confuse with a generic museum.", ["stivka", "viki"], ["gora", "sheluvspaco"], ["unusual_creative", "hidden_history_folklore", "local_culture"], 85, ["src-kazoo"], H("10:00", "17:00", "Thursday is one of the factory's normal operating days; machinery activity can vary, so call the day before and arrive near opening."), C(5, "Self-guided museum is inexpensive; allow a small make-a-kazoo purchase."), "anchor", "call-day-before"),
  S("trec-presque-isle", "Tom Ridge Environmental Center & Presque Isle Gateway", "lake-ecology-and-observation-tower", "Erie", "PA", "2026-10-08", "Interactive lake-and-dune exhibits lead to a 75-foot tower overlooking Presque Isle, making the peninsula's shifting ecology legible before a short shoreline pause.", "Viki gets Lake Erie and a high photo angle, Gora gets environmental systems, and everyone gets fresh air without a five-mile hike.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "quiet_reset", "local_culture"], 105, ["src-trec"], H("08:00", "16:00", "Daily April-October hours; protect the tower and exhibit time by leaving Eden promptly."), C(0), "anchor"),
  S("erie-maritime", "Erie Maritime Museum", "warship-and-lake-industry-museum", "Erie", "PA", "2026-10-08", "A former power plant interprets naval construction, the Battle of Lake Erie and the bay's working waterfront; the indoor reconstructed gun deck matters even when Niagara is away.", "It is the stronger bad-weather choice for Gora and Stivka, mixing engineering, conflict and Erie identity in one compact building.", ["gora", "stivka"], ["viki", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic", "local_culture"], 100, ["src-erie-maritime"], H(null, null, "The official site currently exposes ticketing but not a dependable October 8 hours block; confirm directly before promoting this replacement.", "reconfirm-required"), C(10, "Planning estimate only; confirm current adult admission."), "replacement", "call", R(5, ["trec-presque-isle"], "replacement-d5-erie-maritime", "An indoor engineering-and-warship substitute when the lakefront tower is weathered out.")),
  S("rock-hall", "Rock & Roll Hall of Fame", "music-history-museum", "Cleveland", "OH", "2026-10-09", "Cleveland's glass pyramid connects sound, clothing, handwritten lyrics, instruments and contested definitions of rock across generations rather than offering a simple wall of fame.", "Stivka gets the trip's biggest music archive, Viki gets iconic architecture and performance objects, and everyone gets context before the live show.", ["stivka", "viki"], ["gora", "sheluvspaco"], ["social_nightlife_live", "hidden_history_folklore", "architecture_nature_photogenic"], 150, ["src-rockhall"], H("10:00", "17:00", "September-June Friday hours; timed tickets are strongly recommended for a Friday with a fixed evening show."), C(45), "anchor", "reserve"),
  S("christmas-story-house", "A Christmas Story House", "film-location-house-museum", "Cleveland", "OH", "2026-10-09", "The restored Tremont house turns a familiar film set into a tactile period interior where visitors can trace how an ordinary neighborhood became American holiday mythology.", "It is goofy enough to reset the day, highly photographable for Viki and a clean pop-culture story for everyone without becoming a three-hour commitment.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "architecture_nature_photogenic", "hidden_history_folklore"], 60, ["src-christmas"], H("10:00", "17:00", "Daily hours; guided tours run roughly 45-50 minutes, so buy a slot that leaves margin before Buckland and the concert."), C(20, "Current online planning price before tax and booking fees."), "anchor", "reserve"),
  S("buckland-museum", "Buckland Museum of Witchcraft & Magick", "occult-history-cabinet", "Cleveland", "OH", "2026-10-09", "More than two hundred ritual, publishing and personal objects from Raymond Buckland's collection fill a tiny serious museum about modern witchcraft and occult subcultures.", "This is Viki's off-mainstream museum and Gora's chance to study a belief system through primary objects rather than internet mythology.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative", "hidden_history_folklore"], 55, ["src-buckland", "src-forum-cleveland"], H(null, null, "Official admission and visit length are current, but the site does not publish a stable Friday hours table. Buy a timed ticket only after October 9 inventory appears.", "reserve-and-reconfirm"), C(8, "$8 online or $10 at the door."), "anchor", "reserve"),
  S("sugar-agora", "Sugar at the Agora Theatre", "fixed-live-rock-night", "Cleveland", "OH", "2026-10-09", "Bob Mould's power trio Sugar brings its dense guitar sound to the restored Agora—an exact-date rock night that makes Cleveland the emotional endpoint rather than just the farthest hotel.", "This is designed for Stivka, but the social concert energy also gives Paco and Gora the one big night the route earns after a week of careful pacing.", ["stivka"], ["sheluvspaco", "gora", "viki"], ["social_nightlife_live", "architecture_nature_photogenic", "local_culture"], 180, ["src-sugar"], H("19:00", "23:00", "Friday October 9, 2026: doors 19:00, show 20:00. End time is a planning estimate; venue rules and final set times govern."), C(null, "Ticket price and fees vary by inventory; nightlife is excluded from the $1,500 controllable budget."), "anchor", "reserve-now"),
  S("crawford-auto", "Crawford Auto-Aviation Museum", "transportation-technology-collection", "Cleveland", "OH", "2026-10-09", "A Cleveland-built transportation collection moves from early electric cars and aircraft to industrial design, including the tiny transatlantic sailboat Tinkerbelle.", "It replaces uncertainty with machinery: Gora gets engineering, Viki gets polished forms and Stivka still stays inside Cleveland's cultural history.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "unusual_creative", "local_culture"], 100, ["src-crawford"], H("10:00", "16:00", "Friday Cleveland History Center hours; verify which Crawford galleries are open after the museum's renovation cycle."), C(15, "Planning estimate for general admission; confirm current ticket price."), "replacement", "none", R(6, ["buckland-museum"], "replacement-d6-crawford-auto", "The dependable Friday swap when Buckland has no usable timed inventory.")),
  S("cleveland-art", "Cleveland Museum of Art", "world-art-and-architecture-anchor", "Cleveland", "OH", "2026-10-10", "A free encyclopedic collection wraps around the huge glass-roofed Ames Family Atrium, letting the group choose armor, icons, contemporary art or quiet courtyard light without paying for completeness.", "Viki gets the most beautiful indoor architecture of the route, Stivka can seek sacred art, and each person can follow a different gallery for an hour before regrouping.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 150, ["src-cma"], H("10:00", "17:00", "Saturday hours; general admission is free, but special exhibitions may be timed and paid."), C(0), "anchor"),
  S("lake-view-haserot", "Lake View Cemetery & Haserot Angel", "garden-cemetery-sculpture", "Cleveland", "OH", "2026-10-10", "The bronze Angel of Death Victorious appears to cry black tears from oxidation inside Cleveland's 1869 garden cemetery, surrounded by hills, monuments and old trees.", "It is a quieter, stranger Cleveland exit: Viki and Stivka get sculpture and atmosphere while the group decompresses before the long southbound stage.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 95, ["src-lakeview", "src-haserot", "src-forum-cleveland"], H(null, null, "Public grounds are normally open daily, but exact gate hours must be checked. This is an active cemetery: no props, staged shoot, drones or disturbance."), C(0), "replacement", "same-day-gate-check", R(7, ["cleveland-art"], "replacement-d7-lake-view-haserot", "A foliage-and-sculpture alternative when the group has reached museum saturation.")),
  S("all-saints-canonsburg", "All Saints Greek Orthodox Church", "full-orthodox-sunday", "Canonsburg", "PA", "2026-10-11", "A canonical Greek Orthodox parish anchors the return with the full Sunday sequence—Orthros followed by Divine Liturgy—rather than treating church as a photo stop.", "This is Stivka's deepest fit and a meaningful shared ritual for all four Orthodox travelers; the day stays deliberately light afterward.", ["stivka"], ["sheluvspaco", "viki", "gora"], ["orthodox_spiritual", "architecture_nature_photogenic", "quiet_reset"], 180, ["src-all-saints", "src-goarch-pittsburgh"], H("09:00", "12:00", "Regular post-Labor-Day pattern is Orthros around 09:00 and Divine Liturgy around 10:00, but October 11 must be confirmed in the parish bulletin. Ask about visitor and Communion etiquette."), C(0, "Free; make a respectful offering if desired."), "anchor", "reconfirm-parish"),
  S("bedford-coffee-pot", "Koontz Coffee Pot", "giant-roadside-architecture", "Bedford", "PA", "2026-10-11", "A giant sheet-metal coffee pot built as a 1920s lunch stand survives beside the Lincoln Highway, saved and moved by local preservationists after decades of roadside service.", "It is a ten-minute visual joke with real automobile-era history—perfect after Liturgy and before the final Breezewood push.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["architecture_nature_photogenic", "hidden_history_folklore", "unusual_creative"], 35, ["src-coffee-pot"], H(null, null, "Exterior roadside stop; interior opening is not promised. Park legally and never block Telegraph Road.", "verified-exterior"), C(0), "anchor"),
  S("old-bedford-village", "Old Bedford Village", "living-history-landscape", "Bedford", "PA", "2026-10-11", "Dozens of rescued and reconstructed log, stone and frame buildings create a compact Pennsylvania village where domestic craft and frontier infrastructure sit together.", "It is the fuller folklore-and-architecture option for Viki, Gora and Stivka if the group wants depth rather than one roadside photograph.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "local_culture"], 105, ["src-old-bedford"], H("09:00", "17:00", "September-October Thursday-Sunday pattern; October 11 overlaps Bedford fall-foliage traffic, so confirm admission and allow congestion margin."), C(15, "Planning estimate; confirm 2026 adult admission."), "replacement", "none", R(8, ["bedford-coffee-pot"], "replacement-d8-old-bedford-village", "A longer living-history option when energy and festival traffic both remain manageable.")),
  S("mack-museum", "Mack Trucks Historical Museum", "guided-heavy-machinery-history", "Allentown", "PA", "2026-10-12", "Volunteer ambassadors lead small groups through restored Mack trucks, engines, archives and the bulldog's industrial story inside the active Experience Center campus.", "This is the heavy-machinery finale for Gora and a genuinely behind-the-scenes American manufacturing story for all four—not just a room of polished vehicles.", ["gora"], ["viki", "stivka", "sheluvspaco"], ["hidden_history_folklore", "unusual_creative", "local_culture"], 90, ["src-mack"], H("13:00", "14:30", "Monday tours normally start 9:00, 10:30, 13:00 and 14:30, but October 12 is a federal holiday. The reservation calendar is authoritative; do not drive to the gated campus without confirmation."), C(5, "No admission fee; $5 suggested adult donation."), "anchor", "reserve-and-holiday-confirm"),
  S("allentown-fish-hatchery", "Lil-Le-Hi Trout Nursery", "historic-public-fish-hatchery", "Allentown", "PA", "2026-10-12", "Long concrete raceways full of trout sit inside Lehigh Parkway beside stonework, creek paths and the city's 1883 hatchery tradition.", "It is the automatic low-pressure rescue if Mack closes for the holiday: moving water, infrastructure and a short outdoor reset instead of a locked gate.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "quiet_reset", "local_culture"], 85, ["src-fish-hatchery"], H(null, null, "Public outdoor facility; verify parking and any seasonal feeding restrictions with Allentown Parks. No indoor program is assumed.", "public-space-reconfirm"), C(0), "replacement", "none", R(9, ["mack-museum"], "replacement-d9-allentown-fish-hatchery", "The route-safe outdoor substitute if the holiday removes Mack tour inventory.")),
  S("uncle-sam-danbury", "World's Tallest Uncle Sam Statue", "giant-fairground-survivor", "Danbury", "CT", "2026-10-13", "A 38-foot, 4,500-pound fiberglass Uncle Sam built for the Great Danbury Fair in 1971 now towers over the Railway Museum parking lot—the return route's perfect echo of Samuel Wilson's grave.", "The bookend is the magic: Day 2 meets the real Uncle Sam; Day 10 meets America's enormous carnival version. Viki gets the shot and everyone gets the joke.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "architecture_nature_photogenic", "hidden_history_folklore"], 35, ["src-uncle-sam"], H(null, null, "The Railway Museum is closed Tuesday; this is strictly an exterior parking-lot statue visit during safe daylight. No indoor or rail-yard access is promised.", "verified-exterior-only"), C(0), "anchor"),
  S("danbury-fair-carousel", "Danbury Fair Double-Decker Carousel", "mall-carousel-and-retail-reset", "Danbury", "CT", "2026-10-13", "An Italian-style double-decker carousel inside the mall keeps the vanished Great Danbury Fair's carnival energy alive beside a large modern retail mix.", "Viki gets one practical fashion-shopping window and a playful photograph while the others get a brief fair-history callback without adding road miles.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["shopping_outlets", "unusual_creative", "social_nightlife_live"], 100, ["src-danbury-fair"], H("10:00", "20:00", "Tuesday mall hours. The mall lists carousel service, but the independent ride's exact operating hours and price must be confirmed same day."), C(3, "Planning estimate for one ride; shopping is personal and excluded."), "replacement", "same-day-operator-check", R(10, ["uncle-sam-danbury"], "replacement-d10-danbury-carousel", "An indoor carnival-and-shopping substitute in rain; it replaces the statue rather than stacking with it.")),
  S("mit-museum", "MIT Museum", "invention-and-kinetic-science-museum", "Cambridge", "MA", "2026-10-14", "Kinetic sculptures, holography, architecture, artificial intelligence and Doc Edgerton's frozen instants turn MIT research into objects that move, flicker and surprise.", "It closes the mechanical-dreams thread after both cars are safely returned: Viki gets visual wonder, Gora gets applied science and nobody has to park in Cambridge.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["unusual_creative", "hidden_history_folklore", "architecture_nature_photogenic"], 150, ["src-mit", "src-mit-arts"], H("10:00", "17:00", "Open daily 10:00-17:00. Visit only after both rental cars are returned; use MBTA/rideshare and protect the airport-hotel night."), C(20), "anchor", "reserve-recommended"),
  S("harvard-art", "Harvard Art Museums", "free-art-and-conservation-courtyard", "Cambridge", "MA", "2026-10-14", "More than fifty galleries rise around Renzo Piano's light-filled Calderwood Courtyard, with visible conservation spaces and sacred, ancient and modern art under one roof.", "It is the softer free finale when the group wants beauty and space instead of one more technology collection, with especially strong fits for Viki and Stivka.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "quiet_reset", "hidden_history_folklore"], 135, ["src-harvard"], H("10:00", "17:00", "Open Tuesday-Sunday and free. Weekend registration advice does not apply Wednesday, but check select-date closures before travel."), C(0), "replacement", "none", R(11, ["mit-museum"], "replacement-d11-harvard-art", "An equal-drive post-car-return finale emphasizing architecture, icons and quiet rather than machines."))
];


export const dayPlans = [
  { day: 1, date: "2026-10-04", sleep_city: "Springfield, MA", theme: "Five museums in one garden-sized campus", schedule: [["14:15", "16:45", "springfield-museums", "anchor"]], lodging: ["Springfield downtown/Armory side with two clean rooms and bright two-car parking", "West Springfield only if the live Logan departure ETA is materially better"], fallback: "The working assumption is that both cars leave Logan by 12:15 after the Nantucket-Hyannis-Boston transfer. If pickup slips past that, shorten the museum campus rather than speed; the Armory closes at 16:00 and is a preference swap, not a late-arrival rescue." },
  { day: 2, date: "2026-10-05", sleep_city: "Troy, NY", theme: "A waterfall city and the two faces of Uncle Sam", schedule: [["10:30", "11:40", "cohoes-falls", "anchor"], ["12:10", "14:05", "oakwood-troy", "anchor"]], lodging: ["Troy downtown near walkable dinner with recent cleanliness reviews and secure parking", "Latham only if downtown two-room inventory is weak"], fallback: "Use the year-round upper overlook if the lower falls stairs are wet. Saratoga Auto replaces both anchors in poor weather; do not stack all three." },
  { day: 3, date: "2026-10-06", sleep_city: "Syracuse, NY", theme: "The small-town world capital of boxing", schedule: [["12:00", "14:00", "boxing-hof", "anchor"]], lodging: ["Syracuse downtown/Armory Square with two-room inventory and secure garage", "East Syracuse near I-90 for a quieter, easier morning exit"], fallback: "Chittenango Falls is the foliage swap when the group needs open air. Use only the top overlook in heavy rain or slippery conditions." },
  { day: 4, date: "2026-10-07", sleep_city: "Batavia, NY", theme: "Suffrage decisions, graves and a quiet Victorian landscape", schedule: [["11:30", "13:00", "anthony-house", "anchor"], ["13:20", "14:35", "mount-hope-rochester", "anchor"]], lodging: ["Batavia I-90 corridor with two clean rooms and lighted parking", "Le Roy only if the bed layout and recent reviews are clearly stronger"], fallback: "Reserve the Anthony tour. If rain or tour inventory breaks the pair, choose RMSC and verify the Tesla-coil show time; never stack RMSC onto the two core stops." },
  { day: 5, date: "2026-10-08", sleep_city: "Erie, PA", theme: "Make a kazoo, then look across an inland sea", schedule: [["10:00", "11:25", "eden-kazoo", "anchor"], ["14:10", "15:55", "trec-presque-isle", "anchor"]], lodging: ["Erie bayfront or west side with secure parking and two clean rooms", "Presque Isle gateway only if Friday's live Cleveland ETA stays protected"], fallback: "Call the kazoo factory Wednesday to confirm machinery. TREC closes at 16:00. Erie Maritime replaces TREC only after direct hours confirmation; it is never an extra." },
  { day: 6, date: "2026-10-09", sleep_city: "Cleveland, OH", theme: "Rock artifacts, film mythology, an occult cabinet and the one earned big night", schedule: [["10:45", "13:15", "rock-hall", "anchor"], ["14:00", "15:00", "christmas-story-house", "anchor"], ["15:25", "16:20", "buckland-museum", "anchor"], ["20:00", "23:00", "sugar-agora", "anchor"]], lodging: ["Cleveland downtown with two rooms, secure garage and a short rideshare to Agora", "University Circle only if concert transport and two-car overnight parking are explicit"], fallback: "Book Rock Hall, the film-house tour and Sugar first. Buckland is accepted only with a real timed ticket; Crawford is the measured Friday swap. Park both cars before dinner and use rideshare for the show." },
  { day: 7, date: "2026-10-10", sleep_city: "Canonsburg, PA", theme: "One luminous Cleveland morning, then the return arc begins", schedule: [["10:00", "12:30", "cleveland-art", "anchor"]], lodging: ["Canonsburg/Southpointe with two clean rooms, quiet night and easy church access", "Washington north only if All Saints remains within a short Sunday drive"], fallback: "Do not add a second Cleveland museum after the concert night. Lake View and the Haserot Angel are the quieter replacement; confirm gates and preserve cemetery etiquette." },
  { day: 8, date: "2026-10-11", sleep_city: "McConnellsburg, PA", theme: "Full Orthodox Sunday and one perfect piece of roadside America", schedule: [["09:00", "12:00", "all-saints-canonsburg", "anchor"], ["14:45", "15:20", "bedford-coffee-pot", "anchor"]], lodging: ["McConnellsburg west side in a small inn with two confirmed clean rooms and off-street parking", "Breezewood only if Mack is automatically replaced by the Fish Hatchery on Monday"], fallback: "This is a 209-minute baseline day. Confirm Orthros, Liturgy and visitor etiquette; church is never shortened. Cut the Coffee Pot when the live bed-to-bed ETA exceeds 210. Old Bedford Village is a replacement only when traffic and energy genuinely permit." },
  { day: 9, date: "2026-10-12", sleep_city: "Allentown, PA", theme: "Heavy machines, volunteer memory and the Bulldog", schedule: [["13:00", "14:30", "mack-museum", "anchor"]], lodging: ["South Allentown/Lehigh Parkway side with two-room inventory and secure parking", "Emmaus only if the exact hotel pin keeps the measured day at or below 210"], fallback: "October 12 is a holiday: Mack exists in the plan only if four slots appear in the official reservation calendar. Otherwise use the Fish Hatchery replacement automatically. If McConnellsburg lacks two acceptable rooms and the group sleeps in Breezewood, Mack is also automatically replaced to protect the cap." },
  { day: 10, date: "2026-10-13", sleep_city: "Danbury, CT", theme: "The real Uncle Sam becomes a 38-foot carnival giant", schedule: [["12:15", "12:50", "uncle-sam-danbury", "anchor"]], lodging: ["Danbury downtown with two clean rooms and secure parking", "Danbury Fair/I-84 only when using the carousel replacement"], fallback: "The Railway Museum is closed Tuesday; photograph only the exterior statue from the public parking area. In rain, replace it with the mall carousel and a controlled shopping window rather than stacking both." },
  { day: 11, date: "2026-10-14", sleep_city: "Boston, MA", theme: "Return both cars, then end inside a machine dream", schedule: [["12:30", "15:00", "mit-museum", "anchor"]], lodging: ["Logan airport hotel with confirmed early October 15 shuttle", "East Boston or Revere only with a verified airport transfer and the required two-room setup"], fallback: "Leave Danbury early, return both cars before any Cambridge stop, then use transit. Harvard Art Museums is the free quieter swap with unchanged road mileage. No nightlife is planned on the airport-eve night." }
];
