#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  contextualImagePlaces, energyRebuildPlaceIds, lodgingNodes, manualCoordinates, PEOPLE,
  places as configPlaces,
  replacementVariants, ROUTE_ID, ROUTE_NAME, ROUTE_SLUG
} from "./config.mjs";
import { buildEnergyRoute03 } from "../route-03-energy/build.mjs";

const ROOT = process.cwd();
const ROUTE_DIR = path.join(ROOT, "dataset", "routes", ROUTE_SLUG);
const verifiedAt = "2026-08-23";

const sourceRows = [
  ["src-florence", "Florence Griswold Museum", "official", "https://florencegriswoldmuseum.org/visit/", ["Sunday hours", "art-colony history", "admission"]],
  ["src-cross-sound", "Cross Sound Ferry", "official", "https://www.longislandferry.com/Schedules/ScheduleDeparture.aspx", ["vehicle service", "80-minute crossing", "reservation guidance"]],
  ["src-greenport", "Village of Greenport", "government", "https://www.villageofgreenport.org/mitchell-park", ["Mitchell Park and carousel"]],
  ["src-book-barn", "The Book Barn", "official", "https://www.bookbarnniantic.com/thingstodo", ["daily October hours", "gardens and animals"]],
  ["src-north-ferry", "North Ferry", "official", "https://northferry.com/schedule.html", ["year-round frequency", "no reservations"]],
  ["src-south-ferry", "South Ferry", "official", "https://southferry.com/", ["year-round service", "fare and cash policy"]],
  ["src-mashomack", "The Nature Conservancy", "official", "https://www.nature.org/en-us/get-involved/how-to-help/places-we-protect/long-island-mashomack/", ["preserve scale", "habitats", "trail access"]],
  ["src-parrish", "Parrish Art Museum", "official", "https://parrishart.org/visit/", ["Monday hours", "admission", "architecture"]],
  ["src-big-duck", "Suffolk County Parks", "government", "https://www.suffolkcountyny.gov/Departments/Parks/Historic-Sites/The-Big-Duck", ["daily hours", "roadside-architecture history"]],
  ["src-tanger", "Tanger Riverhead", "official", "https://www.tanger.com/riverhead/stores", ["store directory", "Monday hours"]],
  ["src-aquarium", "Long Island Aquarium", "official", "https://www.longislandaquarium.com/plan-your-visit/facilities/", ["daily hours", "100-plus exhibits"]],
  ["src-cradle", "Cradle of Aviation Museum", "official", "https://www.cradleofaviation.org/", ["Tuesday hours", "admission", "aviation collection"]],
  ["src-silverball", "Silverball Retro Arcade", "official", "https://silverballmuseum.com/asbury-park/", ["daily hours", "free-play admission"]],
  ["src-asbury", "Asbury Park Music Foundation", "official-calendar", "https://asburypark.net/events.shtml", ["2026 venue calendar", "music-scene context"]],
  ["src-ocean-grove", "Ocean Grove Camp Meeting Association", "official", "https://www.oceangrove.org/tour", ["self-guided landmark tour", "Great Auditorium and tent city"]],
  ["src-lucy", "Lucy the Elephant", "official", "https://lucytheelephant.org/visiting/", ["Wednesday tours", "hours and admission"]],
  ["src-nas", "NAS Wildwood Aviation Museum", "official", "https://usnasw.org/visit/", ["October daily hours", "admission"]],
  ["src-cape-may-mac", "Cape May MAC", "official", "https://capemaymac.org/ghosts-mysteries/", ["ghost and oddities tour formats", "Victorian history"]],
  ["src-cape-point", "New Jersey State Park Service", "government", "https://dep.nj.gov/parksandforests/state-park/cape-may-point-state-park/", ["daily gate hours", "lighthouse and Battery 223"]],
  ["src-cmlf", "Cape May-Lewes Ferry", "official", "https://www.cmlf.com/schedules-fares/", ["2026 schedule", "vehicle reservations", "fares"]],
  ["src-fort-miles", "Fort Miles Museum", "official", "https://fortmilesmuseum.org/battery-519-tours-and-museum-hours/", ["Thursday hours", "Battery 519 tours", "admission"]],
  ["src-zwaanendael", "Delaware Historical and Cultural Affairs", "government", "https://history.delaware.gov/zwaanendael-museum/", ["museum identity", "Dutch memorial architecture"]],
  ["src-assateague", "National Park Service", "government", "https://www.nps.gov/asis/planyourvisit/hours.htm", ["October hours", "visitor center", "wild-horse access"]],
  ["src-wallops", "NASA", "government", "https://www.nasa.gov/wallops/visitor-center/plan-your-visit/", ["Friday hours", "free admission", "mission-operations caveat"]],
  ["src-barrier", "Barrier Islands Center", "official", "https://barrierislandscenter.org/visit", ["Friday hours", "free admission", "island-culture collection"]],
  ["src-cbbt", "Chesapeake Bay Bridge-Tunnel", "official", "https://www.cbbt.com/", ["17-mile crossing", "tolls", "travel alerts"]],
  ["src-nauticus", "Nauticus", "official", "https://nauticus.org/visit/hours-tickets/", ["daily hours", "USS Wisconsin access", "admission"]],
  ["src-are", "Edgar Cayce A.R.E.", "official", "https://edgarcayce.org/about-us/location-hours/", ["Saturday hours", "library and visitor center"]],
  ["src-poe", "Poe Museum", "official", "https://poemuseum.org/visit-us/", ["Saturday hours", "admission", "Enchanted Garden"]],
  ["src-hermitage", "Hermitage Museum and Gardens", "official", "https://thehermitagemuseum.org/visit/", ["museum and garden access"]],
  ["src-richmond-orthodox", "Saints Constantine and Helen Cathedral", "official", "https://www.vagocathedral.org/", ["Sunday services", "address"]],
  ["src-bo", "B&O Railroad Museum", "official", "https://www.borail.org/visit-the-bo/plan-your-visit/faqs/", ["daily hours", "admission", "secure parking"]],
  ["src-bo-rides", "B&O Railroad Museum", "official", "https://www.borail.org/visit-the-bo/tours-experiences/train-rides/", ["2026 Mile One ride schedule"]],
  ["src-bmi", "Baltimore Museum of Industry", "official", "https://www.thebmi.org/visit/", ["Sunday hours", "admission", "public tours"]],
  ["src-mutter", "Mutter Museum", "official", "https://muttermuseum.org/about/overview/", ["Monday hours", "medical-history collection", "address"]],
  ["src-metuchen", "Metuchen Downtown Alliance", "official-district", "https://www.downtownmetuchen.org/", ["Main Street dining and downtown district"]],
  ["src-andalusia", "Andalusia Historic House, Gardens and Arboretum", "official", "https://andalusiapa.org/visit/", ["2026 Monday hours", "admission", "house and garden tours"]],
  ["src-sleepy", "Visit Sleepy Hollow", "official-tourism", "https://visitsleepyhollow.com/where-to-see-the-headless-horseman/", ["bridge, statue and folklore locations"]],
  ["src-old-dutch", "Old Dutch Church", "official-tourism", "https://visitsleepyhollow.com/see/old-dutch-church/", ["churchyard history", "October access and 16:30 closing"]],
  ["src-cemetery", "Sleepy Hollow Cemetery", "official-tourism", "https://visitsleepyhollow.com/see/sleepy-hollow-cemetery/", ["daily hours", "Washington Irving grave", "visitor rules"]],
  ["src-blaze", "Historic Hudson Valley", "official-ticketing", "https://tickets.hudsonvalley.org/blaze-hudson-valley-2026/11638", ["October 13 date", "timed admission", "price and duration"]],
  ["src-rockefeller", "The Pocantico Center", "official", "https://www.rbf.org/pocantico/david-rockefeller-creative-arts-center", ["arts-center architecture and exhibitions"]],
  ["src-pez", "PEZ Candy", "official", "https://us.pez.com/pages/pez-visitor-center-hours-and-location", ["Wednesday hours", "admission", "production viewing"]],
  ["src-barker", "Barker Character, Comic and Cartoon Museum", "official", "https://www.barkermuseum.com/PlanYourVisit.aspx", ["2026 Wednesday hours", "admission", "collection access"]],
  ["src-noaa-normals", "NOAA National Centers for Environmental Information", "government-data", "https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals", ["1991-2020 daily climate normals"]],
  ["src-osrm", "Open Source Routing Machine", "routing", "https://project-osrm.org/", ["road-network distance and no-traffic baselines"]]
];
const sources = sourceRows.map(([id, publisher, type, url, supports]) => ({ id, publisher, type, url, supports, verified_at: verifiedAt }));

const replacementByPlace = new Map(replacementVariants.map((variant) => [variant.replacement_place_id, variant]));
// V1 records only; the eleven Energy Rebuild V2 stops are built by scripts/route-03-energy/build.mjs.
const researchPlaces = configPlaces.filter((record) => !energyRebuildPlaceIds.has(record.id));
const baseById = new Map(researchPlaces.map((record) => [record.id, record]));

const detailRows = [];
function D(id, name, kind, city, state, visit_date, summary, why_go, best_for, secondary_for, best_fit_note, categories, duration_minutes, source_ids, options = {}) {
  detailRows.push({ id, name, kind, city, state, visit_date, summary, why_go, best_for, secondary_for, best_fit_note, categories, duration_minutes, source_ids, ...options });
}

D("florence-griswold", "Florence Griswold Museum & Artists' Colony", "art-colony-house", "Old Lyme", "CT", "2026-10-04", "The boarding house where American Impressionist painters lived and worked. They painted directly on the doors and wall panels, and those paintings are still there. Outside is the river landscape they painted again and again.", "Artists who lived together, ate together and painted on the furniture. It is a real story about people, not just a room full of pictures, and it breaks the drive to the ferry.", ["viki", "stivka"], ["gora", "sheluvspaco"], "Good for Viki's atmospheric interiors and for Stivka's quiet side. The story of the artist community gives everyone something easy to talk about.", ["architecture_photogenic", "nature_photogenic", "hidden_history_folklore"], 90, ["src-florence"], { reservation: "recommended", hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Sunday hours in the April-December season." }, cost: { amount_per_person: 15, status: "planning-floor", note: "Confirm 2026 general admission when booking." } });
D("cross-sound-ferry", "Cross Sound Ferry: New London to Orient Point", "vehicle-ferry-experience", "New London", "CT", "2026-10-04", "An 80-minute ferry across Long Island Sound, from New London to Orient Point. You stay on open water the whole way, with lighthouses, small islands and working harbors in view.", "The first real moment of the trip, and it saves about six hours of driving around New York City. You are on a boat, not in traffic.", ["viki", "sheluvspaco"], ["gora", "stivka"], "Good for Viki's wind and lighthouse photos, and for Paco, who wants travel time to feel like part of the holiday.", ["nature_photogenic", "unusual_creative"], 80, ["src-cross-sound"], { reservation: "required-for-two-cars", hours: { opens: null, closes: null, status: "schedule-gated", note: "Target a late-afternoon vehicle sailing; final October departure grid must be reconfirmed." }, cost: { amount_per_person: 35, status: "planning-estimate", note: "Four adults and two standard cars, divided per traveler." } });
D("greenport-waterfront", "Greenport Harbor & Mitchell Park Carousel", "harbor-carousel-walk", "Greenport", "NY", "2026-10-04", "A small harbor village with an antique carousel inside a glass building, looking across at the Shelter Island ferries.", "Salt air, boat lights and one silly carousel ride instead of another hotel check-in. A good way to arrive after a long day.", ["viki", "sheluvspaco"], ["stivka", "gora"], "Good for Viki's photos at blue hour, and for Paco, who wants an easy group mood after a long drive.", ["architecture_photogenic", "nature_photogenic", "unusual_creative"], 75, ["src-greenport"], { priority: "supporting", hours: { opens: "08:00", closes: "21:00", status: "public-park", note: "Waterfront remains accessible; carousel operation is seasonal and not promised." } });
D("book-barn-niantic", "The Book Barn", "used-book-compound", "Niantic", "CT", "2026-10-04", "A used bookshop that has spread across a whole yard of sheds and gardens, with cats, goats and reading corners between the buildings.", "You hunt for books between goats and flower beds. Cheap, warm, and full of small discoveries instead of one polished museum story.", ["viki", "stivka"], ["gora", "sheluvspaco"], "Good for Viki's hidden corners and Stivka's slow browsing. Gora can look for strange history books away from the normal shelves.", ["unusual_creative", "food_coffee_shopping", "nature_photogenic"], 90, ["src-book-barn"], { hours: { opens: "11:00", closes: "18:00", status: "verified", note: "Daily April 1-October 31 hours." }, replacement_reason: "Use when the group wants a cozy, low-cost opening or wet weather makes the river grounds less appealing." });
D("north-ferry", "North Ferry to Shelter Island", "short-vehicle-ferry", "Greenport", "NY", "2026-10-05", "A small working ferry that carries cars across the narrow harbor to Shelter Island. It leaves every few minutes and needs no booking.", "Two short ferries make Shelter Island feel like somewhere you found, not somewhere you drove through.", ["sheluvspaco", "viki"], ["gora", "stivka"], "Good for Paco's sense of a well-built route and for Viki's harbor views. A small adventure right after breakfast.", ["nature_photogenic", "unusual_creative"], 15, ["src-north-ferry"], { cost: { amount_per_person: 11, status: "verified-current", note: "Two cars, drivers and extra passengers divided among four travelers." } });
D("mashomack-preserve", "Mashomack Preserve: Red Trail Sampler", "coastal-preserve-walk", "Shelter Island", "NY", "2026-10-05", "A 2,350-acre nature preserve covering almost a third of Shelter Island, with salt marsh, tidal creeks, oak woodland and open meadow. We walk a short loop.", "Real quiet nature without a long or hard walk. Water, birds and almost nobody else.", ["viki", "gora"], ["stivka", "sheluvspaco"], "Good for Viki's marsh reflections and for Gora's quiet reset. Stivka gets a calm landscape with no tourist show.", ["nature_photogenic", "hidden_history_folklore"], 90, ["src-mashomack"], { hours: { opens: "09:00", closes: "16:00", status: "verified-seasonal", note: "October hours; call before travel because hunting closures can change access." } });
D("south-ferry", "South Ferry to North Haven", "short-vehicle-ferry", "Shelter Island", "NY", "2026-10-05", "A five-minute car ferry from wooded Shelter Island across to the South Fork and the road to Sag Harbor.", "The second short crossing finishes the island loop and means no driving back the way we came.", ["sheluvspaco", "viki"], ["gora", "stivka"], "Good for Paco and Viki as a second, smaller ferry moment. Everyone gains by not repeating the same road.", ["nature_photogenic", "unusual_creative"], 10, ["src-south-ferry"], { cost: { amount_per_person: 9, status: "verified-current", note: "Two standard cars divided among four travelers; cash required." } });
D("parrish-art-museum", "Parrish Art Museum", "contemporary-art-museum", "Water Mill", "NY", "2026-10-05", "A long low museum shaped like two barns, designed by the Swiss architects Herzog & de Meuron, standing in an open meadow. From 25 September 2026 it holds an exhibition on Abstract Expressionism.", "A beautiful building full of light, and the story of why so many artists moved out to this coast.", ["viki", "stivka"], ["sheluvspaco", "gora"], "Good for Viki's strong architecture and landscape photos, and for Stivka's thoughtful art talk. Paco gets an easy indoor stop everyone accepts.", ["architecture_photogenic", "unusual_creative"], 105, ["src-parrish"], { hours: { opens: "11:00", closes: "17:00", status: "verified", note: "Thursday-Monday hours." }, cost: { amount_per_person: 20, status: "verified", note: "Adult admission." } });
D("big-duck", "The Big Duck", "mimetic-roadside-architecture", "Flanders", "NY", "2026-10-05", "A farm shop from 1931 built in the shape of a giant white duck. Architects still use the word 'duck' for any building shaped like the thing it sells.", "Fifteen minutes, one enormous concrete duck, and a real place in architecture history. This is the stop that becomes the group joke.", ["viki", "gora"], ["sheluvspaco", "stivka"], "Good for Viki's strange memory photo, and for Gora, who likes the real story behind a ridiculous object.", ["architecture_photogenic", "unusual_creative", "hidden_history_folklore"], 30, ["src-big-duck"], { priority: "supporting", hours: { opens: "10:00", closes: "17:00", status: "verified-call-ahead", note: "County lists daily hours but asks visitors to confirm by phone." } });
D("tanger-riverhead", "Tanger Outlets Riverhead", "outlet-shopping", "Riverhead", "NY", "2026-10-05", "A large outlet center with Nike, Coach, Armani, Under Armour and dozens of other discount brand shops.", "A proper shopping block, planned on purpose so it does not eat into a nature or museum day.", ["viki"], ["sheluvspaco", "gora", "stivka"], "Built around Viki's love of outlets. The others can split off to sportswear, coffee or an early check-in with no argument.", ["food_coffee_shopping"], 180, ["src-tanger"], { priority: "supporting", hours: { opens: "10:00", closes: "20:00", status: "verified-current", note: "Center hours; individual stores may vary." }, cost: { amount_per_person: 0, status: "verified", note: "No admission; personal shopping excluded from budget." } });
D("long-island-aquarium", "Long Island Aquarium", "interactive-aquarium", "Riverhead", "NY", "2026-10-05", "A small waterfront aquarium with a large living coral reef, a 120,000-gallon shark tank, touch tanks and butterflies.", "The safe choice in bad weather, and it also cuts driving on the South Fork. Everyone finds something here.", ["sheluvspaco", "viki"], ["gora", "stivka"], "Good for Paco's wish to keep the group balanced, and for Viki's close-up color photos. The touch tanks keep it social.", ["unusual_creative", "nature_photogenic"], 150, ["src-aquarium"], { hours: { opens: "10:00", closes: "16:00", status: "verified", note: "Open daily except Thanksgiving and Christmas." }, cost: { amount_per_person: 35, status: "planning-estimate", note: "Confirm 2026 walk-up price." }, replacement_reason: "Replace Parrish and the Big Duck when weather is poor or the group wants one indoor consensus anchor with less driving." });
D("cradle-of-aviation", "Cradle of Aviation Museum", "aviation-space-museum", "Garden City", "NY", "2026-10-06", "A museum of aircraft built on Long Island, including a real Grumman lunar module. It shows how factories in this suburban corridor helped put people on the Moon.", "A real Moon lander, built a few miles away. Serious engineering history, and not another war museum.", ["gora", "viki"], ["stivka", "sheluvspaco"], "Good for Gora's love of engineering and hidden history, and for Viki's photos of spacecraft up close. Stivka gets a hopeful human story.", ["architecture_photogenic", "unusual_creative", "hidden_history_folklore"], 150, ["src-cradle"], { hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Tuesday-Sunday." }, cost: { amount_per_person: 18, status: "verified", note: "Museum-only adult admission." } });
D("asbury-boardwalk", "Asbury Boardwalk, Convention Hall & Carousel Ruins", "boardwalk-architecture-walk", "Asbury Park", "NJ", "2026-10-06", "A seafront of grand old music halls, painted murals, weathered concrete and the roofless shell of an old carousel building.", "Beautiful decay next to new paint. The photos are strong, and the story of the town falling apart and coming back is real.", ["viki", "stivka"], ["gora", "sheluvspaco"], "Good for Viki's architecture and ocean images, and for Stivka's interest in music history. Gora gets the harder story behind the rebuilding.", ["architecture_photogenic", "nature_photogenic", "hidden_history_folklore"], 75, ["src-asbury"], { priority: "supporting" });
D("silverball-asbury", "Silverball Retro Arcade", "free-play-pinball-museum", "Asbury Park", "NJ", "2026-10-06", "Rows of restored pinball and arcade machines, all set to free play after one entry ticket, directly across from the ocean.", "Pay once and play everything. Four people can compete, wander off and come back with no planning at all.", ["sheluvspaco", "viki"], ["gora", "stivka"], "Good for Paco's group energy and for Viki's neon photos. Gora and Stivka get old machines and rock-era nostalgia.", ["unusual_creative", "live_social_nightlife"], 120, ["src-silverball"], { hours: { opens: "10:00", closes: "24:00", status: "verified", note: "Sunday-Thursday hours." }, cost: { amount_per_person: 20, status: "verified", note: "Half-day pass; one-hour and all-day options exist." } });
D("asbury-live-music", "Asbury Live-Music Night", "live-music-district", "Asbury Park", "NJ", "2026-10-06", "A night out across the Stone Pony, the Wonder Bar, House of Independents and smaller rooms nearby. We only commit if the actual line-up is good.", "Asbury Park only gets a big night if the bands are worth it. No generic club as a backup.", ["stivka", "gora"], ["viki", "sheluvspaco"], "Good for Stivka's love of rock and metal, and for Gora's social side. Viki gets a whole walkable district instead of one room.", ["live_social_nightlife"], 240, ["src-asbury"], { reservation: "when-calendar-locks", hours: { opens: "19:00", closes: "24:00", status: "calendar-gated", note: "No suitable October 6 act is published yet; choose among official venue calendars 4-6 weeks out." }, cost: { amount_per_person: 45, status: "planning-estimate", note: "Ticket/drinks excluded from the core budget target." } });
D("ocean-grove", "Ocean Grove Great Auditorium & Tent City", "spiritual-architecture-walk", "Ocean Grove", "NJ", "2026-10-06", "A Methodist camp town where canvas tents are still attached to small wooden cottages, laid out in a grid around a wooden auditorium seating 6,250 people. Alcohol is not sold here.", "A tent city that has been lived in every summer for 150 years, around a huge wooden hall. Strange, calm, and completely unlike Asbury next door.", ["stivka", "viki"], ["gora", "sheluvspaco"], "Good for Stivka's interest in faith and music, and for Viki's unlikely tent architecture. We visit as guests of a living community.", ["architecture_photogenic", "orthodox_spiritual", "hidden_history_folklore"], 90, ["src-ocean-grove"], { hours: { opens: "08:00", closes: "18:00", status: "self-guided-exterior", note: "Official landmark walk works in October; interior auditorium tours are summer-only." }, replacement_reason: "Choose for a no-detour, low-cost spiritual-architecture morning when the aviation museum feels too institutional." });
D("lucy-elephant", "Lucy the Elephant", "zoomorphic-building", "Margate City", "NJ", "2026-10-07", "A six-story building from 1881 shaped like an elephant. You climb a spiral staircase inside her body and come out in the little room on her back, looking at the sea.", "You go inside a giant elephant and out onto her back. Silly on the surface, with a real story of people saving her from demolition.", ["viki", "sheluvspaco"], ["gora", "stivka"], "Good for Viki's strange architecture photos and Paco's sense of fun. The guided climb gives the others the real building story.", ["architecture_photogenic", "unusual_creative", "hidden_history_folklore"], 60, ["src-lucy"], { reservation: "recommended", hours: { opens: "10:00", closes: "20:00", status: "verified-current", note: "Wednesday hours; tours every 45 minutes, subject to change." }, cost: { amount_per_person: 9, status: "verified-current", note: "Adult guided tour." } });
D("nas-wildwood", "NAS Wildwood Aviation Museum", "working-hangar-aviation-museum", "Lower Township", "NJ", "2026-10-07", "A World War II naval air station museum inside a huge unheated wooden hangar. You can climb into cockpits and get close to engines and aircraft.", "A real hangar, still cold and enormous, with aircraft you can touch. Completely different from a museum behind glass.", ["gora", "viki"], ["stivka", "sheluvspaco"], "Good for Gora's military and engineering interests and for Viki's big industrial images. The cold hangar is part of the experience.", ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], 135, ["src-nas"], { hours: { opens: "10:00", closes: "16:00", status: "verified", note: "March-December daily hours; hangar is not climate controlled." }, cost: { amount_per_person: 16, status: "verified", note: "Adult admission." } });
D("cape-may-victorian", "Cape May Victorian Architecture Walk", "historic-district-walk", "Cape May", "NJ", "2026-10-07", "A seaside district of highly decorated wooden houses with porches, towers and patterned shingles, lit at night by gas-style lamps. Very few American towns kept this many.", "The whole town is the attraction. We walk and look instead of buying tickets for one house.", ["viki", "stivka"], ["gora", "sheluvspaco"], "Good for Viki's photogenic streets and Stivka's interest in old churches and houses. Gora gets the social history behind the resort front.", ["architecture_photogenic", "hidden_history_folklore"], 105, ["src-cape-may-mac"], { priority: "supporting" });
D("cape-may-ghosts", "Cape May Spirits & Oddities Trolley", "folklore-trolley", "Cape May", "NJ", "2026-10-07", "A night trolley tour of ghost stories, Victorian superstitions, grave alarms, photographs of the dead and other strange old customs.", "Folklore and dark local history after dark, and it keeps the evening social without turning into a club night.", ["viki", "gora"], ["stivka", "sheluvspaco"], "Good for Viki's love of unusual places and for Gora's interest in uncomfortable history. Stivka can enjoy the stories without confusing them with faith.", ["hidden_history_folklore", "live_social_nightlife", "unusual_creative"], 90, ["src-cape-may-mac"], { reservation: "required-when-calendar-opens", hours: { opens: "18:00", closes: "21:30", status: "calendar-gated", note: "Choose the actual October 7 departure when the date grid is released; do not substitute an unreviewed operator." }, cost: { amount_per_person: 25, status: "planning-estimate", note: "Confirm exact 2026 tour price." } });
D("sunset-beach-atlantus", "Sunset Beach & SS Atlantus", "shipwreck-sunset-stop", "Cape May Point", "NJ", "2026-10-07", "A free beach facing west, where the broken remains of a concrete ship from the First World War still sit just offshore. The sand holds polished quartz pebbles.", "A concrete ship that sank where it stands, seen at sunset. Free, strange, and it works in almost any weather.", ["viki", "gora"], ["stivka", "sheluvspaco"], "Good for Viki's sunset and shipwreck photo and for Gora's interest in things that failed. It gives everyone air before the ghost tour.", ["nature_photogenic", "hidden_history_folklore", "unusual_creative"], 75, ["src-cape-point"], { hours: { opens: "08:00", closes: "20:00", status: "verified-park-window", note: "State park gate is 8:00-20:00; the adjacent beach is visited only in daylight." }, replacement_reason: "Use when Lucy's tour timing is inconvenient or the group wants a free natural-and-industrial sunset anchor." });
D("cape-may-lewes-ferry", "Cape May-Lewes Ferry", "vehicle-ferry-experience", "North Cape May", "NJ", "2026-10-08", "An 85-minute car ferry across Delaware Bay, with open decks, lighthouse views and a real chance of seeing dolphins.", "The crossing is the best part of the day, and it avoids driving back through the Philadelphia corridor.", ["viki", "sheluvspaco"], ["gora", "stivka"], "Good for Viki's sea and lighthouse photos and for Paco's route design. Everyone is forced to slow down for a while.", ["nature_photogenic", "unusual_creative"], 85, ["src-cmlf"], { reservation: "required-for-two-cars", hours: { opens: null, closes: null, status: "date-specific", note: "Book the published October 8 morning sailing and check in 30 minutes early." }, cost: { amount_per_person: 35, status: "planning-estimate", note: "Two standard vehicles and four adults divided per traveler." } });
D("fort-miles", "Fort Miles: Battery 519", "coastal-defense-museum", "Lewes", "DE", "2026-10-08", "An underground World War II gun battery built to defend Delaware Bay, hidden under the dunes. It holds a 12-inch gun, mine-laying equipment and an outdoor artillery park.", "A whole fort buried under a beautiful beach. You walk into the concrete and see what the dunes were really hiding.", ["gora", "stivka"], ["viki", "sheluvspaco"], "Good for Gora's military history and Stivka's serious historical conversation. Viki gets the contrast of concrete against sand.", ["hidden_history_folklore", "architecture_photogenic"], 120, ["src-fort-miles"], { reservation: "recommended", hours: { opens: "10:00", closes: "16:00", status: "verified-date-band", note: "Wednesday-Saturday after Labor Day through November 1." }, cost: { amount_per_person: 6, status: "verified", note: "Guided Battery 519 tour; many exhibits are free." } });
D("great-dune-tower", "Great Dune & Fire-Control Tower", "dune-observation-walk", "Lewes", "DE", "2026-10-08", "A short climb over a moving sand dune to one of the concrete towers built to watch the sea for enemy ships.", "Nature and war machinery in the same photograph, from one short walk.", ["viki", "gora"], ["stivka", "sheluvspaco"], "Good for Viki's wide coast images and for Gora, who wants to see how the bay was watched and controlled.", ["nature_photogenic", "architecture_photogenic", "hidden_history_folklore"], 60, ["src-fort-miles"], { priority: "supporting" });
D("berlin-historic", "Berlin Main Street & Atlantic Hotel", "small-town-evening", "Berlin", "MD", "2026-10-08", "A well-preserved Eastern Shore town of brick shopfronts and porches, built around a Victorian hotel that has been part of local life for generations.", "A deliberately quiet evening: walk, eat well, and let two days of ferries and forts settle.", ["viki", "stivka"], ["sheluvspaco", "gora"], "Good for Viki's warm small-town feeling and for Stivka's low-key evening. Paco gets a calm reset before the longest coastal day.", ["architecture_photogenic", "food_coffee_shopping", "hidden_history_folklore"], 120, ["src-cmlf"], { priority: "supporting" });
D("zwaanendael", "Zwaanendael Museum", "maritime-history-museum", "Lewes", "DE", "2026-10-08", "A small museum in a bright Dutch-style building, telling the story of Delaware's first European settlement and its difficult history at sea.", "An odd little building that looks like it was lifted out of Holland, and an easier stop than the bunker if the ferry runs late.", ["viki", "gora"], ["stivka", "sheluvspaco"], "Good for Viki's storybook building and for Gora's interest in settlement and shipwreck history. Stivka gets a small quiet museum.", ["architecture_photogenic", "hidden_history_folklore"], 75, ["src-zwaanendael"], { hours: { opens: "10:00", closes: "16:30", status: "verify-before-booking", note: "State museum hours should be reconfirmed for October 8." }, replacement_reason: "Promote after a late ferry, hard rain or when a compact Dutch-maritime story fits the group better than two bunker hours." });
D("assateague", "Assateague Wild-Horse Golden Hour", "barrier-island-wildlife", "Berlin", "MD", "2026-10-08", "A late-afternoon drive and walk on a barrier island where wild horses move freely through salt marsh, pine woods and open beach. Nothing is staged.", "Wild horses in beautiful light, and nobody can promise where they will be. That uncertainty is the point.", ["viki", "gora"], ["stivka", "sheluvspaco"], "Good for Viki's best nature photos and for Gora's quiet outdoor side. Everyone must keep the official distance and never feed or touch the horses.", ["nature_photogenic", "unusual_creative"], 90, ["src-assateague"], { hours: { opens: "06:00", closes: "20:00", status: "verified", note: "Maryland district is open year-round; wild-horse encounters are never guaranteed." }, cost: { amount_per_person: 13, status: "planning-estimate", note: "Two vehicle passes divided among four travelers." } });
D("nasa-wallops", "NASA Wallops Visitor Center", "rocket-science-center", "Wallops Island", "VA", "2026-10-09", "A free visitor center next to the NASA range that launches small research rockets and giant scientific balloons. These are the missions too small or too strange for Cape Canaveral.", "A real working NASA launch site, right on our road, doing the science that never makes the news.", ["gora", "viki"], ["stivka", "sheluvspaco"], "Good for Gora's interest in what happens outside the famous space programs, and for Viki's photos of rocket hardware.", ["unusual_creative", "hidden_history_folklore"], 60, ["src-wallops"], { hours: { opens: "10:00", closes: "15:00", status: "verified", note: "Thursday-Saturday after October 1; mission operations can close the center." } });
D("barrier-islands-center", "Barrier Islands Center", "island-culture-museum", "Machipongo", "VA", "2026-10-09", "More than 7,500 objects inside a former poorhouse tell how whole communities lived on Virginia's barrier islands until storms and change emptied them.", "An empty-looking coast turns out to have had towns, schools and families on it. Most people drive straight past this story.", ["gora", "viki"], ["stivka", "sheluvspaco"], "Good for Gora's love of forgotten history and for Viki's worn coastal objects. Stivka gets stories of community and survival.", ["hidden_history_folklore", "architecture_photogenic"], 90, ["src-barrier"], { hours: { opens: "10:00", closes: "16:00", status: "verified", note: "Tuesday-Saturday; free admission." } });
D("chesapeake-bridge-tunnel", "Chesapeake Bay Bridge-Tunnel Crossing", "engineering-landscape", "Cape Charles", "VA", "2026-10-09", "A 17-mile crossing of the open mouth of Chesapeake Bay, made of low bridges that twice dive into tunnels under the shipping lanes.", "The road appears to sink into the sea, then comes back up. It is transport and a huge piece of engineering at the same time.", ["viki", "gora"], ["sheluvspaco", "stivka"], "Good for Viki's images of roads in water and for Gora's interest in heavy engineering. Paco gets another drive that feels like a stop.", ["architecture_photogenic", "unusual_creative"], 35, ["src-cbbt"], { cost: { amount_per_person: 8, status: "verified-current", note: "Two off-peak standard-car tolls divided among four travelers." } });
D("norfolk-pagoda", "Norfolk Pagoda & Oriental Garden", "waterfront-garden", "Norfolk", "VA", "2026-10-09", "A Taiwanese pagoda and small garden beside the working Elizabeth River harbor, next to the old Freemason streets.", "A soft, quiet landing in golden light after rockets, lost islands and the bridge-tunnel. We keep it short on purpose.", ["viki", "stivka"], ["sheluvspaco", "gora"], "Good for Viki's architecture reflected in water and for Stivka's need for a quiet moment.", ["architecture_photogenic", "nature_photogenic"], 45, ["src-nauticus"], { priority: "supporting" });
D("cape-charles", "Cape Charles Historic District", "railroad-beach-town", "Cape Charles", "VA", "2026-10-09", "A small grid of streets with porches and old railway and ferry structures. The beach faces west across Chesapeake Bay, which is unusual on this coast.", "A real town and a west-facing sunset, instead of another museum. Easier and slower.", ["viki", "stivka"], ["gora", "sheluvspaco"], "Good for Viki's pastel streets at sunset and for Stivka's love of quiet towns. Gora can follow the old railway and ferry system.", ["architecture_photogenic", "nature_photogenic", "hidden_history_folklore"], 90, ["src-barrier"], { replacement_reason: "Replace Barrier Islands Center when the group wants an outdoor town-and-bay pause or arrives after museum hours." });
D("nauticus-wisconsin", "Nauticus & Battleship Wisconsin", "battleship-maritime-museum", "Norfolk", "VA", "2026-10-10", "A battleship as long as a city block, open from the bridge down to the engine rooms, next to a museum of hands-on harbor exhibits.", "You walk through the whole ship, from the command bridge to the engines. The size alone explains more than any display case.", ["gora", "stivka"], ["viki", "sheluvspaco"], "Good for Gora's love of heavy machines and for Stivka's interest in the lives of the crew. Viki gets huge deck views over the city.", ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], 150, ["src-nauticus"], { reservation: "general-entry-advance", hours: { opens: "09:00", closes: "17:00", status: "verified", note: "Open daily; special below-deck tours cost extra." }, cost: { amount_per_person: 19.95, status: "verified", note: "Adult general admission includes the ship." } });
D("edgar-cayce-are", "Edgar Cayce A.R.E. Headquarters", "metaphysical-archive", "Virginia Beach", "VA", "2026-10-10", "The library and archive built around more than 14,000 trance readings by Edgar Cayce, on health, dreams, faith, Atlantis and psychic experience.", "Believe it or not, it is a remarkable American mix of religion, medicine, business and outsider ideas, all kept in one archive.", ["gora", "stivka"], ["viki", "sheluvspaco"], "Good for Gora's curiosity about disputed ideas and for Stivka's theology talk. We present the claims critically, not as proven.", ["hidden_history_folklore", "orthodox_spiritual", "unusual_creative"], 75, ["src-are"], { hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Saturday visitor center and bookstore hours; library opens at noon." } });
D("vibe-neptune", "ViBe Murals & King Neptune", "public-art-boardwalk-stop", "Virginia Beach", "VA", "2026-10-10", "A 34-foot bronze statue of the sea god Neptune on the seafront, and changing street murals in the small creative district just behind it.", "One famous statue for the photo, then street art two minutes away. Thirty minutes, no more.", ["viki"], ["sheluvspaco", "stivka", "gora"], "Built around Viki's memory photo. The others get coffee, public art and only a short dose of the tourist seafront.", ["architecture_photogenic", "unusual_creative", "food_coffee_shopping"], 30, ["src-are"], { priority: "supporting" });
D("poe-museum-richmond", "Poe Museum & Enchanted Garden", "literary-gothic-museum", "Richmond", "VA", "2026-10-10", "The oldest standing house in Richmond, holding Edgar Allan Poe's manuscripts and belongings, with a garden built around his poems. Two black cats, Edgar and Pluto, live there.", "Poe's own objects, a garden made from his poems, and cats that live in it. The right mood shift after a battleship.", ["viki", "gora"], ["stivka", "sheluvspaco"], "Good for Viki's gothic garden and cat photos, and for Gora's interest in the hard life behind famous writing. Stivka gets themes of death and conscience.", ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], 70, ["src-poe"], { hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Saturday hours; last admission 16:30." }, cost: { amount_per_person: 12, status: "verified", note: "Adult admission." } });
D("hermitage-norfolk", "Hermitage Museum & Gardens", "arts-and-crafts-house", "Norfolk", "VA", "2026-10-10", "An Arts-and-Crafts house on the water, filled with one family's very personal art collection, hand-carved interiors and gardens with sculpture.", "A quieter Norfolk morning: one house, one garden, one collector's taste, instead of three separate stops.", ["viki", "stivka"], ["gora", "sheluvspaco"], "Good for Viki's house and garden photos and for Stivka's calm art side. Gora still gets an unusual collector's story.", ["architecture_photogenic", "nature_photogenic", "unusual_creative"], 105, ["src-hermitage"], { replacement_reason: "Choose in poor ship-deck weather or when the group wants one eccentric waterfront art block instead of the Pagoda, battleship and ViBe photo stops." });
D("richmond-orthodox", "Saints Constantine & Helen Divine Liturgy", "orthodox-cathedral-service", "Richmond", "VA", "2026-10-11", "Sunday Orthros and Divine Liturgy with Richmond's Greek Orthodox community. This is a service we attend, not a building we tour.", "Sunday stays a real Sunday, and the group starts the long drive north with a shared morning.", ["stivka", "gora", "viki", "sheluvspaco"], [], "Good for all four equally, because Orthodox worship is shared ground. Arrive respectfully, follow the parish, and stay for the whole Liturgy if possible.", ["orthodox_spiritual", "architecture_photogenic"], 180, ["src-richmond-orthodox"], { hours: { opens: "08:15", closes: "11:30", status: "weekly-pattern", note: "Official site links weekly Orthros and Liturgy texts; confirm the October 11 bulletin." } });
D("bo-railroad", "B&O Railroad Museum", "railroad-roundhouse-museum", "Baltimore", "MD", "2026-10-11", "The birthplace of American commercial railways, inside a huge round building from 1884. The locomotives run from horse-drawn beginnings to diesel engines.", "The roundhouse alone is a shock when you walk in. Then it explains how railways rebuilt work, war and whole cities.", ["gora", "viki"], ["stivka", "sheluvspaco"], "Good for Gora's love of machines and systems, and for Viki's circular iron and brick architecture. Paco gets a strong stop that works in any weather.", ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], 120, ["src-bo", "src-bo-rides"], { hours: { opens: "10:00", closes: "16:00", status: "verified", note: "Open daily; the 11:30 train ride is missed after Liturgy, so the core visit does not promise it." }, cost: { amount_per_person: 20, status: "verified", note: "Adult admission." } });
D("baltimore-industry", "Baltimore Museum of Industry", "working-industrial-museum", "Baltimore", "MD", "2026-10-11", "An 1865 oyster cannery on the water. Inside there are canning lines, a belt-driven machine shop and printing equipment, with the stories of the people who worked them.", "Smaller than the railway museum, and on Sunday the staff actually run the machines instead of just labeling them.", ["gora", "viki"], ["stivka", "sheluvspaco"], "Good for Gora's interest in work and machinery, and for Viki's cannery textures and harbor views. Stivka gets human stories of craft and migration.", ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], 120, ["src-bmi"], { hours: { opens: "09:00", closes: "16:00", status: "verified", note: "Tuesday-Sunday; Sunday docent-led tours are included except the fourth Sunday." }, cost: { amount_per_person: 15, status: "verified", note: "Adult admission." }, replacement_reason: "Choose when the group wants labor, manufacturing and waterfront texture instead of a second large transportation collection." });
D("mutter-museum", "Mutter Museum", "medical-history-cabinet", "Philadelphia", "PA", "2026-10-12", "A 19th-century medical collection of preserved human specimens, wax models and old instruments. It also asks hard questions about how such remains were collected and displayed.", "It is uncomfortable on purpose, and it opens a real conversation about medicine, consent and what museums once treated as entertainment.", ["gora", "viki"], ["stivka", "sheluvspaco"], "Good for Gora's appetite for difficult history and Viki's love of unusual institutions. Photography rules and respect for human remains matter more here than photos.", ["hidden_history_folklore", "unusual_creative", "architecture_photogenic"], 135, ["src-mutter"], { reservation: "recommended", hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Open Wednesday-Monday; reconfirm federal-holiday operations and current photography policy." }, cost: { amount_per_person: 20, status: "planning-estimate", note: "Confirm the 2026 timed-ticket price." } });
D("metuchen-main-street", "Metuchen Main Street Reset", "walkable-small-town-center", "Metuchen", "NJ", "2026-10-12", "A small railway town known locally as the Brainy Borough, with an independent bookshop and cafe center rather than a tourist district.", "Deliberately not an attraction: dinner, a short walk and sleep, right beside the road north after three days of heavy traffic.", ["sheluvspaco", "viki"], ["stivka", "gora"], "Good for Paco's management of group tiredness and for Viki's love of small cafes. Everyone gains from an evening with no expectations.", ["food_coffee_shopping", "architecture_photogenic"], 90, ["src-metuchen"], { priority: "supporting" });
D("andalusia-estate", "Andalusia Historic House, Gardens & Arboretum", "riverside-estate-and-gardens", "Andalusia", "PA", "2026-10-12", "A Greek Revival house on the Delaware River with formal gardens and native woodland. In 2026 it shows an exhibition on how the Biddle family split during the Revolution.", "River light, columns and gardens instead of a dark medical collection, and it stays close to the highway.", ["viki", "stivka"], ["gora", "sheluvspaco"], "Good for Viki's house and garden photos and for Stivka's calm architecture. Gora gets political contradictions instead of a tidy founding story.", ["architecture_photogenic", "nature_photogenic", "hidden_history_folklore"], 135, ["src-andalusia"], { reservation: "recommended-if-promoted", hours: { opens: "10:00", closes: "15:00", status: "holiday-gated", note: "The 2026 season lists Mondays, but October 12 is a federal holiday; call before promotion and target the 10:30 house tour." }, cost: { amount_per_person: 30, status: "verified", note: "Big House tour plus gardens." }, replacement_reason: "Choose when the group wants daylight, architecture and Revolutionary family history instead of anatomical collections; promote only after the holiday opening is confirmed." });
D("sleepy-hollow-cemetery", "Sleepy Hollow Cemetery", "literary-garden-cemetery", "Sleepy Hollow", "NY", "2026-10-13", "A 90-acre cemetery of winding paths and steep ravines above the Pocantico River. Washington Irving, Andrew Carnegie and Walter Chrysler are all buried here.", "The real ground behind the legend, and the real people, before the theatrical pumpkin night.", ["gora", "stivka"], ["viki", "sheluvspaco"], "Good for Gora's historical context and Stivka's reflective side. Viki can photograph the landscape and sculpture without treating graves as content.", ["nature_photogenic", "architecture_photogenic", "hidden_history_folklore"], 90, ["src-cemetery"], { hours: { opens: "08:00", closes: "16:30", status: "verified", note: "Daily visiting hours; follow the cemetery's funeral-level standard of respect." } });
D("old-dutch-church", "Old Dutch Church & Burying Ground", "historic-churchyard", "Sleepy Hollow", "NY", "2026-10-13", "A church from about 1685 with a three-acre burial ground, written directly into Irving's story. Some graves here may belong to the real people behind Brom Bones and Katrina Van Tassel.", "This is where the architecture, the faith, the community and the legend actually meet in one place.", ["stivka", "gora"], ["viki", "sheluvspaco"], "Good for Stivka's church history and for Gora's wish to separate the real record from later invention. We enter as an active place of worship.", ["orthodox_spiritual", "architecture_photogenic", "hidden_history_folklore"], 45, ["src-old-dutch"], { hours: { opens: "09:00", closes: "16:30", status: "verified-grounds", note: "Grounds close 16:30; church interior access varies in October." } });
D("headless-horseman", "Headless Horseman Bridge & Statue", "folklore-landscape-stop", "Sleepy Hollow", "NY", "2026-10-13", "The modern bridge and the sculpture near the spot where Irving set the Horseman's pumpkin throw. The bridge is a replacement, not the original colonial one.", "The famous image, with an honest note: this is where the story was set, not an untouched piece of the 1700s.", ["viki", "gora"], ["sheluvspaco", "stivka"], "Good for Viki's folklore photo and for Gora, who wants to know what is genuine and what is just repeated online.", ["architecture_photogenic", "hidden_history_folklore"], 30, ["src-sleepy"], { priority: "supporting" });
D("pumpkin-blaze", "Great Jack O'Lantern Blaze", "immersive-pumpkin-night", "Croton-on-Hudson", "NY", "2026-10-13", "More than 7,000 carved pumpkins built into moving creatures, buildings and a firelit Headless Horseman trail in the grounds of Van Cortlandt Manor.", "The big theatrical finish of the trip, and it only exists on these exact October dates.", ["viki", "sheluvspaco"], ["gora", "stivka"], "Good for Viki's night photography and Paco's group finale. Gora and Stivka get folklore shown openly as art, not sold as truth.", ["unusual_creative", "live_social_nightlife", "hidden_history_folklore"], 60, ["src-blaze"], { reservation: "required-now", hours: { opens: "18:30", closes: "22:00", status: "verified-date-specific", note: "October 13, 2026 tickets are on sale; select a 19:00-19:30 slot." }, cost: { amount_per_person: 38, status: "verified-range", note: "Standard timed tickets vary by entry time." } });
D("rockefeller-arts", "David Rockefeller Creative Arts Center", "adaptive-reuse-art-center", "Tarrytown", "NY", "2026-10-13", "A former glasshouse on the Rockefeller estate, rebuilt as a low-carbon gallery and performance space.", "The modern architecture choice if the weather, the crowds or the group's energy argue against three folklore stops in a row.", ["viki", "stivka"], ["gora", "sheluvspaco"], "Good for Viki's reused architecture and Stivka's quieter art preference. Gora gets material and institutional history instead of another legend.", ["architecture_photogenic", "unusual_creative"], 90, ["src-rockefeller"], { hours: { opens: "11:00", closes: "15:00", status: "verify-exhibition-calendar", note: "Promote only after October 13 public access and exhibition hours are confirmed." }, replacement_reason: "Use for rain, cemetery fatigue or a preference for contemporary design while retaining the Blaze at night." });
D("pez-visitor-center", "PEZ Visitor Center & Factory Window", "candy-design-museum", "Orange", "CT", "2026-10-14", "The world's largest PEZ dispenser, a hundred years of packaging design, rare character heads, and windows looking onto the real packing line on weekdays.", "Cheap, silly and completely specific. Exactly the right last laugh before the drive back to Boston.", ["viki", "sheluvspaco"], ["gora", "stivka"], "Good for Viki's colorful product photos and Paco's mood on the final day. Gora can read the manufacturing history instead of treating it as a shop.", ["unusual_creative", "food_coffee_shopping", "hidden_history_folklore"], 75, ["src-pez"], { hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Open Wednesday; production normally runs weekdays but is not guaranteed." }, cost: { amount_per_person: 5, status: "verified", note: "Includes a $2 same-day shop credit and souvenir lanyard." } });
D("barker-cartoon-museum", "Barker Character, Comic & Cartoon Museum", "private-pop-culture-collection", "Cheshire", "CT", "2026-10-14", "Four crowded rooms holding more than 80,000 toys, lunchboxes, character objects and animation pieces, from 1873 to today.", "Everyone will find a childhood character they had forgotten. It is also further inland, which leaves more time margin for the drive home.", ["viki", "sheluvspaco"], ["gora", "stivka"], "Good for Viki's colorful nostalgia and Paco's group banter. Gora can follow how toys were made; Stivka can hunt rock and cartoon crossovers.", ["unusual_creative", "hidden_history_folklore", "food_coffee_shopping"], 90, ["src-barker"], { hours: { opens: "11:00", closes: "17:00", status: "verified-2026", note: "Wednesday off-season hours are explicitly published for 2026." }, cost: { amount_per_person: 5, status: "verified", note: "Adult admission." }, replacement_reason: "Choose when the group wants a denser, weirder pop-culture finale and more road margin than the coastal PEZ baseline." });

const seedPlaces = detailRows.map((record) => {
  const base = baseById.get(record.id);
  if (!base) throw new Error(`No research config for ${record.id}`);
  const variant = replacementByPlace.get(record.id);
  const priority = variant ? "replacement" : (record.priority || "anchor");
  return {
    ...record,
    address: base.geocode,
    priority,
    reservation: record.reservation || "none",
    hours: record.hours || { opens: null, closes: null, status: "public-space-or-confirm", note: "Confirm any interior access close to travel." },
    cost: record.cost || { amount_per_person: 0, status: "free", note: "No admission planned." },
    replacement: variant ? {
      day: variant.day,
      replaces_place_ids: variant.replaces_place_ids,
      route_variant_id: variant.id,
      reason: record.replacement_reason
    } : undefined
  };
});

if (seedPlaces.length !== researchPlaces.length) {
  throw new Error(`Detail/config count mismatch: ${seedPlaces.length}/${researchPlaces.length}`);
}

const dayPlans = [
  { day: 1, date: "2026-10-04", sleep_city: "Greenport, NY", theme: "American Impressionism, open water and a harbor-village arrival", schedule: [["14:15", "15:45", "florence-griswold", "anchor"], ["17:00", "18:20", "cross-sound-ferry", "anchor"], ["18:45", "20:00", "greenport-waterfront", "supporting"]], lodging: { preferred_area: "Greenport village within walking distance of Mitchell Park", fallback_area: "Southold along NY-25 with recent cleanliness reviews and secure parking", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Book only after the Cross Sound vehicle sailing is locked; prioritize simple, clean inventory over resort extras." }, fallback: "Promote The Book Barn only if its 18:00 closing still fits the actual Boston handoff; otherwise protect the ferry and treat Greenport as the first experience." },
  { day: 2, date: "2026-10-05", sleep_city: "Riverhead, NY", theme: "Two tiny ferries, marsh silence, severe architecture and outlet time", schedule: [["08:15", "08:30", "north-ferry", "supporting"], ["09:00", "10:30", "mashomack-preserve", "anchor"], ["10:50", "11:05", "south-ferry", "supporting"], ["11:35", "13:20", "parrish-art-museum", "anchor"], ["14:00", "14:30", "big-duck", "supporting"], ["14:50", "17:50", "tanger-riverhead", "supporting"]], lodging: { preferred_area: "Riverhead near Route 58 with staffed reception and well-lit parking", fallback_area: "Aquebogue or Calverton only with strong recent cleanliness reviews", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "A practical highway hotel is preferable because the next morning crosses Long Island before New York traffic builds." }, fallback: "Promote Long Island Aquarium for rain or decision fatigue, replacing Parrish and the Big Duck while preserving a generous shopping block." },
  { day: 3, date: "2026-10-06", sleep_city: "Asbury Park, NJ", theme: "A lunar module, seaside ruins, unlimited pinball and a calendar-gated rock night", schedule: [["10:00", "12:30", "cradle-of-aviation", "anchor"], ["15:20", "16:35", "asbury-boardwalk", "supporting"], ["16:45", "18:45", "silverball-asbury", "anchor"], ["19:45", "23:45", "asbury-live-music", "anchor"]], lodging: { preferred_area: "Asbury Park waterfront or Cookman Avenue with staffed parking", fallback_area: "Ocean Grove or West Long Branch with strong two-room inventory", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Park both cars before the evening and walk or rideshare; do not leave luggage visible." }, fallback: "Promote Ocean Grove's Great Auditorium and tent-city exterior walk when the group wants spiritual architecture and less institutional time; the Asbury evening remains optional until a real bill is published." },
  { day: 4, date: "2026-10-07", sleep_city: "Cape May, NJ", theme: "An elephant you can climb, an authentic naval hangar and Victorian oddities after dark", schedule: [["10:00", "11:00", "lucy-elephant", "anchor"], ["12:25", "14:40", "nas-wildwood", "anchor"], ["15:10", "16:55", "cape-may-victorian", "supporting"], ["19:00", "20:30", "cape-may-ghosts", "anchor"]], lodging: { preferred_area: "Cape May historic district with onsite or guaranteed parking", fallback_area: "West Cape May or Lower Township with a short rideshare into town", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Historic inns are suggestions, not a requirement; recent cleanliness, private baths and secure two-car parking come first." }, fallback: "Promote Sunset Beach and the SS Atlantus when Lucy's interior tour timing fails or the group wants sunset nature instead of a second ticketed building." },
  { day: 5, date: "2026-10-08", sleep_city: "Chincoteague, VA", theme: "A bay crossing, buried artillery, an overlooked town and wild horses at golden hour", schedule: [["08:30", "09:55", "cape-may-lewes-ferry", "anchor"], ["10:35", "12:20", "fort-miles", "anchor"], ["12:25", "13:10", "great-dune-tower", "supporting"], ["14:20", "15:20", "berlin-historic", "supporting"], ["15:40", "17:10", "assateague", "anchor"]], lodging: { preferred_area: "Chincoteague town near Main Street with exterior-lighted parking", fallback_area: "Mainland Wallops/Chincoteague Road only if cleanliness and two-room inventory are materially better", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Chincoteague replaces Berlin as the sleep point so the next coastal day remains legal; dinner and the waterfront are the quiet-night experience." }, fallback: "Promote Zwaanendael Museum when wind, rain or limited Battery 519 capacity makes the fort poor value; leave Berlin and Assateague on time because the Chincoteague transfer is cap-sensitive." },
  { day: 6, date: "2026-10-09", sleep_city: "Norfolk, VA", theme: "Small-program rockets, vanished island communities and a road beneath the sea", schedule: [["10:00", "11:00", "nasa-wallops", "anchor"], ["12:25", "13:55", "barrier-islands-center", "anchor"], ["15:00", "15:35", "chesapeake-bridge-tunnel", "supporting"]], lodging: { preferred_area: "Norfolk airport/Military Highway with a staffed hotel and secure lot", fallback_area: "North Norfolk near I-64 only after checking the Saturday museum transfer", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "The practical airport-side sleep point splits two driving days; keep the evening quiet and do not drive downtown merely for dinner." }, fallback: "Promote Cape Charles for porches, old rail-ferry traces and Chesapeake views if Barrier Islands Center timing fails or the group wants outdoor town energy." },
  { day: 7, date: "2026-10-10", sleep_city: "Richmond, VA", theme: "Harbor calm, battleship scale, disputed knowledge and a gothic garden", schedule: [["08:20", "08:50", "norfolk-pagoda", "supporting"], ["09:00", "11:15", "nauticus-wisconsin", "anchor"], ["12:00", "13:15", "edgar-cayce-are", "anchor"], ["13:25", "13:55", "vibe-neptune", "supporting"], ["16:05", "16:55", "poe-museum-richmond", "anchor"]], lodging: { preferred_area: "Richmond West End near Malvern Avenue with secure parking", fallback_area: "Short Pump near I-64 with strong two-room inventory", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "West End placement protects Sunday morning Liturgy; Poe is the first cut if Hampton Roads or I-64 live traffic threatens its 16:30 last entry." }, fallback: "Promote the Hermitage Museum and Gardens when ship-deck weather is poor or the group wants eccentric domestic art instead of another large machine." },
  { day: 8, date: "2026-10-11", sleep_city: "Baltimore East, MD", theme: "A real Orthodox Sunday followed by America's railroad cathedral", schedule: [["08:15", "11:30", "richmond-orthodox", "anchor"], ["14:00", "16:00", "bo-railroad", "anchor"]], lodging: { preferred_area: "Baltimore East near I-95 with staffed reception and well-lit parking", fallback_area: "Essex or the southeast side only if recent safety reviews and parking are strong", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "This utilitarian sleep point protects both the Richmond-Baltimore and Philadelphia-New Jersey driving days." }, fallback: "Promote Baltimore Museum of Industry when the group wants a smaller working-machinery and labor-history museum instead of the B&O roundhouse." },
  { day: 9, date: "2026-10-12", sleep_city: "Metuchen, NJ", theme: "Medical ethics, difficult history and an intentionally easy evening", schedule: [["10:30", "12:45", "mutter-museum", "anchor"], ["17:30", "19:00", "metuchen-main-street", "supporting"]], lodging: { preferred_area: "Metuchen or Edison near I-287 with a staffed hotel and secure lot", fallback_area: "Woodbridge only if the Sleepy Hollow live route remains within the cap", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "No collection photograph is worth disrespecting human remains; October 12 holiday operations and current museum photography rules get a final check." }, fallback: "Promote Andalusia's 10:30 house tour and gardens only after confirming it opens on the October 12 federal holiday; leave greater Philadelphia on time because this bed-to-bed leg is traffic-sensitive." },
  { day: 10, date: "2026-10-13", sleep_city: "Fairfield, CT", theme: "The landscape behind the Headless Horseman and a firelit pumpkin finale", schedule: [["10:15", "11:45", "sleepy-hollow-cemetery", "anchor"], ["12:00", "12:45", "old-dutch-church", "anchor"], ["12:45", "13:15", "headless-horseman", "supporting"], ["19:00", "20:00", "pumpkin-blaze", "anchor"]], lodging: { preferred_area: "Fairfield beside I-95 with late check-in and well-lit parking", fallback_area: "Bridgeport's west side or Stratford only after checking the final-day live ETA", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Reserve a late check-in and leave Croton promptly; the gap before Blaze is for a meal and rest, not another attraction." }, fallback: "Promote the David Rockefeller Creative Arts Center for cemetery fatigue or rain, but only after confirming October 13 public hours; the exact-date Blaze remains the evening anchor." },
  { day: 11, date: "2026-10-14", sleep_city: "Boston, MA", theme: "A candy-design laugh and a protected airport return", schedule: [["10:00", "11:15", "pez-visitor-center", "anchor"]], lodging: { preferred_area: "Logan Airport hotel with confirmed early shuttle", fallback_area: "East Boston or Revere only with a verified airport transfer", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Boston sightseeing is intentionally excluded; returning the cars and protecting the October 15 airport maximum matter more." }, fallback: "Promote Barker's 80,000-object cartoon-and-toy maze for a weirder final laugh and a more comfortable inland road baseline; the airport deadline still wins." }
];

function personFit(record, person) {
  if (record.best_for.includes(person)) return 5;
  if (record.secondary_for.includes(person)) return 4;
  return person === "sheluvspaco" ? 3.8 : 3.4;
}

function scheduleItem(tuple, placeById) {
  const [start, end, placeId, priority] = tuple;
  const record = placeById.get(placeId);
  if (!record) throw new Error(`Unknown place ${placeId}`);
  return { start, end, place_id: placeId, priority, reservation: record.reservation };
}

async function main() {
  const [research, weather, geometry, replacements] = await Promise.all([
    readFile(path.join(ROUTE_DIR, "research-raw.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "weather-normals.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "route-geometry.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "replacement-geometry.json"), "utf8").then(JSON.parse)
  ]);
  const replacementGeometryById = new Map(replacements.variants.map((variant) => [variant.id, variant]));
  const images = [];
  const productionPlaces = seedPlaces.map((record) => {
    const raw = research.places[record.id];
    const coordinates = manualCoordinates[record.id] || (raw?.selected_coordinate ? [raw.selected_coordinate.longitude, raw.selected_coordinate.latitude] : null);
    if (!coordinates) throw new Error(`Missing coordinates for ${record.id}`);
    const imageIds = (raw?.selected_images || []).slice(0, 8).map((image, index) => {
      const id = `img-${record.id}-${index + 1}`;
      images.push({
        id, place_id: record.id, title: image.title, description: image.description,
        search_query: image.search_query, local_path: image.local_path,
        source_page: image.source_page, source_file_url: image.original_url,
        creator: image.creator, credit: image.credit, license: image.license,
        license_url: image.license_url, alt: image.description || `${record.name} photograph`,
        coverage: contextualImagePlaces.has(record.id) ? "place-or-local-context" : "exact-place-or-experience",
        production_usable: image.production_usable ?? image.license !== "Unknown",
        rights_status: image.rights_status || "commons-license-recorded",
        visual_review: image.review_status === "reviewed" ? "reviewed" : "pending-final-review"
      });
      return id;
    });
    const routeVariant = record.replacement ? replacementGeometryById.get(record.replacement.route_variant_id) : null;
    return {
      ...record,
      country: "US",
      coordinates,
      coordinate_order: "longitude_latitude",
      coordinate_source: manualCoordinates[record.id] ? "manual_verified_address" : "openstreetmap_nominatim",
      image_ids: imageIds,
      ratings: { traveler_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), average: null, rating_count: 0 },
      researcher_person_fit: Object.fromEntries(PEOPLE.map((person) => [person, personFit(record, person)])),
      included_in_magic_score: record.priority !== "replacement",
      replacement: record.replacement ? { ...record.replacement, route_variant: routeVariant } : undefined,
      data_status: imageIds.length >= 3 ? "complete" : "image-gap"
    };
  });
  const placeById = new Map(productionPlaces.map((record) => [record.id, record]));
  const weatherByDay = new Map(weather.days.map((day) => [day.day, day]));
  const geometryByDay = new Map(geometry.days.map((day) => [day.day, day]));
  const comfort = [3.8, 3.9, 3.9, 4.0, 4.1, 4.3, 4.2, 4.0, 3.9, 3.7, 3.6];
  const days = dayPlans.map((plan) => {
    const routed = geometryByDay.get(plan.day);
    const normal = weatherByDay.get(plan.day);
    if (!routed || !normal) throw new Error(`Missing routed/weather data for day ${plan.day}`);
    const capStatus = routed.baseline_total_minutes >= 205 || routed.planning_total_minutes.high > 210 ? "live-traffic-gated" : routed.baseline_total_minutes >= 185 ? "near-cap" : "comfortable";
    return {
      ...plan,
      day_of_week: new Intl.DateTimeFormat("en-US", { weekday: "long", timeZone: "America/New_York" }).format(new Date(`${plan.date}T12:00:00-04:00`)),
      drive: {
        legs: routed.legs,
        baseline_total_miles: routed.baseline_total_miles,
        baseline_total_minutes: routed.baseline_total_minutes,
        non_driving_travel_minutes: routed.non_driving_travel_minutes || 0,
        total_travel_minutes_excluding_queues: routed.total_travel_minutes_excluding_queues || routed.baseline_total_minutes,
        planning_total_minutes: routed.planning_total_minutes,
        traffic_risk: routed.risk,
        cap_minutes: 210,
        cap_status: capStatus,
        fallback: plan.fallback
      },
      schedule: plan.schedule.map((item) => scheduleItem(item, placeById)),
      weather: {
        kind: "historical_normal",
        high_c: normal.normal_high_c,
        low_c: normal.normal_low_c,
        precipitation_probability_percent: normal.measurable_precipitation_probability_percent,
        comfort_score: comfort[plan.day - 1],
        station_id: normal.station_id,
        station_name: normal.station_name,
        station_role: normal.station_role,
        source_id: "src-noaa-normals",
        forecast_status: "replace_with_live_forecast_10_days_before"
      }
    };
  });
  const knownCore = productionPlaces
    .filter((record) => record.included_in_magic_score && record.kind !== "live-music-district")
    .reduce((sum, record) => sum + (record.cost.amount_per_person || 0), 0);
  const route = {
    schema_version: "1.0.0",
    route: {
      id: ROUTE_ID, slug: "wild-shore-rockets-folklore-loop", name: ROUTE_NAME, short_name: "Wild Shore & Rockets",
      status: "researched", map_color: "#00A8A8", timezone: "America/New_York",
      start_date: "2026-10-04", end_date: "2026-10-14", airport_date: "2026-10-15",
      origin: { name: "Boston Logan Rental Car Center", coordinates: lodgingNodes["boston-logan-rental"].coordinates },
      destination: { name: "Boston Logan hotel zone", coordinates: lodgingNodes["boston-logan-hotel"].coordinates },
      endpoint_city: "Norfolk, VA",
      direction: "Atlantic ferries and barrier islands south; Norfolk and Richmond apex; Baltimore, Delaware, Sleepy Hollow and coastal Connecticut north",
      countries: ["US"], canada_included: false, total_nights: 11, road_nights: 10, final_boston_nights: 1,
      baseline_total_miles: geometry.route_baseline_total_miles,
      summary: "A warmer-leaning Atlantic loop where ferries replace highway monotony: Long Island marshes and architecture, Asbury pinball and live music, Cape May oddities, Fort Miles, Assateague horses, NASA Wallops, the Chesapeake Bay Bridge-Tunnel, Norfolk and Richmond, Orthodox Sunday, industrial history and an exact-date Sleepy Hollow finale."
    },
    constraints: {
      travelers: 4, cars: 2, cars_follow_same_route: true,
      daily_drive_target_minutes: [120, 180], daily_drive_hard_cap_minutes: 210,
      max_big_nights_out: 4, planned_big_nights_out: 1,
      max_athletic_adrenaline_spots: 2, planned_athletic_adrenaline_spots: 0,
      hike_soft_cap_miles: 6,
      lodging_rooms: [{ count: 1, beds: 1 }, { count: 1, beds: 2 }],
      lodging_priorities: ["safe", "clean", "comfortable", "two-room inventory", "secure parking"],
      visa_policy: "US-only route with no Canada border crossing or J-1 re-entry dependency.",
      budget_target_per_person_usd: 1500,
      budget_excludes: ["lodging", "rental cars", "fuel", "nightlife", "personal shopping"]
    },
    scoring: {
      scale: { min: 1, max: 5, increment: 0.5 }, equal_traveler_weight: true, traveler_ids: PEOPLE,
      route_component_weights_percent: { attraction_and_stop_ratings: 45, excitement_and_uniqueness: 20, driving_comfort: 15, traveler_fairness: 10, cost_and_value: 5, expected_weather: 5 },
      route_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])),
      driving_comfort_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])),
      overall_excitement_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])),
      cost_value_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])),
      weather_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])),
      magic_score: null, magic_score_status: "awaiting_traveler_ratings",
      person_specific_route_scores: Object.fromEntries(PEOPLE.map((person) => [person, null]))
    },
    days,
    place_ids: productionPlaces.map((record) => record.id),
    core_place_ids: productionPlaces.filter((record) => record.included_in_magic_score).map((record) => record.id),
    alternative_place_ids: productionPlaces.filter((record) => !record.included_in_magic_score).map((record) => record.id),
    replacement_place_ids: productionPlaces.filter((record) => record.priority === "replacement").map((record) => record.id),
    replacement_options: replacements.variants.map((variant) => ({
      id: variant.id, day: variant.day, replacement_place_id: variant.replacement_place_id,
      replaces_place_ids: variant.replaces_place_ids, baseline_total_miles: variant.baseline_total_miles,
      baseline_total_minutes: variant.baseline_total_minutes, delta_miles: variant.delta_miles,
      delta_minutes: variant.delta_minutes, cap_minutes: variant.cap_minutes, cap_status: variant.cap_status
    })),
    budget: {
      known_core_admission_floor_per_person_usd: Math.round(knownCore * 100) / 100,
      core_admissions_and_ferries_range_per_person_usd: [285, 430],
      food_and_cafes_range_per_person_usd: [650, 900],
      local_parking_tolls_range_per_person_usd: [110, 180],
      controllable_total_range_per_person_usd: [1045, 1510],
      nightlife_range_per_person_usd: [100, 240], nightlife_excluded_from_target: true,
      note: "The route is designed to land around the $1,500 target before lodging, cars, fuel, nightlife and personal shopping. Ferry pricing for two cars is the largest shared variable."
    },
    booking_priorities: [
      { place_id: "pumpkin-blaze", urgency: "required-now", reason: "October 13, 2026 is date-specific and timed tickets are already on sale." },
      { place_id: "cross-sound-ferry", urgency: "early", reason: "Two vehicle spaces on the target Sunday sailing determine the first day." },
      { place_id: "cape-may-lewes-ferry", urgency: "early", reason: "Two vehicle reservations determine the Fort Miles block." },
      { place_id: "cape-may-ghosts", urgency: "when-calendar-opens", reason: "Select the actual October 7 trolley or walking-tour departure." },
      { place_id: "asbury-live-music", urgency: "when-calendar-opens", reason: "Choose a real rock, metal or strong local bill 4-6 weeks out; do not manufacture a generic nightlife stop." },
      { place_id: "lucy-elephant", urgency: "normal", reason: "A timed interior climb protects the Wildwood transfer." },
      { place_id: "fort-miles", urgency: "normal", reason: "Battery 519 capacity and October operations should be reconfirmed." }
    ],
    validation: {
      date_count: days.length, expected_date_count: 11,
      all_baseline_drive_days_at_or_below_cap: days.every((day) => day.drive.baseline_total_minutes <= 210),
      live_traffic_gated_days: days.filter((day) => day.drive.cap_status === "live-traffic-gated").map((day) => day.day),
      place_count: productionPlaces.length, image_count: images.length,
      places_with_fewer_than_3_usable_images: productionPlaces.filter((record) => record.image_ids.length < 3).map((record) => record.id),
      replacement_option_count: replacements.variants.length,
      all_replacement_variants_at_or_below_cap: replacements.variants.every((variant) => variant.baseline_total_minutes <= variant.cap_minutes),
      unfilled_place_ratings: productionPlaces.length * PEOPLE.length,
      hard_closures_or_conflicts: [
        "Cross Sound and Cape May-Lewes sailings are schedule gates, not road-driving time; vehicle check-in and queue buffers remain separate.",
        "Asbury live music is not locked until an actual October 6 bill is published.",
        "Mashomack access must be reconfirmed for seasonal hunting closures.",
        "NASA Wallops can close for mission operations even on a normally open Friday.",
        "The B&O Mile One 11:30 train is incompatible with Richmond Liturgy and is not promised.",
        "David Rockefeller Creative Arts Center is replacement-only until October 13 exhibition hours are confirmed.",
        "All no-traffic routing must be replaced by live navigation each morning; days flagged live-traffic-gated lose optional stops before the bed-to-bed cap is exceeded."
      ],
      route_lock_status: "research-complete-bookings-pending"
    }
  };

  const geojson = { type: "FeatureCollection", name: ROUTE_SLUG, features: [
    ...days.flatMap((day) => day.drive.legs.map((leg) => ({ type: "Feature", id: leg.id, properties: { feature_kind: "drive_leg", mode: leg.mode, route_id: ROUTE_ID, day: day.day, date: day.date, from: leg.from, to: leg.to, distance_miles: leg.distance_miles, baseline_minutes: leg.baseline_minutes, display_duration_minutes: leg.display_duration_minutes, counts_toward_drive_cap: leg.counts_toward_drive_cap, traffic_risk: leg.traffic_risk, map_color: route.route.map_color }, geometry: leg.geometry }))),
    ...replacements.variants.filter((variant) => variant.geometry).map((variant) => ({ type: "Feature", id: variant.id, properties: { feature_kind: "replacement_drive_variant", route_id: ROUTE_ID, day: variant.day, replacement_place_id: variant.replacement_place_id, replaces_place_ids: variant.replaces_place_ids, baseline_total_miles: variant.baseline_total_miles, baseline_total_minutes: variant.baseline_total_minutes, delta_minutes: variant.delta_minutes, cap_status: variant.cap_status, map_color: route.route.map_color }, geometry: variant.geometry })),
    ...productionPlaces.map((record) => ({ type: "Feature", id: record.id, properties: { feature_kind: "place", route_id: ROUTE_ID, place_id: record.id, name: record.name, city: record.city, state: record.state, visit_date: record.visit_date, priority: record.priority, included_in_magic_score: record.included_in_magic_score }, geometry: { type: "Point", coordinates: record.coordinates } })),
    ...Object.entries(geometry.nodes).map(([id, node]) => ({ type: "Feature", id: `node-${id}`, properties: { feature_kind: "route_node", route_id: ROUTE_ID, node_id: id, name: node.name }, geometry: { type: "Point", coordinates: node.coordinates } }))
  ] };

  await Promise.all([
    writeFile(path.join(ROUTE_DIR, "place-seed.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, places: seedPlaces }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "sources.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, verified_at: verifiedAt, sources }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "places.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, places: productionPlaces }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "images.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, image_policy: "Downloaded Wikimedia Commons derivatives with per-file attribution; contextual coverage is explicitly labeled and every selected image receives final visual review.", images }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "route.json"), `${JSON.stringify(route, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "route.geojson"), `${JSON.stringify(geojson, null, 2)}\n`)
  ]);
  await buildEnergyRoute03({ root: ROOT, routeDir: ROUTE_DIR });
  console.log(`Built ${ROUTE_NAME}: ${productionPlaces.length} places, ${images.length} images, ${days.length} days.`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
