#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  contextualImagePlaces, lodgingNodes, manualCoordinates, PEOPLE, places as researchPlaces,
  replacementVariants, ROUTE_ID, ROUTE_NAME, ROUTE_SLUG
} from "./config.mjs";

const ROOT = process.cwd();
const ROUTE_DIR = path.join(ROOT, "dataset", "routes", ROUTE_SLUG);
const verifiedAt = "2026-08-23";

const sourceRows = [
  ["src-portsmouth-abg", "City of Portsmouth", "government", "https://www.portsmouthnh.gov/publicworks/portsmouth-african-burying-ground-memorial-park", ["memorial history", "DNA-authenticated burial ground"]],
  ["src-albacore", "USS Albacore Museum", "official", "https://www.ussalbacore.org/", ["October hours", "admission", "experimental submarine"]],
  ["src-nubble", "York Parks and Recreation", "government", "https://www.yorkparksandrec.org/nubble-light-house", ["year-round park access", "free parking", "lighthouse viewpoint"]],
  ["src-woodman", "Woodman Museum", "official", "https://woodmanmuseum.org/home/", ["collection identity", "museum access"]],
  ["src-victoria", "Victoria Mansion", "official", "https://victoriamansion.org/visit-us/", ["2026 season", "daily hours", "admission"]],
  ["src-portland-head", "Portland Head Light", "official", "https://portlandheadlight.com/", ["museum", "Fort Williams setting"]],
  ["src-arcadia", "Arcadia", "official", "https://www.arcadiaportland.com/", ["21-plus policy", "Monday hours", "arcade bar"]],
  ["src-desert", "Desert of Maine", "official", "https://desertofmaine.com/visit", ["daily hours", "admission", "glacial sand history"]],
  ["src-gardens", "Coastal Maine Botanical Gardens", "official", "https://www.mainegardens.org/", ["October 18 season end", "Guardians of the Seeds", "admission"]],
  ["src-prison", "Maine Department of Corrections", "government", "https://www.maine.gov/corrections/programs/prisonindustries", ["showroom hours", "inmate-made goods"]],
  ["src-rockland", "Friends of Rockland Harbor Lights", "official", "https://www.rocklandharborlights.org/", ["breakwater and lighthouse access"]],
  ["src-maritime", "Maine Maritime Museum", "official", "https://www.mainemaritimemuseum.org/visit/", ["daily hours", "admission", "shipyard campus"]],
  ["src-owls", "Owls Head Transportation Museum", "official", "https://owlshead.org/", ["daily hours", "admission", "operating collection"]],
  ["src-fort-knox", "Friends of Fort Knox", "official", "https://www.fortknoxmaine.com/", ["October operations", "fort and observatory"]],
  ["src-penobscot", "Penobscot Marine Museum", "official", "https://penobscotmarinemuseum.org/", ["October season", "Tuesday-Sunday hours"]],
  ["src-acadia", "National Park Service", "government", "https://www.nps.gov/acad/planyourvisit/vehicle_reservations.htm", ["2026 Cadillac reservation dates", "sunrise release schedule"]],
  ["src-crypto", "International Cryptozoology Museum", "official", "https://cryptozoologymuseum.com/plan-your-visit/", ["new Bangor address", "year-round hours", "admission"]],
  ["src-bangor", "City of Bangor", "government", "https://www.bangormaine.gov/318/Thomas-Hill-Standpipe", ["standpipe history and grounds"]],
  ["src-seal-cove", "Seal Cove Auto Museum", "official", "https://www.sealcoveautomuseum.org/", ["October hours", "admission", "brass-era collection"]],
  ["src-cole", "Cole Land Transportation Museum", "official", "https://colemuseum.org/", ["season", "daily hours", "admission"]],
  ["src-mineral", "Maine Mineral and Gem Museum", "official", "https://mainemineralmuseum.org/visit/tickets-admission-hours/", ["Friday hours", "admission", "meteorite collection"]],
  ["src-colby", "Colby College Museum of Art", "official", "https://museum.colby.edu/visit/", ["free admission", "museum access"]],
  ["src-weeks", "New Hampshire State Parks", "government", "https://www.nhstateparks.org/find-parks-trails/weeks-state-park", ["exact 2026 hours", "auto road", "tower and house museum"]],
  ["src-fall-stj", "Discover St. Johnsbury", "official-tourism", "https://www.discoverstjohnsbury.com/fallforstj.html", ["October 10-11 2026 festival", "foliage train", "museum offer"]],
  ["src-fairbanks", "Fairbanks Museum and Planetarium", "official", "https://fairbanksmuseum.org/hours-and-fees/", ["daily hours", "admission", "collection"]],
  ["src-dog", "Dog Mountain", "official", "https://www.dogmt.com/", ["Dog Chapel", "gallery and grounds"]],
  ["src-orthodox", "Dormition Greek Orthodox Church", "official-church", "https://www.gocvt.org/", ["Sunday Orthros", "Divine Liturgy", "address"]],
  ["src-shelburne", "Shelburne Museum", "official", "https://shelburnemuseum.org/visit/", ["October 11 2026 hours", "admission", "39-building campus"]],
  ["src-radio-bean", "Radio Bean", "official", "https://radiobean.com/", ["live-music calendar", "venue identity"]],
  ["src-everyday", "Museum of Everyday Life", "official", "https://museumofeverydaylife.org/sample-page/about-us", ["self-service hours", "unheated barn", "mission"]],
  ["src-ben-jerrys", "Ben and Jerry's", "official", "https://www.benjerry.com/about-us/factory-tours", ["October 9-12 tour suspension", "fall hours", "Flavor Graveyard"]],
  ["src-hope", "City of Barre", "government", "https://www.barrecity.org/cemeteries.html", ["cemetery access and rules"]],
  ["src-coolidge", "Calvin Coolidge Presidential Foundation", "official", "https://coolidgefoundation.org/plan-your-visit/", ["mid-October season", "Plymouth Notch site"]],
  ["src-vins", "Vermont Institute of Natural Science", "official", "https://vinsweb.org/", ["daily hours", "raptors", "canopy walk"]],
  ["src-precision", "American Precision Museum", "official", "https://americanprecision.org/explore-vermont/", ["May-October daily hours", "machine-tool collection"]],
  ["src-saint-gaudens", "National Park Service", "government", "https://home.nps.gov/saga/faqs.htm", ["Tuesday building closure", "year-round grounds"]],
  ["src-path-life", "Great River Outfitters", "official-operator", "https://www.greatriveroutfitters.com/path-of-life", ["365-day dawn-dusk access", "18 sculptures"]],
  ["src-currier", "Currier Museum of Art", "official", "https://www.currier.org/frank-lloyd-wright", ["2026 tour season", "Wednesday tour times", "two Wright houses"]],
  ["src-see", "SEE Science Center", "official", "https://see-sciencecenter.org/plan-your-visit/", ["Wednesday hours", "average visit time"]],
  ["src-noaa-normals", "NOAA National Centers for Environmental Information", "government-data", "https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals", ["1991-2020 daily climate normals"]],
  ["src-osrm", "Open Source Routing Machine", "routing", "https://project-osrm.org/", ["road-network distances", "no-traffic durations"]]
];
const sources = sourceRows.map(([id, publisher, type, url, supports]) => ({ id, publisher, type, url, supports, verified_at: verifiedAt }));

const replacementByPlace = new Map(replacementVariants.map((variant) => [variant.replacement_place_id, variant]));
const baseById = new Map(researchPlaces.map((record) => [record.id, record]));
const details = [];
function P(id, name, kind, city, state, date, summary, why_go, best_for, secondary_for, categories, duration_minutes, source_ids, options = {}) {
  details.push({
    id, name, kind, city, state, visit_date: date, summary, why_go, best_for, secondary_for,
    best_fit_note: options.best_fit_note || `Best fit for ${best_for.join(" and ")}: ${why_go}`,
    categories, duration_minutes, source_ids, reservation: options.reservation || "none",
    hours: options.hours || { opens: null, closes: null, status: "public-space-or-confirm", note: "Confirm interior access close to travel." },
    cost: options.cost || { amount_per_person: 0, status: "free", note: "No admission planned." },
    priority: options.priority || "anchor", replacement_reason: options.replacement_reason
  });
}
const H = (opens, closes, status, note) => ({ opens, closes, status, note });
const C = (amount, status, note) => ({ amount_per_person: amount, status, note });

P("african-burying-ground", "African Burying Ground Memorial Park", "memorial-landscape", "Portsmouth", "NH", "2026-10-04", "A memorial on the spot where thirteen African people were buried in the 1700s. Their remains were found under a city street, and DNA testing confirmed their origins. It is the only African burial ground of its time in New England confirmed this way.", "A city paved over its own history, then dug it up and had to answer for it. The memorial is built for people to gather, not only to look.", ["gora", "stivka"], ["viki", "sheluvspaco"], ["hidden_history_folklore", "architecture_photogenic", "orthodox_spiritual"], 40, ["src-portsmouth-abg"], { priority: "supporting", best_fit_note: "Good for Gora's interest in history that was hidden, and for Stivka's reflective side. A short and serious start to the trip." });
P("uss-albacore", "USS Albacore: The Teardrop-Hull Experiment", "experimental-submarine", "Portsmouth", "NH", "2026-10-04", "A research submarine from 1953 with a rounded teardrop shape. It was never a fighting boat. It was built to test speed underwater, and its shape became the model for every modern submarine.", "You climb inside a very small experimental submarine that changed how all later ones were built. A test machine, not a war story.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["hidden_history_folklore", "unusual_creative", "architecture_photogenic"], 75, ["src-albacore"], { best_fit_note: "Good for Gora's engineering interest and Stivka's love of technical stories. The tight space makes it memorable for everyone.", hours: H("09:30", "17:00", "verified-seasonal", "Open daily through Indigenous Peoples' Day."), cost: C(14, "verified", "Adult admission.") });
P("nubble-light", "Nubble Light from Sohier Park", "lighthouse-viewpoint", "York", "ME", "2026-10-04", "A working lighthouse with a red roof, standing on a small rock island just off the shore. You see it from the granite and grass of the park opposite.", "The first big coast picture of the trip: a lighthouse on its own rock with waves all around it. You cannot go onto the island, and we say so up front.", ["viki", "stivka"], ["sheluvspaco", "gora"], ["nature_photogenic", "architecture_photogenic"], 55, ["src-nubble"], { best_fit_note: "Good for Viki's first strong sea photo and for Paco's easy group stop. Nobody has to walk far.", priority: "supporting", hours: H("05:00", "01:00", "verified-public-park", "Sohier Park is open year-round; no parking 01:00-05:00.") });
P("woodman-museum", "The Woodman Museum", "cabinet-of-curiosities", "Dover", "NH", "2026-10-04", "Four old buildings holding stuffed animals, minerals, local art, the home of an anti-slavery senator, and a fortified house from 1675. Nothing has been modernized.", "An old-fashioned museum of curiosities, still arranged the way museums used to be. Strange, wide-ranging and a little dusty.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "unusual_creative", "architecture_photogenic"], 105, ["src-woodman"], { best_fit_note: "Good for Viki's love of odd places and for Gora's interest in how museums once showed the world.", hours: H("10:00", "17:00", "verified-seasonal-pattern", "April-November Wednesday-Sunday; reconfirm 2026 fall hours."), cost: C(10, "verified-current", "Adult admission."), replacement_reason: "Replace Albacore when the group prefers a messier natural-history and local-history cabinet with more personality." });

P("victoria-mansion", "Victoria Mansion: Technology in a Gilded Interior", "historic-house", "Portland", "ME", "2026-10-05", "An Italian-style villa from 1860 that survives almost complete: painted walls, gas lights, indoor plumbing and furniture, all designed together as one scheme.", "Not simply a rich house. Almost nothing was changed, so you see how the whole thing was meant to work, down to the pipes and the lamps.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], 75, ["src-victoria"], { best_fit_note: "Good for Viki's decorated interiors and for Gora's interest in the systems inside a building.", hours: H("10:00", "16:00", "verified-2026", "Open daily May 1-October 31; last admission before close."), cost: C(19, "planning-current", "Confirm 2026 adult admission at booking.") });
P("portland-head-light", "Portland Head Light & Fort Williams", "lighthouse-fort-landscape", "Cape Elizabeth", "ME", "2026-10-05", "The oldest working lighthouse in the United States, standing above the surf beside gun batteries and the ruins of an old coastal fort.", "A famous lighthouse, a rough sea and a hidden military site in one walk, instead of three separate stops.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["nature_photogenic", "architecture_photogenic", "hidden_history_folklore"], 100, ["src-portland-head"], { best_fit_note: "Good for Viki's landmark photo and for Gora's interest in the defenses under a pretty view.", hours: H("10:00", "16:00", "verified-museum-season", "Park is broader-access; lighthouse museum is daily through October 31."), cost: C(3, "planning-floor", "Small museum admission; parking is separate.") });
P("eastern-promenade", "Eastern Promenade Blue-Hour Walk", "bay-overlook", "Portland", "ME", "2026-10-05", "A grassy hillside park above Casco Bay, laid out under the influence of the landscape designer Frederick Law Olmsted. Ferries and islands fill the water below.", "Fresh air and harbor light before the first social night. No ticket and no fixed time.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["nature_photogenic", "architecture_photogenic"], 60, ["src-portland-head"], { best_fit_note: "Good for Viki's evening light and for Stivka's calm hour before a loud one.", priority: "supporting" });
P("arcadia-portland", "Arcadia Pinball & Local-Tap Night", "arcade-social-night", "Portland", "ME", "2026-10-05", "An adults-only bar full of pinball machines, arcade cabinets and board games, with local beer. It is a games bar, not a nightclub.", "Competition makes people talk. Everyone can join in, and everyone can leave before it gets tiring.", ["sheluvspaco", "viki"], ["gora", "stivka"], ["live_social_nightlife", "unusual_creative"], 150, ["src-arcadia"], { best_fit_note: "Good for Paco's group energy and for Gora's social side. Viki and Stivka can play or just watch.", hours: H("17:00", "01:00", "verified", "Open Monday; closed Tuesday."), cost: C(0, "nightlife-excluded", "Drinks and game spend are excluded from the route budget.") });
P("desert-of-maine", "Desert of Maine", "glacial-sand-landscape", "Freeport", "ME", "2026-10-05", "A field of bare glacial sand that slowly buried a farm, its soil and its buildings. There are trails, and some of the old structures are still visible.", "A desert in the middle of coastal Maine. It looks impossible, and it happened because of how the land was farmed.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["nature_photogenic", "unusual_creative", "hidden_history_folklore"], 105, ["src-desert"], { best_fit_note: "Good for Viki's strange landscape photos and for Gora's interest in a mistake people made with the land.", hours: H("10:00", "18:00", "verified", "Open daily."), cost: C(21, "verified", "Adult admission."), replacement_reason: "Replace Victoria Mansion when sunshine makes the glacial landscape more magical than another preserved interior." });

P("coastal-maine-gardens", "Guardians of the Seeds at Coastal Maine Botanical Gardens", "giant-troll-garden", "Boothbay", "ME", "2026-10-06", "Five enormous wooden trolls by the Danish artist Thomas Dambo are hidden around a large seaside botanical garden. Each is built from reclaimed wood and linked to a different part of a tree.", "Finding five giant hidden trolls turns a garden walk into a hunt. Their size is genuinely surprising when you reach them.", ["viki", "sheluvspaco"], ["stivka", "gora"], ["nature_photogenic", "unusual_creative", "architecture_photogenic"], 180, ["src-gardens"], { best_fit_note: "Good for Viki's best photos of the trip and for Paco's group activity. Everyone joins the search.", hours: H("09:00", "17:00", "verified-2026", "Regular season continues through October 18."), cost: C(28, "verified", "Adult online admission; advance purchase is cheaper than walk-up."), reservation: "recommended" });
P("prison-showroom", "Maine State Prison Showroom", "prison-industries-shop", "Thomaston", "ME", "2026-10-06", "A shop selling furniture, model ships, carved boxes and other objects made by people held in Maine's prisons.", "The work is highly skilled, and buying it opens a real conversation about prison labor and craft. Nobody is put on display.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["hidden_history_folklore", "food_coffee_shopping", "unusual_creative"], 50, ["src-prison"], { hours: H("09:00", "16:00", "verified", "Open seven days."), priority: "supporting", best_fit_note: "Good for Gora's interest in work and justice, and for Stivka's thinking about dignity. Viki finds the carving beautiful." });
P("rockland-breakwater", "Rockland Breakwater Lighthouse Walk", "granite-breakwater-walk", "Rockland", "ME", "2026-10-06", "A lighthouse at the end of a granite wall from the 1890s that runs almost a mile out into Penobscot Bay. You walk out along the stone to reach it.", "A mile of granite straight out to sea, with a lighthouse at the end. One of the best sunset pictures of the whole trip.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["nature_photogenic", "architecture_photogenic"], 100, ["src-rockland"], { best_fit_note: "Good for Viki's sunset photo and for Gora's quiet walk. The stones need care, but the walk is flat and short.", hours: H("06:00", "18:30", "daylight-weather-gated", "Breakwater is exposed and uneven; skip for rain, high wind or slippery stone."), priority: "supporting" });
P("maine-maritime", "Maine Maritime Museum & Percy and Small Shipyard", "working-waterfront-museum", "Bath", "ME", "2026-10-06", "A 20-acre former shipyard. A full-size steel outline stands where a six-masted wooden schooner was built, showing its real shape and size. The museum also tells the story of the people who built such ships.", "The steel outline shows you the real size of a wooden ship. It works in rain, costs less and needs less walking than the gardens.", ["gora", "stivka"], ["viki", "sheluvspaco"], ["hidden_history_folklore", "architecture_photogenic", "unusual_creative"], 150, ["src-maritime"], { best_fit_note: "Good for Gora's interest in building things at scale and for Viki's shipyard structures.", hours: H("09:30", "17:00", "verified", "Open daily."), cost: C(22, "verified", "Adult admission."), replacement_reason: "Replace the troll gardens for bad weather, garden fatigue or a stronger appetite for ships and labor history." });

P("owls-head-transportation", "Owls Head Transportation Museum", "operating-machine-museum", "Owls Head", "ME", "2026-10-07", "More than 150 old cars, motorcycles, bicycles and aircraft, kept in working order rather than parked as decoration.", "These machines still run. You see how transport actually developed, not a row of polished show cars.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["hidden_history_folklore", "unusual_creative", "architecture_photogenic"], 120, ["src-owls"], { best_fit_note: "Good for Gora's love of mechanical history. The early aircraft shapes and bright paintwork surprise Viki too.", hours: H("10:00", "16:00", "verified", "Open daily year-round."), cost: C(17, "verified", "Adult admission.") });
P("fort-knox-observatory", "Fort Knox & Penobscot Narrows Observatory", "fort-and-bridge-observatory", "Prospect", "ME", "2026-10-07", "A granite coastal fort, and beside it a bridge tower with a lift rising to a public viewing floor 420 feet above the river.", "Dark stone passages underground, then a lift to a view over the whole valley. Two completely different experiences on one ticket.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_photogenic", "nature_photogenic", "unusual_creative"], 125, ["src-fort-knox"], { best_fit_note: "Good for Gora's military engineering and for Viki's autumn view from high above the river.", hours: H("09:00", "17:00", "verified-october", "Observatory October hours; fort grounds remain open later."), cost: C(11, "planning-current", "Nonresident combined adult admission; reconfirm 2026 fee.") });
P("bar-harbor-shore-path", "Bar Harbor Shore Path at Blue Hour", "historic-waterfront-path", "Bar Harbor", "ME", "2026-10-07", "A flat path along Frenchman Bay, past granite edges, large old hotels and the Porcupine Islands offshore.", "An easy walk with a strong run of views, and no extra drive or ticket after arriving at Acadia.", ["viki", "stivka"], ["sheluvspaco", "gora"], ["nature_photogenic", "architecture_photogenic"], 65, ["src-acadia"], { best_fit_note: "Good for Viki's blue-hour photos and for everyone's need to stretch after the drive.", priority: "supporting" });
P("penobscot-marine", "Penobscot Marine Museum's Sea-Captain Village", "maritime-village-museum", "Searsport", "ME", "2026-10-07", "A group of sea captains houses, with boats, navigation instruments and objects brought home from around the world. This small town once had an unusual number of deep-sea captains.", "One small town sent captains all over the world. This is that story at human scale, not another big machine collection.", ["stivka", "gora"], ["viki", "sheluvspaco"], ["hidden_history_folklore", "architecture_photogenic", "unusual_creative"], 120, ["src-penobscot"], { best_fit_note: "Good for Gora's interest in trade and travel, and for Stivka's family and community stories.", hours: H("10:00", "17:00", "verified-seasonal", "Tuesday-Sunday through the third weekend of October."), cost: C(15, "planning-current", "Confirm 2026 adult admission."), replacement_reason: "Replace Owls Head when the group prefers domestic architecture and seafarer lives over vehicles." });

P("cadillac-mountain", "Cadillac Mountain Sunrise", "reserved-sunrise-summit", "Acadia National Park", "ME", "2026-10-08", "A granite summit with views over islands and open ocean. On these October dates it is the first place in the United States to catch the sunrise.", "The first sunrise in the country, and you drive most of the way up. This is the early start the whole trip is built around.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["nature_photogenic", "orthodox_spiritual"], 75, ["src-acadia"], { best_fit_note: "Good for Viki's biggest photo and for Paco's shared group moment. No long walk is needed.", hours: H("05:30", "07:00", "reservation-gated", "Cadillac vehicle reservation is required May 20-October 25, 2026."), cost: C(9, "planning-share", "Vehicle reservation and park pass divided across four; car count can change this."), reservation: "required" });
P("ocean-path", "Ocean Path: Sand Beach to Thunder Hole Sampler", "coastal-cliff-walk", "Acadia National Park", "ME", "2026-10-08", "A section of coastal path over pink granite, past spruce trees and open ledges, ending at Thunder Hole where waves boom into a narrow inlet.", "The classic Acadia coast, kept to about three easy miles, with a car waiting at the end if anyone has had enough.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["nature_photogenic"], 110, ["src-acadia"], { best_fit_note: "Good for Viki's coastal photos and for Gora's walk. The car exit protects everyone's energy.", hours: H("07:15", "09:05", "weather-and-tide-gated", "Use the safer roadside path; wet granite and heavy surf can cancel the walk."), priority: "supporting" });
P("jordan-pond", "Jordan Pond & the Bubbles View", "glacial-pond-view", "Acadia National Park", "ME", "2026-10-08", "A clear glacial lake with the two rounded hills called the Bubbles at the far end. We walk only the near shore, not the full loop.", "The calmest, most balanced view in Acadia, right after the exposed coast. Short and restful.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["nature_photogenic"], 60, ["src-acadia"], { best_fit_note: "Good for Viki's reflections and Stivka's quiet moment. Nobody has to do the whole loop.", priority: "supporting" });
P("crypto-museum", "International Cryptozoology Museum—New Bangor Home", "cryptid-museum", "Bangor", "ME", "2026-10-08", "The only museum in the world devoted to cryptozoology, the search for animals that may not exist. It holds real zoological specimens, claimed evidence, and the pop culture of Bigfoot and sea serpents.", "Enjoy the strange claims, then judge the evidence separately. That split is exactly the point of the visit.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["hidden_history_folklore", "unusual_creative"], 90, ["src-crypto"], { best_fit_note: "Good for Gora's interest in what counts as proof, and for Viki's love of odd museums.", hours: H("10:00", "18:00", "verified-2026", "Open year-round seven days at 490 Broadway; the former Portland sites are closed."), cost: C(10, "verified", "Adult admission.") });
P("stephen-king-house", "Stephen King's House—Public-Road Exterior", "literary-architecture-stop", "Bangor", "ME", "2026-10-08", "A deep red Victorian house behind an iron gate decorated with bats and spiders. It is now used as a writers' archive, not a house you can enter.", "The gate alone is worth the stop, and it ties these streets to the Maine in his books. We look from the public road and nothing more.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_photogenic", "hidden_history_folklore"], 20, ["src-crypto"], { priority: "supporting", best_fit_note: "Good for Stivka's and Gora's interest in his books. Viki gets the gate. Twenty minutes and no trespassing." });
P("thomas-hill-standpipe", "Thomas Hill Standpipe at Sunset", "industrial-water-landmark", "Bangor", "ME", "2026-10-08", "A huge riveted iron water tank hidden inside a wooden shingled tower 110 feet high, standing on a hill above the city.", "A giant piece of Victorian city engineering, disguised as a wooden tower. Even with the stairs closed, the hill finishes the afternoon well.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["architecture_photogenic", "hidden_history_folklore"], 35, ["src-bangor"], { best_fit_note: "Good for Gora's interest in city infrastructure and for Viki's sunset view over Bangor.", priority: "supporting", hours: H("06:00", "19:00", "grounds-only", "Interior tours are rare special events and are not promised.") });
P("seal-cove-auto", "Seal Cove Auto Museum", "brass-era-auto-museum", "Seal Cove", "ME", "2026-10-08", "A quiet collection of brightly restored cars, motorcycles and early motoring design, from about 1895 to the 1920s.", "A precise wet-weather swap: still mechanical and colorful, but from a narrower period than Owls Head, so it does not repeat it.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["unusual_creative", "hidden_history_folklore", "architecture_photogenic"], 110, ["src-seal-cove"], { best_fit_note: "Good for Gora's mechanical detail and for Viki's colors and shapes. Quiet and indoors.", hours: H("10:00", "17:00", "verified-seasonal", "Open daily May 1-October 31."), cost: C(10, "verified", "Adult admission."), replacement_reason: "Replace the Acadia sunrise-and-walk block for hard rain, dangerous wind or total exhaustion; keep Jordan Pond only if conditions improve." });

P("cole-transportation", "Cole Land Transportation Museum", "transport-and-veteran-museum", "Bangor", "ME", "2026-10-09", "Old trucks, snowplows, railway equipment and military vehicles, showing how people and goods moved across difficult Maine country.", "The best parts are the ordinary working machines and the personal stories of the people who drove them, not glamorous cars.", ["gora", "sheluvspaco"], ["stivka", "viki"], ["hidden_history_folklore", "unusual_creative"], 110, ["src-cole"], { best_fit_note: "Good for Gora's interest in real working machines, and for Stivka's interest in service and memory.", hours: H("09:00", "16:00", "verified-seasonal", "Open daily May 1-November 11."), cost: C(14, "verified", "Adult admission.") });
P("maine-mineral-gem", "Maine Mineral & Gem Museum: Hold the Moon", "mineral-and-meteorite-museum", "Bethel", "ME", "2026-10-09", "Maine tourmaline and local mining history sit beside about 6,000 rocks from space, including pieces of the Moon, Mars and the asteroid belt.", "A small mountain town holds rock from other worlds, and some of it you can meet at hand level. The size of the collection is the shock.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["unusual_creative", "hidden_history_folklore", "nature_photogenic"], 150, ["src-mineral"], { best_fit_note: "Good for Gora's love of real science and for Viki's photos of stone and light. Stivka gets genuine wonder.", hours: H("10:00", "17:00", "verified", "Open Friday; final admission 16:00."), cost: C(15, "verified", "Adult admission.") });
P("bethel-village", "Bethel Common & Mountain-Town Evening", "quiet-village-evening", "Bethel", "ME", "2026-10-09", "A small 18th-century village green with mountains behind it and a short walkable center.", "A deliberately quiet night: dinner, conversation and rest between two museum-heavy days.", ["stivka", "sheluvspaco"], ["viki", "gora"], ["architecture_photogenic", "nature_photogenic", "food_coffee_shopping"], 75, ["src-mineral"], { best_fit_note: "Good for Paco's management of the group's energy and for Stivka's calm evening.", priority: "supporting" });
P("colby-art", "Colby College Museum of Art", "college-art-museum", "Waterville", "ME", "2026-10-09", "A large free collection of American art and modern installations, on a small college campus far from any big city.", "Serious art for free, in a shorter visit, before the long drive to Bethel.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["unusual_creative", "architecture_photogenic"], 105, ["src-colby"], { best_fit_note: "Good for Viki's art photos and for Stivka's calm gallery time. Paco likes that it costs nothing.", hours: H("10:00", "17:00", "verify-2026-friday", "Reconfirm fall Friday hours before promotion."), replacement_reason: "Replace Cole when the group is vehicle-museum saturated or wants a free contemporary-art reset." });

P("weeks-state-park", "Weeks State Park: Summit House & Fire Tower", "mountaintop-historic-estate", "Lancaster", "NH", "2026-10-10", "A 1.6-mile road climbs Mount Prospect to a stone fire tower and a restored country estate from 1912. From the top you see from the Presidential Range across to Vermont's Green Mountains.", "You drive to the summit and get a full circle of view at the height of the autumn color. The 2026 season runs to 12 October, so our date works.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["nature_photogenic", "architecture_photogenic", "hidden_history_folklore"], 85, ["src-weeks"], { best_fit_note: "Good for Viki's widest autumn photo and for Gora's interest in fire towers. No hard climbing.", hours: H("10:00", "16:30", "verified-date-specific", "On Saturday October 10 the auto road is open 10:00-17:00, tower to 16:30 and house museum to 16:00."), cost: C(5, "planning-current", "Confirm 2026 day-use fee when reserving."), reservation: "recommended" });
P("stj-foliage-train", "Fall for St. J Foliage Train", "historic-foliage-train", "St Johnsbury", "VT", "2026-10-10", "A 45-minute ride in historic carriages along the Passumpsic and Connecticut rivers, run during St Johnsbury's autumn festival on these exact dates.", "Autumn color from a train instead of a car window, and the ticket also gets us into the planetarium for free.", ["sheluvspaco", "viki"], ["gora", "stivka"], ["nature_photogenic", "live_social_nightlife", "hidden_history_folklore"], 60, ["src-fall-stj"], { best_fit_note: "Good for Paco's shared experience and for Viki's photos from the window. Everyone sits down for an hour.", hours: H("12:00", "13:00", "calendar-gated", "October 10-11, 2026 is confirmed; exact departures and ticket release are pending."), cost: C(25, "planning-estimate", "Replace with published 2026 train fare."), reservation: "when-calendar-opens" });
P("fairbanks-museum", "Fairbanks Museum's Victorian Cabinet", "natural-history-cabinet", "St Johnsbury", "VT", "2026-10-10", "A Victorian hall in heavy Romanesque style, still full of mounted animals, weather instruments and thousands of specimens, arranged as they were in the 1800s.", "It feels like walking into one collector's mind rather than a modern science center. The train ticket also covers the planetarium.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["unusual_creative", "hidden_history_folklore", "architecture_photogenic"], 110, ["src-fairbanks", "src-fall-stj"], { best_fit_note: "Good for Gora's interest in how knowledge was collected, and for Viki's untouched period interior.", hours: H("10:00", "17:00", "verified", "Open daily; festival scavenger hunt runs all weekend."), cost: C(17, "verified", "Adult museum admission; planetarium is free with festival train ticket.") });
P("dog-mountain", "Dog Mountain & the Dog Chapel", "folk-art-memorial-landscape", "St Johnsbury", "VT", "2026-10-10", "The hilltop folk-art world of the artist Stephen Huneck. At its center is a small chapel whose walls are covered with thousands of handwritten notes about dogs people have loved and lost.", "Funny and heartbreaking in the same hour. Of all our backup stops, this is the one most likely to become the real memory of the day.", ["stivka", "viki"], ["sheluvspaco", "gora"], ["orthodox_spiritual", "unusual_creative", "nature_photogenic", "architecture_photogenic"], 100, ["src-dog"], { best_fit_note: "Good for Stivka's feeling for memory and loss, and for Viki's folk art. Nobody leaves unaffected.", hours: H("10:00", "17:00", "verified-current", "Gallery and chapel hours; grounds dawn to dusk."), replacement_reason: "Replace the train and Fairbanks when train tickets fail, museum fatigue is high or the group wants folk art with real emotional weight." });

P("dormition-orthodox", "Sunday at Dormition Greek Orthodox Church", "orthodox-divine-liturgy", "Burlington", "VT", "2026-10-11", "A living Orthodox parish holding Orthros and the Divine Liturgy. We attend the service. This is not a tour of the building.", "Sunday stays a real Sunday, and the group starts the day with something shared.", ["stivka"], ["sheluvspaco", "gora", "viki"], ["orthodox_spiritual"], 150, ["src-orthodox"], { hours: H("09:00", "11:30", "verified-weekly", "Orthros 09:00; Divine Liturgy approximately 10:00. Reconfirm parish calendar."), best_fit_note: "Good for Stivka above all, and for the whole group as common ground. We follow the parish and stay for the whole Liturgy if we can." });
P("shelburne-museum", "Shelburne Museum: The Three-Hour Treasure Hunt", "open-air-collection-campus", "Shelburne", "VT", "2026-10-11", "Thirty-nine buildings holding folk art, mechanical figures, a round barn, Impressionist paintings, circus carvings, and the 220-foot steamboat Ticonderoga, which sits on dry land.", "Too big to see fully, so each person picks one thing to chase and we all meet at the steamboat. Everyone gets their own discovery.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["unusual_creative", "architecture_photogenic", "hidden_history_folklore"], 220, ["src-shelburne"], { best_fit_note: "Good for all four in different ways. Paco gets a plan that lets people split up without losing the group.", hours: H("10:00", "17:00", "verified-2026", "Open daily May 9-October 25, including Indigenous Peoples' Day."), cost: C(25, "verified-online", "Online adult price; walk-up is $27.50."), reservation: "recommended" });
P("burlington-waterfront", "Burlington Waterfront & Church Street", "lakefront-city-walk", "Burlington", "VT", "2026-10-11", "Sunset over Lake Champlain, then the pedestrian shopping street of Church Street, with its brick fronts and easy places to eat.", "City energy without a tight schedule, and with two cars we can come and go freely before the music.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["nature_photogenic", "architecture_photogenic", "food_coffee_shopping", "live_social_nightlife"], 120, ["src-shelburne"], { best_fit_note: "Good for Viki's browsing and Paco's flexible evening. Everyone eats what they want.", priority: "supporting" });
P("radio-bean", "Radio Bean Calendar-Gated Music Night", "small-room-live-music", "Burlington", "VT", "2026-10-11", "A small neighborhood venue that puts on several live sets a night across different styles. The room is small enough to feel social.", "The second optional big night, and only if the line-up is rock, heavy, folk or genuinely strange. We do not go just to tick a box.", ["stivka", "gora"], ["viki", "sheluvspaco"], ["live_social_nightlife", "unusual_creative"], 150, ["src-radio-bean"], { best_fit_note: "Good for Stivka's music and Gora's social side. Viki gets a real local room rather than a tourist bar.", hours: H("20:00", "23:30", "calendar-gated", "Promote only after the October 11 lineup and age policy are published."), cost: C(0, "nightlife-excluded", "Cover and drinks excluded from the route budget."), reservation: "when-calendar-opens" });
P("museum-everyday-life", "Museum of Everyday Life: Deep Seated", "self-service-barn-museum", "Glover", "VT", "2026-10-11", "An unheated barn museum with no staff. You turn on the lights yourself and look at ordinary objects taken seriously. The 2026 exhibition is about chairs.", "Nobody is there. You let yourself in, switch on the light, and think about chairs. It feels like finding something left unlocked on purpose.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["unusual_creative", "hidden_history_folklore", "architecture_photogenic"], 80, ["src-everyday"], { best_fit_note: "Good for Viki's love of the genuinely strange and for Gora's interest in ordinary things. Free, and unlike anywhere else.", hours: H("08:00", "20:00", "verified", "Open daily, self-service; the space is unheated, so bring a coat."), replacement_reason: "Replace Shelburne Museum when the group wants one truly eccentric exhibition instead of a vast canonical collection; this variant uses almost the entire drive cap." });

P("ben-jerrys-graveyard", "Ben & Jerry's Flavor Graveyard—No Fake Factory Tour", "food-design-stop", "Waterbury", "VT", "2026-10-12", "Granite gravestones with real written epitaphs for discontinued ice cream flavors, on a hill above the factory. There is a shop and a viewing platform over the production floor.", "A cemetery for dead ice cream flavors, written completely seriously. Note clearly: guided tours are closed 9-12 October, so we are not promising one.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["food_coffee_shopping", "unusual_creative", "architecture_photogenic"], 65, ["src-ben-jerrys"], { best_fit_note: "Good for Paco's group humor and Viki's photos. Nobody should expect a factory tour on our dates.", hours: H("10:00", "19:00", "verified-date-specific", "No guided tours October 9-12; mezzanine public viewing, scoop shop and seasonal grounds remain."), cost: C(0, "free-excluding-food", "No tour ticket planned; ice cream is personal food spend."), priority: "supporting" });
P("hope-cemetery", "Hope Cemetery: Barre's Granite Autobiography", "carvers-cemetery", "Barre", "VT", "2026-10-12", "Immigrant granite carvers made their own cemetery into a field of sculpture: airplanes, racing cars, soccer balls, a double bed, and portraits cut from local stone.", "The carvers chose their own memorials, so the stones show pride in their craft, migration, and the lung disease that killed many of them.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_photogenic", "orthodox_spiritual"], 70, ["src-hope"], { hours: H("07:00", "17:00", "verified-current", "Public visiting hours; yield completely to funerals."), best_fit_note: "Good for Gora's labor history and Viki's eye for sculpture. For everyone, it is a burial ground first and an attraction second." });
P("coolidge-site", "Plymouth Notch: The Night a Farmhouse Became the White House", "presidential-village", "Plymouth Notch", "VT", "2026-10-12", "A village kept almost unchanged, where Calvin Coolidge's father swore him in as president by lamplight after Harding died during the night.", "A president took the oath in his father's farmhouse by lamp light. The whole village is still there: church, shop, cheese factory, barns and graves.", ["gora", "stivka"], ["viki", "sheluvspaco"], ["hidden_history_folklore", "architecture_photogenic", "orthodox_spiritual"], 120, ["src-coolidge"], { best_fit_note: "Good for Gora's political history and Stivka's interest in duty. Viki gets a complete old village.", hours: H("10:00", "17:00", "season-gated", "Official season is late May to mid-October; confirm October 12 is inside the final 2026 operating week."), cost: C(12, "planning-current", "Confirm 2026 adult admission."), reservation: "reconfirm-season-end" });
P("vins", "VINS Raptor Center & Forest Canopy", "raptor-and-canopy-center", "Quechee", "VT", "2026-10-12", "A center for rescued birds of prey, with live programs and a raised walkway that takes you from ground level up into the tree canopy.", "Live eagles and owls, and a walk through the treetops. It works in rain and needs no real hiking.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["nature_photogenic", "unusual_creative"], 150, ["src-vins"], { best_fit_note: "Good for Viki's bird close-ups and Stivka's gentle side. Gora gets the science of rehabilitation.", hours: H("10:00", "17:00", "verified", "Open daily."), cost: C(20, "planning-current", "Confirm 2026 adult admission."), replacement_reason: "Replace Plymouth Notch if its seasonal buildings are closed, or when the group needs living nature after two history-heavy days." });

P("quechee-gorge", "Quechee Gorge from the Reopened Bridge", "gorge-overlook", "Quechee", "VT", "2026-10-13", "The Ottauquechee River has cut a deep narrow channel below a road bridge. You look straight down into it, with autumn color on both walls.", "Thirty-five minutes for a real piece of landscape, with no walking, before two museums and the drive to Manchester.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["nature_photogenic", "architecture_photogenic"], 35, ["src-vins"], { best_fit_note: "Good for Viki's gorge photo and Gora's quick nature break. Easy for everyone.", priority: "supporting", hours: H("08:00", "18:00", "daylight-access", "Use signed pedestrian routes and any current bridge safety controls.") });
P("american-precision", "American Precision Museum in the 1846 Armory", "machine-tool-museum", "Windsor", "VT", "2026-10-13", "Inside the old Robbins & Lawrence Armory from 1846, belt-driven machine tools show how America learned to make identical, interchangeable parts.", "This is where mass production actually began, and the machines are still here to inspect. It also covers what that did to the people who worked them.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["hidden_history_folklore", "architecture_photogenic", "unusual_creative"], 120, ["src-precision"], { best_fit_note: "Good for Gora's engineering interest and Viki's old machine shop. The building itself is part of the story.", hours: H("10:00", "17:00", "verified-2026", "Open daily May 1-October 31."), cost: C(15, "planning-current", "Confirm 2026 adult admission.") });
P("saint-gaudens", "Saint-Gaudens Sculpture Grounds—Tuesday Exterior Edition", "artist-estate-grounds", "Cornish", "NH", "2026-10-13", "The estate of the sculptor Augustus Saint-Gaudens, with bronze figures, formal gardens, studios and views across to Mount Ascutney.", "Sculpture set in a designed landscape. Be clear: on Tuesday the visitor center, galleries and house interiors are closed, so we walk the grounds.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_photogenic", "nature_photogenic", "hidden_history_folklore"], 80, ["src-saint-gaudens"], { best_fit_note: "Good for Viki's sculpture and garden photos and Stivka's calm hour. We plan for the grounds only.", hours: H("09:00", "16:30", "verified-grounds-only", "Grounds are open in daylight; seasonal buildings operate Thursday-Monday and are closed Tuesday."), priority: "supporting" });
P("path-of-life", "Path of Life Sculpture Garden", "symbolic-sculpture-landscape", "Windsor", "VT", "2026-10-13", "Eighteen outdoor artworks follow birth, ambition, sorrow, forgiveness, death and rebirth, across open fields, a stone labyrinth and a maze of hemlock trees.", "A walk through a whole life told in sculpture. Four people will read the same symbols completely differently, which is the point.", ["stivka", "viki"], ["gora", "sheluvspaco"], ["orthodox_spiritual", "unusual_creative", "nature_photogenic"], 80, ["src-path-life"], { best_fit_note: "Good for Stivka's reflective side and Viki's landscape art. A quiet alternative to another machine collection.", hours: H("07:00", "18:00", "verified-year-round", "Open 365 days, dawn to dusk; self-guided."), cost: C(10, "planning-donation", "Confirm current self-guided garden fee."), replacement_reason: "Replace American Precision when weather is good and the group needs reflection and art rather than another technical collection." });

P("flw-houses", "Frank Lloyd Wright's Zimmerman & Kalil Houses", "guided-modernist-house-tour", "Manchester", "NH", "2026-10-14", "A two-hour guided visit to two houses by Frank Lloyd Wright. One is a small Usonian home; the other is one of only seven Usonian Automatic houses, built from modular blocks. Both keep their original furniture.", "Two neighbors gave the same architect the same ideas and got completely different houses. You feel it in the light and the ceiling heights.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], 120, ["src-currier"], { best_fit_note: "Good for Viki's architecture and Gora's interest in how a system becomes a home. Booking is required.", hours: H("09:30", "11:30", "verified-2026", "2026 season runs April 22-December 27; tours Wednesday-Sunday at 09:30, 12:00 and 14:30."), cost: C(55, "planning-current", "Confirm exact 2026 combined-house public tour price; museum admission is included."), reservation: "required" });
P("currier-museum", "Currier Museum Highlights", "art-museum", "Manchester", "NH", "2026-10-14", "A compact regional art museum, running from European painting to American decorative arts and modern New England work.", "Entry is already included with the Wright house tour, so one focused hour adds real value without risking the drive back to Boston.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["unusual_creative", "architecture_photogenic"], 70, ["src-currier"], { best_fit_note: "Good for Viki's and Stivka's gallery hour. Paco likes that it costs nothing extra.", hours: H("10:00", "17:00", "verified", "Open Wednesday-Sunday."), cost: C(0, "included", "Included with the Wright houses tour."), priority: "supporting" });
P("see-science", "SEE Science Center & LEGO Millyard", "hands-on-science-center", "Manchester", "NH", "2026-10-14", "Hands-on science experiments around an enormous LEGO model of Manchester's Amoskeag Millyard as it looked at its industrial peak.", "Cheap, hands-on and easy to leave early. The LEGO city also links the play to the real mills outside.", ["sheluvspaco", "viki"], ["gora", "stivka"], ["unusual_creative", "hidden_history_folklore"], 120, ["src-see"], { best_fit_note: "Good for Paco's last-day mood and Viki's curiosity. Gora gets the real industrial history behind the model.", hours: H("10:00", "16:00", "verified-fall-pattern", "Wednesday fall hours; last admission 15:00."), cost: C(14, "planning-current", "Confirm 2026 adult admission."), replacement_reason: "Replace both Wright houses and the Currier when tickets sell out, the group wants hands-on play or the Boston return needs more flexibility." });

const seedPlaces = details.map((record) => {
  const base = baseById.get(record.id);
  if (!base) throw new Error(`No research config for ${record.id}`);
  const variant = replacementByPlace.get(record.id);
  return {
    ...record,
    address: base.geocode,
    priority: variant ? "replacement" : record.priority,
    replacement: variant ? { day: variant.day, replaces_place_ids: variant.replaces_place_ids, route_variant_id: variant.id, reason: record.replacement_reason } : undefined
  };
});
if (seedPlaces.length !== researchPlaces.length) throw new Error(`Detail/config count mismatch: ${seedPlaces.length}/${researchPlaces.length}`);

const dayPlans = [
  { day: 1, date: "2026-10-04", sleep_city: "Portsmouth, NH", theme: "An offshore lighthouse, an experimental submarine and the history under Portsmouth's streets", schedule: [["13:30", "14:25", "nubble-light", "supporting"], ["15:05", "16:20", "uss-albacore", "anchor"], ["16:35", "17:15", "african-burying-ground", "supporting"]], lodging: ["Portsmouth downtown or West End with staffed reception", "Dover hotel corridor if two clean rooms and secure parking are materially better"], fallback: "Promote the Woodman Museum in place of Albacore when the group wants a cabinet of curiosities; do not cut the memorial for entertainment." },
  { day: 2, date: "2026-10-05", sleep_city: "Portland, ME", theme: "A complete Victorian interior, Atlantic fortifications and competitive pinball", schedule: [["10:00", "11:15", "victoria-mansion", "anchor"], ["12:00", "13:40", "portland-head-light", "anchor"], ["16:15", "17:15", "eastern-promenade", "supporting"], ["20:00", "22:30", "arcadia-portland", "anchor"]], lodging: ["Old Port edge or East Bayside with secure two-car parking", "South Portland near the Casco Bay Bridge for better two-room value"], fallback: "Promote Desert of Maine for dry weather and a stranger outdoor story; keep Arcadia optional if anyone needs an early recovery night." },
  { day: 3, date: "2026-10-06", sleep_city: "Rockland, ME", theme: "Giant forest guardians, prison-made craft and a granite path into the bay", schedule: [["09:00", "12:00", "coastal-maine-gardens", "anchor"], ["13:35", "14:25", "prison-showroom", "supporting"], ["15:15", "16:55", "rockland-breakwater", "supporting"]], lodging: ["Rockland harbor/Main Street with recent cleanliness reviews", "Camden outskirts only if parking and two-room inventory are clearly better"], fallback: "Promote Maine Maritime Museum for rain or garden fatigue; skip the exposed breakwater before risking wet granite." },
  { day: 4, date: "2026-10-07", sleep_city: "Bar Harbor, ME", theme: "Machines that still move, a fort beneath a bridge and Acadia at blue hour", schedule: [["10:00", "12:00", "owls-head-transportation", "anchor"], ["13:35", "15:40", "fort-knox-observatory", "anchor"], ["17:10", "18:15", "bar-harbor-shore-path", "supporting"]], lodging: ["Bar Harbor village within walking distance of dinner", "Ellsworth only if Bar Harbor's clean two-room inventory is poor; this changes sunrise wake-up time"], fallback: "Promote Penobscot Marine Museum for sea-captain architecture instead of Owls Head; the observatory closes first for severe wind." },
  { day: 5, date: "2026-10-08", sleep_city: "Bangor, ME", theme: "First light over Acadia, cryptids with an evidence check and Stephen King's civic landscape", schedule: [["05:30", "06:50", "cadillac-mountain", "anchor"], ["07:15", "09:05", "ocean-path", "supporting"], ["09:35", "10:35", "jordan-pond", "supporting"], ["12:30", "14:00", "crypto-museum", "anchor"], ["14:20", "14:40", "stephen-king-house", "supporting"], ["15:00", "15:35", "thomas-hill-standpipe", "supporting"]], lodging: ["Bangor Broadway or downtown edge with staffed reception", "Airport/Hammond Street corridor with well-lit parking and strong recent cleanliness reviews"], fallback: "Promote Seal Cove Auto Museum for dangerous summit/coast weather; after a 04:45 wake-up, cut the standpipe before forcing energy." },
  { day: 6, date: "2026-10-09", sleep_city: "Bethel, ME", theme: "Working Maine machines, rocks from the Moon and a deliberately quiet mountain night", schedule: [["09:00", "10:50", "cole-transportation", "anchor"], ["13:25", "15:55", "maine-mineral-gem", "anchor"], ["16:10", "17:25", "bethel-village", "supporting"]], lodging: ["Bethel village inn or small hotel with two confirmed room types", "Sunday River access road only with strong cleanliness and safe two-car parking"], fallback: "Promote Colby Museum for free art when the group is already machine-saturated; protect a 16:00 final entry at the mineral museum." },
  { day: 7, date: "2026-10-10", sleep_city: "Montpelier, VT", theme: "A 360-degree summit, an exact-date foliage train and a Victorian world cabinet", schedule: [["10:00", "11:25", "weeks-state-park", "supporting"], ["12:35", "13:35", "stj-foliage-train", "anchor"], ["13:50", "15:40", "fairbanks-museum", "anchor"]], lodging: ["Montpelier downtown with safe covered or well-lit parking", "Berlin near I-89 for resilient two-room inventory"], fallback: "Promote Dog Mountain if train tickets fail or the group needs an emotional folk-art landscape; this is a drive-cap day, so no extra detours." },
  { day: 8, date: "2026-10-11", sleep_city: "Burlington, VT", theme: "Granite-carvers' memory, Orthodox Sunday, a 39-building treasure hunt and optional live music", schedule: [["07:00", "07:45", "hope-cemetery", "supporting"], ["09:00", "11:30", "dormition-orthodox", "anchor"], ["12:10", "15:50", "shelburne-museum", "anchor"], ["16:15", "18:15", "burlington-waterfront", "supporting"], ["20:30", "23:00", "radio-bean", "anchor"]], lodging: ["Burlington South End or downtown edge with staffed garage", "South Burlington near I-89 for safer parking and stronger two-room inventory"], fallback: "Promote the Museum of Everyday Life in place of both the cemetery and Shelburne when the group wants one truly eccentric object museum; music remains calendar-gated." },
  { day: 9, date: "2026-10-12", sleep_city: "Woodstock, VT", theme: "Dead ice-cream flavors and a lamplit presidential succession", schedule: [["10:00", "11:05", "ben-jerrys-graveyard", "supporting"], ["13:20", "15:30", "coolidge-site", "anchor"]], lodging: ["Woodstock village or east approach with onsite parking", "Quechee for cleaner two-room inventory while preserving the Tuesday route"], fallback: "Promote VINS if Plymouth Notch closes for the season; do not describe Ben & Jerry's mezzanine access as a guided tour." },
  { day: 10, date: "2026-10-13", sleep_city: "Manchester, NH", theme: "A foliage gorge, the machine-tool revolution and sculpture grounds without a fake interior promise", schedule: [["08:30", "09:05", "quechee-gorge", "supporting"], ["10:00", "12:00", "american-precision", "anchor"], ["12:40", "14:00", "saint-gaudens", "supporting"]], lodging: ["North Manchester or downtown with staffed reception and secure parking", "Bedford near Route 101 only if the 09:15 Currier check-in remains comfortable"], fallback: "Promote Path of Life for a symbolic outdoor walk instead of the Precision Museum; Saint-Gaudens is grounds-only on Tuesday." },
  { day: 11, date: "2026-10-14", sleep_city: "Boston, MA", theme: "Two Frank Lloyd Wright homes and a protected Logan return", schedule: [["09:30", "11:30", "flw-houses", "anchor"], ["11:30", "12:40", "currier-museum", "supporting"]], lodging: ["Logan airport hotel with confirmed early shuttle", "East Boston or Revere only with a verified airport transfer and easy car return"], fallback: "Promote SEE Science Center if Wright tickets sell out or live traffic demands an earlier departure; Boston sightseeing is intentionally excluded." }
];

function personFit(record, person) {
  if (record.best_for.includes(person)) return 5;
  if (record.secondary_for.includes(person)) return 4;
  return person === "sheluvspaco" ? 3.8 : 3.5;
}
function scheduleItem([start, end, place_id, priority], placeById) {
  const record = placeById.get(place_id);
  if (!record) throw new Error(`Unknown scheduled place ${place_id}`);
  return { start, end, place_id, priority, reservation: record.reservation };
}

async function main() {
  const [research, weather, geometry, replacements] = await Promise.all([
    readFile(path.join(ROUTE_DIR, "research-raw.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "weather-normals.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "route-geometry.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "replacement-geometry.json"), "utf8").then(JSON.parse)
  ]);
  const replacementGeometryById = new Map(replacements.variants.map((variant) => [variant.id, variant]));
  const images = [];
  const productionPlaces = seedPlaces.map((record) => {
    const raw = research.places[record.id];
    const coordinates = manualCoordinates[record.id] || (raw?.selected_coordinate ? [raw.selected_coordinate.longitude, raw.selected_coordinate.latitude] : null);
    if (!coordinates) throw new Error(`Missing coordinates for ${record.id}`);
    const imageIds = (raw?.selected_images || []).slice(0, 8).map((item, index) => {
      const id = `img-${record.id}-${index + 1}`;
      images.push({
        id, place_id: record.id, title: item.title, description: item.description, search_query: item.search_query,
        local_path: item.local_path, source_page: item.source_page, source_file_url: item.original_url,
        creator: item.creator || "Unknown", credit: item.credit || "", license: item.license || "Unknown",
        license_url: item.license_url, alt: item.description || `${record.name} photograph`,
        coverage: contextualImagePlaces.has(record.id) ? "place-or-local-context" : "exact-place-or-experience",
        production_usable: item.production_usable ?? item.license !== "Unknown",
        rights_status: item.rights_status || "commons-license-recorded",
        visual_review: item.review_status === "reviewed" ? "reviewed" : "pending-final-review"
      });
      return id;
    });
    const routeVariant = record.replacement ? replacementGeometryById.get(record.replacement.route_variant_id) : null;
    return {
      ...record, country: "US", coordinates, coordinate_order: "longitude_latitude", coordinate_source: "manual_verified_address",
      image_ids: imageIds, ratings: { traveler_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), average: null, rating_count: 0 },
      researcher_person_fit: Object.fromEntries(PEOPLE.map((person) => [person, personFit(record, person)])),
      included_in_magic_score: record.priority !== "replacement",
      replacement: record.replacement ? { ...record.replacement, route_variant: routeVariant } : undefined,
      data_status: imageIds.length >= 3 ? "complete" : "image-gap"
    };
  });
  const placeById = new Map(productionPlaces.map((record) => [record.id, record]));
  const weatherByDay = new Map(weather.days.map((day) => [day.day, day]));
  const geometryByDay = new Map(geometry.days.map((day) => [day.day, day]));
  const comfort = [3.7, 3.7, 3.6, 3.2, 3.3, 3.2, 3.0, 3.1, 3.3, 3.5, 3.7];
  const days = dayPlans.map((plan) => {
    const routed = geometryByDay.get(plan.day);
    const normal = weatherByDay.get(plan.day);
    const capStatus = routed.planning_total_minutes.high > 210 ? "live-traffic-gated" : routed.baseline_total_minutes >= 185 ? "near-cap" : "comfortable";
    return {
      ...plan,
      day_of_week: new Intl.DateTimeFormat("en-US", { weekday: "long", timeZone: "America/New_York" }).format(new Date(`${plan.date}T12:00:00-04:00`)),
      lodging: { preferred_area: plan.lodging[0], fallback_area: plan.lodging[1], room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Strong suggestion only; verify recent safety, cleanliness and parking reviews manually before booking." },
      drive: { legs: routed.legs, baseline_total_miles: routed.baseline_total_miles, baseline_total_minutes: routed.baseline_total_minutes, planning_total_minutes: routed.planning_total_minutes, traffic_risk: routed.risk, cap_minutes: 210, cap_status: capStatus, fallback: plan.fallback },
      schedule: plan.schedule.map((item) => scheduleItem(item, placeById)),
      weather: { kind: "historical_normal", high_c: normal.normal_high_c, low_c: normal.normal_low_c, precipitation_probability_percent: normal.measurable_precipitation_probability_percent, comfort_score: comfort[plan.day - 1], station_id: normal.station_id, station_name: normal.station_name, station_role: normal.station_role, source_id: "src-noaa-normals", forecast_status: "replace_with_live_forecast_10_days_before" }
    };
  });
  const knownCore = productionPlaces.filter((record) => record.included_in_magic_score).reduce((sum, record) => sum + (record.cost.amount_per_person || 0), 0);
  const route = {
    schema_version: "1.0.0",
    route: {
      id: ROUTE_ID, slug: ROUTE_SLUG.replace(/^route-04-/, ""), name: ROUTE_NAME, short_name: "Trolls & Moon Rocks",
      status: "researched", map_color: "#F59E0B", timezone: "America/New_York", start_date: "2026-10-04", end_date: "2026-10-14", airport_date: "2026-10-15",
      origin: { name: lodgingNodes["boston-logan-rental"].name, coordinates: lodgingNodes["boston-logan-rental"].coordinates }, destination: { name: lodgingNodes["boston-logan-hotel"].name, coordinates: lodgingNodes["boston-logan-hotel"].coordinates },
      endpoint_city: "Bar Harbor, ME", direction: "Maine coast to Acadia; Bangor and western Maine inland; Vermont south through New Hampshire to Boston",
      countries: ["US"], canada_included: false, total_nights: 11, road_nights: 10, final_boston_nights: 1, baseline_total_miles: geometry.route_baseline_total_miles,
      summary: "A peak-foliage curiosity loop built around giant forest trolls, Acadia sunrise, cryptids, moon and Mars rocks, a Victorian natural-history cabinet, Orthodox Sunday, folk-art memorials, machine-tool history and two Frank Lloyd Wright homes. It is Route 4's coolest-weather option, so every day carries Celsius normals and bad-weather substitutions."
    },
    constraints: {
      travelers: 4, cars: 2, cars_follow_same_route: true, daily_drive_target_minutes: [120, 180], daily_drive_hard_cap_minutes: 210,
      max_big_nights_out: 4, planned_big_nights_out: 2, max_athletic_adrenaline_spots: 2, planned_athletic_adrenaline_spots: 0, hike_soft_cap_miles: 6,
      lodging_rooms: [{ count: 1, beds: 1 }, { count: 1, beds: 2 }], lodging_priorities: ["safe", "clean", "comfortable", "two-room inventory", "secure parking"],
      visa_policy: "US-only; no Canada crossing or J-1 re-entry dependency.", budget_target_per_person_usd: 1500,
      budget_excludes: ["lodging", "rental cars", "fuel", "nightlife", "personal shopping"]
    },
    scoring: {
      scale: { min: 1, max: 5, increment: 0.5 }, equal_traveler_weight: true, traveler_ids: PEOPLE,
      route_component_weights_percent: { attraction_and_stop_ratings: 45, excitement_and_uniqueness: 20, driving_comfort: 15, traveler_fairness: 10, cost_and_value: 5, expected_weather: 5 },
      route_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), driving_comfort_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])),
      overall_excitement_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), cost_value_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), weather_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])),
      magic_score: null, magic_score_status: "awaiting_traveler_ratings", person_specific_route_scores: Object.fromEntries(PEOPLE.map((person) => [person, null]))
    },
    days, place_ids: productionPlaces.map((record) => record.id), core_place_ids: productionPlaces.filter((record) => record.included_in_magic_score).map((record) => record.id),
    alternative_place_ids: productionPlaces.filter((record) => !record.included_in_magic_score).map((record) => record.id), replacement_place_ids: productionPlaces.filter((record) => record.priority === "replacement").map((record) => record.id),
    replacement_options: replacements.variants.map((variant) => ({ id: variant.id, day: variant.day, replacement_place_id: variant.replacement_place_id, replaces_place_ids: variant.replaces_place_ids, baseline_total_miles: variant.baseline_total_miles, baseline_total_minutes: variant.baseline_total_minutes, delta_miles: variant.delta_miles, delta_minutes: variant.delta_minutes, cap_minutes: variant.cap_minutes, cap_status: variant.cap_status })),
    budget: { known_core_admission_floor_per_person_usd: Math.round(knownCore * 100) / 100, core_admissions_range_per_person_usd: [260, 365], food_and_cafes_range_per_person_usd: [600, 850], local_parking_tolls_range_per_person_usd: [80, 150], controllable_total_range_per_person_usd: [940, 1365], nightlife_excluded_from_target: true, note: "Planning range stays below the $1,500 controllable-spend target with room for food upgrades; lodging, cars, fuel, nightlife and shopping remain excluded." },
    booking_priorities: [
      { place_id: "cadillac-mountain", urgency: "two-release-windows", reason: "Sunrise vehicle reservations release 30 percent 90 days ahead and 70 percent two days ahead." },
      { place_id: "flw-houses", urgency: "early", reason: "Four seats on the 09:30 October 14 tour protect the Boston return." },
      { place_id: "stj-foliage-train", urgency: "when-calendar-opens", reason: "The festival dates are confirmed but 2026 departures and tickets are not yet published." },
      { place_id: "coolidge-site", urgency: "reconfirm", reason: "Confirm October 12 falls before the exact 2026 seasonal building closure." },
      { place_id: "radio-bean", urgency: "calendar-gated", reason: "Add only if the actual lineup fits the group." }
    ],
    validation: {
      date_count: days.length, expected_date_count: 11, all_baseline_drive_days_at_or_below_cap: days.every((day) => day.drive.baseline_total_minutes <= 210),
      live_traffic_gated_days: days.filter((day) => day.drive.cap_status === "live-traffic-gated").map((day) => day.day), place_count: productionPlaces.length, image_count: images.length,
      places_with_fewer_than_3_usable_images: productionPlaces.filter((record) => record.image_ids.length < 3).map((record) => record.id), replacement_option_count: replacements.variants.length,
      all_replacement_variants_at_or_below_cap: replacements.variants.every((variant) => variant.baseline_total_minutes <= variant.cap_minutes), unfilled_place_ratings: productionPlaces.length * PEOPLE.length,
      hard_closures_or_conflicts: ["Ben and Jerry's has no guided factory tours October 9-12; only public mezzanine, shop and seasonal grounds are planned.", "Saint-Gaudens buildings are closed Tuesday; only grounds and outdoor sculpture are planned.", "Radio Bean remains unscheduled in practice until the October 11 bill is published.", "Coolidge's exact 2026 seasonal closing date must be reconfirmed.", "No traffic is included in OSRM baselines; live ETAs control optional-stop cuts each morning."], route_lock_status: "research-complete-bookings-pending"
    }
  };
  const geojson = { type: "FeatureCollection", name: ROUTE_SLUG, features: [
    ...days.flatMap((day) => day.drive.legs.map((leg) => ({ type: "Feature", id: leg.id, properties: { feature_kind: "drive_leg", route_id: ROUTE_ID, day: day.day, date: day.date, from: leg.from, to: leg.to, distance_miles: leg.distance_miles, baseline_minutes: leg.baseline_minutes, map_color: route.route.map_color }, geometry: leg.geometry }))),
    ...replacements.variants.filter((variant) => variant.geometry).map((variant) => ({ type: "Feature", id: variant.id, properties: { feature_kind: "replacement_drive_variant", route_id: ROUTE_ID, day: variant.day, replacement_place_id: variant.replacement_place_id, replaces_place_ids: variant.replaces_place_ids, baseline_total_miles: variant.baseline_total_miles, baseline_total_minutes: variant.baseline_total_minutes, delta_minutes: variant.delta_minutes, cap_status: variant.cap_status, map_color: route.route.map_color }, geometry: variant.geometry })),
    ...productionPlaces.map((record) => ({ type: "Feature", id: record.id, properties: { feature_kind: "place", route_id: ROUTE_ID, place_id: record.id, name: record.name, city: record.city, state: record.state, visit_date: record.visit_date, priority: record.priority, included_in_magic_score: record.included_in_magic_score }, geometry: { type: "Point", coordinates: record.coordinates } })),
    ...Object.entries(geometry.nodes).map(([id, node]) => ({ type: "Feature", id: `node-${id}`, properties: { feature_kind: "route_node", route_id: ROUTE_ID, node_id: id, name: node.name }, geometry: { type: "Point", coordinates: node.coordinates } }))
  ] };
  await Promise.all([
    writeFile(path.join(ROUTE_DIR, "place-seed.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, places: seedPlaces }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "sources.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, verified_at: verifiedAt, sources }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "places.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, places: productionPlaces }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "images.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, image_policy: "Downloaded Wikimedia Commons derivatives with per-file attribution; contextual coverage is labeled and every selected image receives visual review.", images }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "route.json"), `${JSON.stringify(route, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "route.geojson"), `${JSON.stringify(geojson, null, 2)}\n`)
  ]);
  console.log(`Built ${ROUTE_NAME}: ${productionPlaces.length} places, ${images.length} images, ${days.length} days.`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
