#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { contextualImagePlaces, lodgingNodes, manualCoordinates, PEOPLE, replacementVariants, ROUTE_ID, ROUTE_NAME, ROUTE_SLUG } from "./config.mjs";
import { buildEnergyRoute02 } from "../route-02-energy/build.mjs";

const ROOT = process.cwd();
const ROUTE_DIR = path.join(ROOT, "dataset", "routes", ROUTE_SLUG);
const verifiedAt = "2026-08-21";

const sources = [
  ["src-three-sisters", "Three Sisters Sanctuary", "official", "https://threesisterssanctuary.com/three-sisters-sanctuary-covid19/", ["daily hours", "admission", "eight-acre environmental art garden"]],
  ["src-smith", "Smith College Botanic Garden", "official", "https://garden.smith.edu/visit", ["daily conservatory hours", "free admission", "parking"]],
  ["src-tunnel", "The Tunnel Bar", "official", "https://www.thetunnelbar.com/", ["venue identity"]],
  ["src-tunnel-maps", "Apple Maps", "map-review-aggregator", "https://maps.apple.com/place?place-id=I81E5F8B11A6466B8", ["current hours", "historic train-tunnel context", "review signal"]],
  ["src-mass-moca", "MASS MoCA", "official", "https://massmoca.org/visit/", ["Monday hours", "admission", "advance-ticket guidance"]],
  ["src-mass-moca-exhibitions", "MASS MoCA", "official", "https://massmoca.org/long-term-exhibitions/", ["2026 long-term installations", "James Turrell", "Laurie Anderson", "Sol LeWitt"]],
  ["src-grafton", "Grafton Peace Pagoda", "official", "https://www.graftonpeacepagoda.org/contact/", ["sunrise-to-sunset daily access", "address"]],
  ["src-saratoga", "New York State Parks", "government", "https://parks.ny.gov/visit/state-parks/saratoga-spa-state-park", ["2026 hours", "vehicle fees", "mineral springs"]],
  ["src-saratoga-springs-map", "New York State Parks", "government", "https://parks.ny.gov/sites/default/files/SaratogaSpaSpaParkMineralSpringsBrochure.pdf", ["twelve public mineral-spring locations"]],
  ["src-congress", "City of Saratoga Springs", "government", "https://www.saratoga-springs.org/Archive/ViewFile/Item/241", ["Congress Park mineral-water and sculpture context"]],
  ["src-howe", "Howe Caverns", "official", "https://howecaverns.com/", ["traditional-tour format", "online-ticket requirement", "stairs and boat ride"]],
  ["src-howe-price", "Howe Caverns", "official", "https://howecaverns.com/howe-caverns-pricing/", ["2026 adult price", "90-minute duration"]],
  ["src-iroquois", "Iroquois Museum", "official", "https://www.iroquoismuseum.org/", ["October Tuesday hours", "address", "Haudenosaunee stewardship"]],
  ["src-cooperstown", "Destination Marketing Corporation for Otsego County", "official-tourism", "https://www.cooperstownny.org/wp-content/uploads/2025/02/Cooperstown-Brochure-for-web-1-1.pdf", ["lakefront and Cooperstown context", "Ommegang context"]],
  ["src-ommegang", "Brewery Ommegang", "official", "https://www.ommegang.com/tap-room-restaurant/", ["Tuesday taproom hours", "address", "tours weekend-only"]],
  ["src-fenimore", "Fenimore Farm", "official", "https://www.fenimorefarm.org/visit/", ["October hours", "admission", "site operations"]],
  ["src-fenimore-explore", "Fenimore Farm", "official", "https://www.fenimorefarm.org/explore", ["Cardiff Giant history", "Empire State Carousel details"]],
  ["src-taughannock", "New York State Parks", "government", "https://parks.ny.gov/visit/state-parks/taughannock-falls-state-park", ["2026 trail status", "dawn-to-dusk hours", "1.5-mile gorge walk"]],
  ["src-cornell", "Cornell Botanic Gardens", "official", "https://cornellbotanicgardens.org/visit/visitor-faq", ["free admission", "dawn-to-dusk grounds", "weekday parking"]],
  ["src-ithaca-gorges", "Cornell University", "official", "https://bpb-us-e1.wpmucdn.com/blogs.cornell.edu/dist/f/3277/files/2024/05/2024-Gorges-Brochure.pdf", ["Ithaca Falls access", "gorge safety", "seasonal trail context"]],
  ["src-corning", "Corning Museum of Glass", "official", "https://visit.cmog.org/plan-your-visit", ["October daily hours", "admission", "hot-glass demonstrations"]],
  ["src-corning-make", "Corning Museum of Glass", "official", "https://glassmaking.cmog.org/make-your-own-glass", ["studio hours", "advance-reservation advice", "separate experience"]],
  ["src-corning-fall", "Corning Museum of Glass", "official", "https://visit.cmog.org/savor-fall-at-the-museum", ["fall glass projects", "seasonal demonstrations"]],
  ["src-eastman", "George Eastman Museum", "official", "https://www.eastman.org/", ["Friday hours", "admission", "October 2026 exhibitions"]],
  ["src-artisanworks", "ARTISANworks", "official", "https://artisanworks.net/", ["Friday public hours", "admission", "accessibility"]],
  ["src-house-guitars", "House of Guitars", "official", "https://houseofguitars.com/sitemap/", ["Friday hours", "address"]],
  ["src-house-guitars-story", "Atlas Obscura", "editorial", "https://www.atlasobscura.com/articles/on-tour-with-the-war-on-drugs-rochester-s-church-of-gear", ["warren-like layout", "rock memorabilia", "unusual character"]],
  ["src-radio-social", "Radio Social", "official", "https://radio-social.com/plan-your-visit/", ["Friday hours", "bowling reservations", "21-plus policy after 9pm"]],
  ["src-rochester-market", "City of Rochester", "government", "https://www.cityofrochester.gov/departments/department-recreation-and-human-services-drhs/public-market", ["Saturday hours", "federal-holiday closure rule"]],
  ["src-letchworth", "New York State Parks", "government", "https://parks.ny.gov/visit/state-parks/letchworth-state-park", ["2026 hours", "vehicle fee", "permanent Trail 7 closure"]],
  ["src-canalside", "Visit Buffalo Niagara", "official-tourism", "https://visitbuffalo.com/neighborhood/canalside-waterfront/", ["waterfront context", "grain-elevator skyline"]],
  ["src-buffalo-nightlife", "Reddit r/Buffalo", "forum", "https://www.reddit.com/r/Buffalo/comments/1vammle/buffalo_night_life/", ["2026 local nightlife signal", "Essex Street and live-music recommendations"]],
  ["src-annunciation", "Annunciation Greek Orthodox Church", "official-bulletin", "https://bulletinbuilder.org/HOCA/current/20260726", ["Sunday Orthros and Divine Liturgy schedule", "address"]],
  ["src-power-vista", "New York Power Authority", "government", "https://nypa.gov/Communities/Visitors-Centers/Niagara-Power-Vista", ["daily hours", "free admission and parking", "interactive exhibits"]],
  ["src-maid", "Maid of the Mist", "official", "https://www.maidofthemist.com/schedule-pricing/", ["October 11 hours", "2026 price", "US-side boarding"]],
  ["src-cave-winds", "Niagara Falls State Park", "official", "https://www.niagarafallsstatepark.com/attractions/cave-of-the-winds/", ["October 11 hours", "2026 admission", "wet-footwear warning"]],
  ["src-niagara-park", "New York State Parks", "government", "https://parks.ny.gov/visit/state-parks/niagara-falls-state-park", ["US park access", "October parking fee"]],
  ["src-niagara-light", "Niagara Falls State Park", "official", "https://www.niagarafallsstatepark.com/tours-events/illuminations/", ["October 11 illumination start time"]],
  ["src-martin", "Frank Lloyd Wright's Martin House", "official", "https://martinhouse.org/visit/prepare/hours/", ["Monday hours", "interior guided-tour requirement"]],
  ["src-martin-tours", "Frank Lloyd Wright's Martin House", "official", "https://martinhouse.org/tours/", ["tour types", "2026 price", "advance booking"]],
  ["src-tr", "Theodore Roosevelt Inaugural Site", "official", "https://www.trsite.org/about/faq/", ["October 12 hours", "guided-only visit", "admission"]],
  ["src-armory", "Visit Syracuse", "official-tourism", "https://www.visitsyracuse.com/things-to-do/neighborhoods/armory-square/", ["restaurants and compact historic-district context"]],
  ["src-erie", "Erie Canal Museum", "official", "https://eriecanalmuseum.org/visit/", ["daily hours", "pay-what-you-wish admission", "2026 construction warning"]],
  ["src-pine", "Albany Pine Bush Preserve Commission", "official", "https://www.albanypinebush.org/", ["Tuesday hours", "free Discovery Center", "globally rare inland pine barrens"]],
  ["src-pine-forum", "Reddit r/Albany", "forum", "https://www.reddit.com/r/Albany/comments/1s4qwmm/pine_bush_discovery_center/", ["2026 local hidden-gem validation"]],
  ["src-capitol", "New York State Office of General Services", "government", "https://empirestateplaza.ny.gov/node/10336", ["weekday tour times", "free admission", "tour duration"]],
  ["src-turnpark", "TurnPark Art Space", "official", "https://www.turnpark.com/visit/", ["Wednesday hours", "admission", "former quarry setting"]],
  ["src-magic-wings", "Magic Wings", "official", "https://magicwings.com/faq/", ["Sunday hours", "admission", "4,000 free-flying butterflies"]],
  ["src-clark", "Clark Art Institute", "official", "https://www.clarkart.edu/visit/", ["Monday closed warning", "campus access", "admission"]],
  ["src-secret", "Secret Caverns", "official", "https://secretcaverns.com/", ["2026 daily hours", "admission", "100-foot underground waterfall"]],
  ["src-fly-creek", "Fly Creek Cider Mill", "official", "https://www.flycreekcidermill.com/plan-your-visit", ["free self-guided mill tour", "working cider process"]],
  ["src-fly-creek-hours", "Fly Creek Cider Mill", "official", "https://www.flycreekcidermill.com/fly-creek-cider-mill-voted-best-cidery-nation", ["daily hours", "fall pressing season"]],
  ["src-earth", "Museum of the Earth", "official", "https://www.museumoftheearth.org/visit/plan-your-visit", ["Thursday hours", "admission", "mastodon and whale exhibits"]],
  ["src-strong", "The Strong National Museum of Play", "official", "https://www.museumofplay.org/visit/hours-and-admissions/", ["Friday hours", "admission", "half-price Friday after 4pm"]],
  ["src-eternal", "Erie County Parks", "government", "https://www3.erie.gov/parks/sites/www3.erie.gov.parks/files/2021-08/eternal-flametrail-map_11x17.pdf", ["official trail map", "trailhead and route"]],
  ["src-old-fort", "Old Fort Niagara", "official", "https://www.oldfortniagara.org/plan-your-visit", ["October 11 hours", "2026 admission", "living-history program"]],
  ["src-forest", "Forest Lawn", "official", "https://forest-lawn.com/plan-your-visit/", ["daily access", "self-guided app and map"]],
  ["src-blue-sky", "Blue Sky Mausoleum", "official", "https://www.blueskymausoleum.com/", ["Frank Lloyd Wright design", "open-sky memorial context"]],
  ["src-stockade", "Discover Schenectady", "official-tourism", "https://www.discoverschenectady.com/things-to-do/attractions/historic-stockade-stockade-tours/", ["300-year-old neighborhood", "self-guided walking tour"]],
  ["src-six", "Six Depot Roastery and Cafe", "official", "https://sixdepot.com/pages/visit-cafe", ["Wednesday hours", "historic station", "roastery and gallery"]],
  ["src-rochester-forum", "Reddit r/Rochester", "forum", "https://www.reddit.com/r/Rochester/comments/1ad7dz0", ["ARTISANworks and House of Guitars hidden-gem validation"]],
  ["src-upstate-caves-forum", "Reddit r/upstate_new_york", "forum", "https://www.reddit.com/r/upstate_new_york/comments/1v1n31f/nice_trip_to_howe_caverns_imagine_finding_this_in/", ["Howe versus Secret Caverns comparison"]],
  ["src-noaa-normals", "NOAA National Centers for Environmental Information", "government-data", "https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals", ["1991-2020 daily climate normals"]],
  ["src-osrm", "Open Source Routing Machine", "routing", "https://project-osrm.org/", ["road-network distance and no-traffic duration baselines"]]
].map(([id, publisher, type, url, supports]) => ({ id, publisher, type, url, supports, verified_at: verifiedAt }));

const replacementByPlace = new Map(replacementVariants.map((variant) => [variant.replacement_place_id, {
  day: variant.day,
  replaces_place_ids: variant.replaces_place_ids,
  route_variant_id: variant.id
}]));

function place(input) {
  const replacement = replacementByPlace.get(input.id);
  return {
    reservation: "none",
    hours: { opens: null, closes: null, status: "verified", note: "Public outdoor access during the scheduled window." },
    cost: { amount_per_person: 0, status: "verified", note: "No admission charge." },
    secondary_for: ["sheluvspaco"],
    categories: ["unusual_creative"],
    ...input,
    priority: replacement ? "replacement" : input.priority || "anchor",
    replacement: replacement ? { ...replacement, reason: input.replacement_reason } : undefined
  };
}

const seedPlaces = [
  place({ id: "three-sisters-sanctuary", name: "Three Sisters Sanctuary", kind: "environmental-art-garden", city: "Goshen", state: "MA", address: "188 Cape Street, Goshen, MA 01032", visit_date: "2026-10-04", summary: "Eight acres of hand-built garden art in the Berkshire hills: stone, water, flower beds, memorials and even a dragon cave. One man built it all by hand over many years, in memory of his daughter.", why_go: "This is not a normal sculpture park. It is one man's private world, strange and personal, and it opens the trip in a way nobody will forget.", best_for: ["viki", "stivka"], secondary_for: ["gora", "sheluvspaco"], best_fit_note: "Good for Viki, who likes dreamlike photos, and for Stivka, who likes quiet places. The family story behind it gives everyone something to feel.", categories: ["architecture_photogenic", "nature_photogenic", "unusual_creative", "hidden_history_folklore"], duration_minutes: 90, hours: { opens: "08:00", closes: "18:00", status: "verified", note: "Official daily garden hours." }, cost: { amount_per_person: 20, status: "verified", note: "Adult entry." }, source_ids: ["src-three-sisters"] }),
  place({ id: "smith-botanic-garden", name: "Lyman Conservatory & Smith Botanic Garden", kind: "botanic-conservatory", city: "Northampton", state: "MA", address: "16 College Lane, Northampton, MA 01063", visit_date: "2026-10-04", summary: "A glasshouse from 1895 at Smith College, free to enter. Inside there are rooms with different climates, from desert to rainforest, full of unusual plants. Outside there is a park with many kinds of trees.", why_go: "A warm green room full of strange plants, in the middle of a long driving day. Much better than a normal stop at the side of the road, and it costs nothing.", best_for: ["viki", "stivka"], secondary_for: ["sheluvspaco"], best_fit_note: "Good for Viki's plant and glasshouse photos, and for Stivka, who prefers calm places.", categories: ["architecture_photogenic", "nature_photogenic"], duration_minutes: 60, priority: "supporting", hours: { opens: "09:00", closes: "16:00", status: "verified", note: "Daily Lyman Conservatory hours." }, source_ids: ["src-smith"] }),
  place({ id: "tunnel-bar-northampton", name: "The Tunnel Bar", kind: "cocktail-bar", city: "Northampton", state: "MA", address: "125 Pleasant Street, Northampton, MA 01060", visit_date: "2026-10-04", summary: "A cocktail bar built inside the old brick tunnel that passengers once used to walk under Northampton's railway station. It is long, narrow and completely underground.", why_go: "You drink in a railway tunnel under the old station. An easy, social first evening that does not turn into a late night before an early start.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki, who loves unusual rooms, and for Gora's social side. Paco gets a relaxed start to the trip.", categories: ["architecture_photogenic", "unusual_creative", "live_social_nightlife"], duration_minutes: 90, priority: "supporting", hours: { opens: "16:00", closes: "23:00", status: "map-verified", note: "Sunday hours; reconfirm before travel." }, cost: { amount_per_person: 25, status: "planning-estimate", note: "One drink plus food; nightlife spending is excluded from the route budget target." }, source_ids: ["src-tunnel", "src-tunnel-maps"] }),
  place({ id: "mass-moca", name: "MASS MoCA", kind: "contemporary-art-museum", city: "North Adams", state: "MA", address: "1040 MASS MoCA Way, North Adams, MA 01247", visit_date: "2026-10-05", summary: "A huge old factory of 24 buildings, now full of modern art. The works are made for whole rooms, not for walls: light, sound and color by artists such as James Turrell, Laurie Anderson and Sol LeWitt.", why_go: "Art the size of buildings, inside a factory the size of a village. You walk through it, and nobody expects you to behave like a gallery visitor.", best_for: ["viki", "stivka"], secondary_for: ["gora", "sheluvspaco"], best_fit_note: "Good for Viki, who likes big unusual spaces and strong images. Stivka gets experimental sound and very large rooms.", categories: ["architecture_photogenic", "unusual_creative", "hidden_history_folklore"], duration_minutes: 150, reservation: "recommended", hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Monday hours; Tuesday is closed." }, cost: { amount_per_person: 25, status: "verified", note: "Adult admission; some Turrell works require a no-cost reservation." }, source_ids: ["src-mass-moca", "src-mass-moca-exhibitions"] }),
  place({ id: "grafton-peace-pagoda", name: "Grafton Peace Pagoda", kind: "spiritual-landmark", city: "Petersburgh", state: "NY", address: "87 Crandall Road, Petersburgh, NY 12138", visit_date: "2026-10-05", summary: "A white Buddhist peace pagoda on a quiet wooded hill, built by the Japanese order Nipponzan Myohoji. Paths lead around it, and there are wide views over the valley.", why_go: "A calm, honest place of prayer between two cities, with almost no tourists. We visit with respect, not as a curiosity.", best_for: ["stivka", "viki"], secondary_for: ["gora", "sheluvspaco"], best_fit_note: "Good for Stivka, who takes faith seriously, and for Viki, who likes buildings in nature.", categories: ["architecture_photogenic", "nature_photogenic", "orthodox_spiritual"], duration_minutes: 60, hours: { opens: "07:00", closes: "18:15", status: "verified-seasonal", note: "Official policy is sunrise to sunset daily; displayed times are a planning daylight window." }, source_ids: ["src-grafton"] }),
  place({ id: "saratoga-mineral-springs", name: "Saratoga Mineral-Spring Tasting Walk", kind: "mineral-spring-walk", city: "Saratoga Springs", state: "NY", address: "Saratoga Spa State Park, Saratoga Springs, NY 12866", visit_date: "2026-10-05", summary: "A short walk between natural mineral springs in the town park. The water comes out of the ground with natural bubbles, and every spring tastes completely different. You can drink from them.", why_go: "You do not only look at a spa town, you taste it. Try Orenda, Hathorn and the others and see which one you can actually drink.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki, who enjoys strange experiences, and for Gora, who wants to know what is really under a polished resort story.", categories: ["nature_photogenic", "unusual_creative", "hidden_history_folklore"], duration_minutes: 65, hours: { opens: "07:00", closes: "18:15", status: "verified-seasonal", note: "Park is year-round; planning window stays within daylight." }, cost: { amount_per_person: 0, status: "verified", note: "Springs are free; October 5 is a Monday, so the seasonal weekend/holiday vehicle fee does not apply." }, source_ids: ["src-saratoga", "src-saratoga-springs-map"] }),
  place({ id: "congress-park", name: "Congress Park & Canfield Casino", kind: "historic-park", city: "Saratoga Springs", state: "NY", address: "268 Broadway, Saratoga Springs, NY 12866", visit_date: "2026-10-05", summary: "A small park in the middle of Saratoga Springs with mineral springs, Italian gardens and marble statues. In the middle stands the old Canfield Casino, a rich and highly decorated gambling house.", why_go: "Money, gambling and health cures in one small park. It is beautiful at sunset, and the casino tells the part of the story the spa brochures leave out.", best_for: ["viki", "gora"], secondary_for: ["sheluvspaco"], best_fit_note: "Good for Viki's architecture photos and for Gora, who wants the real gambling history behind the elegant image.", categories: ["architecture_photogenic", "nature_photogenic", "hidden_history_folklore"], duration_minutes: 60, priority: "supporting", source_ids: ["src-congress"] }),
  place({ id: "howe-caverns", name: "Howe Caverns Traditional Tour", kind: "cave-tour", city: "Howes Cave", state: "NY", address: "255 Discovery Drive, Howes Cave, NY 12092", visit_date: "2026-10-06", summary: "A 90-minute walk through limestone passages deep under the ground. The tour includes a quarter-mile boat ride on an underground river, and there are 139 steps.", why_go: "You go down into the rock and then travel by boat on a river under the ground. Dramatic, but organised and safe enough for a driving day.", best_for: ["gora", "viki"], secondary_for: ["sheluvspaco"], best_fit_note: "Good for Gora, who likes geology and discovery, and for Viki, who wants places that look nothing like normal sightseeing.", categories: ["nature_photogenic", "unusual_creative", "athletic_adrenaline"], duration_minutes: 90, reservation: "required", hours: { opens: "10:00", closes: "17:00", status: "ticket-calendar-pending", note: "Traditional tour must be booked online; lock a 10:00 slot when October inventory opens." }, cost: { amount_per_person: 29.5, status: "verified-before-fees", note: "2026 adult base price; taxes and online fees extra." }, source_ids: ["src-howe", "src-howe-price", "src-upstate-caves-forum"] }),
  place({ id: "iroquois-museum", name: "Iroquois Museum", kind: "indigenous-museum", city: "Howes Cave", state: "NY", address: "324 Caverns Road, Howes Cave, NY 12092", visit_date: "2026-10-06", summary: "A museum about the Haudenosaunee (Iroquois) people, in a building shaped like a traditional longhouse. It shows modern Native art together with history, and Native people decide how that history is told.", why_go: "Most road trips treat Native history as scenery or a short footnote. Here the people tell their own story, in their own building.", best_for: ["gora", "stivka"], secondary_for: ["viki", "sheluvspaco"], best_fit_note: "Good for Gora, who wants to look past the simple mainstream story, and for Stivka, who cares about belief and community.", categories: ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], duration_minutes: 75, hours: { opens: "10:00", closes: "17:00", status: "verified", note: "May 1-October 31 Tuesday hours." }, cost: { amount_per_person: 8, status: "verified", note: "Adult admission." }, source_ids: ["src-iroquois"] }),
  place({ id: "cooperstown-lakefront", name: "Council Rock & Otsego Lakefront", kind: "lakefront-viewpoint", city: "Cooperstown", state: "NY", address: "River Street, Cooperstown, NY 13326", visit_date: "2026-10-06", summary: "A small park on the shore of Otsego Lake, where the Susquehanna River begins. Hills stand around the water, and in October the trees are turning color.", why_go: "Ten quiet minutes by the water before dinner. It lets Cooperstown feel like a real small town, not only a row of museums.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki's quiet lake photos, and for Gora, who needs a break after two museums.", categories: ["nature_photogenic", "hidden_history_folklore"], duration_minutes: 40, priority: "supporting", source_ids: ["src-cooperstown"] }),
  place({ id: "brewery-ommegang", name: "Brewery Ommegang Farmstead Taproom", kind: "brewery-taproom", city: "Cooperstown", state: "NY", address: "656 County Highway 33, Cooperstown, NY 13326", visit_date: "2026-10-06", summary: "A Belgian-style brewery on a farm outside Cooperstown, with a large lawn, a restaurant and small glasses for tasting several beers.", why_go: "A relaxed evening with good beer and food on a farm. Social, but not a big night out, so the next morning still works.", best_for: ["gora", "stivka"], secondary_for: ["viki", "sheluvspaco"], best_fit_note: "Good for Gora's social side and for Stivka, who enjoys an easy beer evening. Viki still gets a beautiful farm setting.", categories: ["architecture_photogenic", "food_coffee_shopping", "live_social_nightlife"], duration_minutes: 120, priority: "supporting", hours: { opens: "12:00", closes: "20:00", status: "verified", note: "Tuesday café, mercantile and taproom hours; brewery tours are weekend-only." }, cost: { amount_per_person: 30, status: "planning-estimate", note: "Food and one tasting; drinks are excluded from the route budget target." }, source_ids: ["src-ommegang", "src-cooperstown"] }),
  place({ id: "fenimore-farm", name: "Fenimore Farm & Country Village", kind: "living-history-museum", city: "Cooperstown", state: "NY", address: "5775 State Highway 80, Cooperstown, NY 13326", visit_date: "2026-10-07", summary: "A working farm and a rebuilt 19th-century village. Staff do the old jobs with real tools, and in autumn the village fills with handmade scarecrows.", why_go: "Not just old buildings: this is where the Cardiff Giant and the hand-carved carousel live, and both get their own stop.", best_for: ["gora", "stivka"], secondary_for: ["viki", "sheluvspaco"], best_fit_note: "Good for Gora, who likes history you can touch, and for Stivka, who is interested in older community life.", categories: ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], duration_minutes: 60, hours: { opens: "10:00", closes: "16:00", status: "verified-seasonal", note: "September 2-October 31 Wednesday hours; homepage may show broader summer hours, so use the dated seasonal schedule." }, cost: { amount_per_person: 17.5, status: "verified", note: "Admission also covers the Cardiff Giant and Empire State Carousel." }, source_ids: ["src-fenimore"] }),
  place({ id: "cardiff-giant", name: "The Cardiff Giant", kind: "historic-hoax", city: "Cooperstown", state: "NY", address: "Inside Fenimore Farm, 5775 State Highway 80, Cooperstown, NY 13326", visit_date: "2026-10-07", summary: "A ten-foot stone figure of a man, made in 1868 and buried so that people would find it. The maker was inspired by a line in the Bible about giants. Thousands paid to see it before it was proved false.", why_go: "One of the most successful fakes in American history. People believed it because they wanted to, and that is what makes it worth twenty minutes.", best_for: ["gora", "stivka"], secondary_for: ["viki", "sheluvspaco"], best_fit_note: "Good for Gora, who is interested in how truth gets bent, and for Stivka, because the Bible was used to sell the lie.", categories: ["hidden_history_folklore", "unusual_creative"], duration_minutes: 20, hours: { opens: "10:00", closes: "16:00", status: "verified", note: "Open during Fenimore Farm hours." }, cost: { amount_per_person: 0, status: "included", note: "Included with Fenimore Farm admission." }, source_ids: ["src-fenimore-explore"] }),
  place({ id: "empire-state-carousel", name: "Empire State Carousel", kind: "folk-art-carousel", city: "Cooperstown", state: "NY", address: "Inside Fenimore Farm, 5775 State Highway 80, Cooperstown, NY 13326", visit_date: "2026-10-07", summary: "A carousel you can ride, built as a museum of New York State. It has 25 hand-carved animals and painted panels of local stories. More than 1,000 volunteers made it by hand.", why_go: "State history you can sit on and ride. A thousand people made it by hand, and it is far more fun than another glass case.", best_for: ["viki", "stivka"], secondary_for: ["sheluvspaco", "gora"], best_fit_note: "Good for Viki, who likes playful images, and for Stivka, who appreciates craft, music and art made by a community.", categories: ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], duration_minutes: 25, hours: { opens: "10:00", closes: "16:00", status: "verified", note: "Open during Fenimore Farm hours." }, cost: { amount_per_person: 0, status: "included", note: "Included with Fenimore Farm admission." }, source_ids: ["src-fenimore-explore"] }),
  place({ id: "taughannock-falls", name: "Taughannock Falls Gorge Walk", kind: "waterfall-walk", city: "Trumansburg", state: "NY", address: "1740 Taughannock Boulevard, Trumansburg, NY 14886", visit_date: "2026-10-07", summary: "An easy walk of about 0.75 miles along a gorge to a waterfall 215 feet high. The water falls into a round stone bowl with very high walls.", why_go: "This waterfall is taller than the main drop at Niagara, but the walk to it is flat and calm. Big reward, small effort.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki's strongest autumn photos and for Gora's quiet side. The 1.5-mile round trip rests the group instead of tiring it.", categories: ["nature_photogenic"], duration_minutes: 90, hours: { opens: "07:10", closes: "18:35", status: "verified-seasonal", note: "Dawn-to-dusk park; all trails were open in the April 17, 2026 update. Recheck conditions." }, cost: { amount_per_person: 5, status: "derived", note: "Two $10 vehicle fees split four ways." }, source_ids: ["src-taughannock"] }),
  place({ id: "cornell-botanic-gardens", name: "Cornell Botanic Gardens & Newman Arboretum", kind: "botanic-garden", city: "Ithaca", state: "NY", address: "124 Comstock Knoll Drive, Ithaca, NY 14850", visit_date: "2026-10-07", summary: "A large free garden and tree park belonging to Cornell University, with theme gardens, ponds and sculpture. It was planted to look its best in autumn.", why_go: "A calm, free end to a day full of museums, with no queue and no fixed time. Perfect in the last hour of daylight.", best_for: ["viki", "stivka"], secondary_for: ["gora", "sheluvspaco"], best_fit_note: "Good for Viki's autumn colors and landscapes, and for Stivka, who likes a calm finish to the day.", categories: ["nature_photogenic", "architecture_photogenic"], duration_minutes: 50, priority: "supporting", hours: { opens: "07:10", closes: "18:35", status: "verified-seasonal", note: "Grounds are free daily dawn to dusk; Welcome Center closes at 17:00." }, cost: { amount_per_person: 0.75, status: "derived", note: "Approximate share of one hour of ParkMobile parking for two cars; admission is free." }, source_ids: ["src-cornell"] }),
  place({ id: "ithaca-falls", name: "Ithaca Falls at Lake Street", kind: "urban-waterfall", city: "Ithaca", state: "NY", address: "Lake Street, Ithaca, NY 14850", visit_date: "2026-10-08", summary: "A waterfall 150 feet high, almost inside the city. You park at the road and walk a few minutes to reach it.", why_go: "A big waterfall a few steps from the street, first thing in the morning. Very little effort for a very strong start to the day.", best_for: ["viki", "gora"], secondary_for: ["sheluvspaco"], best_fit_note: "Good for Viki's city-meets-nature photo, and for Gora, who wants fresh air without a long walk.", categories: ["nature_photogenic", "unusual_creative"], duration_minutes: 30, source_ids: ["src-ithaca-gorges"] }),
  place({ id: "corning-museum-of-glass", name: "Corning Museum of Glass", kind: "art-science-museum", city: "Corning", state: "NY", address: "1 Museum Way, Corning, NY 14830", visit_date: "2026-10-08", summary: "The most important glass museum in the world. It shows 3,500 years of glass, has live demonstrations where workers shape hot glass in front of you, and a bright modern wing for contemporary work.", why_go: "You watch people shape glowing hot glass by hand, then see everything humans have made from glass over 3,500 years.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki, who loves material and color, and for Gora, who wants to see how difficult things are actually made.", categories: ["architecture_photogenic", "unusual_creative", "hidden_history_folklore"], duration_minutes: 165, reservation: "recommended", hours: { opens: "09:00", closes: "17:00", status: "verified", note: "April-December daily hours." }, cost: { amount_per_person: 25, status: "verified", note: "Adult admission; valid two consecutive days." }, source_ids: ["src-corning", "src-corning-fall"] }),
  place({ id: "make-your-own-glass", name: "Make Your Own Glass: Fall Object", kind: "hands-on-workshop", city: "Corning", state: "NY", address: "The Studio, 1 Museum Way, Corning, NY 14830", visit_date: "2026-10-08", summary: "A short guided session where each person shapes their own object from hot glass, with help from a glassmaker. You take it home with you.", why_go: "Everyone leaves with something they made with their own hands. Better than another photograph, and every object is different.", best_for: ["viki", "sheluvspaco"], secondary_for: ["gora", "stivka"], best_fit_note: "Good for Viki's creative side, and for Paco, who wants one shared moment where each person still makes something of their own.", categories: ["unusual_creative", "architecture_photogenic"], duration_minutes: 45, reservation: "required", hours: { opens: "09:00", closes: "17:00", status: "verified", note: "Daily; advance slots frequently sell out." }, cost: { amount_per_person: 48, status: "planning-estimate", note: "Projects range from $13-$62; budget assumes a blown seasonal object." }, source_ids: ["src-corning-make", "src-corning-fall"] }),
  place({ id: "rochester-high-falls", name: "High Falls & Pont de Rennes View", kind: "industrial-waterfall-view", city: "Rochester", state: "NY", address: "4 Cataract Street, Rochester, NY 14605", visit_date: "2026-10-08", summary: "A waterfall 96 feet high in the middle of Rochester, surrounded by old mills, bridges and brick factory walls. You see it from a footbridge.", why_go: "A big waterfall between factory walls. It shows you at once why the city was built here.", best_for: ["viki", "gora"], secondary_for: ["sheluvspaco"], best_fit_note: "Good for Viki, who photographs nature and industry together, and for Gora's interest in industrial history.", categories: ["architecture_photogenic", "nature_photogenic", "hidden_history_folklore"], duration_minutes: 55, priority: "supporting", source_ids: ["src-rochester-forum"] }),
  place({ id: "george-eastman-museum", name: "George Eastman Museum", kind: "photography-film-museum", city: "Rochester", state: "NY", address: "900 East Avenue, Rochester, NY 14607", visit_date: "2026-10-09", summary: "The restored house and gardens of George Eastman, who founded Kodak. It holds one of the world's most important collections of photography and film. In 2026 there is an exhibition about the Lambda Network, the LGBT employee group at Kodak.", why_go: "A beautiful house and the whole history of photography in one place. The Kodak exhibition also shows the company's real inside story, not only its advertising.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki's photography, and for Gora, who is interested in the difference between a company's public image and the lives of its workers.", categories: ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], duration_minutes: 105, hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Friday hours; Picturing Equality runs through November 8, 2026." }, cost: { amount_per_person: 23, status: "verified", note: "Adult museum admission." }, source_ids: ["src-eastman"] }),
  place({ id: "artisanworks", name: "ARTISANworks", kind: "immersive-art-maze", city: "Rochester", state: "NY", address: "565 Blossom Road, Rochester, NY 14610", visit_date: "2026-10-09", summary: "An old factory filled from floor to ceiling with art, themed rooms, old fire engines, cars and working studios. There is no fixed route: you simply wander.", why_go: "People in Rochester call it the city's hidden gem. Nothing is tidy, and that is exactly why it is fun to explore.", best_for: ["viki", "stivka"], secondary_for: ["gora", "sheluvspaco"], best_fit_note: "Good for Viki, who loves places that are full and unusual, and for Stivka, who likes music, craft and strong personality.", categories: ["architecture_photogenic", "unusual_creative", "hidden_history_folklore"], duration_minutes: 120, hours: { opens: "12:00", closes: "17:00", status: "verified", note: "Public Friday-Sunday hours." }, cost: { amount_per_person: 15, status: "verified", note: "Adult admission." }, source_ids: ["src-artisanworks", "src-rochester-forum"] }),
  place({ id: "house-of-guitars", name: "House of Guitars", kind: "cult-music-store", city: "Rochester", state: "NY", address: "645 Titus Avenue, Rochester, NY 14617", visit_date: "2026-10-09", summary: "A famous and very untidy music shop: narrow stairs, old guitars, dusty rooms full of records, and walls covered with signed instruments.", why_go: "It is messy, dark and full of treasure. Local musicians call it a time capsule, and the fun is in the search.", best_for: ["stivka", "gora"], secondary_for: ["viki", "sheluvspaco"], best_fit_note: "Good for Stivka's love of metal and rock, and for Gora, who enjoys digging through unsorted history for something real.", categories: ["unusual_creative", "hidden_history_folklore", "food_coffee_shopping"], duration_minutes: 60, priority: "supporting", hours: { opens: "10:00", closes: "21:00", status: "verified", note: "Monday-Saturday hours." }, source_ids: ["src-house-guitars", "src-house-guitars-story", "src-rochester-forum"] }),
  place({ id: "radio-social", name: "Radio Social Bowling Night", kind: "social-games-night", city: "Rochester", state: "NY", address: "20 Carlson Road, Rochester, NY 14610", visit_date: "2026-10-09", summary: "A large old industrial building turned into a place with bowling lanes, garden games, Mediterranean food, drinks and DJs. It is stylish but relaxed, and it is not a nightclub.", why_go: "The first big night out: bowling, food and music in one building. Everyone can join in without being pushed onto a dance floor.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki and Gora's social sides. Bowling and food let Stivka and Paco join in without a normal club night.", categories: ["live_social_nightlife", "unusual_creative"], duration_minutes: 240, reservation: "recommended", hours: { opens: "16:30", closes: "24:00", status: "verified", note: "Friday hours; 21+ after 21:00." }, cost: { amount_per_person: 55, status: "planning-estimate", note: "Lane share, shoes, food and drinks; excluded from the route budget target as nightlife." }, source_ids: ["src-radio-social"] }),
  place({ id: "rochester-public-market", name: "Rochester Public Market", kind: "public-market", city: "Rochester", state: "NY", address: "280 North Union Street, Rochester, NY 14609", visit_date: "2026-10-10", summary: "A city market more than 120 years old. Under long open roofs there are fruit and vegetable stalls, bakeries, immigrant food stands and breakfast counters.", why_go: "Breakfast inside real Rochester life instead of a hotel dining room. Cheap, busy, and full of things to try.", best_for: ["viki", "gora"], secondary_for: ["sheluvspaco", "stivka"], best_fit_note: "Good for Viki, who likes looking around markets, and for Gora, who enjoys meeting different people over simple food.", categories: ["food_coffee_shopping", "architecture_photogenic", "hidden_history_folklore"], duration_minutes: 90, hours: { opens: "06:00", closes: "15:00", status: "verified", note: "Saturday market hours; October 10 is not a federal holiday." }, source_ids: ["src-rochester-market"] }),
  place({ id: "letchworth-falls", name: "Letchworth Three-Falls Drive", kind: "waterfall-scenic-drive", city: "Castile", state: "NY", address: "1 Letchworth State Park, Castile, NY 14427", visit_date: "2026-10-10", summary: "A drive along a deep river gorge with walls up to 600 feet high. You stop at the Upper and Middle Falls and at the tall Genesee Arch railway bridge.", why_go: "The best autumn colors of the whole trip, seen from viewpoints you drive to. Short walks only, no hard hiking.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki's most dramatic autumn photos and for Gora's quiet side. Everyone benefits from the very light walking.", categories: ["nature_photogenic", "architecture_photogenic"], duration_minutes: 165, hours: { opens: "06:00", closes: "23:00", status: "verified", note: "Drive between Middle Falls and Upper Falls/Arch Bridge: Trail 7 between them is permanently closed." }, cost: { amount_per_person: 5, status: "derived", note: "Two $10 vehicle fees split four ways; collected 09:00-17:00 through October 18." }, source_ids: ["src-letchworth"] }),
  place({ id: "buffalo-canalside", name: "Canalside & Grain-Elevator Skyline", kind: "waterfront-district", city: "Buffalo", state: "NY", address: "44 Prime Street, Buffalo, NY 14202", visit_date: "2026-10-10", summary: "Buffalo's waterfront, with old naval ships, the remains of the Erie Canal, lift bridges and enormous grain towers on the far bank.", why_go: "Small boats and giant grain towers in the same view. It shows you in one look what built this city.", best_for: ["viki", "gora"], secondary_for: ["sheluvspaco"], best_fit_note: "Good for Viki's industrial waterfront photos, and for Gora, who wants to see the machines behind a city's power.", categories: ["architecture_photogenic", "nature_photogenic", "hidden_history_folklore"], duration_minutes: 90, priority: "supporting", source_ids: ["src-canalside"] }),
  place({ id: "elmwood-essex-music-night", name: "Elmwood–Essex–Allentown Music Circuit", kind: "live-music-bar-circuit", city: "Buffalo", state: "NY", address: "Start at Essex Street Pub, 530 Rhode Island Street, Buffalo, NY 14213", visit_date: "2026-10-10", summary: "An evening in Buffalo's bar streets, built around Essex Street Pub and one live concert we check in advance at Nietzsche's or another Elmwood venue. We move between them by taxi.", why_go: "A real local music night, chosen in advance so we do not simply wander and hope. Bars, live music, and no big club.", best_for: ["stivka", "gora"], secondary_for: ["viki", "sheluvspaco"], best_fit_note: "Good for Stivka if the concert is rock or metal, and for Gora, who likes a busy bar where you can still talk. Viki gets a whole neighborhood, not one room.", categories: ["live_social_nightlife", "hidden_history_folklore"], duration_minutes: 240, reservation: "check-later", hours: { opens: "20:00", closes: "24:00", status: "live-calendar-pending", note: "Choose the exact live set 4-6 weeks before travel; use rideshare and stay together between venues." }, cost: { amount_per_person: 65, status: "planning-estimate", note: "Cover, rideshare share, food and drinks; excluded from the target as nightlife." }, source_ids: ["src-buffalo-nightlife"] }),
  place({ id: "annunciation-buffalo", name: "Orthros & Divine Liturgy at Annunciation", kind: "orthodox-church-service", city: "Buffalo", state: "NY", address: "146 West Utica Street, Buffalo, NY 14222", visit_date: "2026-10-11", summary: "Sunday morning worship in Buffalo's historic Greek Orthodox Church of the Annunciation. It begins with Orthros, the morning prayers, and continues into the Divine Liturgy.", why_go: "Sunday stays a real Sunday. This is part of our normal life on the trip, not a quick photo inside a church.", best_for: ["stivka", "sheluvspaco"], secondary_for: ["gora", "viki"], best_fit_note: "Good for Stivka's faith, and for Paco, who wants the trip to feel truly shared. It gives all four a calm centre before Niagara.", categories: ["orthodox_spiritual", "architecture_photogenic", "hidden_history_folklore"], duration_minutes: 165, hours: { opens: "08:45", closes: "11:30", status: "verified-recurring", note: "Sunday Orthros at 08:45 and Divine Liturgy at 10:00; confirm the October bulletin closer to travel." }, cost: { amount_per_person: 0, status: "donation-optional", note: "No admission; optional offering." }, source_ids: ["src-annunciation"] }),
  place({ id: "niagara-power-vista", name: "Niagara Power Vista", kind: "interactive-power-museum", city: "Lewiston", state: "NY", address: "5777 Lewiston Road, Lewiston, NY 14092", visit_date: "2026-10-11", summary: "A free viewing platform high above the Niagara river, over New York's huge hydroelectric power station. Inside there are more than 50 hands-on exhibits, including a ride where you control a virtual power grid.", why_go: "See how Niagara is used before you see how it looks. Free, hands-on, and it makes the whole day make sense.", best_for: ["gora", "viki"], secondary_for: ["sheluvspaco", "stivka"], best_fit_note: "Good for Gora, who wants the engineering behind the public story, and for Viki, who likes unusual buildings and high river views.", categories: ["architecture_photogenic", "unusual_creative", "hidden_history_folklore"], duration_minutes: 60, hours: { opens: "09:00", closes: "17:00", status: "verified", note: "Open daily except certain holidays; October 11 is not a listed closure." }, source_ids: ["src-power-vista"] }),
  place({ id: "maid-of-the-mist", name: "Maid of the Mist", kind: "boat-experience", city: "Niagara Falls", state: "NY", address: "332 Prospect Street, Niagara Falls, NY 14303", visit_date: "2026-10-11", summary: "An electric boat that goes from the American side right into the spray at the bottom of Niagara Falls.", why_go: "You cannot understand the size of Niagara from the edge. On the boat you feel it: noise, water and wind.", best_for: ["viki", "gora"], secondary_for: ["sheluvspaco", "stivka"], best_fit_note: "Good for Viki's once-in-a-lifetime memory and for Gora, who loves raw natural force. Almost everyone enjoys this one.", categories: ["nature_photogenic", "athletic_adrenaline"], duration_minutes: 75, reservation: "recommended", hours: { opens: "09:00", closes: "17:00", status: "verified-date-specific", note: "Official September 28-November 8 daily schedule; boarding remains first-come even with online tickets." }, cost: { amount_per_person: 30.25, status: "verified", note: "2026 adult ticket including the elevator." }, source_ids: ["src-maid"] }),
  place({ id: "cave-of-the-winds", name: "Cave of the Winds", kind: "waterfall-deck-experience", city: "Niagara Falls", state: "NY", address: "10 Goat Island Loop Road, Niagara Falls, NY 14303", visit_date: "2026-10-11", summary: "A lift takes you down beside Bridal Veil Falls, and wooden walkways bring you close enough to stand in the spray.", why_go: "The boat shows you the whole waterfall. Here you stand right under it. Two different experiences, not the same thing twice.", best_for: ["gora", "viki"], secondary_for: ["sheluvspaco"], best_fit_note: "Good for Gora's physical side and for Viki, who wants a memory she will feel. Stivka can stay on the lower decks if the spray is too much.", categories: ["nature_photogenic", "unusual_creative"], duration_minutes: 75, reservation: "none", hours: { opens: "09:00", closes: "18:15", status: "verified-date-specific", note: "October 10-11 schedule; last ticket at 18:15. Bring footwear that can get wet." }, cost: { amount_per_person: 23, status: "verified", note: "2026 adult in-season price; tickets sold on site." }, source_ids: ["src-cave-winds"] }),
  place({ id: "goat-island-illumination", name: "Goat Island & Terrapin Point Illumination", kind: "night-waterfall-view", city: "Niagara Falls", state: "NY", address: "Goat Island Loop Road, Niagara Falls, NY 14303", visit_date: "2026-10-11", summary: "Paths around Goat Island in the last light of day, ending at Terrapin Point when the colored lights are switched on across the falls.", why_go: "The quiet end of the Niagara day: first gold light, then colored light on the water. Nothing to book and nothing to rush.", best_for: ["viki", "stivka"], secondary_for: ["gora", "sheluvspaco"], best_fit_note: "Good for Viki's final famous photographs, and for Stivka, who prefers a slow calm finish after an intense day.", categories: ["nature_photogenic", "live_social_nightlife"], duration_minutes: 120, hours: { opens: "17:00", closes: "24:00", status: "verified-date-specific", note: "The public park walk begins at 17:00; illumination begins at 18:15 on October 1-15 and continues to 02:00. Route leaves by 19:00." }, cost: { amount_per_person: 5, status: "derived", note: "Two $10 park vehicle fees split four ways; walking access itself is free." }, source_ids: ["src-niagara-park", "src-niagara-light"] }),
  place({ id: "martin-house", name: "Frank Lloyd Wright's Martin House", kind: "architecture-tour", city: "Buffalo", state: "NY", address: "125 Jewett Parkway, Buffalo, NY 14214", visit_date: "2026-10-12", summary: "A group of houses designed by Frank Lloyd Wright, now completely restored. There is decorated glass in the windows, a long covered walkway and a rebuilt glasshouse.", why_go: "One of Frank Lloyd Wright's greatest works, rebuilt over forty years after it was nearly lost. You see both the design and the repair.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki's eye for architecture, and for Gora, who is interested in the slow honest truth behind a 40-year rebuild.", categories: ["architecture_photogenic", "hidden_history_folklore"], duration_minutes: 75, reservation: "required", hours: { opens: "09:30", closes: "16:00", status: "verified", note: "Monday hours; interior access is by tour. Arrive 15-20 minutes early." }, cost: { amount_per_person: 25, status: "verified", note: "75-minute Martin House Tour." }, source_ids: ["src-martin", "src-martin-tours"] }),
  place({ id: "tr-inaugural-site", name: "Theodore Roosevelt Inaugural Site", kind: "guided-history-site", city: "Buffalo", state: "NY", address: "641 Delaware Avenue, Buffalo, NY 14202", visit_date: "2026-10-12", summary: "The house where Theodore Roosevelt became president, after McKinley was shot in Buffalo. You can only visit with a guide, and the visit lasts about an hour.", why_go: "One room, one hour, one sudden change of power. It is about that exact moment, not a long list of presidents.", best_for: ["gora", "stivka"], secondary_for: ["sheluvspaco", "viki"], best_fit_note: "Good for Gora, who likes real turning points in history, and for Stivka, who thinks about duty, death and responsibility.", categories: ["hidden_history_folklore", "architecture_photogenic"], duration_minutes: 60, reservation: "recommended", hours: { opens: "10:00", closes: "17:00", status: "verified-date-specific", note: "Open daily February-December; tours hourly 10:30-15:30. Indigenous Peoples' Day is not a listed closure." }, cost: { amount_per_person: 12, status: "verified", note: "Adult admission." }, source_ids: ["src-tr"] }),
  place({ id: "armory-square", name: "Armory Square Slow Evening", kind: "historic-dining-district", city: "Syracuse", state: "NY", address: "Armory Square, Syracuse, NY 13202", visit_date: "2026-10-12", summary: "A small district of brick warehouse streets in Syracuse, now full of independent restaurants, bars and shops.", why_go: "A calm evening with a free choice of food. Monday is not a party night, so we keep it easy and rest.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki, who likes walking around a city, and for Gora's flexible social side. Everyone can split up briefly and meet again for dinner.", categories: ["architecture_photogenic", "food_coffee_shopping", "live_social_nightlife"], duration_minutes: 180, priority: "supporting", hours: { opens: "16:00", closes: "22:00", status: "venue-dependent", note: "District is always accessible; select a Monday-open restaurant closer to travel." }, cost: { amount_per_person: 45, status: "planning-estimate", note: "Dinner and one drink; personal alcohol is excluded from the target." }, source_ids: ["src-armory"] }),
  place({ id: "erie-canal-museum", name: "Erie Canal Museum & 1850 Weighlock", kind: "infrastructure-museum", city: "Syracuse", state: "NY", address: "318 Erie Boulevard East, Syracuse, NY 13202", visit_date: "2026-10-13", summary: "The last weighlock building left in the country, where canal boats were once weighed. Inside there is a full-size canal boat and exhibits about the technology, the workers and the canal that changed New York.", why_go: "The Erie Canal built this whole region. This building is the only one of its kind still standing, and you can walk inside the boat.", best_for: ["gora", "viki"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Gora's interest in infrastructure and workers, and for Viki, who likes reused old buildings. Paco gets low cost and a flexible hour.", categories: ["architecture_photogenic", "hidden_history_folklore", "unusual_creative"], duration_minutes: 60, hours: { opens: "10:00", closes: "16:00", status: "verified", note: "Daily hours; renovation work may affect parts of the 1850 building." }, cost: { amount_per_person: 12, status: "suggested-donation", note: "Pay what you wish; $12 recommended." }, source_ids: ["src-erie"] }),
  place({ id: "albany-pine-bush", name: "Albany Pine Bush Discovery Center", kind: "rare-ecosystem-center", city: "Albany", state: "NY", address: "195 New Karner Road, Albany, NY 12205", visit_date: "2026-10-13", summary: "A free visitor center and a short sandy path into one of the best remaining pine barrens on Earth. The sand comes from an ancient glacial lake, and the plants here need fire to survive.", why_go: "Sand dunes and a fire-dependent forest, in the suburbs of Albany. It looks like it belongs somewhere else completely.", best_for: ["gora", "viki"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Gora, who likes finding the real nature under ordinary land, and for Viki, who likes places that feel out of place.", categories: ["nature_photogenic", "hidden_history_folklore", "unusual_creative"], duration_minutes: 70, hours: { opens: "09:00", closes: "16:00", status: "verified", note: "Monday-Friday Discovery Center hours; preserve trails remain open 24/7." }, source_ids: ["src-pine", "src-pine-forum"] }),
  place({ id: "ny-state-capitol-plaza", name: "New York State Capitol & Empire State Plaza", kind: "civic-architecture", city: "Albany", state: "NY", address: "State Street and Washington Avenue, Albany, NY 12224", visit_date: "2026-10-13", summary: "New York's parliament building, built in heavy carved stone with huge staircases. Next to it stands a completely different modern concrete plaza with a building shaped like an egg.", why_go: "Two kinds of government in stone, side by side: heavy 19th-century decoration and cold 20th-century concrete. The contrast is the point.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki, who likes strong architectural contrast, and for Gora's interest in politics. The outdoor walk is free and easy to shorten.", categories: ["architecture_photogenic", "hidden_history_folklore"], duration_minutes: 75, hours: { opens: "07:00", closes: "18:00", status: "verified-partial", note: "The 14:00 guided tour is not compatible with the Pine Bush schedule; use the public plaza and exterior, and enter only if security/public hours permit. Do not promise the Million Dollar Staircase." }, source_ids: ["src-capitol"] }),
  place({ id: "turnpark-art-space", name: "TurnPark Art Space", kind: "quarry-sculpture-park", city: "West Stockbridge", state: "MA", address: "2 Moscow Road, West Stockbridge, MA 01266", visit_date: "2026-10-14", summary: "A 16-acre marble and limestone quarry turned into an open-air sculpture park, with cliffs, meadows and very large artworks.", why_go: "The last stop of the trip: art and rock together, out in the open. Strong images, with none of the tiredness of another museum.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki's strange landscape photos and for Gora's quiet side. Paco gets a strong finish that still protects the drive to the airport.", categories: ["architecture_photogenic", "nature_photogenic", "unusual_creative"], duration_minutes: 90, hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Wednesday-Monday hours; closed Tuesday." }, cost: { amount_per_person: 14, status: "verified", note: "Adult admission." }, source_ids: ["src-turnpark"] }),

  place({ id: "magic-wings", name: "Magic Wings Butterfly Conservatory", kind: "butterfly-conservatory", city: "South Deerfield", state: "MA", address: "281 Greenfield Road, South Deerfield, MA 01373", visit_date: "2026-10-04", summary: "A warm glasshouse with more than 4,000 butterflies flying free around you, plus tortoises, birds and reptiles among tropical plants.", why_go: "Butterflies landing on you in a warm glasshouse. It works in any weather and it is genuinely magical, not just an indoor museum.", best_for: ["viki", "stivka"], secondary_for: ["sheluvspaco"], best_fit_note: "Good for Viki's color and close-up photos, and for Stivka's gentle side.", categories: ["nature_photogenic", "unusual_creative"], duration_minutes: 75, hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Sunday hours; final admission 16:30." }, cost: { amount_per_person: 20, status: "verified", note: "Adult admission." }, source_ids: ["src-magic-wings"], replacement_reason: "Use if cold rain makes the outdoor sanctuary a weak opening." }),
  place({ id: "clark-art-institute", name: "Clark Art Institute Campus", kind: "art-architecture-campus", city: "Williamstown", state: "MA", address: "225 South Street, Williamstown, MA 01267", visit_date: "2026-10-05", summary: "A quiet art campus with water pools and buildings by the Japanese architect Tadao Ando. There are forest paths outside, and inside a small but excellent collection of Old Master and Impressionist paintings.", why_go: "Calmer and more polished than MASS MoCA. This is a real choice of mood, not a weaker copy.", best_for: ["viki", "stivka"], secondary_for: ["sheluvspaco", "gora"], best_fit_note: "Good for Viki's architecture and water reflections, and for Stivka, who prefers a calm art experience.", categories: ["architecture_photogenic", "nature_photogenic", "unusual_creative"], duration_minutes: 120, hours: { opens: "09:00", closes: "17:00", status: "partial-closure", note: "Museum galleries are closed Monday; this replacement is the always-open outdoor campus and trails only, so promote it only if the group explicitly prefers architecture/nature to gallery art." }, cost: { amount_per_person: 0, status: "verified", note: "Outdoor campus and trails are open to walkers at all times; galleries would be closed Monday." }, source_ids: ["src-clark"], replacement_reason: "Outdoor architecture-and-landscape alternative when the group wants less gallery intensity." }),
  place({ id: "secret-caverns", name: "Secret Caverns", kind: "independent-cave-tour", city: "Howes Cave", state: "NY", address: "671 Caverns Road, Howes Cave, NY 12092", visit_date: "2026-10-06", summary: "A smaller, rougher cave, famous for its hand-painted road signs. You go down 103 stone steps to an underground waterfall 100 feet high.", why_go: "No polish and no boat, but a much stronger ending: a 100-foot waterfall under the ground. It also costs less.", best_for: ["gora", "viki"], secondary_for: ["sheluvspaco"], best_fit_note: "Good for Gora, who prefers rough and unpackaged places, and for Viki's unusual waterfall photos.", categories: ["nature_photogenic", "unusual_creative", "athletic_adrenaline"], duration_minutes: 60, hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Open daily in 2026; tours hourly, no reservation." }, cost: { amount_per_person: 20, status: "verified-cash", note: "$20 cash; card payment adds $2 per adult." }, source_ids: ["src-secret", "src-upstate-caves-forum"], replacement_reason: "Choose if the group values weird independent atmosphere and a giant underground waterfall over Howe's boat ride." }),
  place({ id: "fly-creek-cider-mill", name: "Fly Creek Cider Mill", kind: "working-water-mill", city: "Fly Creek", state: "NY", address: "288 Goose Street, Fly Creek, NY 13337", visit_date: "2026-10-07", summary: "An old mill that still presses apples using water power and original machinery. There is a tasting room, a mill pond, and you can walk around the working mill.", why_go: "Autumn, apples and old machines still turning. A slower and very local alternative in the Cooperstown countryside.", best_for: ["viki", "gora"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Viki's warm autumn atmosphere, and for Gora, who likes working machines and old ways of making things.", categories: ["architecture_photogenic", "food_coffee_shopping", "hidden_history_folklore"], duration_minutes: 75, hours: { opens: "09:00", closes: "18:00", status: "verified-seasonal", note: "Current daily hours and fall pressing season; reconfirm the October pressing calendar." }, cost: { amount_per_person: 0, status: "verified", note: "Self-guided mill visit is free; food, cider and shopping extra." }, source_ids: ["src-fly-creek", "src-fly-creek-hours"], replacement_reason: "Replace the three Fenimore Farm cards when the group wants a lighter, food-centered start or farm admission does not feel worth it." }),
  place({ id: "museum-of-earth", name: "Museum of the Earth", kind: "paleontology-museum", city: "Ithaca", state: "NY", address: "1259 Trumansburg Road, Ithaca, NY 14850", visit_date: "2026-10-08", summary: "A small museum about the history of life on Earth. It has an almost complete mastodon, the 44-foot skeleton of a right whale, and many fossils. A 500-foot painted wall shows life through time.", why_go: "A calm science morning instead of the drive to Corning, and it saves almost an hour in the car.", best_for: ["gora", "stivka"], secondary_for: ["viki", "sheluvspaco"], best_fit_note: "Good for Gora's interest in deep time, and for Stivka, who likes talking about creation, time and the natural world.", categories: ["hidden_history_folklore", "unusual_creative"], duration_minutes: 105, hours: { opens: "10:00", closes: "17:00", status: "verified", note: "Thursday hours; Dino Zone closes 16:30." }, cost: { amount_per_person: 12.5, status: "verified", note: "Adult admission." }, source_ids: ["src-earth"], replacement_reason: "Use for lower driving, lower cost, or when glassmaking slots are unavailable." }),
  place({ id: "strong-museum-play", name: "The Strong National Museum of Play", kind: "interactive-play-museum", city: "Rochester", state: "NY", address: "1 Manhattan Square Drive, Rochester, NY 14607", visit_date: "2026-10-09", summary: "A very large hands-on museum about play: video games, pinball machines, toys, comics, a butterfly garden and the World Video Game Hall of Fame.", why_go: "The safest choice when the group wants fun instead of strange art. Everyone finds something, and it is easy to split up.", best_for: ["sheluvspaco", "viki"], secondary_for: ["gora", "stivka"], best_fit_note: "Good for Paco, who wants the whole group happy, and for Viki's curiosity. Games make it easy to separate and meet again.", categories: ["unusual_creative", "live_social_nightlife"], duration_minutes: 180, hours: { opens: "10:00", closes: "20:00", status: "verified", note: "Friday hours; admission is half-price after 16:00 if the day is rearranged." }, cost: { amount_per_person: 25, status: "verified-floor", note: "Standard one-day adult tickets start at $25." }, source_ids: ["src-strong"], replacement_reason: "Consensus rain-proof alternative replacing ARTISANworks and House of Guitars." }),
  place({ id: "eternal-flame-falls", name: "Eternal Flame Falls", kind: "short-waterfall-hike", city: "Orchard Park", state: "NY", address: "Chestnut Ridge Park, Route 277, Orchard Park, NY 14127", visit_date: "2026-10-10", summary: "A short walk through a gorge to a small waterfall with a real flame burning behind the water. Natural gas comes out of the rock and stays alight.", why_go: "A fire that burns behind a waterfall. It sounds like a story, but it is real. The path can be muddy and the flame sometimes goes out.", best_for: ["gora", "viki"], secondary_for: ["sheluvspaco"], best_fit_note: "Good for Gora, who likes rare natural events, and for Viki's unusual nature photos. It uses our second and last walking slot.", categories: ["nature_photogenic", "hidden_history_folklore", "athletic_adrenaline"], duration_minutes: 90, hours: { opens: "07:00", closes: "18:30", status: "daylight-planning", note: "Use official trailhead; check mud, water and flame conditions. Do not relight or disturb the vent." }, source_ids: ["src-eternal"], replacement_reason: "Use if the group wants less driving and a stranger short hike instead of Letchworth's grand scenic circuit." }),
  place({ id: "old-fort-niagara", name: "Old Fort Niagara", kind: "living-history-fort", city: "Youngstown", state: "NY", address: "102 Morrow Plaza, Youngstown, NY 14174", visit_date: "2026-10-11", summary: "A fort at the mouth of the Niagara River with original 18th-century buildings. French, British, Native and American forces all held it over three hundred years.", why_go: "Real old buildings, real contested history, and a dramatic position on Lake Ontario. A good choice in bad weather, or if the boat is not for you.", best_for: ["gora", "stivka"], secondary_for: ["viki", "sheluvspaco"], best_fit_note: "Good for Gora's interest in military and power history, and for Stivka, who values old shared and sacred spaces. Viki gets the fort and the lake.", categories: ["architecture_photogenic", "hidden_history_folklore", "nature_photogenic"], duration_minutes: 120, hours: { opens: "10:00", closes: "16:00", status: "verified-date-specific", note: "Open daily September 1-October 15; ticket sales end 30 minutes before close." }, cost: { amount_per_person: 21, status: "verified", note: "2026 adult admission." }, source_ids: ["src-old-fort"], replacement_reason: "Replace Maid of the Mist and Cave of the Winds if cold, wind, queue tolerance or getting soaked makes them unattractive." }),
  place({ id: "forest-lawn-blue-sky", name: "Forest Lawn: Blue Sky Mausoleum Walk", kind: "cemetery-architecture-walk", city: "Buffalo", state: "NY", address: "1990 Main Street, Buffalo, NY 14208", visit_date: "2026-10-12", summary: "A walk through Buffalo's old cemetery to the Blue Sky Mausoleum, designed by Frank Lloyd Wright and open to the sky. On the way there are a lake and many large 19th-century monuments.", why_go: "A Frank Lloyd Wright design with no roof, in a very quiet place. Cheaper, stranger and calmer than the guided house tour.", best_for: ["stivka", "viki"], secondary_for: ["gora", "sheluvspaco"], best_fit_note: "Good for Stivka, who thinks about life and death, and for Viki's interest in natural architecture. Gora gets names and stories the city usually leaves out.", categories: ["architecture_photogenic", "nature_photogenic", "hidden_history_folklore"], duration_minutes: 75, hours: { opens: "08:00", closes: "19:00", status: "verified", note: "Daily gate hours; use Forest Lawn's free map/app and behave as visitors to an active cemetery." }, source_ids: ["src-forest", "src-blue-sky"], replacement_reason: "Quieter, free Wright-and-memorial alternative when the Martin House tour is sold out or the group needs reflection." }),
  place({ id: "schenectady-stockade", name: "Schenectady Stockade Audio Walk", kind: "historic-neighborhood-walk", city: "Schenectady", state: "NY", address: "North Church and Front Streets, Schenectady, NY 12305", visit_date: "2026-10-13", summary: "A self-guided walk through the first historic district ever protected in New York State. People have lived on these streets for more than 300 years, and hundreds of old houses remain.", why_go: "Dutch streets, floods and three centuries of continuous life, with no museum queue. Easy on a long travel day.", best_for: ["gora", "viki"], secondary_for: ["stivka", "sheluvspaco"], best_fit_note: "Good for Gora's layered regional history and for Viki's old colonial streets. It stays light on a long day.", categories: ["architecture_photogenic", "hidden_history_folklore"], duration_minutes: 60, hours: { opens: "08:00", closes: "18:00", status: "public-neighborhood", note: "Public residential streets; use the official self-guided walk, keep voices low and do not enter private property." }, source_ids: ["src-stockade"], replacement_reason: "Route-safe human-history alternative if the group prefers architecture and settlement stories to the Pine Bush ecosystem." }),
  place({ id: "six-depot", name: "No. Six Depot Roastery & Gallery", kind: "coffee-roastery-gallery", city: "West Stockbridge", state: "MA", address: "6 Depot Street, West Stockbridge, MA 01266", visit_date: "2026-10-14", summary: "A small coffee roastery, cafe and gallery inside the old railway station of West Stockbridge, looking towards Lenox Mountain.", why_go: "A warm, calm last stop if the weather is bad or the group is tired. Still a real place, not a coffee stop on the highway.", best_for: ["viki", "sheluvspaco"], secondary_for: ["stivka", "gora"], best_fit_note: "Good for Viki's love of small cafes, and for Paco, who needs to read the group's energy honestly on the last day.", categories: ["architecture_photogenic", "food_coffee_shopping", "unusual_creative"], duration_minutes: 75, hours: { opens: "08:00", closes: "15:00", status: "verified", note: "Open seven days." }, cost: { amount_per_person: 18, status: "planning-estimate", note: "Coffee and light food; no admission." }, source_ids: ["src-six"], replacement_reason: "Use for rain, fatigue or a group vote for a warm slow finale instead of the outdoor quarry." })
];

const dayPlans = [
  { day: 1, date: "2026-10-04", sleep_city: "Northampton, MA", theme: "Glasshouse calm, private mythology and a railway-tunnel drink", schedule: [["14:35", "15:35", "smith-botanic-garden", "supporting"], ["16:05", "17:35", "three-sisters-sanctuary", "anchor"], ["20:00", "21:30", "tunnel-bar-northampton", "supporting"]], lodging: { preferred_area: "Walkable downtown Northampton near Main and Pleasant Streets", fallback_area: "Hadley near Route 9 with easy parking", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Choose staffed, clean lodging with confirmed parking; Tunnel Bar should be walkable or a short rideshare." }, fallback: "If rental-car departure slips past 12:45, skip Smith Conservatory and protect Three Sisters before its 18:00 close." },
  { day: 2, date: "2026-10-05", sleep_city: "Saratoga Springs, NY", theme: "Factory-scale art, a peace ridge and mineral-water strangeness", schedule: [["10:00", "12:30", "mass-moca", "anchor"], ["13:20", "14:20", "grafton-peace-pagoda", "anchor"], ["15:40", "16:45", "saratoga-mineral-springs", "anchor"], ["17:00", "18:00", "congress-park", "supporting"]], lodging: { preferred_area: "Downtown Saratoga Springs near Broadway", fallback_area: "Exit 15 hotel cluster with strong cleanliness reviews", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Downtown is worth a modest premium because the evening remains walkable." }, fallback: "If MASS MoCA runs long, shorten Congress Park; do not rush the peace pagoda or mineral-spring circuit after dark." },
  { day: 3, date: "2026-10-06", sleep_city: "Cooperstown, NY", theme: "Underground river, Indigenous authorship and a lake-town beer reset", schedule: [["10:00", "11:30", "howe-caverns", "anchor"], ["11:45", "13:00", "iroquois-museum", "anchor"], ["14:20", "15:00", "cooperstown-lakefront", "supporting"], ["15:30", "17:30", "brewery-ommegang", "supporting"]], lodging: { preferred_area: "Cooperstown village center or lake edge", fallback_area: "Milford/Cooperstown south with excellent cleanliness and parking", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "A small inn is welcome if both room configurations and late check-in are guaranteed." }, fallback: "If the 10:00 Howe slot is unavailable, book the earliest slot that still reaches Iroquois Museum by 15:30, or promote Secret Caverns." },
  { day: 4, date: "2026-10-07", sleep_city: "Ithaca, NY", theme: "America's giant hoax, rideable folklore and a taller-than-Niagara gorge", schedule: [["10:00", "11:00", "fenimore-farm", "anchor"], ["11:00", "11:20", "cardiff-giant", "anchor"], ["11:20", "11:45", "empire-state-carousel", "anchor"], ["14:35", "16:05", "taughannock-falls", "anchor"], ["16:35", "17:25", "cornell-botanic-gardens", "supporting"]], lodging: { preferred_area: "Downtown Ithaca/Commons with a staffed garage", fallback_area: "Southwest Ithaca near Route 13", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Protect secure luggage storage because both cars remain packed until check-in." }, fallback: "The road baseline is near the cap; if departure from Fenimore is after noon, use the Taughannock overlook instead of the full gorge walk and keep Cornell optional." },
  { day: 5, date: "2026-10-08", sleep_city: "Rochester, NY", theme: "A waterfall in town, molten glass and an industrial-gorge arrival", schedule: [["08:10", "08:40", "ithaca-falls", "supporting"], ["09:45", "12:30", "corning-museum-of-glass", "anchor"], ["12:45", "13:30", "make-your-own-glass", "anchor"], ["15:40", "16:35", "rochester-high-falls", "supporting"]], lodging: { preferred_area: "East End or Neighborhood of the Arts with secure parking", fallback_area: "Pittsford/Brighton near I-490 with strong two-room inventory", room_setup: "Keep the same two rooms for two nights", notes: "Favor an area that makes Friday's museums and Radio Social a short ride." }, fallback: "If glassmaking is sold out, promote Museum of the Earth and enjoy a much shorter drive day; do not substitute a weak retail glass demo." },
  { day: 6, date: "2026-10-09", sleep_city: "Rochester, NY", theme: "Photography truth, maximalist art, rock archaeology and games", schedule: [["10:00", "11:45", "george-eastman-museum", "anchor"], ["12:15", "14:15", "artisanworks", "anchor"], ["14:35", "15:35", "house-of-guitars", "supporting"], ["19:00", "23:00", "radio-social", "anchor"]], lodging: { preferred_area: "Same East End or Neighborhood of the Arts hotel", fallback_area: "Same Pittsford/Brighton hotel", room_setup: "Keep both rooms for a second night", notes: "Cars stay parked after the afternoon; rideshare to Radio Social." }, fallback: "Promote The Strong if the group finds ARTISANworks plus House of Guitars too niche, or if Friday energy calls for one consensus indoor anchor." },
  { day: 7, date: "2026-10-10", sleep_city: "Buffalo, NY", theme: "Real market life, peak foliage, grain elevators and live music", schedule: [["07:30", "09:00", "rochester-public-market", "anchor"], ["10:30", "13:15", "letchworth-falls", "anchor"], ["14:50", "16:20", "buffalo-canalside", "supporting"], ["20:00", "24:00", "elmwood-essex-music-night", "anchor"]], lodging: { preferred_area: "Elmwood Village near Delaware/Utica with secure off-street parking", fallback_area: "Downtown near Theatre District with staffed garage", room_setup: "Keep the same two rooms for two nights", notes: "Do not leave luggage visible; use rideshare for nightlife and stay together when moving venues." }, fallback: "Promote Eternal Flame for a shorter drive and shorter hike; at Letchworth never attempt the permanently closed Trail 7 connection." },
  { day: 8, date: "2026-10-11", sleep_city: "Buffalo, NY", theme: "Orthodox Sunday, hidden hydroelectric scale and Niagara from every level", schedule: [["08:45", "11:30", "annunciation-buffalo", "anchor"], ["12:15", "13:15", "niagara-power-vista", "anchor"], ["13:45", "15:00", "maid-of-the-mist", "anchor"], ["15:15", "16:30", "cave-of-the-winds", "anchor"], ["17:00", "19:00", "goat-island-illumination", "anchor"]], lodging: { preferred_area: "Same Elmwood Village hotel", fallback_area: "Same downtown hotel", room_setup: "Keep both rooms for a second night", notes: "Carry dry socks, a waterproof phone pouch and a warm layer; return to Buffalo rather than changing hotels." }, fallback: "Promote Old Fort Niagara if marine operations, wind, cold, queues or group preference makes both wet attractions poor value." },
  { day: 9, date: "2026-10-12", sleep_city: "Syracuse, NY", theme: "Wright's opus, an abrupt presidency and an intentionally easy city night", schedule: [["09:30", "10:45", "martin-house", "anchor"], ["11:30", "12:30", "tr-inaugural-site", "anchor"], ["16:15", "19:15", "armory-square", "supporting"]], lodging: { preferred_area: "Armory Square with staffed or attached parking", fallback_area: "University Hill near major hotels with secure parking", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Monday dinner options must be confirmed; do not frame this as one of the four big nights." }, fallback: "Promote Forest Lawn if the Martin House tour sells out; leave Buffalo by 12:45 because the Syracuse transfer is traffic-gated." },
  { day: 10, date: "2026-10-13", sleep_city: "Albany, NY", theme: "Canal machinery, glacial sand dunes and a clash of capitol architecture", schedule: [["10:00", "10:50", "erie-canal-museum", "anchor"], ["13:45", "14:55", "albany-pine-bush", "anchor"], ["15:15", "16:30", "ny-state-capitol-plaza", "anchor"]], lodging: { preferred_area: "East Greenbush/Rensselaer near US-4 and I-90", fallback_area: "Downtown Albany only if final-day live routing remains below cap", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "This practical east-side lodging placement is what keeps both final road days legal." }, fallback: "The OSRM baseline is exactly 210 minutes. Leave Syracuse on time, replace Pine Bush with Stockade only if live ETA passes, and drop the Capitol walk before exceeding the cap." },
  { day: 11, date: "2026-10-14", sleep_city: "Boston, MA", theme: "Quarry sculpture, one last slow breath and a protected airport return", schedule: [["10:00", "11:30", "turnpark-art-space", "anchor"]], lodging: { preferred_area: "Logan Airport hotel with confirmed shuttle", fallback_area: "Revere or East Boston with a verified early airport transfer", room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Airport convenience and clean two-room inventory take priority over Boston sightseeing." }, fallback: "This is live-traffic-gated. Promote Six Depot or skip the West Stockbridge stop entirely if the live estimate would exceed 210 minutes; the airport deadline wins." }
];

function personFit(record, person) {
  if (record.best_for.includes(person)) return 5;
  if (record.secondary_for.includes(person)) return 4;
  return person === "sheluvspaco" ? 3.8 : 3.4;
}

function scheduleItem(tuple, placeById) {
  const [start, end, placeId, priority] = tuple;
  const record = placeById.get(placeId);
  if (!record) throw new Error(`Unknown place ${placeId}`);
  return { start, end, place_id: placeId, priority, reservation: record.reservation };
}

async function main() {
  await buildEnergyRoute02({ root: ROOT, routeDir: ROUTE_DIR });
  return;

  // Legacy Route 02 builder retained below as historical implementation context.
  const [research, weather, geometry, replacements] = await Promise.all([
    readFile(path.join(ROUTE_DIR, "research-raw.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "weather-normals.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "route-geometry.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "replacement-geometry.json"), "utf8").then(JSON.parse)
  ]);
  const replacementGeometryById = new Map(replacements.variants.map((variant) => [variant.id, variant]));
  const images = [];
  const productionPlaces = seedPlaces.map((record) => {
    const raw = research.places[record.id];
    const coordinates = manualCoordinates[record.id] || (raw?.selected_coordinate ? [raw.selected_coordinate.longitude, raw.selected_coordinate.latitude] : null);
    if (!coordinates) throw new Error(`Missing coordinates for ${record.id}`);
    const imageIds = (raw?.selected_images || []).slice(0, 8).map((image, index) => {
      const id = `img-${record.id}-${index + 1}`;
      images.push({
        id,
        place_id: record.id,
        title: image.title,
        description: image.description,
        search_query: image.search_query,
        local_path: image.local_path,
        source_page: image.source_page,
        source_file_url: image.original_url,
        creator: image.creator,
        credit: image.credit,
        license: image.license,
        license_url: image.license_url,
        alt: image.description || `${record.name} photograph`,
        coverage: contextualImagePlaces.has(record.id) ? "place-or-local-context" : "exact-place-or-experience",
        production_usable: image.production_usable ?? image.license !== "Unknown",
        rights_status: image.rights_status || "commons-license-recorded",
        visual_review: image.review_status === "reviewed" ? "reviewed" : "pending-final-review"
      });
      return id;
    });
    const routeVariant = record.replacement ? replacementGeometryById.get(record.replacement.route_variant_id) : null;
    return {
      ...record,
      country: "US",
      coordinates,
      coordinate_order: "longitude_latitude",
      coordinate_source: manualCoordinates[record.id] ? "manual_verified_address" : "openstreetmap_nominatim",
      image_ids: imageIds,
      ratings: { traveler_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), average: null, rating_count: 0 },
      researcher_person_fit: Object.fromEntries(PEOPLE.map((person) => [person, personFit(record, person)])),
      included_in_magic_score: record.priority !== "replacement",
      replacement: record.replacement ? { ...record.replacement, route_variant: routeVariant } : undefined,
      data_status: imageIds.length >= 3 ? "complete" : "image-gap"
    };
  });
  const placeById = new Map(productionPlaces.map((record) => [record.id, record]));
  const weatherByDay = new Map(weather.days.map((day) => [day.day, day]));
  const geometryByDay = new Map(geometry.days.map((day) => [day.day, day]));
  const comfort = [4.1, 3.9, 3.5, 3.7, 3.7, 3.7, 3.4, 3.4, 3.5, 3.5, 3.7];
  const days = dayPlans.map((plan) => {
    const routed = geometryByDay.get(plan.day);
    const normal = weatherByDay.get(plan.day);
    const capStatus = routed.baseline_total_minutes >= 205 || routed.planning_total_minutes.high > 210 ? "live-traffic-gated" : routed.baseline_total_minutes >= 185 ? "near-cap" : "comfortable";
    return {
      ...plan,
      day_of_week: new Intl.DateTimeFormat("en-US", { weekday: "long", timeZone: "America/New_York" }).format(new Date(`${plan.date}T12:00:00-04:00`)),
      drive: { legs: routed.legs, baseline_total_miles: routed.baseline_total_miles, baseline_total_minutes: routed.baseline_total_minutes, planning_total_minutes: routed.planning_total_minutes, traffic_risk: routed.risk, cap_minutes: 210, cap_status: capStatus, fallback: plan.fallback },
      schedule: plan.schedule.map((item) => scheduleItem(item, placeById)),
      weather: { kind: "historical_normal", high_c: normal.normal_high_c, low_c: normal.normal_low_c, precipitation_probability_percent: normal.measurable_precipitation_probability_percent, comfort_score: comfort[plan.day - 1], station_id: normal.station_id, station_name: normal.station_name, station_role: normal.station_role, source_id: "src-noaa-normals", forecast_status: "replace_with_live_forecast_10_days_before" }
    };
  });
  const knownCore = productionPlaces.filter((record) => record.included_in_magic_score && !["cocktail-bar", "brewery-taproom", "social-games-night", "live-music-bar-circuit", "historic-dining-district"].includes(record.kind)).reduce((sum, record) => sum + (record.cost.amount_per_person || 0), 0);
  const route = {
    schema_version: "1.0.0",
    route: { id: ROUTE_ID, slug: "falls-fire-clockwork-loop", name: ROUTE_NAME, short_name: "Falls & Clockwork", status: "researched", map_color: "#6C5CE7", timezone: "America/New_York", start_date: "2026-10-04", end_date: "2026-10-14", airport_date: "2026-10-15", origin: { name: "Boston Logan Rental Car Center", coordinates: lodgingNodes["boston-logan-rental"].coordinates }, destination: { name: "Boston Logan hotel zone", coordinates: lodgingNodes["boston-logan-hotel"].coordinates }, endpoint_city: "Niagara Falls, NY", direction: "west through the Berkshires, Mohawk Valley and Finger Lakes; Niagara apex; east through the Erie Canal corridor", countries: ["US"], canada_included: false, total_nights: 11, road_nights: 10, final_boston_nights: 1, baseline_total_miles: geometry.route_baseline_total_miles, summary: "A foliage-season US-only loop built around private environmental art, caves, Haudenosaunee culture, glassmaking, Rochester's cult art-and-music spaces, Letchworth, Orthodox Sunday, Niagara, Buffalo architecture and the Erie Canal, with one measured anchor replacement for every day." },
    constraints: { travelers: 4, cars: 2, cars_follow_same_route: true, daily_drive_target_minutes: [120, 180], daily_drive_hard_cap_minutes: 210, max_big_nights_out: 4, planned_big_nights_out: 2, max_athletic_adrenaline_spots: 2, planned_athletic_adrenaline_spots: 2, hike_soft_cap_miles: 6, lodging_rooms: [{ count: 1, beds: 1 }, { count: 1, beds: 2 }], lodging_priorities: ["safe", "clean", "comfortable", "two-room inventory", "secure parking"], visa_policy: "US-only route; Niagara is visited entirely from New York with no Canada border crossing or J-1 re-entry dependency.", budget_target_per_person_usd: 1500, budget_excludes: ["lodging", "rental cars", "fuel", "nightlife", "personal shopping"] },
    scoring: { scale: { min: 1, max: 5, increment: 0.5 }, equal_traveler_weight: true, traveler_ids: PEOPLE, route_component_weights_percent: { attraction_and_stop_ratings: 45, excitement_and_uniqueness: 20, driving_comfort: 15, traveler_fairness: 10, cost_and_value: 5, expected_weather: 5 }, route_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), driving_comfort_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), overall_excitement_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), cost_value_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), weather_ratings: Object.fromEntries(PEOPLE.map((person) => [person, null])), magic_score: null, magic_score_status: "awaiting_traveler_ratings", person_specific_route_scores: Object.fromEntries(PEOPLE.map((person) => [person, null])) },
    days,
    place_ids: productionPlaces.map((record) => record.id),
    core_place_ids: productionPlaces.filter((record) => record.included_in_magic_score).map((record) => record.id),
    alternative_place_ids: productionPlaces.filter((record) => !record.included_in_magic_score).map((record) => record.id),
    replacement_place_ids: productionPlaces.filter((record) => record.priority === "replacement").map((record) => record.id),
    replacement_options: replacements.variants.map((variant) => ({ id: variant.id, day: variant.day, replacement_place_id: variant.replacement_place_id, replaces_place_ids: variant.replaces_place_ids, baseline_total_miles: variant.baseline_total_miles, baseline_total_minutes: variant.baseline_total_minutes, delta_miles: variant.delta_miles, delta_minutes: variant.delta_minutes, cap_minutes: variant.cap_minutes, cap_status: variant.cap_status })),
    budget: { known_core_admission_floor_per_person_usd: Math.round(knownCore * 100) / 100, core_admissions_planning_range_per_person_usd: [300, 440], food_and_cafes_range_per_person_usd: [600, 900], local_parking_tolls_range_per_person_usd: [120, 220], controllable_total_range_per_person_usd: [1020, 1450], nightlife_range_per_person_usd: [180, 300], nightlife_excluded_from_target: true, note: "The $1,500 target remains realistic before lodging, cars, fuel and nightlife. Make Your Own Glass is the largest variable admission choice." },
    booking_priorities: [
      { place_id: "howe-caverns", urgency: "early", reason: "Traditional Tour requires online timed tickets." },
      { place_id: "make-your-own-glass", urgency: "early", reason: "Seasonal projects sell out and determine the Corning schedule." },
      { place_id: "martin-house", urgency: "early", reason: "Interior tours have limited capacity." },
      { place_id: "radio-social", urgency: "normal", reason: "Reserve one lane for the exact 19:00 block." },
      { place_id: "maid-of-the-mist", urgency: "normal", reason: "Online ticket saves the purchase step but does not skip the boarding queue." },
      { place_id: "elmwood-essex-music-night", urgency: "when-calendar-opens", reason: "Select the actual live set 4-6 weeks out." }
    ],
    validation: { date_count: days.length, expected_date_count: 11, all_baseline_drive_days_at_or_below_cap: days.every((day) => day.drive.baseline_total_minutes <= 210), live_traffic_gated_days: days.filter((day) => day.drive.cap_status === "live-traffic-gated").map((day) => day.day), place_count: productionPlaces.length, image_count: images.length, places_with_fewer_than_3_usable_images: productionPlaces.filter((record) => record.image_ids.length < 3).map((record) => record.id), replacement_option_count: replacements.variants.length, all_replacement_variants_at_or_below_cap: replacements.variants.every((variant) => variant.baseline_total_minutes <= variant.cap_minutes), unfilled_place_ratings: productionPlaces.length * PEOPLE.length, hard_closures_or_conflicts: ["Yaddo Gardens is closed until further notice after storm damage and is excluded.", "Silo City has no public tour on October 10, 2026 and is excluded.", "Letchworth Trail 7 from Middle Falls to the Genesee Arch Bridge is permanently closed; drive between viewpoints.", "Clark Art Institute galleries are closed Monday; its replacement card is outdoor campus/trails only.", "The New York State Capitol 14:00 guided tour is incompatible with the Pine Bush timing; the core card promises only the public plaza/exterior.", "Day 10 routes at the 210-minute no-traffic cap and Day 11 at 207; both require live traffic gates and optional-stop deletion rules."], route_lock_status: "research-complete-bookings-pending" }
  };

  const geojson = { type: "FeatureCollection", name: ROUTE_SLUG, features: [
    ...days.flatMap((day) => day.drive.legs.map((leg) => ({ type: "Feature", id: leg.id, properties: { feature_kind: "drive_leg", route_id: ROUTE_ID, day: day.day, date: day.date, from: leg.from, to: leg.to, distance_miles: leg.distance_miles, baseline_minutes: leg.baseline_minutes, traffic_risk: leg.traffic_risk, map_color: route.route.map_color }, geometry: leg.geometry }))),
    ...replacements.variants.filter((variant) => variant.geometry).map((variant) => ({ type: "Feature", id: variant.id, properties: { feature_kind: "replacement_drive_variant", route_id: ROUTE_ID, day: variant.day, replacement_place_id: variant.replacement_place_id, replaces_place_ids: variant.replaces_place_ids, baseline_total_miles: variant.baseline_total_miles, baseline_total_minutes: variant.baseline_total_minutes, delta_minutes: variant.delta_minutes, cap_status: variant.cap_status, map_color: route.route.map_color }, geometry: variant.geometry })),
    ...productionPlaces.map((record) => ({ type: "Feature", id: record.id, properties: { feature_kind: "place", route_id: ROUTE_ID, place_id: record.id, name: record.name, city: record.city, state: record.state, visit_date: record.visit_date, priority: record.priority, included_in_magic_score: record.included_in_magic_score }, geometry: { type: "Point", coordinates: record.coordinates } })),
    ...Object.entries(geometry.nodes).map(([id, node]) => ({ type: "Feature", id: `node-${id}`, properties: { feature_kind: "route_node", route_id: ROUTE_ID, node_id: id, name: node.name }, geometry: { type: "Point", coordinates: node.coordinates } }))
  ] };

  await Promise.all([
    writeFile(path.join(ROUTE_DIR, "place-seed.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, places: seedPlaces }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "sources.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, verified_at: verifiedAt, sources }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "places.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, places: productionPlaces }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "images.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, image_policy: "Downloaded Wikimedia Commons derivatives with per-file attribution; contextual coverage is explicitly labeled.", images }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "route.json"), `${JSON.stringify(route, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "route.geojson"), `${JSON.stringify(geojson, null, 2)}\n`)
  ]);
  console.log(`Built ${ROUTE_NAME}: ${productionPlaces.length} places, ${images.length} images, ${days.length} days.`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
