export const verifiedAt = "2026-08-24";

export const sourceRows = [
  ["src-nemm", "New England Motorcycle Museum", "official", "https://www.newenglandmotorcyclemuseum.org/", ["Sunday hours", "mill reuse", "collection scale", "address"]],
  ["src-nemm-price", "CTvisit - New England Motorcycle Museum", "government-tourism", "https://ctvisit.com/listings/new-england-motorcycle-museum", ["adult admission"]],
  ["src-hillstead", "Hill-Stead Museum - visit", "official", "https://hillstead.org/visit/", ["Sunday hours", "guided access", "admission", "grounds"]],
  ["src-hillstead-about", "Hill-Stead Museum - about", "official", "https://hillstead.org/about/", ["Theodate Pope Riddle", "architecture", "collection"]],
  ["src-baps", "BAPS Swaminarayan Akshardham - visit", "official-faith-site", "https://usa.akshardham.org/visit", ["Monday hours", "free entry", "tour availability", "dress and visitor rules"]],
  ["src-sayen", "Hamilton Township - Sayen House and Gardens", "government", "https://www.hamiltonnj.com/sayengardens", ["daily access", "free admission", "garden features"]],
  ["src-hagley-hours", "Hagley - hours and tickets", "official", "https://www.hagley.org/hours-tickets", ["Tuesday hours", "Wednesday closure", "admission"]],
  ["src-hagley-visit", "Hagley - visitor information", "official", "https://www.hagley.org/visitor-information", ["powder works", "water power", "demonstrations", "235 acres"]],
  ["src-winterthur-hours", "Winterthur - hours", "official", "https://www.winterthur.org/view-hours/", ["Tuesday hours", "house and garden access"]],
  ["src-winterthur-price", "Winterthur - admission packages", "official", "https://www.winterthur.org/visit/admission-packages/", ["adult admission", "two-day validity", "included experiences"]],
  ["src-marine-hours", "National Museum of the Marine Corps - hours", "official-government", "https://www.usmcmuseum.com/hours.html", ["daily hours", "free admission"]],
  ["src-marine-plan", "National Museum of the Marine Corps - plan your visit", "official-government", "https://www.usmcmuseum.com/plan-your-visit.html", ["recommended duration", "visitor logistics", "exhibits"]],
  ["src-government-island", "Virginia 250 - Government Island", "government", "https://www.va250.org/placestovisit-detail/?id=57", ["October hours", "free admission", "trail length", "White House and Capitol stone"]],
  ["src-government-dhr", "Virginia DHR - Public Quarry at Government Island", "government", "https://www.dhr.virginia.gov/historic-registers/089-0103/", ["quarry history", "Aquia sandstone", "national significance"]],
  ["src-agecroft", "Agecroft Hall - visit", "official", "https://www.agecrofthall.org/visit", ["Thursday hours", "admission", "house and garden access"]],
  ["src-lewis-ginter", "Lewis Ginter Botanical Garden - hours and admissions", "official", "https://www.lewisginter.org/visit/hours-admissions/", ["daily hours", "adult admission", "conservatory and gardens"]],
  ["src-taubman", "Taubman Museum of Art - visit", "official", "https://www.taubmanmuseum.org/visit/", ["Friday hours", "free general admission", "architecture"]],
  ["src-link-visit", "Historical Society of Western Virginia - visit", "official", "https://roanokehistory.org/visit/", ["Friday hours", "admission", "current location"]],
  ["src-link-collection", "O. Winston Link Museum", "official", "https://roanokehistory.org/o-winston-link-museum/", ["night photography", "steam-era sound recordings", "collection scope"]],
  ["src-star", "City of Roanoke - Mill Mountain Park", "government", "https://www.playroanoke.com/parks-facilities/mill-mountain-park/", ["star dimensions", "overlooks", "drive-up access"]],
  ["src-vmt", "Virginia Museum of Transportation", "official", "https://vmt.org/", ["Saturday hours", "rail yard", "locomotive and transport collections"]],
  ["src-pinball", "Roanoke Pinball Museum", "official", "https://roanokepinball.org/", ["Saturday hours", "free-play admission model", "address"]],
  ["src-pinball-about", "Roanoke Pinball Museum - about", "official", "https://roanokepinball.org/about-us-1", ["approximately 75 playable machines", "1932-present range", "physics-art-history mission"]],
  ["src-myrrh", "Holy Myrrhbearers Orthodox Christian Church", "official-parish", "https://holymyrrh.org/", ["Sunday Hours and Liturgy", "ROCOR affiliation", "visitor welcome"]],
  ["src-myrrh-directory", "ROCOR clergy and parish directory - Holy Myrrhbearers", "official-church", "https://directory.synod.com/listing/550/holy-myrrhbearers-orthodox-christian-church/", ["canonical jurisdiction", "current physical address", "service time"]],
  ["src-harrisonburg-art", "Visit Harrisonburg - downtown public art tour", "official-tourism", "https://visitharrisonburgva.com/tours/downtown-public-art-tour/", ["murals", "sculptures", "Arts and Cultural District"]],
  ["src-carrier", "James Madison University - Edith J. Carrier Arboretum", "official-university", "https://www.jmu.edu/arboretum/index.shtml", ["daily dawn-to-dusk access", "free admission", "110-acre expansion"]],
  ["src-aaca", "America's Transportation Experience - visit", "official", "https://atexpa.org/visit/", ["holiday Monday hours", "admission", "parking", "accessibility"]],
  ["src-civilwar", "National Civil War Museum - visit", "official", "https://www.nationalcivilwarmuseum.org/visit/", ["holiday hours", "admission", "artifact count", "content advisory"]],
  ["src-skylands", "New Jersey Botanical Garden - hours and admission", "official", "https://www.njbg.org/hours-admission/", ["Tuesday hours", "free admission", "historic registration", "coordinates"]],
  ["src-skylands-state", "New Jersey DEP - Skylands Manor", "government", "https://dep.nj.gov/parksandforests/state-park/skylands-manor/", ["Tudor architecture", "grounds access", "manor tour limitations"]],
  ["src-pyramid", "Morris County Parks - Pyramid Mountain", "government", "https://www.morrisparks.net/parks_trails/pyramid-mountain-natural-historic-area/", ["glacial erratics", "trail rules", "Tripod Rock"]],
  ["src-pyramid-map", "Morris County Parks - Tripod Rock suggested hike", "government", "https://www.morrisparks.net/wp-content/uploads/2023/04/Pyramid-Mountain-Suggested-Hike-Tripod-Rock-Trail-Map.pdf", ["official route map", "trail safety"]],
  ["src-athenaeum", "Boston Athenaeum - visit", "official", "https://bostonathenaeum.org/visit/", ["Wednesday hours", "one-day membership", "first-floor admission", "tour booking"]],
  ["src-waterworks", "Metropolitan Waterworks Museum - visit", "official", "https://waterworksmuseum.org/visit/", ["Wednesday hours", "free admission", "transport access", "special-access limits"]],
  ["src-waterworks-engines", "Metropolitan Waterworks Museum", "official", "https://waterworksmuseum.org/", ["three historic steam pumps", "engineering and public-health interpretation"]],
  ["src-noaa-normals", "NOAA U.S. Climate Normals", "government", "https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals", ["1991-2020 normals methodology"]],
  ["src-osrm", "Open Source Routing Machine", "routing", "https://project-osrm.org/", ["road-network baselines", "no live traffic"]],
  ["src-forum-roanoke", "r/roanoke local discussions", "forum", "https://www.reddit.com/r/roanoke/", ["Taubman, Pinball and Star combination", "local pacing cross-check"]],
  ["src-forum-nj", "r/newjersey local discussions", "forum", "https://www.reddit.com/r/newjersey/", ["Skylands fall atmosphere", "weekday crowd cross-check"]]
];

const H = (opens, closes, note, status = "verified-current") => ({ opens, closes, status, note });
const C = (amount, note = "Adult planning price; reconfirm before travel.", status = "verified-current") => ({ amount_per_person: amount, status, note });
const R = (day, replaces, variant, reason) => ({ day, replaces_place_ids: replaces, route_variant_id: variant, reason });
const S = (id, name, kind, city, state, date, summary, why_go, best_for, secondary_for, categories, duration_minutes, source_ids, hours, cost, priority = "anchor", reservation = "none", replacement = null) => ({
  id, name, kind, city, state, visit_date: date, summary, why_go, best_for, secondary_for,
  best_fit_note: `Best for ${best_for.join(" and ")}: ${why_go}`,
  categories, duration_minutes, source_ids, reservation, hours, cost, priority,
  ...(replacement ? { replacement_reason: replacement.reason, replacement } : {}), address: name
});

export const seedPlaces = [
  S("new-england-motorcycle", "New England Motorcycle Museum in the Hockanum Mill", "motorcycles-inside-a-revived-textile-mill", "Rockville", "CT", "2026-10-04", "A 205-year-old textile mill has been rescued as a dense working collection of vintage and custom motorcycles, memorabilia and more than twenty-five marques—the building's journey from looms to engines is half the story.", "Gora gets machines, strength culture and restoration truth; Viki gets a dramatic industrial shell; Paco gets an energetic first shared obsession that is still short enough for ferry-day reality.", ["gora", "sheluvspaco"], ["viki", "stivka"], ["unusual_creative", "hidden_history_folklore", "architecture_nature_photogenic"], 60, ["src-nemm", "src-nemm-price"], H("10:00", "15:00", "Sunday hours are short. Leave Logan by about 12:10 and treat 14:00 as the latest responsible arrival; holiday hours must still be checked."), C(10), "anchor", "same-day-hours-check"),
  S("hill-stead", "Hill-Stead Museum, Sunken Garden & Theodate Pope Riddle House", "woman-designed-country-house-and-art", "Farmington", "CT", "2026-10-04", "One of America's first licensed women architects designed this restrained country house around her family's Impressionist art; the guided rooms, sunken garden and hillside feel intimate rather than showy.", "Viki gets architecture and garden photographs, Stivka gets a quiet first afternoon, and the house's female design history gives the replacement more substance than another mansion checklist.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 90, ["src-hillstead", "src-hillstead-about"], H("10:00", "16:00", "House is guided only; last tour starts 15:00. Reserve a 14:00 or 14:30 tour and use the free grounds only if Boston pickup runs late."), C(20), "replacement", "reserve", R(1, ["new-england-motorcycle"], "replacement-d1-hill-stead", "A calmer art-and-architecture start when the group prefers gardens to motorcycles or NEMM's short Sunday window fails.")),
  S("baps-akshardham", "BAPS Swaminarayan Akshardham", "monumental-living-hindu-sacred-complex", "Robbinsville", "NJ", "2026-10-05", "An intricately carved living Hindu sacred complex turns stone, devotion and volunteer craft into one of the most visually overwhelming buildings on the route; the visit is spiritual space first and sightseeing second.", "Stivka gets respectful interfaith understanding, Viki gets extraordinary non-mainstream architecture, Gora gets material craft, and everyone practices entering another community as guests rather than content collectors.", ["stivka", "viki"], ["gora", "sheluvspaco"], ["orthodox_spiritual", "architecture_nature_photogenic", "local_culture", "unusual_creative"], 150, ["src-baps"], H("09:00", "19:30", "Open Monday. Guided tours for fewer than fifteen run hourly 10:00-17:00 subject to availability. Cover shoulders and knees, remove shoes, silence phones, and do not plan commercial photography or outside food."), C(0), "anchor", "tour-reservation-recommended"),
  S("sayen-gardens", "Sayen House & Gardens", "free-woodland-garden-and-historic-house-setting", "Hamilton", "NJ", "2026-10-05", "Wooded paths, streams, ponds, bridges and the 1912 Sayen house form a free garden sanctuary built from a world-traveling nurseryman's plant collection.", "It is the gentle weather-and-energy alternative for Viki and Stivka: photogenic, free and local, with no sacred-site etiquette burden when the group is not ready for a long formal visit.", ["viki", "stivka"], ["sheluvspaco", "gora"], ["architecture_nature_photogenic", "quiet_reset", "local_culture"], 90, ["src-sayen"], H("dawn", "dusk", "Gardens are free and open daily. The house may be closed for private events; the public experience is the garden, not promised interior access."), C(0), "replacement", "weather-check", R(2, ["baps-akshardham"], "replacement-d2-sayen", "A low-pressure garden replacement if sacred-site timing, dress, crowding or group energy makes Akshardham a poor fit that morning.")),
  S("hagley", "Hagley Powder Yards, Waterpower & Eleutherian Mills", "working-industrial-landscape", "Wilmington", "DE", "2026-10-06", "The first DuPont black-powder works stretches through 235 wooded acres along the Brandywine, where stone ruins, turbines, an eight-ton roll mill, machine shop, workers' community and family home expose the machinery and risk behind an industrial dynasty.", "This is for Gora's search for how power and wealth actually worked, but Viki gets river architecture and Stivka gets landscape; the point is to see labor, danger, invention and privilege together.", ["gora"], ["viki", "stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic", "unusual_creative"], 165, ["src-hagley-hours", "src-hagley-visit"], H("10:00", "17:00", "Open Tuesday and closed Wednesday. Arrive before 11:00, prioritize the powder yard and one live demonstration, and leave by 13:30 for Baltimore."), C(22), "anchor", "none"),
  S("winterthur", "Winterthur House, Galleries & Garden Tram", "american-decorative-arts-estate", "Winterthur", "DE", "2026-10-06", "Henry Francis du Pont turned a vast country estate into a layered museum of American rooms, decorative arts, meadow, woodland and designed garden; a tram makes the scale manageable.", "Viki gets the richer interiors and designed landscape, Gora gets objects as evidence of taste and power, and the group gets a polished counterpoint to Hagley's industrial grit.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 165, ["src-winterthur-hours", "src-winterthur-price"], H("10:00", "17:00", "Open Tuesday. Choose one house experience plus the tram and one garden sector; the general ticket is valid two days, but this route uses only Tuesday."), C(29), "replacement", "reserve-recommended", R(3, ["hagley"], "replacement-d3-winterthur", "A more comfortable interior-and-garden replacement when machinery demonstrations, walking or industrial history feel too heavy.")),
  S("marine-corps-museum", "National Museum of the Marine Corps", "immersive-military-history-museum", "Triangle", "VA", "2026-10-07", "Immersive galleries move from the Corps' founding through major conflicts using aircraft, vehicles, artifacts and reconstructed environments beneath a building shaped around the Iwo Jima flag-raising image.", "Gora gets consequential history and hardware, Viki gets one of the route's strongest modern buildings, and the group must actively separate institutional memory from the only possible interpretation of war.", ["gora"], ["viki", "stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic", "unusual_creative"], 210, ["src-marine-hours", "src-marine-plan"], H("09:00", "17:00", "Open daily and free. Allow 3-3.5 hours, choose conflicts rather than attempting every label, and read the museum as a Marine Corps institution with a defined point of view."), C(0), "anchor", "none"),
  S("government-island", "Government Island Aquia Sandstone Quarry & Boardwalk", "birthstone-of-washington-architecture", "Stafford", "VA", "2026-10-07", "A 1.5-mile boardwalk and forest loop reaches quarry scars where workers cut Aquia sandstone for the White House and early Capitol, tying a quiet wetland directly to the physical construction of national power.", "Gora gets labor and material history, Viki gets reflections and carved rock, and Stivka gets a calm outdoor day instead of another institutionally framed war museum.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic", "quiet_reset"], 105, ["src-government-island", "src-government-dhr"], H("08:00", "20:00", "October daily hours. Trail is 1.5 miles with a paved approach, boardwalk and then dirt; skip the dirt loop if wet while keeping the quarry interpretation."), C(0), "replacement", "weather-check", R(4, ["marine-corps-museum"], "replacement-d4-government-island", "A quieter, more critical material-history replacement if museum fatigue or the military framing does not suit the group.")),
  S("agecroft-hall", "Agecroft Hall & James River Garden", "sixteenth-century-english-house-reassembled-in-virginia", "Richmond", "VA", "2026-10-08", "A genuine Tudor manor was dismantled in Lancashire, shipped across the Atlantic and reassembled above the James River, creating a beautiful but complicated fantasy of old England in 1920s Richmond.", "Viki gets the architectural shock, Gora gets questions of wealth and authenticity, Stivka gets garden quiet, and the whole group gets a house whose relocation is stranger than its rooms.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "unusual_creative"], 135, ["src-agecroft"], H("12:00", "17:00", "Open Thursday. Reserve the first house tour and walk only the compact formal gardens before the near-cap drive to Danville."), C(12), "anchor", "reserve-recommended"),
  S("lewis-ginter", "Lewis Ginter Conservatory & Botanical Garden", "glasshouse-and-designed-garden", "Richmond", "VA", "2026-10-08", "A domed conservatory, water garden and linked themed landscapes create a highly designed nature stop that stays rewarding in imperfect weather and was substantially expanded for 2026.", "Viki gets glasshouse geometry and color, Stivka gets a restorative garden, and Paco gets a low-conflict alternative whose paths can be shortened without ruining it.", ["viki", "stivka"], ["sheluvspaco", "gora"], ["architecture_nature_photogenic", "quiet_reset", "unusual_creative"], 135, ["src-lewis-ginter"], H("09:00", "17:00", "Open daily. Enter at opening, prioritize the conservatory and one outdoor circuit, and depart on time because the replacement baseline is 209 minutes."), C(24), "replacement", "reserve-recommended", R(5, ["agecroft-hall"], "replacement-d5-lewis-ginter", "A more accessible and weather-resilient architecture-plus-nature replacement when a guided historic house feels too formal.")),
  S("taubman-art", "Taubman Museum of Art", "sculptural-building-and-free-american-art", "Roanoke", "VA", "2026-10-09", "Randall Stout's angular zinc, glass and steel building folds Blue Ridge forms into downtown while free galleries move through American, regional and contemporary art.", "Viki gets both a photographable building and art, Gora gets changing American self-images, and free entry lets Paco leave after the strongest rooms without sunk-cost pressure.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["architecture_nature_photogenic", "unusual_creative", "quiet_reset"], 135, ["src-taubman"], H("10:00", "17:00", "Open Friday with free general admission. Check the 2026 exhibition calendar and pair permanent highlights with only one temporary show."), C(0), "anchor", "none"),
  S("winston-link", "O. Winston Link Night-Trains & Roanoke History Museum", "staged-night-photography-and-railroad-memory", "Roanoke", "VA", "2026-10-09", "Meticulously staged 1950s night photographs and field recordings catch steam locomotives tearing through cinemas, porches and swimming holes, inside a Raymond Loewy-redesigned passenger station.", "Viki gets technically astonishing images, Gora gets the last years of steam as community evidence, and the group gets a compact museum with a stronger sense of place than a generic gallery.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "local_culture"], 105, ["src-link-visit", "src-link-collection"], H("10:00", "16:30", "Open Friday. Call before travel to confirm how much of the Link collection is installed after recent gallery changes; the adjoining history galleries share admission."), C(6), "replacement", "call-week-before", R(6, ["taubman-art"], "replacement-d6-winston-link", "A more region-specific photography-and-industrial-memory replacement if Taubman's 2026 exhibitions are weak.")),
  S("roanoke-star", "Mill Mountain Roanoke Star & Blue Ridge Overlook", "drive-up-neon-mountain-overlook", "Roanoke", "VA", "2026-10-09", "An 88.5-foot steel star with 2,000 feet of neon crowns a drive-up overlook above the valley, turning a 1949 shopping-season stunt into the enduring identity of the Star City.", "Viki gets the sunset city-and-mountain photograph, Paco gets a simple shared reveal, and nobody needs a long hike after the road.", ["viki", "sheluvspaco"], ["stivka", "gora"], ["architecture_nature_photogenic", "local_culture", "quiet_reset"], 60, ["src-star"], H("dawn", "23:00", "Use the paved overlook near sunset; do not add a long trail. Fog or rain turns this into an automatic cut, not a reason to wait in the car."), C(0), "supporting", "weather-check"),
  S("virginia-transportation", "Virginia Museum of Transportation & Outdoor Railyard", "giant-machines-in-a-century-old-freight-station", "Roanoke", "VA", "2026-10-10", "Virginia's official transportation museum puts steam, diesel and electric locomotives—including the immense Norfolk & Western 611 and 1218—beside cars, aviation and a climb-aboard outdoor railyard.", "This is Gora's route-defining machinery stop, but the physical scale should impress everyone; it also explains why Roanoke became a city rather than treating trains as decoration.", ["gora"], ["viki", "sheluvspaco", "stivka"], ["unusual_creative", "hidden_history_folklore", "architecture_nature_photogenic"], 165, ["src-vmt"], H("10:00", "17:00", "Open Saturday. Start at opening, use the railyard before crowds and weather, and leave by 13:00 for Mount Crawford."), C(15, "Planning allowance; current checkout pricing should be reconfirmed.", "price-reconfirm"), "anchor", "none"),
  S("roanoke-pinball", "Roanoke Pinball Museum", "playable-century-of-pinball", "Roanoke", "VA", "2026-10-10", "About seventy-five playable machines from 1932 to today turn physics, graphic art, engineering and American amusement history into a social competition with every game on free play.", "Paco gets group energy, Gora gets reflex and mechanism, Viki gets pop graphics, and it is the route's only intentionally playful pseudo-athletic experience.", ["sheluvspaco", "gora"], ["viki", "stivka"], ["social_nightlife_live", "unusual_creative", "athletic_adrenaline"], 120, ["src-pinball", "src-pinball-about"], H("11:00", "20:00", "Saturday hours shown on the official site; call the box office because private events can close early. Leave by 13:00 despite all-day admission."), C(15, "Official ticket checkout is dynamic; use $15 as a planning figure and reconfirm.", "price-reconfirm"), "replacement", "same-day-hours-check", R(7, ["virginia-transportation"], "replacement-d7-pinball", "A hands-on social replacement when the group wants to play together rather than study another large machinery collection.")),
  S("holy-myrrhbearers", "Protected Orthodox Sunday at Holy Myrrhbearers", "canonical-rocor-hours-and-divine-liturgy", "Mount Crawford", "VA", "2026-10-11", "A growing canonical ROCOR parish in the Shenandoah Valley celebrates Hours and Divine Liturgy primarily in English with some Slavonic, giving the trip an actual worship commitment rather than a decorative church stop.", "This is essential for Stivka and belongs equally to all four Orthodox travelers. The small-parish scale offers human community after a week of monumental institutions.", ["stivka"], ["sheluvspaco", "viki", "gora"], ["orthodox_spiritual", "quiet_reset", "local_culture"], 165, ["src-myrrh", "src-myrrh-directory"], H("09:45", "12:30", "Weekly Hours and Liturgy begin 09:45. Contact the parish before travel about October 11, visitor etiquette and Communion; worship is never shortened for the road."), C(0, "Free; make a respectful offering if appropriate."), "anchor", "parish-confirm"),
  S("harrisonburg-public-art", "Harrisonburg Public Art & Hidden-History Circuit", "small-city-murals-sculpture-and-memory", "Harrisonburg", "VA", "2026-10-11", "A compact self-guided circuit threads murals, sculpture, LOVEworks and old downtown fabric through a designated Arts and Cultural District, with the visitor-center building adding local history context.", "Viki gets color and streetscape photographs, Gora gets a town told through public memory instead of a single authority, and it gently reactivates everyone after Liturgy.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["architecture_nature_photogenic", "local_culture", "quiet_reset"], 75, ["src-harrisonburg-art"], H("dawn", "dusk", "Outdoor works are public. The visitor center is typically open 09:00-17:00, but the route does not depend on its interior; keep the circuit under one mile."), C(0), "anchor", "weather-check"),
  S("carrier-arboretum", "Edith J. Carrier Arboretum", "free-valley-arboretum-and-pond", "Harrisonburg", "VA", "2026-10-11", "A university arboretum expanded to 110 acres in 2026 combines pond, woodland, native plantings and meadow, while the route uses only a compact dawn-to-dusk loop.", "Stivka gets post-Liturgy quiet, Viki gets autumn reflection, and Paco gets a reliable low-cost decompression before the long Carlisle leg.", ["stivka", "viki"], ["sheluvspaco", "gora"], ["architecture_nature_photogenic", "quiet_reset"], 75, ["src-carrier"], H("dawn", "dusk", "Grounds are free daily. Use the signed visitor lots and a one-mile pond-and-woodland circuit; construction or rain makes the public-art core the better choice."), C(0), "replacement", "weather-check", R(8, ["harrisonburg-public-art"], "replacement-d8-carrier", "A quieter nature replacement after the same protected worship when social or visual overload has accumulated.")),
  S("aaca-museum", "America's Transportation Experience at the AACA Museum", "cars-buses-and-industrial-design", "Hershey", "PA", "2026-10-12", "A large transportation museum goes beyond polished cars with vintage buses, changing design exhibits and an exceptional Tucker collection, making mobility, marketing and engineering visible across decades.", "Gora gets engineering and power, Viki gets design and color, and the broad mix avoids feeling like a showroom even after Roanoke's locomotives.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["unusual_creative", "hidden_history_folklore", "architecture_nature_photogenic"], 150, ["src-aaca"], H("09:00", "17:00", "Open daily and not closed for the October 12 holiday. Enter around 10:00 and choose Tucker, buses and one changing exhibit rather than every vehicle."), C(18), "anchor", "none"),
  S("civil-war-museum", "National Civil War Museum", "artifact-led-war-and-aftermath-history", "Harrisburg", "PA", "2026-10-12", "Nearly 850 artifacts across 25,000 square feet trace causes, war experience and aftermath from multiple perspectives, with the museum explicitly warning that evidence of injury and death is shown.", "Gora gets serious history and primary objects, while the group gets a counterweight to a vehicle museum; the value depends on critical reading, not accepting balance as neutrality.", ["gora"], ["stivka", "viki", "sheluvspaco"], ["hidden_history_folklore", "local_culture"], 165, ["src-civilwar"], H("10:00", "17:00", "The museum posts regular holiday hours and extended Sunday-season hours through October. Follow the content advisory and select galleries rather than forcing a four-hour completion."), C(20), "replacement", "none", R(9, ["aaca-museum"], "replacement-d9-civil-war", "A people-and-consequences history replacement when the group has had enough machines or wants a more difficult conversation.")),
  S("skylands", "Skylands Manor & New Jersey Botanical Garden", "tudor-revival-estate-and-free-autumn-garden", "Ringwood", "NJ", "2026-10-13", "A 44-room granite Tudor Revival manor anchors ninety-six acres of formal and naturalized gardens inside Ringwood State Park, creating an estate landscape that local visitors praise across seasons.", "Viki gets the strongest return-day architecture-and-foliage combination, Stivka gets quiet, and the free weekday grounds keep the final road day light on both cost and decisions.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "quiet_reset", "local_culture"], 135, ["src-skylands", "src-skylands-state", "src-forum-nj"], H("08:00", "20:00", "Open Tuesday during Eastern Daylight Time and free. Manor interiors are not promised—tours run only on select Sundays—so the experience is architecture exterior plus gardens."), C(0), "anchor", "weather-check"),
  S("pyramid-mountain", "Pyramid Mountain Tripod Rock Hike", "glacial-erratic-balancing-rock", "Montville", "NJ", "2026-10-13", "A forest trail reaches enormous glacial erratics left more than eighteen thousand years ago, climaxing at Tripod Rock—an immense boulder perched on three smaller stones like an impossible natural table.", "Gora gets geology and movement, Viki gets the route's strangest natural photograph, and it earns the trip's only real hike slot without approaching the six-mile limit.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "unusual_creative", "athletic_adrenaline"], 150, ["src-pyramid", "src-pyramid-map"], H("sunrise", "sunset", "Use the official Tripod Rock suggested route, download the map offline, stay on blazed trails and cancel for rain or poor footing. No climbing is allowed."), C(0), "replacement", "weather-check", R(10, ["skylands"], "replacement-d10-pyramid", "A more active geology replacement if the group wakes fresh and the trail is dry; it is not added after Skylands.")),
  S("boston-athenaeum", "Boston Athenaeum Full-Building Day Membership", "twelve-story-independent-library-and-art", "Boston", "MA", "2026-10-14", "A twelve-story independent library hides sunlit reading rooms, art, rare books, George Washington's library, a terrace and quiet corners behind a discreet Beacon Street facade.", "Viki gets the staircase and rooms, Gora gets primary-source history, Stivka gets stillness, and everyone reaches it only after both cars are safely returned.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 180, ["src-athenaeum"], H("09:00", "20:00", "Open Wednesday. Buy the $40 day membership for all twelve floors or deliberately choose the $11 first-floor ticket; reserve an architecture tour separately if desired."), C(40, "Full-building one-day membership; first-floor-only admission is $11."), "anchor", "reserve-recommended"),
  S("waterworks", "Metropolitan Waterworks Museum Great Engines Hall", "victorian-steam-pumps-and-public-health", "Boston", "MA", "2026-10-14", "Three coal-powered steam pumping engines rise more than three stories inside an ornate former high-service station, linking spectacular machinery to clean water, public health and urban growth.", "Gora gets monumental engineering, Viki gets a cathedral-like industrial interior, and the free two-hour scale is ideal if the Athenaeum feels expensive or too quiet.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "unusual_creative"], 120, ["src-waterworks", "src-waterworks-engines"], H("11:00", "16:00", "Open Wednesday and free. The paid climb-on Special Access Tour is not offered Wednesday, so do not promise engine climbing or basement access."), C(0), "replacement", "none", R(11, ["boston-athenaeum"], "replacement-d11-waterworks", "A free, shorter engineering-and-architecture finale after the same protected car return."))
];

export const promotedHiddenGemIds = new Set([
  "hill-stead", "sayen-gardens", "winterthur", "government-island", "lewis-ginter",
  "winston-link", "roanoke-pinball", "carrier-arboretum", "civil-war-museum",
  "pyramid-mountain", "waterworks"
]);

const simplePlaceCopy = {
  "new-england-motorcycle": {
    summary: "More than 25 motorcycle brands fill a rescued 205-year-old textile mill. The old factory now feels alive again.",
    whyGo: "Gora gets machines and restoration. Viki gets a dramatic factory building. It is a lively first stop after Boston."
  },
  "hill-stead": {
    summary: "One of America's first licensed women architects designed this quiet country house. It holds Impressionist art and a sunken garden.",
    whyGo: "Viki gets architecture and garden photos. Stivka gets a calm walk. The house has a strong story about women in design."
  },
  "baps-akshardham": {
    summary: "Thousands of carved stone details cover this large Hindu temple. It is an active place of worship, so visitors enter with care.",
    whyGo: "Stivka gets a respectful look at another faith. Viki gets remarkable architecture. Everyone sees how devotion can shape a building."
  },
  "sayen-gardens": {
    summary: "Wooded paths pass ponds, streams, bridges, and the 1912 Sayen house. The gardens are free and easy to explore.",
    whyGo: "Viki gets colorful garden photos. Stivka gets a peaceful break. It adds a soft nature stop after the large temple."
  },
  hagley: {
    summary: "Old powder mills, water wheels, and workshops line the Brandywine River. They show how the DuPont business first grew.",
    whyGo: "Gora gets working machines and industrial history. Viki gets stone buildings beside the river. The story joins invention, danger, and wealth."
  },
  winterthur: {
    summary: "Winterthur is a large country estate filled with American rooms and decorative art. A garden tram makes the grounds easier to see.",
    whyGo: "Viki gets rich interiors and gardens. Gora gets objects that show taste and power. It gives the day a beautiful contrast to Hagley."
  },
  "marine-corps-museum": {
    summary: "Aircraft, vehicles, and rebuilt scenes tell the history of the Marine Corps. The sharp glass building is also part of the experience.",
    whyGo: "Gora gets important history and military machines. Viki gets bold modern architecture. The group can compare the museum's view with other sources."
  },
  "government-island": {
    summary: "A boardwalk leads to the quarry that supplied stone for the White House and early Capitol. Tool marks remain in the rock.",
    whyGo: "Gora gets labor and building history. Viki gets water and stone photos. Stivka gets a quiet outdoor walk after the museum."
  },
  "agecroft-hall": {
    summary: "This real Tudor house was taken apart in England and rebuilt above the James River. Its move is stranger than its rooms.",
    whyGo: "Viki gets a surprising old building. Gora gets questions about money and authenticity. Stivka gets formal gardens and river views."
  },
  "lewis-ginter": {
    summary: "A glass conservatory, water garden, and themed paths make this a colorful nature stop. The visit still works when the weather changes.",
    whyGo: "Viki gets glass, plants, and color. Stivka gets a calm garden. The group can shorten the walk without losing the main experience."
  },
  "taubman-art": {
    summary: "A sharp zinc-and-glass building holds free American and modern art. Its roofline copies the shapes of the Blue Ridge Mountains.",
    whyGo: "Viki gets both art and architecture. Gora gets changing views of American life. Free entry makes a short focused visit easy."
  },
  "winston-link": {
    summary: "Carefully staged night photos show steam trains racing past cinemas, homes, and swimming pools. Train sounds bring the pictures to life.",
    whyGo: "Viki gets clever night photography. Gora gets the final years of steam power. The old passenger station makes the story feel local."
  },
  "roanoke-star": {
    summary: "A giant neon star stands above Roanoke with wide views of the city and mountains. It began as a 1949 shopping display.",
    whyGo: "Viki gets the sunset view. Paco gets a simple shared reveal. Nobody needs a long hike after the drive."
  },
  "virginia-transportation": {
    summary: "Huge steam and diesel engines fill an old freight station and outdoor rail yard. Visitors can get close to famous locomotives.",
    whyGo: "This is Gora's biggest machine stop. The scale can impress everyone. It also explains why the railway made Roanoke grow."
  },
  "roanoke-pinball": {
    summary: "About 75 pinball machines from 1932 to today are ready to play. One ticket turns the museum into a group competition.",
    whyGo: "Paco gets group energy. Gora gets moving mechanisms. Viki gets bright pop art. It adds play after the serious railway museum."
  },
  "holy-myrrhbearers": {
    summary: "This small Orthodox parish celebrates Hours and Divine Liturgy in English with some Slavonic. The stop is real worship, not sightseeing.",
    whyGo: "The service matters deeply to Stivka and belongs to all four Orthodox travelers. The small parish offers warm community during the trip."
  },
  "harrisonburg-public-art": {
    summary: "A short downtown walk joins murals, sculpture, LOVEworks, and old buildings. The art tells local stories in the open air.",
    whyGo: "Viki gets color and street photos. Gora gets history outside a formal museum. The walk gently wakes everyone after church."
  },
  "carrier-arboretum": {
    summary: "A free university garden surrounds a pond with woods, native plants, and meadow. The route uses a short and easy loop.",
    whyGo: "Stivka gets quiet after church. Viki gets autumn reflections. Paco gets a free reset before the long drive north."
  },
  "aaca-museum": {
    summary: "Classic cars, buses, and rare Tucker vehicles show how transport design changed. The museum feels broader than a car showroom.",
    whyGo: "Gora gets engineering. Viki gets shape and color. The group can focus on Tucker cars, buses, and one changing display."
  },
  "civil-war-museum": {
    summary: "Hundreds of objects explain the causes, fighting, and results of the Civil War. Some displays include difficult images of injury and death.",
    whyGo: "Gora gets serious history and original objects. The group gets a human story after many machines. Read every claim with care."
  },
  skylands: {
    summary: "A large granite Tudor-style manor stands inside 96 acres of free gardens. On Tuesday, the visit focuses on the outside and grounds.",
    whyGo: "Viki gets strong architecture and autumn color. Stivka gets quiet paths. The free grounds keep the final road days relaxed."
  },
  "pyramid-mountain": {
    summary: "A forest trail leads to giant rocks left by ancient ice. Tripod Rock balances on three smaller stones like a natural table.",
    whyGo: "Gora gets geology and movement. Viki gets one of the trip's strangest photos. It uses the route's one real hiking slot."
  },
  "boston-athenaeum": {
    summary: "This quiet private library hides art, rare books, bright reading rooms, and a terrace behind its Beacon Street door.",
    whyGo: "Viki gets beautiful rooms. Gora gets old books and history. Stivka gets calm after both rental cars are returned."
  },
  waterworks: {
    summary: "Three steam-powered pumps rise more than three stories inside a grand stone pumping station. They once helped give Boston clean water.",
    whyGo: "Gora gets giant engineering. Viki gets a cathedral-like machine hall. The free museum creates a powerful final contrast with the library."
  }
};

for (const place of seedPlaces) {
  const copy = simplePlaceCopy[place.id];
  if (!copy) throw new Error(`Missing simple Route 10 copy for ${place.id}`);
  place.summary = copy.summary;
  place.why_go = copy.whyGo;
  place.best_fit_note = `Best for ${place.best_for.join(" and ")}: ${copy.whyGo}`;
  if (promotedHiddenGemIds.has(place.id)) {
    place.priority = "supporting";
    delete place.replacement_reason;
    delete place.replacement;
  }
}

export const dayPlans = [
  { day: 1, date: "2026-10-04", sleep_city: "East Milford/Orange, CT", theme: "Motorcycles, a woman-designed house, and quiet gardens", schedule: [["14:00", "15:00", "new-england-motorcycle", "anchor"], ["15:40", "16:40", "hill-stead", "supporting"]], lodging: ["East Milford or Orange with two clean rooms and bright, secure parking", "New Haven edge only with strong recent reviews and easy Monday highway access"], fallback: "The drive uses 208 baseline minutes. The motorcycle museum closes at 15:00, so leave Logan on time. Hill-Stead is a garden and exterior visit unless an earlier house tour is booked." },
  { day: 2, date: "2026-10-05", sleep_city: "Hamilton, NJ", theme: "A living stone temple and a free garden", schedule: [["10:00", "12:30", "baps-akshardham", "anchor"], ["13:15", "14:30", "sayen-gardens", "supporting"]], lodging: ["Hamilton or Robbinsville with two clean rooms and secure two-car parking", "Princeton east only if Tuesday's live Hagley ETA stays inside the cap"], fallback: "The drive uses about 200 baseline minutes. Follow the temple's dress, shoe, phone, and food rules. Keep Sayen to one short garden loop." },
  { day: 3, date: "2026-10-06", sleep_city: "Baltimore, MD", theme: "Grand rooms, black powder, and river power", schedule: [["10:00", "11:45", "winterthur", "supporting"], ["12:10", "14:25", "hagley", "anchor"]], lodging: ["Harbor East or Canton waterfront with two clean rooms and staffed parking", "Fells Point edge only with strong current safety and garage reviews"], fallback: "The drive reaches the 210-minute cap before traffic. See one Winterthur house area and one garden view. At Hagley, choose the powder yard and one machine demonstration." },
  { day: 4, date: "2026-10-07", sleep_city: "North Richmond, VA", theme: "War machines and the stone that built Washington", schedule: [["09:00", "12:00", "marine-corps-museum", "anchor"], ["12:30", "14:00", "government-island", "supporting"]], lodging: ["North Richmond or Lakeside with two clean rooms and secure parking", "Scott's Addition only if the exact property is quieter and safer for two cars"], fallback: "The drive uses about 207 baseline minutes. Choose the most important Marine Corps galleries. At Government Island, use the boardwalk and quarry loop only if the ground is dry." },
  { day: 5, date: "2026-10-08", sleep_city: "Danville, VA", theme: "A glass garden and a Tudor house moved across the ocean", schedule: [["09:00", "11:00", "lewis-ginter", "supporting"], ["12:00", "14:00", "agecroft-hall", "anchor"]], lodging: ["Danville River District with two clean rooms and secure off-street parking", "North Danville only if cleanliness and parking are clearly stronger"], fallback: "The drive uses about 209 baseline minutes. Start Lewis Ginter at opening. Reserve Agecroft's first afternoon house tour and leave after a short garden walk." },
  { day: 6, date: "2026-10-09", sleep_city: "Roanoke, VA", theme: "Modern art, night trains, and the Roanoke Star", schedule: [["10:00", "11:45", "taubman-art", "anchor"], ["12:00", "13:20", "winston-link", "supporting"], ["17:30", "18:30", "roanoke-star", "supporting"]], lodging: ["Downtown Roanoke with two clean rooms, garage parking, and walkable dinner", "South Roanoke only if Saturday's museum departure stays unchanged"], fallback: "Only about 136 baseline minutes are planned. Call ahead to confirm the Link galleries. Cut the Star in fog or rain and enjoy an unhurried dinner." },
  { day: 7, date: "2026-10-10", sleep_city: "Mount Crawford, VA", theme: "Giant locomotives followed by hands-on pinball", schedule: [["10:00", "12:15", "virginia-transportation", "anchor"], ["12:30", "14:00", "roanoke-pinball", "supporting"]], lodging: ["Mount Crawford or Harrisonburg south with two clean rooms and quiet parking", "Harrisonburg center only if Sunday church ETA remains under ten minutes"], fallback: "The drive uses about 128 baseline minutes. Start with the outdoor rail yard, then play a focused 90-minute pinball session. Leave Roanoke by 14:00." },
  { day: 8, date: "2026-10-11", sleep_city: "Carlisle, PA", theme: "Orthodox Sunday, quiet trees, and downtown color", schedule: [["09:45", "12:30", "holy-myrrhbearers", "anchor"], ["12:45", "13:30", "carrier-arboretum", "supporting"], ["13:45", "14:30", "harrisonburg-public-art", "anchor"]], lodging: ["Historic Carlisle with two clean rooms and off-street parking", "Carlisle I-81 edge only if the exact property is quieter and safer"], fallback: "The drive reaches the 210-minute cap, but worship stays protected. Keep the arboretum and public-art stops short. Leave Harrisonburg by 14:30." },
  { day: 9, date: "2026-10-12", sleep_city: "Stroudsburg, PA", theme: "Civil War stories, rare cars, and the Poconos", schedule: [["10:00", "12:00", "civil-war-museum", "supporting"], ["12:35", "14:35", "aaca-museum", "anchor"]], lodging: ["Stroudsburg with two clean rooms and secure parking near dinner", "Bartonsville only if Tuesday's exact garden-and-hike route is rechecked"], fallback: "The drive uses about 208 baseline minutes. Read the war museum's difficult displays with care. At AACA, choose Tucker cars, buses, and one changing display." },
  { day: 10, date: "2026-10-13", sleep_city: "Danbury, CT", theme: "Tripod Rock and a granite manor in autumn gardens", schedule: [["07:30", "09:45", "pyramid-mountain", "supporting"], ["11:00", "12:30", "skylands", "anchor"]], lodging: ["West Danbury or Ridgebury with two clean rooms and secure parking", "Central Danbury only if recent safety and cleanliness evidence is stronger"], fallback: "The drive uses about 208 baseline minutes. Hike only on dry trails and use the official map. Skylands is an exterior and garden visit because Tuesday manor tours are not promised." },
  { day: 11, date: "2026-10-14", sleep_city: "Boston, MA", theme: "Return the cars, then see giant pumps and a hidden library", schedule: [["11:00", "12:30", "waterworks", "supporting"], ["13:30", "16:00", "boston-athenaeum", "anchor"]], lodging: ["Logan airport hotel with the exact one-bed plus two-bed room setup and confirmed October 15 shuttle", "East Boston or Revere only with a verified airport transfer"], fallback: "The drive uses about 203 baseline minutes. Leave Danbury around 06:15 and return both cars first. Use transit or rideshare for both Boston stops and keep the evening quiet." }
];
