export const verifiedAt = "2026-08-24";
export const sourceRows = [
  ["src-dummy", "Dummy source", "official", "https://example.com", ["dummy claim"]]
];

const H = (opens, closes, note, status = "verified-current") => ({ opens, closes, status, note });
const C = (amount, note = "Adult planning price; reconfirm before travel.", status = "verified-current") => ({ amount_per_person: amount, status, note });
const S = (id, name, kind, city, state, date, summary, why_go, best_for, secondary_for, categories, duration_minutes, source_ids, hours, cost, priority = "anchor", reservation = "none", replacement = null) => ({
  id, name, kind, city, state, visit_date: date, summary, why_go, best_for, secondary_for,
  best_fit_note: `Best for ${best_for.join(" and ")}: ${why_go}`,
  categories, duration_minutes, source_ids, reservation, hours, cost, priority,
  ...(replacement ? { replacement_reason: replacement.reason, replacement } : {}), address: name
});

export const seedPlaces = [
  S("keystone-arches", "Keystone Arch Bridges trail sampler", "stone-infrastructure-walk", "City", "ST", "2026-10-04", "Use a **short 60–70 minute sampler**, not the full multi-mile route. The arches are 19th-century stone railroad infrastructure embedded in the Berkshire woods. This is a route-break with its own identity rather than a convenience stop.", "Gora + Viki; Stivka gets quiet forest / stone scale.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 65, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("art-omi", "Art Omi Sculpture & Architecture Park", "landscape-scale-contemporary-art", "City", "ST", "2026-10-04", "The original chose the right place. Huge works distributed through a rural landscape feel more like environmental exploration than gallery viewing. **Current fall signal:** Benenson Center 09:00–17:00; Sunday park access through daylight in the current fall schedule. Vehicle registration is recommended.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 115, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("opus-40", "Opus 40", "quarry-scale-earthwork", "City", "ST", "2026-10-05", "Harvey Fite spent decades turning an abandoned bluestone quarry into a six-acre earthwork of ramps, terraces, walls and stone pathways. The distinction is crucial: this is not sculpture displayed in a park; **the landscape itself is the artwork**.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 105, ["src-dummy"], H("09:00", "17:00", ""), C(20), "anchor"),
  S("rail-explorers-express", "Rail Explorers Catskills — Mt. Tremper Express", "pedal-machine-rail", "City", "ST", "2026-10-05", "**Selected format:** four-seat Quad, approximately four miles / 90 minutes **Current price:** **from $135 per Quad = $33.75 pp for four**", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 90, ["src-dummy"], H("09:00", "17:00", ""), C(33.75), "anchor"),
  S("worlds-end", "Worlds End State Park", "active-gorge-waterfall", "City", "ST", "2026-10-06", "Choose the day's version by conditions: - **Double Run sampler** for waterfalls, pools and harder footing, or", "Gora + Viki.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 120, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("bilgers-rocks", "Bilger's Rocks", "sandstone-rock-city", "City", "ST", "2026-10-07", "A 300-million-year-old sandstone “rock city” with rooms, corridors, cliffs and passageways. It is an ideal physical counterpoint to the human-made worlds later.", "Gora + Viki.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 105, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("scripture-rocks", "Scripture Rocks Heritage Park", "outsider-scripture-landscape", "City", "ST", "2026-10-07", "Approximately 1.5 miles of trail through a landscape containing dozens of carved boulders. It survives because the environment itself is the story. **Current fall access:** daylight / seasonal park access through October.", "Stivka + Viki + Gora for the human story.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 105, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("bayernhof", "Bayernhof Museum", "secret-mansion-automatic-music", "City", "ST", "2026-10-08", "**Booking:** **Required; guided tour by advance arrangement; small capacity** This is one of the few original Route 09 places that is essentially untouchable: a private-house fantasy containing automatic musical machines, unusual rooms and hidden architectural tricks.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 150, ["src-dummy"], H("09:00", "17:00", ""), C(10), "anchor"),
  S("palace-of-gold", "Prabhupada's Palace of Gold", "hand-built-sacred-maximalism", "City", "ST", "2026-10-08", "**Current tour model:** approximately **$12 pp / $48 group**, recheck official booking page The ornate palace and living spiritual complex add a hand-built visionary world without turning the day into another museum. It also gives Stivka a major sacred environment outside the Sunday liturgy.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 105, ["src-dummy"], H("09:00", "17:00", ""), C(12), "anchor"),
  S("alan-cottrill", "Alan Cottrill Sculpture Studio", "working-bronze-sculptor-world", "City", "ST", "2026-10-09", "**Admission:** no normal admission currently published; model **$0 / verify before departure** The reason to stop is the scale of one sculptor's output and the chance to encounter the making environment, not to “see a gallery.”", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 75, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("otherworld", "Otherworld Columbus", "interactive-surreal-labyrinth", "City", "ST", "2026-10-09", "Dozens of large-scale rooms, hidden passages and interactive installations create the route's most complete perception shift. It earns its slot because exploration is the point, not gallery viewing.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 150, ["src-dummy"], H("09:00", "17:00", ""), C(30), "anchor"),
  S("faustus-escape", "Captivating Worlds — Sins of Doctor Faustus", "puzzle-world-escape", "City", "ST", "2026-10-10", "**Traditional escape room:** #1 of 2 in active core **Current price evidence:** approximately **$20–28 pp**; use **$28 pp / $112 group ceiling** until Oct. 10 booking inventory is locked", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 75, ["src-dummy"], H("09:00", "17:00", ""), C(28), "anchor"),
  S("warther-museum", "Ernest Warther Museum & Gardens", "lifetime-carving-obsession", "City", "ST", "2026-10-10", "Warther's lifetime carving obsession, original home/workshop, button collection and gardens make this a creator-world rather than a generic museum stop.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 120, ["src-dummy"], H("09:00", "17:00", ""), C(20), "anchor"),
  S("grove-city-outlets", "Grove City Premium Outlets", "shopping-block", "City", "ST", "2026-10-10", "**Admission:** Free; purchases excluded This wins the route's single shopping block because it sits directly on the western-PA return line. The center has 120+ brand-name stores and Pennsylvania does not tax most clothing/shoes.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 135, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("st-nicholas-orthodox", "St. Nicholas Orthodox Church", "orthodox-sunday-worship", "City", "ST", "2026-10-11", "Current parish schedule lists Sunday Divine Liturgy at 10:00. Recheck the weekly bulletin immediately before departure.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 105, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("parker-dam", "Parker Dam State Park", "quiet-lake-forest-reset", "City", "ST", "2026-10-11", "A quiet lake/forest reset deliberately inserted after the intense western-half worlds. Use an easy lake-edge / Souders Trail sampler or the slightly more active New Giants option depending energy.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 55, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("bellefonte-talleyrand", "Bellefonte & Talleyrand Park", "victorian-town-reset", "City", "ST", "2026-10-11", "Bellefonte & Talleyrand Park is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 75, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("hickory-run-boulder-field", "Hickory Run Boulder Field", "natural-boulder-field", "City", "ST", "2026-10-12", "A giant flat field of boulders where the “trail” is literally negotiating rock. This is a rare physical-perception experience rather than another overlook. **Safety:** Stones can move; use proper footwear. Viki can stay near the field edge rather than cross the full surface.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 60, ["src-dummy"], H("09:00", "17:00", ""), C(0), "anchor"),
  S("skirmish-paintball", "Skirmish Paintball", "compete-paintball", "City", "ST", "2026-10-12", "**Official Oct. 12, 2026 preregistration price:** **$21.50 pp / $86 group** **Includes:** marker, mask, unlimited air/N2, referees, all-day field access; current promotion includes 100 paintballs when paid at least 24h ahead", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 165, ["src-dummy"], H("09:00", "17:00", ""), C(73.5), "anchor"),
  S("columcille", "Columcille Megalith Park", "modern-sacred-stone-environment", "City", "ST", "2026-10-12", "**Admission:** Free / donation-supported Modern standing stones, wooded trails and deliberate sacred atmosphere. **Do not climb the stones.** This works especially well after paintball because the interaction texture reverses completely.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 105, ["src-dummy"], H("09:00", "17:00", ""), C(5), "anchor"),
  S("fonthill-castle", "Fonthill Castle", "hand-mixed-concrete-castle", "City", "ST", "2026-10-13", "A 44-room reinforced-concrete home with handmade tile, irregular rooms, stairs, passages and construction logic that feels invented in real time. It is one of the best “someone actually built this?” experiences on the route. **Near-signatures:** Northlandz, Columcille Megalith Park and the conditional Troy Hill Darkhouse Lighthouse.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 75, ["src-dummy"], H("09:00", "17:00", ""), C(20), "anchor"),
  S("northlandz", "Northlandz", "massive-miniature-world", "City", "ST", "2026-10-13", "**Current public schedule:** daily approximately 10:00–18:00 **Current group-of-four indoor ticket:** **$135 total = $33.75 pp**", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 150, ["src-dummy"], H("09:00", "17:00", ""), C(33.75), "anchor"),
  S("puzzle-theory-spectral", "Puzzle Theory — Spectral Rift", "specialist-puzzle-finale", "City", "ST", "2026-10-14", "**Traditional escape room:** #2 of 2 active core **Current room format:** 3–10 players / 60 minutes", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 75, ["src-dummy"], H("09:00", "17:00", ""), C(35), "anchor"),
  S("worlds-largest-kaleidoscope", "World's Largest Kaleidoscope", "optical-wildcard", "City", "ST", "2026-10-05", "Use only as a short optical wildcard if timing works. Recent value feedback is mixed; “world's largest” is not sufficient reason to give it a full core block.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 45, ["src-dummy"], H("09:00", "17:00", ""), C(5), "supporting"),
  S("rail-explorers-river-run", "Rail Explorers — River Run", "longer-railbike", "City", "ST", "2026-10-05", "River Run is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 150, ["src-dummy"], H("09:00", "17:00", ""), C(45), "supporting"),
  S("kaaterskill-falls", "Kaaterskill Falls", "catskill-waterfall", "City", "ST", "2026-10-05", "Kaaterskill Falls is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 90, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("saugerties-lighthouse", "Saugerties Lighthouse", "hudson-reset", "City", "ST", "2026-10-05", "Saugerties Lighthouse is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 60, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("spiral-house-park", "Spiral House Park", "artist-built-environment", "City", "ST", "2026-10-05", "Spiral House Park is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 45, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("roebling-aqueduct", "Roebling's Delaware Aqueduct", "historic-suspension-engineering", "City", "ST", "2026-10-06", "Roebling's Delaware Aqueduct is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 45, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("hawks-nest", "Hawks Nest Highway", "scenic-road", "City", "ST", "2026-10-06", "Hawks Nest Highway is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 25, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("ricketts-glen", "Ricketts Glen Falls Trail", "high-output-hiking", "City", "ST", "2026-10-06", "Ricketts Glen Falls Trail is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 180, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("elk-country-visitor-center", "Elk Country Visitor Center", "autumn-elk-landscape", "City", "ST", "2026-10-07", "Elk Country Visitor Center is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 90, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("kinzua-bridge", "Kinzua Bridge Skywalk", "glass-floor-skywalk", "City", "ST", "2026-10-07", "Kinzua Bridge Skywalk is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 90, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("austin-dam", "Austin Dam Memorial Park", "ruined-concrete-dam", "City", "ST", "2026-10-07", "Austin Dam Memorial Park is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 60, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("penns-cave", "Penn's Cave", "all-water-cavern", "City", "ST", "2026-10-11", "If the group wants an underground “impossible space” rather than Parker Dam / Bellefonte time, Penn's Cave currently runs cavern tours **daily 10:00–16:00 throughout October 2026**. It is a true boat-through-cavern experience.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 90, ["src-dummy"], H("09:00", "17:00", ""), C(25), "supporting"),
  S("troy-hill-lighthouse", "Darkhouse Lighthouse", "working-lighthouse-rowhouse", "City", "ST", "2026-10-08", "Darkhouse Lighthouse is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 60, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("troy-hill-hutte-royal", "La Hütte Royal", "whole-house-art-world", "City", "ST", "2026-10-08", "La Hütte Royal is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 60, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("troy-hill-kunzhaus", "Kunzhaus", "whole-house-photography", "City", "ST", "2026-10-08", "Kunzhaus is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 60, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("troy-hill-mrs-christopher", "Mrs. Christopher's House", "whole-house-environment", "City", "ST", "2026-10-08", "Mrs. Christopher's House is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 60, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("gamegrounds-columbus", "Gamegrounds Columbus", "room-scale-mental-skill-games", "City", "ST", "2026-10-09", "Twelve RFID-scored room games blending memory, agility, coordination and skill. The concept fits, but recent adult feedback is mixed enough that it stays optional rather than displacing Otherworld or the stronger dedicated puzzle rooms.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 90, ["src-dummy"], H("09:00", "17:00", ""), C(25), "supporting"),
  S("captivating-worlds-machine", "Welcome to the Machine", "technology-heavy-escape", "City", "ST", "2026-10-10", "Welcome to the Machine is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 75, ["src-dummy"], H("09:00", "17:00", ""), C(28), "supporting"),
  S("book-loft", "The Book Loft", "labyrinthine-bookstore", "City", "ST", "2026-10-09", "The Book Loft is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 90, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("hartman-rock-garden", "Hartman Rock Garden", "outsider-built-concrete-yard", "City", "ST", "2026-10-10", "Hartman Rock Garden is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 60, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("cook-forest-cathedral", "Cook Forest Cathedral", "ancient-tree-reset", "City", "ST", "2026-10-07", "Cook Forest Cathedral is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 90, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("lakota-wolf", "Lakota Wolf Preserve", "wolf-watch", "City", "ST", "2026-10-13", "Lakota Wolf Preserve is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 75, ["src-dummy"], H("09:00", "17:00", ""), C(17), "supporting"),
  S("luna-parc", "Luna Parc", "private-studio-universe", "City", "ST", "2026-10-13", "Luna Parc is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 60, ["src-dummy"], H("09:00", "17:00", ""), C(10), "supporting"),
  S("tarrywile", "Tarrywile Mansion / Park", "low-energy-fallback", "City", "ST", "2026-10-13", "Tarrywile Mansion is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 90, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("optical-heritage-museum", "Optical Heritage Museum", "optical-perception-history", "City", "ST", "2026-10-14", "Wednesday walk-ins are currently accepted 10:00–16:00; adult admission **$10**. This is a very on-theme optical/perception alternate if the group wants lower physicality.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 60, ["src-dummy"], H("09:00", "17:00", ""), C(10), "supporting"),
  S("puzzle-theory-kraken", "Kraken's Revenge", "alternate-puzzle-room", "City", "ST", "2026-10-14", "Kraken's Revenge is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 75, ["src-dummy"], H("09:00", "17:00", ""), C(35), "supporting"),
  S("harvard-natural-history", "Harvard Museum of Natural History", "craft-science-fallback", "City", "ST", "2026-10-14", "Harvard Museum of Natural History is a recommended stop on this route.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 120, ["src-dummy"], H("09:00", "17:00", ""), C(20), "supporting"),
  S("y-bridge", "Zanesville Y Bridge", "infrastructure-photo", "City", "ST", "2026-10-09", "A clever 20–30 minute infrastructure/photo stop if the group is running early. It is not allowed to consume prime itinerary time merely because it is unusual.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 25, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
  S("ramapo-valley", "Ramapo Valley County Reservation", "structural-flex-break", "City", "ST", "2026-10-13", "If live navigation from Flemington to Danbury predicts **>~2h20 uninterrupted**, insert a **20–35 minute Scarlet Oak Pond / river-edge reset** in Mahwah. Bergen County describes Ramapo Valley as a 4,000+ acre Highlands park with river, ponds and extensive trails. This is a real experience break, not a loophole.", "Everyone.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative"], 45, ["src-dummy"], H("09:00", "17:00", ""), C(0), "supporting"),
];

export const dayPlans = [
  { day: 1, date: "2026-10-04", sleep_city: "Ghent, NY", theme: "Boston to Berkshires", schedule: [["13:30", "14:35", "keystone-arches", "anchor"], ["15:45", "17:30", "art-omi", "anchor"]], lodging: ["Ghent/Chatham", "Hudson"], fallback: "" },
  { day: 2, date: "2026-10-05", sleep_city: "Hancock, NY", theme: "Catskills to Hancock", schedule: [["10:00", "11:45", "opus-40", "anchor"], ["13:00", "14:30", "rail-explorers-express", "anchor"], ["15:00", "15:30", "worlds-largest-kaleidoscope", "supporting"], ["15:30", "16:00", "rail-explorers-river-run", "supporting"], ["16:00", "16:30", "kaaterskill-falls", "supporting"], ["16:30", "17:00", "saugerties-lighthouse", "supporting"], ["17:00", "17:30", "spiral-house-park", "supporting"]], lodging: ["Hancock", ""], fallback: "" },
  { day: 3, date: "2026-10-06", sleep_city: "Williamsport, PA", theme: "Worlds End", schedule: [["10:45", "12:45", "worlds-end", "anchor"], ["14:00", "14:30", "roebling-aqueduct", "supporting"], ["14:30", "15:00", "hawks-nest", "supporting"], ["15:00", "15:30", "ricketts-glen", "supporting"]], lodging: ["Williamsport", ""], fallback: "" },
  { day: 4, date: "2026-10-07", sleep_city: "Brookville, PA", theme: "Rock City and Scripture", schedule: [["10:30", "12:15", "bilgers-rocks", "anchor"], ["13:45", "15:30", "scripture-rocks", "anchor"], ["16:00", "16:30", "elk-country-visitor-center", "supporting"], ["16:30", "17:00", "kinzua-bridge", "supporting"], ["17:00", "17:30", "austin-dam", "supporting"], ["17:30", "18:00", "cook-forest-cathedral", "supporting"]], lodging: ["Brookville", ""], fallback: "" },
  { day: 5, date: "2026-10-08", sleep_city: "Wheeling, WV", theme: "Secret Machines", schedule: [["10:00", "12:30", "bayernhof", "anchor"], ["14:15", "16:00", "palace-of-gold", "anchor"], ["17:00", "17:30", "troy-hill-lighthouse", "supporting"], ["17:30", "18:00", "troy-hill-hutte-royal", "supporting"], ["18:00", "18:30", "troy-hill-kunzhaus", "supporting"], ["18:30", "19:00", "troy-hill-mrs-christopher", "supporting"]], lodging: ["Wheeling", ""], fallback: "" },
  { day: 6, date: "2026-10-09", sleep_city: "Columbus, OH", theme: "Bronze and Surrealism", schedule: [["10:00", "11:15", "alan-cottrill", "anchor"], ["14:30", "17:00", "otherworld", "anchor"], ["18:00", "18:30", "gamegrounds-columbus", "supporting"], ["18:30", "19:00", "book-loft", "supporting"], ["19:00", "19:30", "y-bridge", "supporting"]], lodging: ["Columbus", ""], fallback: "" },
  { day: 7, date: "2026-10-10", sleep_city: "West Middlesex, PA", theme: "Puzzles and Shopping", schedule: [["09:00", "10:15", "faustus-escape", "anchor"], ["12:15", "14:15", "warther-museum", "anchor"], ["16:15", "18:30", "grove-city-outlets", "anchor"], ["19:00", "19:30", "captivating-worlds-machine", "supporting"], ["19:30", "20:00", "hartman-rock-garden", "supporting"]], lodging: ["West Middlesex", ""], fallback: "" },
  { day: 8, date: "2026-10-11", sleep_city: "Bellefonte, PA", theme: "Orthodox Sunday", schedule: [["10:00", "11:45", "st-nicholas-orthodox", "anchor"], ["14:15", "15:10", "parker-dam", "anchor"], ["16:15", "17:30", "bellefonte-talleyrand", "anchor"], ["18:00", "18:30", "penns-cave", "supporting"]], lodging: ["Bellefonte", ""], fallback: "" },
  { day: 9, date: "2026-10-12", sleep_city: "Bangor, PA", theme: "Paintball and Stones", schedule: [["09:45", "10:45", "hickory-run-boulder-field", "anchor"], ["11:30", "14:15", "skirmish-paintball", "anchor"], ["15:15", "17:00", "columcille", "anchor"]], lodging: ["Bangor", ""], fallback: "" },
  { day: 10, date: "2026-10-13", sleep_city: "Danbury, CT", theme: "Castles and Miniatures", schedule: [["10:00", "11:15", "fonthill-castle", "anchor"], ["12:15", "14:45", "northlandz", "anchor"], ["16:00", "16:30", "lakota-wolf", "supporting"], ["16:30", "17:00", "luna-parc", "supporting"], ["17:00", "17:30", "tarrywile", "supporting"], ["17:30", "18:00", "ramapo-valley", "supporting"]], lodging: ["Danbury", ""], fallback: "" },
  { day: 11, date: "2026-10-14", sleep_city: "Boston, MA", theme: "Final Puzzle", schedule: [["10:30", "11:45", "puzzle-theory-spectral", "anchor"], ["13:00", "13:30", "optical-heritage-museum", "supporting"], ["13:30", "14:00", "puzzle-theory-kraken", "supporting"], ["14:00", "14:30", "harvard-natural-history", "supporting"]], lodging: ["Boston", ""], fallback: "" }
];
