export const verifiedAt = "2026-08-24";

export const sourceRows = [
  ["src-art-omi", "Art Omi - visit", "official", "https://artomi.org/visit/", ["October hours", "free admission", "park scale", "visitor registration"]],
  ["src-naumkeag", "The Trustees - Naumkeag", "official", "https://thetrustees.org/place/naumkeag/", ["estate access", "Blue Steps", "property scale"]],
  ["src-naumkeag-halloween", "The Trustees - Halloween 2026", "official", "https://thetrustees.org/program/halloween/", ["October 2026 event dates", "timed ticket release", "pumpkin display"]],
  ["src-kaleidoscope", "The Emerson - Kaleidoshow hours and admission", "official", "https://emersonresort.com/kaleidoscope/location-hours/", ["Monday hours", "adult admission", "immersive show"]],
  ["src-kaleidoscope-about", "The Emerson - Silo Kaleidoscope experience", "official", "https://emersonresort.com/silo-kaleidoscope-experience/", ["silo dimensions", "show duration", "Guinness claim"]],
  ["src-opus40", "Opus 40 - visiting", "official", "https://opus40.org/visiting/", ["Monday hours", "admission", "earthwork scale", "terrain"]],
  ["src-taber", "Thomas T. Taber Museum", "official", "https://tabermuseum.org/", ["Tuesday hours", "admission", "regional and toy-train collections"]],
  ["src-williamsport", "Visit Lycoming County - historic Williamsport", "tourism", "https://www.visitlycomingcounty.com/", ["Millionaires Row", "Way's Garden", "self-guided architecture"]],
  ["src-scripture", "Scripture Rocks Heritage Park", "official", "https://scripturerocks.com/contact-us/", ["operator", "address", "historical interpretation"]],
  ["src-scripture-hours", "Brookville Chamber - Scripture Rocks", "regional-tourism", "https://brookvillechamber.com/directory/scripture-rocks-heritage-park/", ["dawn-to-dusk season", "free access", "1.5-mile paths", "carved-boulder count"]],
  ["src-punx", "Visit Punxsutawney", "official-tourism", "https://www.visitpunxsutawney.com/", ["Gobbler's Knob", "Phil's Burrow", "public folklore sites"]],
  ["src-bayernhof", "Bayernhof Museum", "official", "https://www.bayernhofmuseum.com/index.html", ["appointment tours", "admission", "music machines", "hidden architecture"]],
  ["src-heinz", "Heinz History Center - visit", "official", "https://www.heinzhistorycenter.org/visit/heinz-history-center/", ["Thursday hours", "admission", "six floors", "regional collections"]],
  ["src-cottrill", "Alan Cottrill Sculpture Studio - contact", "official", "https://www.alancottrill.com/contact", ["Friday hours", "no appointment", "address"]],
  ["src-cottrill-tourism", "Visit Zanesville - Alan Cottrill Studio", "official-tourism", "https://www.visitzanesville.com/Explore/Destinations/105/Alan-Cottrill-Sculpture-Studio--Gallery/", ["300-plus bronzes", "working studio", "visitor experience"]],
  ["src-ybridge", "Visit Zanesville - Y Bridge", "official-tourism", "https://www.visitzanesville.com/Explore/Destinations/175/", ["bridge form", "Putnam overlook", "public access"]],
  ["src-otherworld", "Otherworld - tickets and hours", "official", "https://www.otherworld.com/main/tickets-and-hours", ["Friday hours", "online timed ticket", "adult admission", "free parking"]],
  ["src-cambridge-glass", "National Museum of Cambridge Glass", "official", "https://cambridgeglass.org/", ["Friday hours", "season", "glassmaking collection"]],
  ["src-butler", "Butler Institute of American Art", "official", "https://butlerart.com/", ["Saturday hours", "free admission", "American-art mission", "2026 exhibitions"]],
  ["src-fellows", "Mill Creek MetroParks - Fellows Riverside Gardens", "government", "https://www.millcreekmetroparks.org/fellows-riverside-gardens/", ["daily garden hours", "free access", "12-acre garden", "fall roses"]],
  ["src-stnicholas", "St Nicholas Orthodox Church - service schedule", "official-parish", "https://www.stnicholasdubois.org/schedule", ["Sunday Hours service", "Divine Liturgy or Obednitsa with Communion", "service time"]],
  ["src-stnicholas-oca", "Orthodox Church in America - St Nicholas DuBois", "official-church", "https://www.oca.org/parishes/oca-wp-dujsnc", ["canonical parish", "service pattern", "contact details"]],
  ["src-talleyrand", "Borough of Bellefonte - Talleyrand Park", "government", "https://bellefonte.net/departments/parks-rec/talleyrand-park/", ["Victorian context", "waterfront walk", "park features"]],
  ["src-bellefonte-art", "Bellefonte Art Museum", "official", "https://www.bellefontemuseum.org/", ["Sunday access", "historic Linn House", "regional exhibitions"]],
  ["src-columcille", "Columcille - visiting the park", "official", "https://www.columcille.org/visitingthepark", ["daily hours", "90-plus stone settings", "rough trails", "no climbing", "photo policy"]],
  ["src-columcille-history", "Columcille - refuge to megalithic park", "official", "https://www.columcille.org/refuge-to-megalithic-park", ["founding story", "Celtic inspiration", "stone-setting history"]],
  ["src-asapacker-events", "Asa Packer Mansion - October 2026", "official", "https://asapackermansion.com/events/", ["2026 October opening", "Monday access", "tour frequency"]],
  ["src-asapacker-tour", "Asa Packer Mansion - tour information", "official", "https://asapackermansion.letartliveon.com/tour/", ["admission", "guided-only access", "October duration", "original contents"]],
  ["src-tarrywile", "Tarrywile Park - park information", "official", "https://tarrywile.com/the-park/", ["daily sunrise-to-sunset access", "free admission", "722 acres", "trail network"]],
  ["src-hearthstone", "Tarrywile - Hearthstone Castle", "official", "https://tarrywile.com/hearthstone-castle/", ["1890s architecture", "ruin status", "fence and no-trespassing rule"]],
  ["src-aldrich", "The Aldrich - visit", "official", "https://thealdrich.org/visit", ["Tuesday museum closure", "admission", "sculpture garden", "parking"]],
  ["src-aldrich-garden", "CTvisit - Aldrich sculpture garden", "government-tourism", "https://ctvisit.com/listings/aldrich-contemporary-art-museum", ["free outdoor garden", "daily dawn-to-dusk access", "museum Tuesday closure"]],
  ["src-harvard", "Harvard Museums of Science and Culture - visit", "official", "https://hmsc.harvard.edu/visit/", ["Wednesday hours", "July 2026 admission", "combined Peabody entry", "photography"]],
  ["src-harvard-collections", "Harvard Museum of Natural History", "official", "https://www.hmnh.harvard.edu/", ["Glass Flowers", "minerals", "paleontology", "2026 exhibitions"]],
  ["src-mgh", "Mass General - Russell Museum and Ether Dome", "official", "https://www.massgeneral.org/museum", ["Wednesday public hours", "free admission", "medical-history interpretation", "Ether Dome"]],
  ["src-noaa-normals", "NOAA U.S. Climate Normals", "government", "https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals", ["1991-2020 normals methodology"]],
  ["src-osrm", "Open Source Routing Machine", "routing", "https://project-osrm.org/", ["road-network baselines", "no live traffic"]],
  ["src-forum-ohio", "r/Ohio and r/Columbus local discussions", "forum", "https://www.reddit.com/r/Ohio/", ["Otherworld value cross-check", "Zanesville and Youngstown pacing"]],
  ["src-forum-pa", "r/Pennsylvania road-trip discussions", "forum", "https://www.reddit.com/r/Pennsylvania/", ["small-town pacing", "Poconos and central Pennsylvania cross-check"]]
];

const H = (opens, closes, note, status = "verified-current") => ({ opens, closes, status, note });
const C = (amount, note = "Adult planning price; reconfirm before travel.", status = "verified-current") => ({ amount_per_person: amount, status, note });
const R = (day, replaces, variant, reason) => ({ day, replaces_place_ids: replaces, route_variant_id: variant, reason });
const S = (id, name, kind, city, state, date, summary, why_go, best_for, secondary_for, categories, duration_minutes, source_ids, hours, cost, priority = "anchor", reservation = "none", replacement = null) => ({
  id, name, kind, city, state, visit_date: date, summary, why_go, best_for, secondary_for,
  best_fit_note: `Best for ${best_for.join(" and ")}: ${why_go}`,
  categories, duration_minutes, source_ids, reservation, hours, cost, priority,
  ...(replacement ? { replacement_reason: replacement.reason, replacement } : {}), address: name
});

export const seedPlaces = [
  S("art-omi", "Art Omi Sculpture & Architecture Park", "landscape-scale-contemporary-art", "Ghent", "NY", "2026-10-04", "More than sixty works occupy meadow and woodland across a 120-acre park, so architecture, sculpture and the first autumn landscape arrive as one experience instead of a conventional gallery visit.", "It is a forgiving but genuinely strange first-day landing: Viki gets art embedded in nature, Gora gets material and engineering, Stivka gets quiet, and Paco can shorten the loop if Boston traffic bites.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "architecture_nature_photogenic", "quiet_reset"], 115, ["src-art-omi"], H("09:00", "dusk", "Visitor center closes at 17:00; the park remains open to dusk on Sunday. Register both vehicles and use the short loop because sunset is early."), C(0, "Free with a suggested $15 donation."), "anchor", "vehicle-registration"),
  S("naumkeag-pumpkin", "Naumkeag Blue Steps & Daytime Pumpkin Walk", "gilded-estate-and-seasonal-design", "Stockbridge", "MA", "2026-10-04", "A shingle-style country house, Fletcher Steele's Blue Steps and an intensely designed hillside garden gain a temporary layer of roughly a thousand pumpkins during the October program.", "This is the strongest first-day photo alternative for Viki and a softer architectural garden for Stivka; it feels seasonal without turning the night into a haunted-house commitment.", ["viki", "stivka"], ["sheluvspaco", "gora"], ["architecture_nature_photogenic", "unusual_creative", "local_culture"], 120, ["src-naumkeag", "src-naumkeag-halloween"], H("12:00", "16:00", "October 4 is in the confirmed 2026 Wednesday-Sunday event run, but the exact daytime timed slot is not released until August 26; select an early-afternoon ticket that preserves Ghent."), C(35, "Planning allowance until 2026 timed-ticket pricing is released.", "date-confirmed-price-pending"), "replacement", "reserve-after-august-26", R(1, ["art-omi"], "replacement-d1-naumkeag", "A ticketed Gilded Age garden-and-pumpkin swap if Art Omi is muddy or the group wants a more designed first photograph.")),
  S("worlds-largest-kaleidoscope", "World's Largest Kaleidoscope & Kaleidostore", "silo-sized-optical-show", "Mount Tremper", "NY", "2026-10-05", "A former grain silo becomes a 56-foot optical chamber: visitors lean back beneath three huge mirrors while a Catskills-inspired light-and-sound show turns a roadside record into immersive art.", "It is Route 9's first true oddity—short, playful and impossible to confuse with a normal museum. Viki gets color, Gora gets optics and construction, and everyone gets a shared absurd memory.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "local_culture", "architecture_nature_photogenic"], 75, ["src-kaleidoscope", "src-kaleidoscope-about"], H("10:00", "17:00", "Open Thursday-Monday. The show is about twenty minutes; allow time for the artist kaleidoscopes and restored dairy-barn shops."), C(5), "anchor"),
  S("opus-40", "Opus 40", "monumental-bluestone-earthwork", "Saugerties", "NY", "2026-10-05", "Over decades, Harvey Fite fitted Catskills bluestone into a 6.5-acre walkable sculpture of ramps, walls, terraces and a central monolith, with quarry and mountain landscape completing the work.", "This is the more physically immersive alternative for Viki and Gora: an obsessive human-made landform that reads as archaeology from another civilization, without becoming a long hike.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["unusual_creative", "architecture_nature_photogenic", "athletic_adrenaline"], 120, ["src-opus40"], H("10:00", "17:00", "Monday hours with last entry at 16:00. Stone is uneven and can be slippery; use sturdy shoes and skip in heavy rain."), C(20), "replacement", "weather-check", R(2, ["worlds-largest-kaleidoscope"], "replacement-d2-opus-40", "A larger outdoor art-and-landscape swap when the group wants movement and scale rather than a short indoor show.")),
  S("taber-museum", "Thomas T. Taber Museum", "regional-history-and-railroad-obsession", "Williamsport", "PA", "2026-10-06", "A county-history museum unexpectedly hides one of Pennsylvania's largest model-train collections—more than three hundred toy trains—beside lumber, Indigenous, domestic and industrial material.", "It looks modest but rewards Gora's appetite for how a region actually worked, while the giant train layout gives the group a playful mechanical surprise after a long drive.", ["gora"], ["sheluvspaco", "stivka", "viki"], ["hidden_history_folklore", "unusual_creative", "local_culture"], 120, ["src-taber"], H("09:30", "16:00", "Tuesday hours. The route targets 12:00-14:00; confirm that the train gallery is operating before leaving Hancock."), C(12), "anchor", "call-week-before"),
  S("millionaires-row", "Millionaires' Row & Way's Garden Circuit", "lumber-era-architecture-walk", "Williamsport", "PA", "2026-10-06", "A compact walk along West Fourth Street passes the exuberant homes built during Williamsport's lumber boom, then decompresses among the paths, fountain and plantings of Way's Garden.", "It converts a transit day into architecture and labor-economy context for Viki and Gora without risking a Tuesday museum closure or adding meaningful driving.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 90, ["src-williamsport"], H("dawn", "dusk", "Public sidewalks and park; view houses from the street, respect residents and keep the circuit to about 1.5 miles."), C(0), "replacement", "weather-check", R(3, ["taber-museum"], "replacement-d3-millionaires-row", "A zero-reservation outdoor architecture swap if the museum or train gallery cannot be confirmed.")),
  S("scripture-rocks", "Scripture Rocks Heritage Park", "outsider-scripture-landscape", "Brookville", "PA", "2026-10-07", "A 1.5-mile forest circuit threads past more than sixty boulders carved in the early 1900s with biblical passages by Douglas Stahlman, whose open-air preaching and troubled biography are interpreted rather than mythologized.", "This is the route's strangest meeting of faith, folk history and nature: compelling for Stivka and Gora, visually uncanny for Viki, and quiet enough to reset the whole group.", ["stivka", "gora"], ["viki", "sheluvspaco"], ["orthodox_spiritual", "hidden_history_folklore", "architecture_nature_photogenic", "unusual_creative"], 105, ["src-scripture", "src-scripture-hours"], H("dawn", "dusk", "Open April-October, dawn to dusk. Gravel paths can be wet; interpret Stahlman's mental-health history carefully and do not treat the inscriptions as Orthodox teaching."), C(0, "Free; donation supports the historical society."), "anchor"),
  S("punxsutawney-folklore", "Gobbler's Knob & Phil's Burrow Folklore Circuit", "living-american-weather-folklore", "Punxsutawney", "PA", "2026-10-07", "The famous February broadcast site, its oversized stump stage and the downtown burrow turn a one-day weather ritual into a year-round town identity, complete with painted Phil statues.", "It is intentionally fun rather than profound: Paco gets group levity, Viki gets absurd roadside images, and Gora can examine how media turns local folklore into national ritual.", ["sheluvspaco", "viki"], ["gora", "stivka"], ["hidden_history_folklore", "unusual_creative", "local_culture"], 105, ["src-punx"], H("dawn", "dusk", "Outdoor sites are public on Wednesday. The Weather Discovery Center is closed Wednesday and is not promised or silently added."), C(0), "replacement", "none", R(4, ["scripture-rocks"], "replacement-d4-punxsutawney", "A longer but cap-tested folklore swap if trail weather makes Scripture Rocks unsafe.")),
  S("bayernhof", "Bayernhof Museum", "secret-house-of-music-machines", "Pittsburgh", "PA", "2026-10-08", "A 19,000-square-foot mansion above the Allegheny conceals passages, trick architecture and a private collection of automatic music boxes, organs and mechanical instruments demonstrated during a guided tour.", "This is Route 9's signature hidden-gem anchor: engineering and obsession for Gora, theatrical interiors for Viki, musical history for Stivka and pure reveal-after-reveal fun for Paco.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["unusual_creative", "hidden_history_folklore", "architecture_nature_photogenic"], 150, ["src-bayernhof"], H("10:00", "16:00", "Tours are by advance appointment, normally daily except major holidays; only twelve visitors fit. Secure a Thursday morning slot before treating Route 9 as bookable."), C(10), "anchor", "reserve-now"),
  S("heinz-history", "Senator John Heinz History Center", "six-floor-western-pa-history", "Pittsburgh", "PA", "2026-10-08", "Six floors inside a converted ice warehouse connect the oldest surviving Jeep, industrial Pittsburgh, sports, immigration and the original Mister Rogers neighborhood set.", "This is the resilient alternative when Bayernhof's tiny tour cannot be booked: Gora still gets industrial truth and Viki gets design and television-memory artifacts without gambling on a private appointment.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "local_culture", "unusual_creative"], 180, ["src-heinz"], H("10:00", "17:00", "Open daily. Select two or three floors rather than attempting the entire museum before Wheeling."), C(20), "replacement", "none", R(5, ["bayernhof"], "replacement-d5-heinz", "The large, dependable history alternative when the small Bayernhof appointment is unavailable.")),
  S("alan-cottrill", "Alan Cottrill Sculpture Studio & Gallery", "working-bronze-artist-labyrinth", "Zanesville", "OH", "2026-10-09", "Hundreds of bronzes crowd two floors and spill onto the street while artists work amid clay, molds and monumental figures; the studio claims the largest exhibition of work by a living sculptor.", "Gora gets craft, strength and historical figures; Viki gets a visually overwhelming working studio; Paco gets direct human contact instead of another silent museum.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["unusual_creative", "hidden_history_folklore", "local_culture"], 90, ["src-cottrill", "src-cottrill-tourism"], H("09:00", "17:00", "Friday hours; no appointment is required for four people, but call if access to active work matters."), C(2, "Admission is not posted as a fixed fee; allow a respectful donation.", "donation-planning"), "anchor"),
  S("y-bridge", "Zanesville Y Bridge & Putnam Overlook", "three-way-river-bridge", "Zanesville", "OH", "2026-10-09", "The fifth bridge at the confluence lets drivers turn in the middle of the river, producing a literal Y best understood from the Putnam Hill overlook above town.", "It is a fifteen-minute infrastructure riddle for Viki and Gora, and the elevated view makes the geometry immediately legible without consuming the day.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["architecture_nature_photogenic", "unusual_creative", "local_culture"], 35, ["src-ybridge"], H("dawn", "dusk", "Public road and overlook. Photograph only from legal pull-offs and sidewalks; never stop on the bridge."), C(0), "supporting"),
  S("otherworld", "Otherworld Columbus", "interactive-surreal-art-world", "Columbus", "OH", "2026-10-09", "Dozens of artist-built rooms connect through glowing forests, impossible laboratories, creatures, secret doors and optional puzzles inside a former retail shell.", "This is the shared-excitement endpoint: Viki gets the route's most unreal images, Gora gets hidden systems and puzzles, and everyone can explore together without a mainstream club night.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "architecture_nature_photogenic", "social_nightlife_live"], 150, ["src-otherworld", "src-forum-ohio"], H("10:00", "22:00", "Friday hours. Buy an online-only timed ticket around 15:30; puzzles can extend the visit, so leave before fatigue makes dinner unpleasant."), C(30), "anchor", "reserve"),
  S("cambridge-glass", "National Museum of Cambridge Glass", "color-glass-and-making-history", "Cambridge", "OH", "2026-10-09", "Thousands of pieces in dramatic colors trace the Cambridge Glass Company while hands-on stations explain molds, etching and the labor behind the region's most glamorous tableware.", "It gives Viki color and design and gives Gora the industrial process; use it when the group wants craft history instead of a second immersive digital environment.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["unusual_creative", "hidden_history_folklore", "local_culture"], 90, ["src-cambridge-glass"], H("10:00", "16:00", "Open Wednesday-Saturday April-October. This replacement changes the visit sequence: glass first, then Cottrill and the Y Bridge; do not also visit Otherworld."), C(7), "replacement", "none", R(6, ["otherworld"], "replacement-d6-cambridge-glass", "A quieter craft-and-industry replacement when Otherworld tickets, sensory load or cost do not fit.")),
  S("butler-institute", "Butler Institute of American Art", "free-american-art-museum", "Youngstown", "OH", "2026-10-10", "One of the earliest museums devoted exclusively to American art mixes familiar paintings with regional, contemporary and technology-focused wings in a monumental McKim building—and admission remains free.", "Viki gets architecture and art, Gora gets a usable cross-section of American self-image, and the free format makes a two-hour stop feel generous instead of compulsory.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 135, ["src-butler"], H("11:00", "16:00", "Saturday hours. Arrive close to opening after the long Polaris drive and choose permanent highlights plus one 2026 exhibition."), C(0), "anchor"),
  S("fellows-riverside", "Fellows Riverside Gardens", "free-city-garden-overlook", "Youngstown", "OH", "2026-10-10", "A twelve-acre public garden rolls toward Lake Glacier through terraces, seasonal beds and overlooks; fall roses normally continue into early November.", "It is the nature-and-photo recovery swap for Viki and Stivka when nobody wants another museum, with almost no cost and an easy ninety-minute circuit.", ["viki", "stivka"], ["sheluvspaco", "gora"], ["architecture_nature_photogenic", "quiet_reset"], 90, ["src-fellows"], H("sunrise", "sunset", "Gardens are free and open daily; the visitor center is open Saturday 10:00-17:00. Garden Café is closed for redevelopment in 2026."), C(0), "replacement", "weather-check", R(7, ["butler-institute"], "replacement-d7-fellows", "A lower-energy outdoor replacement when fall weather is beautiful or museum fatigue appears.")),
  S("st-nicholas-dubois", "Protected Orthodox Sunday at St Nicholas Orthodox Church", "canonical-orthodox-worship", "DuBois", "PA", "2026-10-11", "A small canonical OCA parish protects Sunday worship at the center of the return, with Hours at 9:40 and either Divine Liturgy or Obednitsa with Communion at 10:00.", "This is Stivka's essential route commitment and belongs to all four Orthodox travelers. The small parish also offers the intimate community scale the trip's famous churches cannot.", ["stivka"], ["sheluvspaco", "viki", "gora"], ["orthodox_spiritual", "quiet_reset", "local_culture"], 150, ["src-stnicholas", "src-stnicholas-oca"], H("09:40", "12:00", "Officially the 10:00 service alternates between Divine Liturgy and Obednitsa with Communion. Call the parish and confirm October 11; the dataset never falsely promises full Liturgy."), C(0, "Free; make a respectful offering if appropriate."), "anchor", "parish-confirm"),
  S("bellefonte-victorian", "Bellefonte Victorian & Talleyrand Waterfront Walk", "victorian-small-town-reset", "Bellefonte", "PA", "2026-10-11", "A walk from the spring-fed waterfront and old rail station into courthouse streets reveals ironwork, towers and intact Victorian houses in a town most travelers pass on the way to Penn State.", "After worship and driving, Viki gets architecture and reflections, Gora gets the lumber-and-iron wealth story, and Stivka gets the quiet small-town evening he asked for.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "quiet_reset", "hidden_history_folklore"], 105, ["src-talleyrand"], H("dawn", "dusk", "Public park and sidewalks. Keep the walk compact after the drive; the buildings are private unless explicitly open."), C(0), "anchor"),
  S("bellefonte-art", "Bellefonte Art Museum in the Linn House", "small-town-art-in-victorian-house", "Bellefonte", "PA", "2026-10-11", "Rotating regional art occupies an 1810 limestone house, turning a short indoor visit into both local creative culture and an intimate historic-building experience.", "It is a weatherproof Sunday alternative for Viki and Stivka without sacrificing the gentle Bellefonte night or asking the group to drive again.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "local_culture", "quiet_reset"], 75, ["src-bellefonte-art"], H("12:00", "16:30", "Typical Sunday access; exhibition turnover can close galleries, so verify October 11 directly."), C(0, "Free; donation encouraged."), "replacement", "reconfirm-exhibitions", R(8, ["bellefonte-victorian"], "replacement-d8-bellefonte-art", "The indoor, low-walking substitute after the same protected Orthodox service and unchanged drive.")),
  S("columcille", "Columcille Megalith Park", "celtic-inspired-stone-sanctuary", "Bangor", "PA", "2026-10-12", "More than ninety stone settings occupy twenty wooded acres on Blue Mountain—circles, towers, bells and named monoliths arranged as a living sanctuary of myth, contemplation and personal story.", "This may be Route 9's most magical landscape: Stivka gets spiritual quiet, Viki gets ancient-looking forms in autumn woods, and Gora gets the honest modern history of how the stones were set.", ["stivka", "viki"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "quiet_reset", "hidden_history_folklore", "unusual_creative"], 135, ["src-columcille", "src-columcille-history"], H("dawn", "dusk", "Open daily. Trails are rough and unpaved; never climb stones. Personal photos are allowed, but website/commercial reuse requires written permission."), C(5, "No fixed admission; plan a donation."), "anchor", "weather-check"),
  S("asa-packer", "Asa Packer Mansion", "intact-industrial-magnate-house", "Jim Thorpe", "PA", "2026-10-12", "An 1861 eighteen-room mansion preserves original Packer family contents and extraordinary carved wood while a guided tour reveals the railroad fortune behind both the house and the town.", "Viki gets the richest interior, Gora gets industry and power through primary objects, and the thirty-minute October format reduces walking when Columcille weather fails.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "local_culture"], 90, ["src-asapacker-events", "src-asapacker-tour"], H("11:00", "15:30", "Officially open throughout October 2026 except Tuesdays. October tours are about thirty minutes and first-come, first-served; arrive early on the holiday Monday."), C(13), "replacement", "holiday-confirm", R(9, ["columcille"], "replacement-d9-asa-packer", "The exact cap-tested indoor alternative for rain, poor footing or a desire for industrial-era interiors.")),
  S("tarrywile", "Tarrywile Mansion, Park & Hearthstone Exterior", "municipal-estate-and-fenced-castle-ruin", "Danbury", "CT", "2026-10-13", "A 722-acre city park combines a shingle-style mansion, former farm, ponds and the distant legal exterior of roofless Hearthstone Castle—an 1890s Norman fantasy now secured behind fencing.", "The contrast is what makes it work: Viki gets romantic architecture and autumn landscape, Gora gets an honest preservation failure, and everyone gets a calm final road-night stop.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 135, ["src-tarrywile", "src-hearthstone"], H("sunrise", "sunset", "Park is free and open daily weather permitting. Hearthstone is a dangerous ruin: remain outside every fence, obey closures and never trespass. This is a short mansion/pond/exterior circuit, not a 21-mile hike."), C(0), "anchor", "weather-check"),
  S("aldrich", "Aldrich Outdoor Sculpture Garden", "free-contemporary-sculpture-garden", "Ridgefield", "CT", "2026-10-13", "The museum's two-acre campus places contemporary sculpture against old Main Street and a wooded edge, giving the group a compact art break without pretending the Tuesday galleries are open.", "It is the precise low-walking swap for Viki and Paco when Tarrywile trails are wet; its honesty matters—the outdoor garden is the experience, not the closed museum.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "architecture_nature_photogenic", "quiet_reset"], 75, ["src-aldrich", "src-aldrich-garden"], H("dawn", "dusk", "The museum is CLOSED Tuesday. Only use the free outdoor sculpture garden if daily public access remains posted; verify the gate on October 13 and never advertise gallery entry."), C(0), "replacement", "same-day-gate-check", R(10, ["tarrywile"], "replacement-d10-aldrich-garden", "A compact outdoor-art substitute, route-tested at 200 minutes, if Tarrywile is muddy or the group needs less walking.")),
  S("harvard-natural-history", "Harvard Museum of Natural History & Glass Flowers", "scientific-wonder-cabinet", "Cambridge", "MA", "2026-10-14", "The Blaschkas' astonishing glass plants sit beside minerals, fossils, mounted animals and current research collections, blurring the line between scientific specimen and impossible craft.", "This is a strong all-group finale: Viki gets glass artistry, Gora gets science and specimens, Stivka gets wonder, and both rental cars are already returned before anyone enters Cambridge.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["unusual_creative", "hidden_history_folklore", "architecture_nature_photogenic"], 180, ["src-harvard", "src-harvard-collections"], H("09:00", "17:00", "Open daily. Enter around 12:00 only after both cars are returned at Logan; one ticket also includes the Peabody, but do not attempt both collections exhaustively."), C(20, "Official adult rate effective July 1, 2026."), "anchor", "reserve-recommended"),
  S("ether-dome", "Russell Museum & Ether Dome", "medical-innovation-and-ethical-history", "Boston", "MA", "2026-10-14", "Mass General's free medical-history museum leads into the story of the surgical amphitheater where ether anesthesia was publicly demonstrated, pairing innovation with questions about pain, patients and medical memory.", "Gora gets consequential history, Viki gets an extraordinary amphitheater interior, and the whole group gets a short, free finale when a three-hour natural-history museum is too much.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic", "unusual_creative"], 120, ["src-mgh"], H("10:00", "14:00", "Russell Museum is open Wednesday 10:00-14:00. Confirm public Ether Dome access with staff; this is a working hospital, so patient care, privacy and security override sightseeing."), C(0), "replacement", "call-week-before", R(11, ["harvard-natural-history"], "replacement-d11-ether-dome", "A shorter free medical-history finale after the same car return, with unchanged road mileage."))
];

// Route 09 is written for friends who speak English as a second language.
// Keep each place concrete, short, and easy to picture while preserving the
// verified facts and the reason it belongs on this route.
const simplePlaceCopy = {
  "art-omi": {
    summary: "More than sixty big artworks stand in fields and woods across this 120-acre park. You walk between them at your own pace, with no gallery walls.",
    why_go: "It is a relaxed but interesting way to start the trip. Everyone can explore in a different direction and meet up later."
  },
  "naumkeag-pumpkin": {
    summary: "This grand old house has a famous blue staircase called the Blue Steps, set inside a carefully designed garden. In October, about a thousand pumpkins fill the grounds.",
    why_go: "Choose this warm, colorful option if the weather turns and you want a softer first day."
  },
  "worlds-largest-kaleidoscope": {
    summary: "An old grain silo was turned into a giant kaleidoscope. You lean back inside it while huge mirrors and lights make a moving picture show about twenty minutes long.",
    why_go: "It is short, strange, and fun for everyone. Nobody expects a roadside stop like this."
  },
  "opus-40": {
    summary: "One man spent decades stacking local stone into ramps, walls, and platforms across 6.5 acres. Walking through it feels like exploring ancient ruins, but it was built by hand in modern times.",
    why_go: "Choose this bigger outdoor option when the group wants to walk around real stonework instead of a short indoor show."
  },
  "taber-museum": {
    summary: "This small county museum tells the story of local history, lumber, and factory life. It also holds one of Pennsylvania's largest toy train collections, more than three hundred trains.",
    why_go: "It looks quiet from outside but has a fun surprise inside. The toy trains give everyone a break from serious history."
  },
  "millionaires-row": {
    summary: "A short walk down West Fourth Street passes grand old houses built by lumber families long ago. The walk ends in Way's Garden, a calm park with paths and a fountain.",
    why_go: "Choose this free outdoor walk instead of the train museum if you want fresh air and old architecture without driving further."
  },
  "scripture-rocks": {
    summary: "A forest path winds past more than sixty large rocks. Each one was carved with Bible verses in the early 1900s by a man named Douglas Stahlman.",
    why_go: "It is a strange and quiet place that mixes faith, history, and nature. The story behind it is honest, including the hard parts of the man's life."
  },
  "punxsutawney-folklore": {
    summary: "This is the real town from the famous groundhog weather tradition. You can see Gobbler's Knob, where the yearly announcement happens, and painted groundhog statues around town.",
    why_go: "It is a fun, easy stop, not a serious history lesson. Everyone gets a laugh and a good photo."
  },
  "bayernhof": {
    summary: "This huge hidden mansion has secret passages and strange rooms built just for fun. A guide shows you a private collection of machines that play music by themselves, like organs and music boxes.",
    why_go: "This is one of the most surprising stops on the whole trip. Only twelve people can join each tour, so book it early."
  },
  "heinz-history": {
    summary: "Six floors inside an old ice warehouse hold real objects from the region's history: factories, sports, immigration, and even the actual set from Mister Rogers' TV show.",
    why_go: "Choose this large museum if the small Bayernhof tour cannot be booked. There is enough here for a full visit on its own."
  },
  "alan-cottrill": {
    summary: "Hundreds of bronze statues fill two floors of this working art studio. You can often see the artists shaping clay or working with metal while you walk through.",
    why_go: "It feels alive, not like a quiet museum. You get to see real work happening, not just finished art behind glass."
  },
  "y-bridge": {
    summary: "This unusual bridge crosses two rivers at once, so drivers can actually turn in the middle of it. The best way to understand its shape is from the hill above town.",
    why_go: "It only takes fifteen minutes but gives a fun, easy-to-understand view of a strange piece of engineering."
  },
  "otherworld": {
    summary: "Dozens of glowing, strange rooms connect together inside an old store building. You walk through a forest of light, hidden doors, and odd creatures, solving small puzzles along the way.",
    why_go: "This is the most exciting, unusual stop of the day. Everyone can explore together and find a favorite room."
  },
  "cambridge-glass": {
    summary: "This museum holds thousands of pieces of colorful glass made by a famous local glass company. Hands-on displays show how the glass was shaped, cut, and colored.",
    why_go: "Choose this quieter, craft-focused stop instead of Otherworld if the group wants color and history instead of another big sensory experience."
  },
  "butler-institute": {
    summary: "This large art museum was one of the first in America built only for American art. Entry is completely free, and the building itself is grand and historic.",
    why_go: "It gives real art and architecture without any cost. A relaxed stop after a long day of driving."
  },
  "fellows-riverside": {
    summary: "This twelve-acre garden sits on a hill above a lake, filled with flower beds, paths, and wide views. Roses often still bloom here into November.",
    why_go: "Choose this free outdoor garden instead of another museum when the group wants fresh air and color."
  },
  "st-nicholas-dubois": {
    summary: "This small Orthodox church protects Sunday morning worship in the middle of the trip. Morning prayers begin at 9:40, followed by a full service at 10:00.",
    why_go: "This stop matters most for Stivka, and the whole group shares it together. The small church feels warm and personal."
  },
  "bellefonte-victorian": {
    summary: "A short walk along the water and past an old train station leads into a town full of pretty old houses and iron details. It feels like stepping back in time.",
    why_go: "After church and driving, this gives everyone a calm, easy walk with pretty views and no pressure."
  },
  "bellefonte-art": {
    summary: "This small art museum sits inside an old stone house built in 1810. Local and regional art fills the rooms of the historic home.",
    why_go: "Choose this indoor option instead of the outdoor walk if the weather turns bad on Sunday."
  },
  "columcille": {
    summary: "More than ninety large standing stones are arranged across twenty acres of forest. People built it as a peaceful place to think, not to copy an ancient site.",
    why_go: "This might be the most magical spot on the whole trip. It feels ancient, but the true story of how it was built is honest and modern."
  },
  "asa-packer": {
    summary: "This grand 1861 mansion still holds its original furniture and decorations. A guide walks you through the eighteen rooms in about thirty minutes.",
    why_go: "Choose this indoor mansion tour instead of the stone park if the weather is bad or the group wants less walking."
  },
  "tarrywile": {
    summary: "This large park holds an old mansion, ponds, and walking paths. From a safe distance, you can also see the outside of Hearthstone Castle, a roofless ruin now closed off with fencing.",
    why_go: "It is a calm, pretty stop with a strange twist: a real castle that was never finished and is now falling apart."
  },
  "aldrich": {
    summary: "This free outdoor sculpture garden sits beside an old town street. Since the museum itself is closed on Tuesdays, only the outdoor art is open to visit.",
    why_go: "Choose this short, free stop if the ground at Tarrywile is too wet or muddy for walking."
  },
  "harvard-natural-history": {
    summary: "Delicate glass flowers that look completely real sit beside rocks, fossils, and stuffed animals. Skilled artists made the glass flowers so carefully that they still amaze scientists today.",
    why_go: "This is a strong last stop for the whole group. Everyone finds something different to enjoy here."
  },
  "ether-dome": {
    summary: "This free museum tells the story of medicine at a real hospital. It leads to a famous old surgery room where doctors first showed the world that pain during surgery could be stopped.",
    why_go: "Choose this shorter, free stop if a long museum visit feels like too much on the last day."
  }
};

// Plain-language "best for" lines. Each one names the people it suits and why,
// in short sentences, instead of repeating the why_go text back at the reader.
const bestFitNotes = {
  "art-omi": "Good for Viki, who can photograph art set in nature, and for Paco, who likes an easy, relaxed start. Gora enjoys studying how the pieces are built.",
  "naumkeag-pumpkin": "Good for Viki's photos and Stivka's love of a calm garden. A warm backup when the weather turns.",
  "worlds-largest-kaleidoscope": "Good for Viki's colors and Paco's sense of fun. Gora enjoys the mirrors and the mechanics behind the show.",
  "opus-40": "Good for Viki's photos and Gora's love of real engineering. A good choice when everyone wants to walk and explore instead of watching a short show.",
  "taber-museum": "Good for Gora, who enjoys real local history and the toy trains. A calm, easy stop after a long drive.",
  "millionaires-row": "Good for Viki's architecture photos and Gora's interest in how the town grew rich. Free and easy after a long drive.",
  "scripture-rocks": "Good for Stivka's quiet reflection and Gora's interest in the man's real story. Viki gets strange and striking photos.",
  "punxsutawney-folklore": "Good for Paco's sense of humor and Viki's fun photos. Gora enjoys seeing how a small town built its own legend.",
  "bayernhof": "Good for Gora's love of machines and Viki's love of strange rooms. Stivka enjoys the music, and Paco enjoys the constant surprises.",
  "heinz-history": "Good for Gora's real history and Viki's design eye. A safe backup with plenty to see on its own.",
  "alan-cottrill": "Good for Gora's respect for craft and Viki's love of a busy, visual space. Paco enjoys meeting real working artists.",
  "y-bridge": "Good for Viki's photos and Gora's curiosity about how it works. A quick and easy stop for everyone.",
  "otherworld": "Good for Viki's photos and Paco's sense of fun. Gora enjoys finding the hidden puzzles and secret doors.",
  "cambridge-glass": "Good for Viki's love of color and Gora's interest in how things are made. A calmer choice than Otherworld.",
  "butler-institute": "Good for Viki's art and architecture eye and Gora's interest in American history. Free, so nobody feels rushed.",
  "fellows-riverside": "Good for Viki's photos and Stivka's quiet moment outdoors. Free and easy after days of museums.",
  "st-nicholas-dubois": "Good for Stivka above all, and a shared calm morning for the whole group. Small and personal rather than grand.",
  "bellefonte-victorian": "Good for Viki's architecture photos and Stivka's quiet walk. A gentle way to end a busy Sunday.",
  "bellefonte-art": "Good for Viki's love of old buildings and Stivka's calm mood. The right choice on a rainy Sunday.",
  "columcille": "Good for Stivka's quiet spirit and Viki's photos of ancient-looking stones. Gora appreciates the honest, modern story behind it.",
  "asa-packer": "Good for Viki's love of grand interiors and Gora's interest in the family's real power and money. Short and easy on a busy holiday Monday.",
  "tarrywile": "Good for Viki's photos of the mansion and the ponds. Gora finds the story of the failed castle honestly interesting.",
  "aldrich": "Good for Viki's photos and Paco's easy pace. A short, free stop when the group needs less walking.",
  "harvard-natural-history": "Good for Viki's love of beautiful, delicate art and Gora's interest in real science. A strong finish for the whole group.",
  "ether-dome": "Good for Gora's interest in real history and Viki's photos of the old surgery room. Short and free on a busy last day."
};

for (const place of seedPlaces) {
  const copy = simplePlaceCopy[place.id];
  if (!copy) throw new Error(`Missing simple Route 09 copy for ${place.id}`);
  const fitNote = bestFitNotes[place.id];
  if (!fitNote) throw new Error(`Missing Route 09 best-fit note for ${place.id}`);
  place.summary = copy.summary;
  place.why_go = copy.why_go;
  place.best_fit_note = fitNote;
}

export const dayPlans = [
  { day: 1, date: "2026-10-04", sleep_city: "Ghent, NY", theme: "Sculpture in autumn fields after the island transfer", schedule: [["15:35", "17:30", "art-omi", "anchor"]], lodging: ["Ghent/Chatham with two clean rooms, strong recent safety reviews and illuminated parking", "Hudson east only if the exact pin still preserves Monday's cap"], fallback: "The 208-minute OSRM baseline assumes both cars leave Logan near 12:15 and has no traffic. Art Omi's visitor center closes at 17:00, so use the short park loop and cut it entirely if pickup slips. Naumkeag replaces it only with a real early-afternoon 2026 ticket." },
  { day: 2, date: "2026-10-05", sleep_city: "Hancock, NY", theme: "Enter a giant kaleidoscope, then cross the Catskills", schedule: [["10:15", "11:30", "worlds-largest-kaleidoscope", "anchor"]], lodging: ["Hancock village with two clean rooms and secure two-car parking", "Deposit only if the exact property has materially stronger cleanliness and bedding"], fallback: "The 193-minute baseline is balanced but rural. Confirm the Kaleidoshow is operating Monday, fuel before the longer second leg and reach Hancock in daylight. Opus 40 is a replacement, never an added second attraction." },
  { day: 3, date: "2026-10-06", sleep_city: "Williamsport, PA", theme: "Toy trains, lumber wealth and an unhurried river city", schedule: [["12:00", "14:00", "taber-museum", "anchor"]], lodging: ["Central Williamsport near West Fourth Street with two clean rooms and bright parking", "South Williamsport only if parking and room configuration are clearly better"], fallback: "This 206-minute baseline is near the hard cap before traffic. Confirm the toy-train gallery, leave Hancock early and stop only for food/fuel. Millionaires' Row replaces the museum if access fails; it is not stacked after a full visit." },
  { day: 4, date: "2026-10-07", sleep_city: "Brookville, PA", theme: "Scripture carved into a forest, then a quiet historic town", schedule: [["11:15", "13:00", "scripture-rocks", "anchor"]], lodging: ["Historic Brookville or the PA-36 edge with two clean rooms and visible parking", "Clarion only if the exact hotel pin remains under the 210-minute measured bed-to-bed limit"], fallback: "The 154-minute baseline intentionally creates recovery. Walk only the safest 1.5-mile circuit and interpret Stahlman's story critically. In rain or poor footing, use the separately measured Punxsutawney outdoor folklore circuit; the Weather Discovery Center is closed Wednesday." },
  { day: 5, date: "2026-10-08", sleep_city: "Wheeling, WV", theme: "Secret doors and self-playing machines above Pittsburgh", schedule: [["10:30", "13:00", "bayernhof", "anchor"]], lodging: ["Wheeling riverfront or central district with two clean rooms and secure parking", "The Highlands only if the current hotel record is substantially safer and cleaner"], fallback: "Bayernhof is the booking lock. The 202-minute baseline is live-traffic-gated around Pittsburgh; reserve a morning tour and check ETA before leaving Brookville. Heinz replaces Bayernhof if no appointment exists—never stack both." },
  { day: 6, date: "2026-10-09", sleep_city: "Columbus, OH", theme: "Bronze giants, a bridge riddle and another world", schedule: [["10:00", "11:30", "alan-cottrill", "anchor"], ["11:40", "12:15", "y-bridge", "supporting"], ["15:15", "17:45", "otherworld", "anchor"]], lodging: ["North Columbus/Polaris with two clean rooms, secure two-car parking and walkable dinner options", "Westerville only if the exact hotel keeps Saturday's measured departure point"], fallback: "At 170 baseline minutes this is the most layered day, not permission to add more. Reserve Otherworld, keep Zanesville lunch quick and stop the puzzles at the scheduled exit. Cambridge Glass replaces Otherworld and changes the sequence; it does not join it." },
  { day: 7, date: "2026-10-10", sleep_city: "West Middlesex, PA", theme: "American art, then a quiet border-town night", schedule: [["11:00", "13:15", "butler-institute", "anchor"]], lodging: ["West Middlesex near I-80 with two clean rooms and strong recent safety reviews", "Hermitage only if Sunday morning ETA to DuBois remains under the tested route"], fallback: "The 208-minute baseline is live-traffic-gated. Leave Polaris around 07:30 and enter Butler at opening. Fellows Riverside Gardens is the better-weather replacement; neither option justifies an extra Youngstown stop before the protected Sunday drive." },
  { day: 8, date: "2026-10-11", sleep_city: "Bellefonte, PA", theme: "Protected Orthodox worship and a Victorian small-town exhale", schedule: [["09:40", "12:00", "st-nicholas-dubois", "anchor"], ["14:00", "15:45", "bellefonte-victorian", "anchor"]], lodging: ["Historic Bellefonte with two clean rooms and off-street parking", "State College north only if Bellefonte inventory fails and Monday's exact route is re-measured"], fallback: "Leave West Middlesex by 07:30. The parish officially alternates Divine Liturgy and Obednitsa with Communion, so call to identify October 11 and ask about Communion etiquette. Worship is never shortened; Bellefonte Art Museum merely replaces the outdoor walk." },
  { day: 9, date: "2026-10-12", sleep_city: "Tannersville, PA", theme: "A modern megalith sanctuary in the Poconos woods", schedule: [["11:15", "13:30", "columcille", "anchor"]], lodging: ["Tannersville/Bartonsville with two clean rooms, secure parking and an easy I-80 exit", "Stroudsburg west only if Tuesday's exact Tarrywile routing remains under 210 minutes"], fallback: "The 209-minute baseline is at the cap and October 12 is a holiday. Leave early, use no scenic detours and treat rough or wet trails as a cancellation signal. Asa Packer is the official 2026 Monday alternative; it replaces Columcille and has its own 209-minute measured route." },
  { day: 10, date: "2026-10-13", sleep_city: "Danbury, CT", theme: "A mansion, ponds and the legal edge of a lost castle", schedule: [["12:00", "14:15", "tarrywile", "anchor"]], lodging: ["West Danbury/Ridgebury with two clean rooms and secure parking", "Central Danbury only if the recent safety and cleanliness record is stronger"], fallback: "The 190-minute baseline leaves useful daylight. Use the mansion/pond/exterior circuit and never cross Hearthstone fencing. Aldrich museum is closed Tuesday; only its free outdoor sculpture garden is a valid replacement if daily gate access is reconfirmed." },
  { day: 11, date: "2026-10-14", sleep_city: "Boston, MA", theme: "Return both cars, then study flowers that are actually glass", schedule: [["12:00", "15:00", "harvard-natural-history", "anchor"]], lodging: ["Logan airport hotel with the exact one-bed plus two-bed room setup and confirmed early October 15 shuttle", "East Boston or Revere only with a verified airport transfer"], fallback: "The 203-minute baseline is live-traffic-gated. Leave Danbury around 06:15, return both cars at Logan before any attraction and continue by transit/rideshare. Russell Museum and the Ether Dome are the shorter free replacement; no airport-eve nightlife is scheduled." }
];
