#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  contextualImagePlaces, lodgingNodes, manualCoordinates, PEOPLE, replacementVariants,
  ROUTE_ID, ROUTE_NAME, ROUTE_SLUG
} from "./config.mjs";
import { buildEnergyRoute05 } from "../route-05-energy/build.mjs";

const ROOT = process.cwd();
const ROUTE_DIR = path.join(ROOT, "dataset", "routes", ROUTE_SLUG);
const verifiedAt = "2026-08-23";

const sourceRows = [
  ["src-wadsworth", "Wadsworth Atheneum Museum of Art", "official", "https://www.thewadsworth.org/visit/hours-admission/", ["Sunday hours", "admission", "advance-reservation policy"]],
  ["src-holy-land", "Holy Land USA", "official", "https://www.holylandwaterbury.org/faqs", ["daylight public access", "address", "no after-sunset access"]],
  ["src-holy-land-events", "Holy Land USA - 2026 Events", "official", "https://www.holylandwaterbury.org/events", ["August 2026 Stations trail and three-cross dedication", "footwear and parking caution"]],
  ["src-mark-twain", "The Mark Twain House & Museum", "official", "https://marktwainhouse.org/visit/", ["guided-tour-only interior", "advance booking", "seven-day operation and last tour"]],
  ["src-lackawanna", "Lackawanna County", "government", "https://www.lackawannaconnect.com/news/coal-mine-tour-open-for-season-on-april-2-2026-03-26", ["2026 operating days", "last tour", "arrival rule"]],
  ["src-steamtown", "National Park Service - Steamtown", "government", "https://www.nps.gov/stea/learn/management/lawsandpolicies.htm", ["2026 regular season", "hours", "admission"]],
  ["src-scranton-iron", "Pennsylvania Historical and Museum Commission", "government", "https://www.pa.gov/agencies/phmc/historic-sites-and-museums/industrial-heritage-trail/scranton-iron", ["site history", "dawn-dusk access"]],
  ["src-houdini", "Houdini Museum", "official", "https://www.houdinimuseum.net/contact-10", ["year-round operation", "call-ahead requirement"]],
  ["src-watch-clock", "National Association of Watch and Clock Collectors", "official", "https://www.nawcc.org/visit/", ["fall hours", "admission", "collection"]],
  ["src-central-market", "Lancaster Central Market", "official", "https://centralmarketlancaster.com/visit/", ["Tuesday hours", "vendor market"]],
  ["src-troll-market", "Lancaster Troll Market", "official", "https://www.lancastertrollmarket.com/", ["Tuesday hours", "curiosity shop"]],
  ["src-wolves", "Wolf Sanctuary of PA", "official", "https://wolfsanctuarypa.org/tours-events/", ["Tuesday public tour", "reservation", "price"]],
  ["src-ephrata", "Ephrata Cloister", "official", "https://ephratacloister.org/", ["Wednesday hours", "historic interpretation"]],
  ["src-railroad-pa", "Railroad Museum of Pennsylvania", "government", "https://www.rrmuseumpa.org/visit/hours-admissions", ["Wednesday hours", "admission", "collection"]],
  ["src-covered-bridges", "Lancaster County", "government", "https://co.lancaster.pa.us/1526/Covered-Bridges", ["bridge identity", "driving caution"]],
  ["src-harrisburg-river", "City of Harrisburg - Riverfront Park", "government", "https://harrisburg.recdesk.com/Community/Facility/Detail?facilityId=65", ["public riverfront", "Walnut Street Bridge plaza"]],
  ["src-turkey-hill", "Turkey Hill Experience", "official", "https://www.turkeyhillexperience.com/plan-your-visit/", ["hours", "interactive experience", "admission"]],
  ["src-pa-capitol", "Pennsylvania Department of General Services", "government", "https://www.pa.gov/agencies/dgs/visit-the-capitol-complex", ["weekday access", "tour logistics"]],
  ["src-antietam", "National Park Service - Antietam", "government", "https://www.nps.gov/anti/planyourvisit/hours.htm", ["visitor center hours", "battlefield access"]],
  ["src-harpers-hours", "National Park Service - Harpers Ferry", "government", "https://www.nps.gov/hafe/planyourvisit/hours.htm?fullweb=1", ["museum hours", "shuttle window"]],
  ["src-harpers-trails", "National Park Service - Virginius Island", "government", "https://home.nps.gov/hafe/planyourvisit/virginius-island-trail.htm", ["trail distance", "industrial ruins", "daylight access"]],
  ["src-seton", "National Shrine of Saint Elizabeth Ann Seton", "official", "https://setonshrine.org/hours-directions/", ["daily hours", "museum and historic homes"]],
  ["src-luray", "Luray Caverns", "official", "https://luraycaverns.com/plan/", ["October hours", "admission"]],
  ["src-skyline", "National Park Service - Skyline Drive", "government", "https://www.nps.gov/shen/planyourvisit/driving-skyline-drive.htm", ["road speed", "weather closures", "drive time"]],
  ["src-stony-man", "National Park Service - Stony Man", "government", "https://www.nps.gov/thingstodo/hike-stony-man.htm", ["trail length", "difficulty", "summit access"]],
  ["src-cville-downtown", "Friends of Charlottesville Downtown", "nonprofit", "https://www.downtowncharlottesville.com/", ["pedestrian mall", "dining and live scene"]],
  ["src-shen-caverns", "Shenandoah Caverns", "official", "https://shenandoahcaverns.com/", ["fall hours", "October 9 Fright Night"]],
  ["src-monticello", "Thomas Jefferson Foundation - Monticello", "official", "https://www.monticello.org/visit/hours", ["hours", "From Slavery to Freedom tour", "admission"]],
  ["src-jefferson-school", "Jefferson School African American Heritage Center", "official", "https://jeffschoolheritagecenter.org/", ["Saturday hours", "local Black history"]],
  ["src-kluge", "Kluge-Ruhe Aboriginal Art Collection", "official", "https://kluge-ruhe.org/plan-your-visit/", ["Tuesday-Sunday hours", "free tours", "collection scope"]],
  ["src-ix", "IX Art Park", "official", "https://www.ixartpark.org/", ["Saturday hours", "Looking Glass", "public art"]],
  ["src-morgan-wade", "Charlottesville Events Calendar", "tourism", "https://events.searchcharlottesville.com/cal?category=2351", ["Morgan Wade October 10 2026", "20:00 show"]],
  ["src-exchange", "Exchange Hotel Civil War Medical Museum", "official", "https://theexchangehotelmuseum.org/hours-of-operation", ["Saturday hours", "admission"]],
  ["src-transfiguration", "Transfiguration Greek Orthodox Church", "official", "https://www.transfiguration.va.goarch.org/", ["Sunday Orthros", "Divine Liturgy", "address"]],
  ["src-civil-war-medicine", "National Museum of Civil War Medicine", "official", "https://www.civilwarmed.org/nmcwm/plan/", ["Sunday hours", "admission", "museum scope"]],
  ["src-balls-bluff", "NOVA Parks - Ball's Bluff Battlefield", "government", "https://www.novaparks.com/parks/balls-bluff-battlefield", ["dawn-dusk access", "interpretive trail", "cemetery and bluff"]],
  ["src-burnside", "Historic Bethlehem Museums and Sites", "nonprofit", "https://www.historicbethlehem.org/visit-us/museums-sites/burnside-plantation/", ["dawn-dusk grounds", "Moravian farm history", "horse-power wheel"]],
  ["src-illicks", "Wildlands Conservancy - Monocacy Way", "nonprofit", "https://www.wildlandspa.org/preserve/monocacy-way/", ["mill and creek context", "public trail"]],
  ["src-fairfield", "Town of Newtown - Fairfield Hills", "government", "https://www.newtown-ct.gov/fairfield-hills-campus/pages/background-information", ["hospital-campus history", "architecture", "public reuse"]],
  ["src-fairfield-trails", "Town of Newtown - Start Walking", "government", "https://www.newtown-ct.gov/health-department/pages/start-walking", ["paved trails", "fruit trail", "public access"]],
  ["src-newtown-meeting", "Newtown Meeting House", "official", "https://www.newtownmeetinghouse.com/", ["historic meeting house", "visitor contact"]],
  ["src-mapparium", "Christian Science - Mapparium visitor information", "official", "https://www.christianscience.com/the-mother-church-in-boston/how-do-you-see-the-world-experience/how-do-you-see-the-world-visitor-information", ["Wednesday hours", "ticket price", "photography policy"]],
  ["src-worcester", "Worcester Art Museum", "official", "https://www.worcesterart.org/visit/", ["Wednesday hours", "admission", "arms and armor access"]],
  ["src-worcester-armor", "Worcester Art Museum - Arms and Armor", "official", "https://www.worcesterart.org/collection/arms-and-armor/", ["collection size", "new galleries"]],
  ["src-noaa-normals", "NOAA U.S. Climate Normals", "government", "https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals", ["1991-2020 normals methodology"]],
  ["src-osrm", "OSRM", "routing", "https://project-osrm.org/", ["road-network baselines", "no live traffic"]],
  ["src-forum-scranton", "r/Scranton local discussion", "forum", "https://www.reddit.com/r/Scranton/", ["local cross-check of coal mine and Steamtown"]],
  ["src-forum-lancaster", "r/lancaster local discussion", "forum", "https://www.reddit.com/r/lancaster/", ["local cross-check of market and non-tourist-trap stops"]],
  ["src-forum-shenandoah", "r/Shenandoah local discussion", "forum", "https://www.reddit.com/r/Shenandoah/", ["October crowd and early-start cross-check"]],
  ["src-forum-cville", "r/Charlottesville local discussion", "forum", "https://www.reddit.com/r/Charlottesville/", ["IX, Kluge-Ruhe and live-scene cross-check"]]
];
const sources = sourceRows.map(([id, title, source_type, url, claims]) => ({ id, title, source_type, url, verified_at: verifiedAt, claims }));

const H = (opens, closes, note, status = "verified-current") => ({ opens, closes, status, note });
const C = (amount, note = "Adult planning price; reconfirm before booking.", status = "verified-current") => ({ amount_per_person: amount, status, note });
const R = (day, replaces, variant, reason) => ({ day, replaces_place_ids: replaces, route_variant_id: variant, reason });
const bestFitNotes = {
  "wadsworth-atheneum": "Good for Viki's love of strong buildings, and for Stivka's interest in religious art. Gora can go deep on the history instead.",
  "holy-land-usa": "Good for Viki's photos and for Stivka, though this is a Catholic folk site, not an Orthodox one. We are clear about that.",
  "mark-twain-house": "Good for Viki's love of decorated interiors, and for Gora, who wants the real person behind the famous name.",
  "lackawanna-coal": "Good for Gora's history and for Viki's unusual spaces. It is cool underground, so bring a layer.",
  "steamtown": "Good for Gora's industrial history and Viki's photos of very large machines.",
  "scranton-iron": "Good for Viki's photos and for Gora's interest in industry. Short, free and easy for everyone.",
  "houdini-museum": "Good for Viki's love of strange places and Paco's group fun. Gora gets the real history behind the tricks.",
  "watch-clock": "Good for Gora's curiosity about how things work and Viki's eye for fine detail.",
  "lancaster-central-market": "Good for Viki's architecture and Paco's need for a stop where everyone picks their own food.",
  "lancaster-troll-market": "Good for Viki above all. Everyone else gets a short, funny stop between two heavy museums.",
  "wolf-sanctuary": "Good for Viki's animal photos and for Stivka's gentle side. Gora gets the science of how they live.",
  "ephrata-cloister": "Good for Stivka's interest in serious faith and for Gora's interest in unusual American communities. Viki gets very stark buildings.",
  "railroad-museum-pa": "Good for Gora's engineering interest and for Viki's very large interiors. No extra driving needed.",
  "eshelman-covered-bridge": "Good for Viki's picture. For everyone, it is a short and respectful stop rather than a staged one.",
  "harrisburg-riverfront": "Good for Viki's photos and for everyone's need to walk after a day of museums.",
  "turkey-hill-experience": "Good for Paco's group mood and Viki's creative side. Easy and fun for all four.",
  "pa-capitol": "Good for Viki's decorated architecture and Gora's political history. Free to enter.",
  "antietam": "Good for Gora's careful history. For Stivka and Viki it is a calm, serious place rather than a spectacle.",
  "harpers-lower-town": "Good for everyone: nature for Viki, engineering and John Brown history for Gora, and a strong sunset for all four.",
  "storer-college": "Good for Gora's search for the record underneath the tourist version. Stivka gets a story about faith and education.",
  "virginius-island": "Good for Viki's photos and for Gora's industrial evidence, with almost no climbing.",
  "seton-shrine": "Good for Stivka's faith. Gora gets the story of how a religious community was actually built and run.",
  "luray-caverns": "Good for Viki's surreal photos and for Gora's geology and acoustics. No hard walking.",
  "skyline-overlooks": "Good for Viki's landscapes. Keeping it short protects the driving limit and everyone's energy.",
  "stony-man": "Good for Gora, who wants to move. Short enough that it does not punish anyone else.",
  "charlottesville-downtown": "Good for Paco's flexible evening and Viki's browsing. Nobody is forced into a club.",
  "shenandoah-caverns-fright": "Good for Stivka and Gora if the mood is right. It replaces Skyline color and a quiet dinner, so it is a real trade.",
  "monticello": "Good for Gora's interest in the contradiction under the national story, and for Viki's architecture. Paco gets a real conversation for the group.",
  "jefferson-school": "Good for Gora and for the whole group as a corrective. Short, serious and close to dinner.",
  "kluge-ruhe": "Good for Viki's love of strong color and pattern, and for Gora's interest in Indigenous voices and land rights.",
  "ix-looking-glass": "Good for Viki above all, and for Paco's group energy. Everyone gets to move around and enjoy themselves.",
  "morgan-wade-jefferson": "Good for Stivka's rock side and Gora's interest in regional music. Viki gets a beautiful room.",
  "exchange-hotel": "Good for Gora when Monticello is fully booked or the group wants history without crowds.",
  "transfiguration-orthodox": "Good for Stivka above all, and shared ground for the whole group. We follow the parish and stay to the end.",
  "civil-war-medicine": "Good for Gora's evidence-first history. Everyone learns where modern emergency medicine came from.",
  "balls-bluff": "Good for Gora's interest in how myths get made, and for Viki's quiet autumn river view. Gentle walking for everyone.",
  "burnside-plantation": "Good for Gora's interest in old machinery and Stivka's Moravian history. It turns a long driving day into something real.",
  "illicks-mill": "Good for Viki's water and stone photos and for Gora's industrial detail. Short and restful.",
  "fairfield-hills": "Good for Viki's unusual architecture and Gora's interest in institutions. We visit it with respect.",
  "newtown-meeting-house": "Good for Viki's clean architecture and for Stivka's quiet stop. Gentle, and easy on everyone.",
  "mapparium": "Good for Viki's photos, Gora's interest in changing borders, and Stivka's feeling for unusual sacred spaces.",
  "worcester-arms-armor": "Good for Gora above all, and for Viki's dramatic display design. A solid backup if Boston traffic looks bad."
};

const S = (id, name, kind, city, state, date, summary, why_go, best_for, secondary_for, categories, duration_minutes, source_ids, hours, cost, priority = "anchor", reservation = "none", replacement = null) => ({
  id, name, kind, city, state, visit_date: date, summary, why_go, best_for, secondary_for,
  best_fit_note: bestFitNotes[id] || `Best for ${best_for.join(" and ")}: ${why_go}`,
  categories, duration_minutes, source_ids, reservation, hours, cost, priority,
  ...(replacement ? { replacement_reason: replacement.reason, replacement } : {}), address: name
});

const seedPlaces = [
  S("wadsworth-atheneum", "Wadsworth Atheneum Museum of Art", "castle-art-museum", "Hartford", "CT", "2026-10-04", "A museum that looks like a Gothic castle from outside. Inside, five joined buildings hold American, European and modern art, together with cabinets of stranger objects.", "A castle full of art, where the next room is never what you expect. Everyone can follow their own thread through it.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "unusual_creative", "hidden_history_folklore"], 90, ["src-wadsworth"], H("10:00", "17:00", "Sunday open; last entry 16:30 and advance reservation is suggested, not required."), C(22), "anchor", "reserve-recommended"),
  S("holy-land-usa", "Holy Land USA & Stations Trail", "folk-religious-landscape", "Waterbury", "CT", "2026-10-04", "A hillside above Waterbury covered with small hand-built models of biblical places. There is a giant lit cross and a new prayer trail with the Stations of the Cross. Volunteers rebuilt it all.", "Nobody expects this. A whole miniature Holy Land built by hand on a hill, strange and sincere at the same time.", ["stivka", "viki"], ["gora", "sheluvspaco"], ["orthodox_spiritual", "architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 60, ["src-holy-land", "src-holy-land-events"], H(null, null, "Open for self-guided public exploration in daylight only; steep and uneven ground, limited parking, and no after-sunset access.", "verified-public-space"), C(0, "Free public site; donation optional."), "anchor"),
  S("mark-twain-house", "The Mark Twain House & Museum", "gothic-writer-house", "Hartford", "CT", "2026-10-04", "Mark Twain's 25-room red brick house, full of carved wood and patterned walls. He wrote several of his major books in the billiard room upstairs.", "One writer's house, one guided story, and the room where the books were actually written. More personal than a huge museum.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "unusual_creative"], 90, ["src-mark-twain"], H("09:30", "17:00", "Open seven days in October with last house tour currently listed at 16:15; timed guided tour is required and can sell out."), C(29, "Planning estimate; choose an available timed house tour.", "estimate"), "replacement", "reserve", R(1, ["wadsworth-atheneum"], "replacement-d1-mark-twain", "A tighter human story and more theatrical interior when the group wants a guided house rather than a broad museum.")),
  S("lackawanna-coal", "Lackawanna Coal Mine Tour", "underground-industry", "Scranton", "PA", "2026-10-05", "A guided trip about 300 feet down into a real anthracite coal mine, walking the tunnels with guides who know the working history.", "You go down inside a real mine. This is the honest, uncomfortable labor history at the center of the whole route.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "unusual_creative"], 105, ["src-lackawanna"], H("10:00", "16:00", "Monday open in the 2026 pattern; last tour 14:30 and arrive by 14:00."), C(12), "anchor", "walk-up-early"),
  S("steamtown", "Steamtown National Historic Site", "rail-industry", "Scranton", "PA", "2026-10-05", "A working railway roundhouse with a turntable and a collection of steam locomotives, on the yards that made Scranton a rail city.", "Huge machines, a working turntable, and the story of the people who ran them. The scale alone is worth the stop.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic"], 100, ["src-steamtown"], H("09:30", "17:00", "Regular season includes Monday October 5."), C(0, "Park admission is free; special rides cost extra."), "anchor"),
  S("scranton-iron", "Scranton Iron Furnaces", "industrial-ruins", "Scranton", "PA", "2026-10-05", "Four huge stone blast furnace stacks still stand beside the city, left from the Lackawanna iron works.", "Four giant stone ruins in the middle of a city, free to walk around, and best in evening light.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore"], 35, ["src-scranton-iron"], H(null, null, "Grounds open dawn to dusk.", "verified-public-space"), C(0), "supporting"),
  S("houdini-museum", "Houdini Museum", "magic-cabinet", "Scranton", "PA", "2026-10-05", "A small and deliberately odd collection of Harry Houdini objects in an old Scranton building, shown with live magic.", "A personal, slightly chaotic museum with a live magic show. Much more intimate than the rail yard.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "hidden_history_folklore"], 150, ["src-houdini"], H(null, null, "Year-round but date and show time require a direct phone confirmation.", "call-to-confirm"), C(25, "Planning estimate until direct confirmation.", "estimate"), "replacement", "call", R(2, ["steamtown", "scranton-iron"], "replacement-d2-houdini", "Use when weather is poor or the group wants one concentrated oddity instead of two industrial sites.")),
  S("watch-clock", "National Watch & Clock Museum", "time-machine-museum", "Columbia", "PA", "2026-10-06", "Thousands of clocks and watches show how people learned to measure time, from huge tower clocks down to tiny precision watches.", "A whole museum about measuring time, from tower clocks to watches you could lose in your hand.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["unusual_creative", "hidden_history_folklore"], 100, ["src-watch-clock"], H("10:00", "17:00", "Tuesday in the September 7-November 30 fall schedule."), C(15), "anchor"),
  S("lancaster-central-market", "Lancaster Central Market", "historic-food-hall", "Lancaster", "PA", "2026-10-06", "A market hall from 1889 in heavy Romanesque style, still working as the center of a real regional food economy.", "Lunch inside a beautiful old market hall, with real local food rather than a tourist version of it.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["food_cafes", "architecture_nature_photogenic", "local_culture"], 75, ["src-central-market"], H("06:00", "15:00", "Tuesday market day; arrive before 14:00 for full vendor choice."), C(18, "Flexible lunch allowance.", "estimate"), "anchor"),
  S("lancaster-troll-market", "Lancaster Troll Market", "curiosity-shop", "Lancaster", "PA", "2026-10-06", "A small shop full of fantasy and folklore objects: specimens, oddities and handmade things.", "A strange little shop full of things you will not find anywhere else. A deliberate break from serious history.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "shopping_outlets", "hidden_history_folklore"], 55, ["src-troll-market"], H("11:00", "18:00", "Tuesday open."), C(0, "Browsing is free; shopping excluded."), "supporting"),
  S("wolf-sanctuary", "Wolf Sanctuary of Pennsylvania", "wildlife-sanctuary", "Lititz", "PA", "2026-10-06", "A booked walk among rescued wolves and wolf-dogs, with guides who explain their behavior and how they are cared for.", "Real wolves, a few feet away, with people who know them. You must book ahead.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "unusual_creative"], 90, ["src-wolves"], H("10:00", "11:30", "Tuesday public tour begins at 10:00; reservation required."), C(25), "replacement", "reserve", R(3, ["watch-clock"], "replacement-d3-wolves", "Trade precision machines for a high-emotion wildlife encounter; requires an early Scranton departure.")),
  S("ephrata-cloister", "Ephrata Cloister", "radical-religious-settlement", "Ephrata", "PA", "2026-10-07", "Plain timber buildings from an 18th-century German religious community that lived without marriage and organized its life around music, printing and hard work.", "A community that chose silence, singing and celibacy, and built the plain wooden houses to match.", ["stivka", "gora"], ["viki", "sheluvspaco"], ["orthodox_spiritual", "hidden_history_folklore", "architecture_nature_photogenic"], 100, ["src-ephrata"], H("09:00", "16:00", "Wednesday open under the current schedule."), C(10), "anchor"),
  S("railroad-museum-pa", "Railroad Museum of Pennsylvania", "rail-mega-museum", "Strasburg", "PA", "2026-10-07", "A hall the size of a cathedral, full of locomotives and railway carriages. It covers both the engineering and the working conditions behind it.", "Standing next to a steam locomotive indoors tells you more about its size than any photograph.", ["gora", "viki"], ["sheluvspaco", "stivka"], ["hidden_history_folklore", "architecture_nature_photogenic"], 120, ["src-railroad-pa"], H("10:00", "16:00", "Wednesday open."), C(10), "anchor"),
  S("eshelman-covered-bridge", "Eshelman's Mill Covered Bridge", "covered-bridge", "Paradise", "PA", "2026-10-07", "A working one-lane covered bridge over Pequea Creek, reached on quiet back roads rather than a tourist strip.", "The classic Lancaster County photo, on a real road, away from the places that sell Amish life as a show.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "local_culture"], 30, ["src-covered-bridges"], H(null, null, "Public road; park only where legal and never block local traffic.", "public-road"), C(0), "supporting"),
  S("harrisburg-riverfront", "Harrisburg Riverfront & Walnut Street Bridge", "riverfront-blue-hour", "Harrisburg", "PA", "2026-10-07", "A long park along the Susquehanna River facing City Island, with the broken remains of the 1890 Walnut Street truss bridge standing in the water.", "A half-collapsed iron bridge standing in a wide river at golden hour. Calm, free and very photogenic.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "quiet_reset"], 65, ["src-harrisburg-river"], H(null, null, "Outdoor park; use daylight and normal city awareness.", "public-space"), C(0), "supporting"),
  S("turkey-hill-experience", "Turkey Hill Experience", "food-lab", "Columbia", "PA", "2026-10-07", "A hands-on brand museum where you design your own ice cream flavor and packaging, with an optional lab where you make some.", "You invent an ice cream and then eat it. A light, social break when everyone is tired of museums.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "food_cafes"], 120, ["src-turkey-hill"], H("10:00", "16:00", "Reconfirm exact October 7 entry windows."), C(25, "Experience plus lab planning allowance.", "estimate"), "replacement", "reserve-lab", R(4, ["railroad-museum-pa", "eshelman-covered-bridge"], "replacement-d4-turkey-hill", "Swap trains and bridge for an interactive flavor-making afternoon in poor weather.")),
  S("pa-capitol", "Pennsylvania State Capitol", "civic-palace", "Harrisburg", "PA", "2026-10-08", "A Beaux-Arts parliament building whose inside is far richer than the outside suggests: a tiled dome, huge staircases and painted murals.", "From outside it looks ordinary. Inside there is a tiled dome and a staircase copied from the Paris Opera.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore"], 75, ["src-pa-capitol"], H("07:00", "18:00", "Weekday public access; reserve or join a morning guided tour."), C(0), "anchor", "reserve-tour"),
  S("antietam", "Antietam National Battlefield", "battlefield-landscape", "Sharpsburg", "MD", "2026-10-08", "Quiet farm fields, lanes and a stone bridge hold the record of the bloodiest single day in American history.", "The landscape is peaceful now, and that is exactly what makes it hard. Nothing here is dramatized.", ["gora", "stivka"], ["viki", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic", "quiet_reset"], 110, ["src-antietam"], H("09:00", "17:00", "Visitor center open daily; battlefield roads remain daylight-dependent."), C(15, "Private vehicle pass planning amount."), "anchor"),
  S("harpers-lower-town", "Harpers Ferry Lower Town & The Point", "confluence-history", "Harpers Ferry", "WV", "2026-10-08", "Steep brick streets run down to the point where the Potomac and Shenandoah rivers meet, under railway bridges and steep mountain walls.", "Two rivers meet between mountains, with a whole old town on the slope above. One of the best views of the trip.", ["viki", "gora", "stivka"], ["sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore"], 95, ["src-harpers-hours"], H("09:00", "17:00", "Most staffed museums 09:00-17:00; park and shuttle from the visitor center."), C(20, "Vehicle pass; confirm current fee."), "anchor"),
  S("storer-college", "Storer College & Camp Hill", "education-freedom-site", "Harpers Ferry", "WV", "2026-10-08", "On the hill above the town stand the remains of a college founded after the Civil War to educate people who had been enslaved. An early Niagara Movement meeting was held here.", "The postcard town is below; the harder and more important story is up on this hill. It deserves real time.", ["gora", "stivka"], ["viki", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic"], 45, ["src-harpers-hours"], H(null, null, "Outdoor Camp Hill walk; daylight."), C(0), "supporting"),
  S("virginius-island", "Virginius Island Ruins Trail", "industrial-ruins-trail", "Harpers Ferry", "WV", "2026-10-08", "An easy riverside path leads through the ruins of mills, canals, turbine pits and a rifle works, now overgrown by forest.", "Industrial ruins being slowly eaten by the forest, on a flat and easy path. Beautiful and unsettling at once.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore"], 55, ["src-harpers-trails"], H(null, null, "Daylight only; up to 2 miles round trip but use the compact 1-mile ruins loop."), C(0), "supporting"),
  S("seton-shrine", "National Shrine of Saint Elizabeth Ann Seton", "saint-history-shrine", "Emmitsburg", "MD", "2026-10-08", "A basilica, a museum and historic houses tell the story of Elizabeth Ann Seton, the first American-born Catholic saint, and the community she founded.", "A serious place of pilgrimage rather than another battlefield. It is Catholic, not Orthodox, and we say so plainly.", ["stivka", "viki"], ["gora", "sheluvspaco"], ["orthodox_spiritual", "architecture_nature_photogenic", "hidden_history_folklore"], 90, ["src-seton"], H("10:00", "17:00", "Daily; museum, basilica and historic areas have separate access patterns."), C(12, "Planning admission; basilica prayer access may be free."), "replacement", "none", R(5, ["antietam"], "replacement-d5-seton", "Choose saint history and architecture over a second battlefield; explicitly Catholic, not an Orthodox service.")),
  S("luray-caverns", "Luray Caverns", "show-cave", "Luray", "VA", "2026-10-09", "Enormous underground chambers, a mirror-still pool called Dream Lake, and an organ that plays by striking the rock formations themselves.", "An instrument that plays the cave. The chambers are the most theatrical underground space on the whole trip.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "unusual_creative"], 110, ["src-luray"], H("09:00", "18:00", "Daily after Labor Day through October 31."), C(36), "anchor"),
  S("skyline-overlooks", "Skyline Drive Overlook Sequence", "scenic-drive", "Shenandoah National Park", "VA", "2026-10-09", "A short section of Skyline Drive between Thornton Gap and Stony Man, stopping at viewpoints rather than driving the full 105 miles.", "The Blue Ridge in layers, from the car, at the best time of year for color. Short by design.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "quiet_reset"], 60, ["src-skyline"], H(null, null, "Road generally open 24/7 but weather can close it without notice."), C(30, "Shenandoah private-vehicle pass; shared across park stops."), "supporting"),
  S("stony-man", "Stony Man Summit", "short-summit-hike", "Shenandoah National Park", "VA", "2026-10-09", "A walk of about 1.6 miles reaches one of the widest views in Shenandoah National Park.", "One of the biggest views in the park for a short and gentle walk. This is one of only two real walks on the route.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "athletic_adrenaline"], 80, ["src-stony-man"], H(null, null, "Daylight trail; avoid wet rock and crowded edges."), C(0, "Covered by park pass."), "supporting"),
  S("charlottesville-downtown", "Charlottesville Downtown Mall", "pedestrian-social-district", "Charlottesville", "VA", "2026-10-09", "A long brick street closed to cars, lined with independent restaurants, theaters, terraces and shops.", "Dinner where everyone chooses for themselves, outdoors, with no fixed plan after a day in the mountains.", ["sheluvspaco", "viki"], ["gora", "stivka"], ["social_nightlife_live", "food_cafes", "architecture_nature_photogenic"], 150, ["src-cville-downtown"], H(null, null, "Public district; venue hours vary."), C(45, "Dinner allowance only; nightlife excluded."), "anchor"),
  S("shenandoah-caverns-fright", "Shenandoah Caverns + American Fright Night", "cavern-night-event", "Quicksburg", "VA", "2026-10-09", "A quieter commercial cave that becomes a theatrical horror experience on this exact Friday night.", "A cave turned into a haunted attraction, on one specific night. Only worth it if the group wants that instead of a calm evening.", ["viki", "gora"], ["sheluvspaco", "stivka"], ["unusual_creative", "social_nightlife_live"], 160, ["src-shen-caverns"], H("09:00", "21:30", "Cavern last regular tour 16:00; Fright Night October 9 runs approximately 18:30-21:30."), C(35, "Combined planning estimate; confirm event ticket."), "replacement", "reserve", R(6, ["luray-caverns", "skyline-overlooks", "stony-man"], "replacement-d6-shenandoah-fright", "Exact-date spooky alternative; it creates a late Charlottesville arrival and replaces the whole daylight mountain program.")),
  S("monticello", "Monticello - From Slavery to Freedom", "truth-centered-historic-house", "Charlottesville", "VA", "2026-10-10", "Thomas Jefferson's famous house, visited on a tour that centers on the lives, work and resistance of the people he enslaved there.", "The famous building, told through the people who were owned on the same ground. It is a harder and better visit than the usual one.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic"], 150, ["src-monticello"], H("08:30", "17:30", "Hours vary by date; reserve the morning From Slavery to Freedom product."), C(42), "anchor", "reserve"),
  S("jefferson-school", "Jefferson School African American Heritage Center", "community-history-center", "Charlottesville", "VA", "2026-10-10", "A former segregated school, now a center telling Charlottesville's Black history through exhibitions put together by the community itself.", "Monticello should not be the last word. This is the same history told by the city that still lives with it.", ["gora", "stivka"], ["viki", "sheluvspaco"], ["hidden_history_folklore", "local_culture"], 65, ["src-jefferson-school"], H("10:00", "13:00", "Saturday only; protect this narrow window."), C(10, "Suggested admission/donation planning amount."), "anchor"),
  S("kluge-ruhe", "Kluge-Ruhe Aboriginal Art Collection", "indigenous-art-museum", "Charlottesville", "VA", "2026-10-10", "The only museum outside Australia devoted to Aboriginal Australian art. It is small, but nothing else like it exists in America.", "Bold, ancient and contemporary art from the other side of the world, in a small university museum in Virginia.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["unusual_creative", "hidden_history_folklore"], 75, ["src-kluge"], H("10:00", "16:00", "Saturday; free tours at 10:30 and 13:30, reservation encouraged."), C(0), "anchor", "reserve-tour-optional"),
  S("ix-looking-glass", "IX Art Park & The Looking Glass", "immersive-art-playground", "Charlottesville", "VA", "2026-10-10", "Murals and outdoor installations surround an indoor art space full of mirrors, color and things to walk through.", "The biggest pure visual hit of the day, and a chance to play rather than read labels before the concert.", ["viki", "sheluvspaco"], ["gora", "stivka"], ["unusual_creative", "architecture_nature_photogenic"], 105, ["src-ix"], H("10:00", "18:00", "Saturday Looking Glass hours; outdoor art remains visible outside ticketed time."), C(20, "Planning ticket amount."), "anchor"),
  S("morgan-wade-jefferson", "Morgan Wade at The Jefferson Theater", "live-music-night", "Charlottesville", "VA", "2026-10-10", "The Virginia singer Morgan Wade, whose songs sit between country and rock, plays an ornate theatre from 1912 on this exact Saturday night.", "A real local artist in a beautiful old theatre, on the night we are there. Not a generic club.", ["stivka", "gora"], ["viki", "sheluvspaco"], ["social_nightlife_live", "architecture_nature_photogenic"], 150, ["src-morgan-wade"], H("20:00", "22:30", "Exact October 10 listing; doors and final ticket terms must be confirmed."), C(55, "Ticket planning estimate; nightlife spend excluded.", "estimate"), "anchor", "book-when-on-sale"),
  S("exchange-hotel", "Exchange Hotel Civil War Medical Museum", "field-hospital-museum", "Gordonsville", "VA", "2026-10-10", "A former railway hotel that became a Civil War receiving hospital. The medical rooms, the graffiti on the walls, and the human cost are all still there.", "A hospital where the wounded actually arrived, with their marks still on the walls. Small, dark and very direct.", ["gora", "stivka"], ["viki", "sheluvspaco"], ["hidden_history_folklore", "unusual_creative"], 120, ["src-exchange"], H("10:00", "16:00", "Saturday open."), C(16), "replacement", "none", R(7, ["monticello", "jefferson-school"], "replacement-d7-exchange-hotel", "Trade the two-city history anchors for a compact, eerie field-hospital story; preserve Kluge, IX and the concert.")),
  S("transfiguration-orthodox", "Transfiguration Greek Orthodox Church", "orthodox-sunday", "Charlottesville", "VA", "2026-10-11", "A real parish Sunday: Orthros and then the Divine Liturgy. We attend the service, we do not tour the building.", "Sunday stays a real Sunday before the long drive north, and all four of us share it.", ["stivka", "sheluvspaco", "viki", "gora"], [], ["orthodox_spiritual", "local_culture"], 150, ["src-transfiguration"], H("09:00", "11:30", "Current Sunday pattern is Orthros 09:00 and Divine Liturgy 10:00; reconfirm October calendar and contact parish about visitor etiquette."), C(0, "Free worship; discreet donation optional."), "anchor", "reconfirm-parish-calendar"),
  S("civil-war-medicine", "National Museum of Civil War Medicine", "medical-history-museum", "Frederick", "MD", "2026-10-11", "A focused museum about battlefield medicine: how the wounded were sorted and moved, how anesthesia was used, and which myths about it are wrong.", "Most of what people believe about Civil War surgery is wrong, and this museum says so with evidence.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "unusual_creative"], 105, ["src-civil-war-medicine"], H("11:00", "17:00", "Sunday open; protect a 15:15 latest arrival."), C(15), "anchor"),
  S("balls-bluff", "Ball's Bluff Battlefield & National Cemetery", "river-bluff-history-trail", "Leesburg", "VA", "2026-10-11", "A one-mile woodland loop reaches a tiny national cemetery and the steep bluff above the Potomac. Bad information, makeshift boats and confused orders turned a small 1861 movement into a disaster.", "A small battle that went wrong in every possible way, on a quiet walk above the river. A good way to move after church.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic", "quiet_reset"], 90, ["src-balls-bluff"], H(null, null, "Park open dawn-dusk. The free Sunday tours are at 11:00 and 13:00, but this route arrives later and uses the official self-guided trail; terrain is moderately difficult."), C(0, "Free regional park."), "replacement", "none", R(8, ["civil-war-medicine"], "replacement-d8-balls-bluff", "Choose one evidence-rich outdoor story and Potomac overlook when the group needs air after church instead of another museum.")),
  S("burnside-plantation", "Burnside Plantation", "moravian-farm-landscape", "Bethlehem", "PA", "2026-10-12", "A farm inside the city, with an 18th-century Moravian farmhouse, bank barns, an old orchard and one of the few surviving large horse-powered wheels in America.", "A working 18th-century farm still standing inside a modern city, open from dawn to dusk and free to walk.", ["stivka", "gora"], ["viki", "sheluvspaco"], ["orthodox_spiritual", "hidden_history_folklore", "architecture_nature_photogenic", "quiet_reset"], 100, ["src-burnside"], H(null, null, "Grounds open dawn-dusk; buildings open only for events or prearranged tours."), C(0), "anchor"),
  S("illicks-mill", "Illick's Mill & Monocacy Creek", "mill-trail", "Bethlehem", "PA", "2026-10-12", "A stone mill and a creek corridor with a fish passage, hidden inside modern Bethlehem beside a small green walkway.", "Moving water, stone and old industry in a short walk. Less to see than the farm, but easier and quieter.", ["viki", "stivka"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "quiet_reset", "hidden_history_folklore"], 65, ["src-illicks"], H(null, null, "Outdoor trail in daylight; mill interior is not promised."), C(0), "replacement", "none", R(9, ["burnside-plantation"], "replacement-d9-illicks-mill", "A shorter creek-and-mill reset on the same Bethlehem edge; no interior promise.")),
  S("fairfield-hills", "Fairfield Hills Adaptive-Reuse Campus", "institutional-reuse-landscape", "Newtown", "CT", "2026-10-13", "A 1930s state psychiatric hospital campus, now partly reused as public space, with wide lawns, heavy brick buildings and walking trails.", "Enormous institutional buildings on open lawns, being slowly given back to the town. We treat it as public space, not as a haunted attraction.", ["viki", "gora"], ["stivka", "sheluvspaco"], ["architecture_nature_photogenic", "hidden_history_folklore", "quiet_reset"], 95, ["src-fairfield", "src-fairfield-trails"], H("08:00", "18:00", "Public campus trails generally open 08:00-18:00; abandoned buildings are not open for entry."), C(0), "anchor"),
  S("newtown-meeting-house", "Newtown Meeting House & Flagpole", "meeting-house-streetscape", "Newtown", "CT", "2026-10-13", "A white meeting house on a hill facing Newtown's well-known flagpole in the middle of the road, in a preserved town center.", "A calm, handsome town center if the old hospital feels too heavy at the end of a long drive.", ["stivka", "viki"], ["gora", "sheluvspaco"], ["architecture_nature_photogenic", "orthodox_spiritual", "quiet_reset"], 55, ["src-newtown-meeting"], H(null, null, "Exterior and town-center walk; interior requires event or direct confirmation."), C(0), "replacement", "none", R(10, ["fairfield-hills"], "replacement-d10-newtown-meeting", "Choose a calm meeting-house streetscape instead of institutional history; bed-to-bed driving is effectively unchanged.")),
  S("mapparium", "Mapparium Globe", "immersive-stained-glass-map", "Boston", "MA", "2026-10-14", "A walkway passes through the inside of a three-story stained-glass globe showing the world as it was mapped in 1935. The sound behaves very strangely inside it.", "You walk inside the world. The glass shows borders that no longer exist, and a whisper carries right across the room.", ["viki", "gora", "stivka"], ["sheluvspaco"], ["architecture_nature_photogenic", "unusual_creative", "hidden_history_folklore"], 80, ["src-mapparium"], H("10:00", "17:00", "Wednesday open; last tour 16:40. Photography is permitted only after the presentation under the venue policy."), C(6), "anchor", "reserve"),
  S("worcester-arms-armor", "Worcester Art Museum - Arms & Armor Galleries", "global-armor-gallery", "Worcester", "MA", "2026-10-14", "New galleries hold more than a thousand pieces of armor from the Higgins collection: European, Japanese and other traditions, with parts you can handle.", "A thousand pieces of real armor, some of which you can pick up. The best possible last stop for Gora.", ["gora", "viki"], ["stivka", "sheluvspaco"], ["hidden_history_folklore", "architecture_nature_photogenic", "unusual_creative"], 120, ["src-worcester", "src-worcester-armor"], H("10:00", "16:00", "Wednesday open; as of February 2026 timed armor reservations are no longer required."), C(22), "replacement", "none", R(11, ["mapparium"], "replacement-d11-worcester-armor", "Use the easier I-84/I-90 stop when Boston traffic or Mapparium tickets threaten the protected Logan return."))
];

const dayPlans = [
  { day: 1, date: "2026-10-04", sleep_city: "Danbury, CT", theme: "A Gothic art castle, then a living hill of handmade biblical miniatures", schedule: [["14:15", "15:45", "wadsworth-atheneum", "anchor"], ["16:25", "17:25", "holy-land-usa", "anchor"]], lodging: ["Danbury west side near I-84 with staffed reception, interior corridors and two-car parking", "Danbury Fair/West Street only with strong recent cleanliness reviews and the exact one-bed plus two-bed inventory"], fallback: "This is a live-traffic-gated departure. If the cars leave Boston after 12:15, protect daylight at Holy Land and shorten or cut the Wadsworth; the reserved Mark Twain tour replaces the Wadsworth only, never the driving buffer." },
  { day: 2, date: "2026-10-05", sleep_city: "Scranton, PA", theme: "Three hundred feet down, then steam and blast-furnace ruins", schedule: [["10:45", "12:30", "lackawanna-coal", "anchor"], ["13:10", "14:50", "steamtown", "anchor"], ["15:05", "15:40", "scranton-iron", "supporting"]], lodging: ["Scranton downtown near Steamtown with well-lit parking", "Montage Mountain corridor for stronger two-room inventory"], fallback: "Coal last-tour arrival controls the day; promote Houdini only after a direct call, and cut the furnaces first if live traffic consumes the buffer." },
  { day: 3, date: "2026-10-06", sleep_city: "Lancaster, PA", theme: "Mechanical time, a real market lunch and one room of folklore weirdness", schedule: [["10:25", "12:05", "watch-clock", "anchor"], ["13:00", "14:15", "lancaster-central-market", "anchor"], ["14:25", "15:20", "lancaster-troll-market", "supporting"]], lodging: ["Lancaster central business district within walking distance of dinner", "Manheim Township only with safe parking and a clearly cleaner two-room option"], fallback: "The market closes at 15:00; if the 10:00 wolf tour is booked, it replaces the clock museum and requires a 07:15 departure." },
  { day: 4, date: "2026-10-07", sleep_city: "Harrisburg, PA", theme: "A radical religious settlement, giant locomotives and one honest covered bridge", schedule: [["09:00", "10:35", "ephrata-cloister", "anchor"], ["11:20", "13:20", "railroad-museum-pa", "anchor"], ["13:35", "14:05", "eshelman-covered-bridge", "supporting"], ["16:15", "17:20", "harrisburg-riverfront", "supporting"]], lodging: ["Harrisburg downtown or riverfront with staffed garage", "Camp Hill only if secure parking and room configuration are materially better"], fallback: "Promote Turkey Hill for rain or museum fatigue; never stop in the bridge travel lane and cut it entirely in unsafe traffic." },
  { day: 5, date: "2026-10-08", sleep_city: "Winchester, VA", theme: "A civic palace, battlefield silence and the hidden Harpers Ferry above and below the postcard", schedule: [["08:45", "10:00", "pa-capitol", "anchor"], ["11:55", "13:45", "antietam", "anchor"], ["14:35", "16:10", "harpers-lower-town", "anchor"], ["16:10", "16:55", "storer-college", "supporting"], ["16:55", "17:50", "virginius-island", "supporting"]], lodging: ["Winchester Old Town edge with onsite two-car parking", "I-81 east side only with strong recent cleanliness and safety reviews"], fallback: "This is a near-cap day: use the visitor-center shuttle, choose either Storer or Virginius if live ETA slips, and promote Seton instead of Antietam only when the group wants the spiritual route." },
  { day: 6, date: "2026-10-09", sleep_city: "Charlottesville, VA", theme: "Mirror lakes underground, Blue Ridge layers above and a flexible brick-mall evening", schedule: [["09:00", "10:50", "luray-caverns", "anchor"], ["11:45", "12:45", "skyline-overlooks", "supporting"], ["12:50", "14:10", "stony-man", "supporting"], ["17:30", "20:00", "charlottesville-downtown", "anchor"]], lodging: ["Charlottesville downtown/West Main with secure parking and walkable dinner", "Pantops only if two-room inventory is cleaner and the Saturday schedule remains easy"], fallback: "Skyline weather decides the mountain sequence; Fright Night is an all-or-nothing exact-date replacement and creates a late arrival, not an extra stop." },
  { day: 7, date: "2026-10-10", sleep_city: "Charlottesville, VA", theme: "The contradiction at Monticello, Black Charlottesville, Indigenous Australian art and a real Virginia rock night", schedule: [["08:30", "11:00", "monticello", "anchor"], ["11:25", "12:30", "jefferson-school", "anchor"], ["13:30", "14:45", "kluge-ruhe", "anchor"], ["15:10", "16:55", "ix-looking-glass", "anchor"], ["20:00", "22:30", "morgan-wade-jefferson", "anchor"]], lodging: ["Same Charlottesville hotel; no room move", "Same Pantops fallback if chosen Friday"], fallback: "Jefferson School closes at 13:00; protect it. Exchange Hotel can replace the two history anchors, but never add it on top of this already full concert day." },
  { day: 8, date: "2026-10-11", sleep_city: "Frederick, MD", theme: "Orthodox Sunday, then the real mechanics of Civil War medicine", schedule: [["09:00", "11:30", "transfiguration-orthodox", "anchor"], ["14:45", "16:30", "civil-war-medicine", "anchor"]], lodging: ["Historic Frederick edge near Carroll Creek with staffed reception", "North Frederick near US-15 only if parking and two-room stock are stronger"], fallback: "Reconfirm parish calendar and visitor etiquette. Ball's Bluff is the outdoor evidence-and-river replacement; its guided tours occur too early for this sequence, so use the official self-guided loop. The Emmitsburg shrines were rejected because they push the bed-to-bed route beyond the cap." },
  { day: 9, date: "2026-10-12", sleep_city: "Bethlehem, PA", theme: "A protected northbound push ending at an outdoor Moravian farm machine", schedule: [["12:30", "14:10", "burnside-plantation", "anchor"]], lodging: ["Burnside/Lehigh Valley airport side of Bethlehem to preserve both adjacent drive caps", "West Bethlehem only; downtown/SteelStacks shifts the next day beyond the hard cap"], fallback: "This is a live-traffic-gated drive day. Burnside buildings are not promised; use Illick's Mill only as the nearby outdoor replacement and do not add central Bethlehem." },
  { day: 10, date: "2026-10-13", sleep_city: "Newtown, CT", theme: "A deliberate transit day ending in respectful institutional reuse and meadow trails", schedule: [["13:30", "15:05", "fairfield-hills", "anchor"]], lodging: ["Newtown/Fairfield Hills or the closest clean two-room property on the Danbury-east edge", "Southbury only if the morning live ETA proves the extra distance still stays below 210 minutes"], fallback: "Leave by 08:30 and take a real highway meal break. The Meeting House is the softer destination replacement; no abandoned-building entry or ghost-tour framing." },
  { day: 11, date: "2026-10-14", sleep_city: "Boston, MA", theme: "Walk through the world of 1935, return both cars and protect the airport night", schedule: [["10:30", "11:50", "mapparium", "anchor"]], lodging: ["Logan airport hotel with confirmed early shuttle", "East Boston or Revere only with a verified airport transfer and completed car return"], fallback: "Worcester's new armor galleries are the strongest traffic-resilient replacement. Return cars by 14:30; Boston sightseeing beyond the one finale is intentionally excluded." }
];

function personFit(record, person) { if (record.best_for.includes(person)) return 5; if (record.secondary_for.includes(person)) return 4; return person === "sheluvspaco" ? 3.8 : 3.5; }
function scheduleItem([start, end, place_id, priority], placeById) { const r = placeById.get(place_id); if (!r) throw new Error(`Unknown scheduled place ${place_id}`); return { start, end, place_id, priority, reservation: r.reservation }; }

async function main() {
  await buildEnergyRoute05({ root: ROOT, routeDir: ROUTE_DIR });
  return;

  // Legacy Route 05 builder retained below as historical implementation context.
  const [research, weather, geometry, replacements] = await Promise.all([
    readFile(path.join(ROUTE_DIR, "research-raw.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "weather-normals.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "route-geometry.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROUTE_DIR, "replacement-geometry.json"), "utf8").then(JSON.parse)
  ]);
  const replacementGeometryById = new Map(replacements.variants.map((v) => [v.id, v]));
  const images = [];
  const productionPlaces = seedPlaces.map((record) => {
    const raw = research.places[record.id];
    const coordinates = manualCoordinates[record.id] || (raw?.selected_coordinate ? [raw.selected_coordinate.longitude, raw.selected_coordinate.latitude] : null);
    if (!coordinates) throw new Error(`Missing coordinates for ${record.id}`);
    const imageIds = (raw?.selected_images || []).slice(0, 8).map((item, index) => {
      const id = `img-${record.id}-${index + 1}`;
      images.push({ id, place_id: record.id, title: item.title, description: item.description, search_query: item.search_query, local_path: item.local_path, source_page: item.source_page, source_file_url: item.original_url, creator: item.creator || "Unknown", credit: item.credit || "", license: item.license || "Unknown", license_url: item.license_url, alt: item.description || `${record.name} photograph`, coverage: contextualImagePlaces.has(record.id) ? "place-or-local-context" : "exact-place-or-experience", production_usable: item.production_usable ?? item.license !== "Unknown", rights_status: item.rights_status || "commons-license-recorded", visual_review: item.review_status === "reviewed" ? "reviewed" : "pending-final-review" });
      return id;
    });
    const routeVariant = record.replacement ? replacementGeometryById.get(record.replacement.route_variant_id) : null;
    return { ...record, country: "US", coordinates, coordinate_order: "longitude_latitude", coordinate_source: "manual_verified_address", image_ids: imageIds, ratings: { traveler_ratings: Object.fromEntries(PEOPLE.map((p) => [p, null])), average: null, rating_count: 0 }, researcher_person_fit: Object.fromEntries(PEOPLE.map((p) => [p, personFit(record, p)])), included_in_magic_score: record.priority !== "replacement", replacement: record.replacement ? { ...record.replacement, route_variant: routeVariant } : undefined, data_status: imageIds.length >= 3 ? "complete" : "image-gap" };
  });
  const placeById = new Map(productionPlaces.map((r) => [r.id, r]));
  const weatherByDay = new Map(weather.days.map((d) => [d.day, d]));
  const geometryByDay = new Map(geometry.days.map((d) => [d.day, d]));
  const comfort = [4.0, 3.7, 3.8, 4.2, 3.4, 3.5, 4.6, 3.8, 2.8, 2.7, 3.4];
  const days = dayPlans.map((plan) => {
    const routed = geometryByDay.get(plan.day), normal = weatherByDay.get(plan.day);
    const capStatus = routed.baseline_total_minutes >= 200 ? "live-traffic-gated" : routed.baseline_total_minutes >= 185 ? "near-cap" : "comfortable";
    return { ...plan, day_of_week: new Intl.DateTimeFormat("en-US", { weekday: "long", timeZone: "America/New_York" }).format(new Date(`${plan.date}T12:00:00-04:00`)), lodging: { preferred_area: plan.lodging[0], fallback_area: plan.lodging[1], room_setup: "Two rooms: one 1-bed room and one 2-bed room", notes: "Strong suggestion only; manually verify recent safety, cleanliness, two-car parking and exact bed layout." }, drive: { legs: routed.legs, baseline_total_miles: routed.baseline_total_miles, baseline_total_minutes: routed.baseline_total_minutes, planning_total_minutes: routed.planning_total_minutes, traffic_risk: routed.risk, cap_minutes: 210, cap_status: capStatus, fallback: plan.fallback }, schedule: plan.schedule.map((i) => scheduleItem(i, placeById)), weather: { kind: "historical_normal", high_c: normal.normal_high_c, low_c: normal.normal_low_c, precipitation_probability_percent: normal.measurable_precipitation_probability_percent, comfort_score: comfort[plan.day - 1], station_id: normal.station_id, station_name: normal.station_name, station_role: normal.station_role, source_id: "src-noaa-normals", forecast_status: "replace_with_live_forecast_10_days_before" } };
  });
  const knownCore = productionPlaces
    .filter((r) => r.included_in_magic_score && !r.categories.includes("social_nightlife_live"))
    .reduce((sum, r) => sum + (r.cost.amount_per_person || 0), 0);
  const route = {
    schema_version: "1.0.0",
    route: { id: ROUTE_ID, slug: ROUTE_SLUG.replace(/^route-05-/, ""), name: ROUTE_NAME, short_name: "Coal Veins & Blue Ridge", status: "researched", map_color: "#E11D48", timezone: "America/New_York", start_date: "2026-10-04", end_date: "2026-10-14", airport_date: "2026-10-15", origin: { name: lodgingNodes["boston-logan-rental"].name, coordinates: lodgingNodes["boston-logan-rental"].coordinates }, destination: { name: lodgingNodes["boston-logan-hotel"].name, coordinates: lodgingNodes["boston-logan-hotel"].coordinates }, endpoint_city: "Charlottesville, VA", direction: "Connecticut art and folk-faith opening into Pennsylvania's industrial spine, south through Harpers Ferry and Shenandoah; Frederick, Moravian Bethlehem and western Connecticut return", countries: ["US"], canada_included: false, total_nights: 11, road_nights: 10, final_boston_nights: 1, baseline_total_miles: geometry.route_baseline_total_miles, summary: "A warmer Appalachian loop that opens with a Gothic art castle and a handmade biblical hill, descends into an anthracite mine and caverns, then climbs through Harpers Ferry and Skyline Drive to a truth-centered Charlottesville art, history and live-music day. The return uses Orthodox Sunday, Civil War medicine, a Moravian farm, respectful institutional reuse and a stained-glass globe." },
    constraints: { travelers: 4, cars: 2, cars_follow_same_route: true, daily_drive_target_minutes: [120, 180], daily_drive_hard_cap_minutes: 210, max_big_nights_out: 4, planned_big_nights_out: 1, max_athletic_adrenaline_spots: 2, planned_athletic_adrenaline_spots: 1, hike_soft_cap_miles: 6, lodging_rooms: [{ count: 1, beds: 1 }, { count: 1, beds: 2 }], lodging_priorities: ["safe", "clean", "comfortable", "two-room inventory", "secure two-car parking"], visa_policy: "US-only; no Canada crossing or J-1 re-entry dependency.", budget_target_per_person_usd: 1500, budget_excludes: ["lodging", "rental cars", "fuel", "nightlife", "personal shopping"] },
    scoring: { scale: { min: 1, max: 5, increment: 0.5 }, equal_traveler_weight: true, traveler_ids: PEOPLE, route_component_weights_percent: { attraction_and_stop_ratings: 45, excitement_and_uniqueness: 20, driving_comfort: 15, traveler_fairness: 10, cost_and_value: 5, expected_weather: 5 }, route_ratings: Object.fromEntries(PEOPLE.map((p) => [p, null])), driving_comfort_ratings: Object.fromEntries(PEOPLE.map((p) => [p, null])), overall_excitement_ratings: Object.fromEntries(PEOPLE.map((p) => [p, null])), cost_value_ratings: Object.fromEntries(PEOPLE.map((p) => [p, null])), weather_ratings: Object.fromEntries(PEOPLE.map((p) => [p, null])), magic_score: null, magic_score_status: "awaiting_traveler_ratings", person_specific_route_scores: Object.fromEntries(PEOPLE.map((p) => [p, null])) },
    days, place_ids: productionPlaces.map((r) => r.id), core_place_ids: productionPlaces.filter((r) => r.included_in_magic_score).map((r) => r.id), alternative_place_ids: productionPlaces.filter((r) => !r.included_in_magic_score).map((r) => r.id), replacement_place_ids: productionPlaces.filter((r) => r.priority === "replacement").map((r) => r.id), replacement_options: replacements.variants.map((v) => ({ id: v.id, day: v.day, replacement_place_id: v.replacement_place_id, replaces_place_ids: v.replaces_place_ids, baseline_total_miles: v.baseline_total_miles, baseline_total_minutes: v.baseline_total_minutes, delta_miles: v.delta_miles, delta_minutes: v.delta_minutes, cap_minutes: v.cap_minutes, cap_status: v.cap_status })),
    budget: { known_core_admission_floor_per_person_usd: Math.round(knownCore * 100) / 100, core_admissions_range_per_person_usd: [300, 380], food_and_cafes_range_per_person_usd: [600, 850], local_parking_tolls_range_per_person_usd: [80, 160], controllable_total_range_per_person_usd: [980, 1390], nightlife_excluded_from_target: true, note: "The controllable-spend planning range stays below $1,500 without lodging, cars, fuel, nightlife, concert tickets or shopping. Premium tours and shopping can lift it." },
    booking_priorities: [
      { place_id: "morgan-wade-jefferson", urgency: "early", reason: "Exact Saturday show and four adjacent tickets." },
      { place_id: "monticello", urgency: "early", reason: "Reserve the specific From Slavery to Freedom product in the protected morning window." },
      { place_id: "transfiguration-orthodox", urgency: "reconfirm", reason: "Check the October parish calendar and visitor etiquette rather than treating normal Sunday hours as an event guarantee." },
      { place_id: "lackawanna-coal", urgency: "morning-of-live-eta", reason: "Arrive by 14:00 for the published last-tour rule; earlier is safer." },
      { place_id: "mapparium", urgency: "within-60-day-window", reason: "Reserve a 10:30-11:00 tour so car return remains protected." }
    ],
    validation: { date_count: days.length, expected_date_count: 11, all_baseline_drive_days_at_or_below_cap: days.every((d) => d.drive.baseline_total_minutes <= 210), live_traffic_gated_days: days.filter((d) => d.drive.cap_status === "live-traffic-gated").map((d) => d.day), place_count: productionPlaces.length, image_count: images.length, places_with_fewer_than_3_usable_images: productionPlaces.filter((r) => r.image_ids.length < 3).map((r) => r.id), replacement_option_count: replacements.variants.length, all_replacement_variants_at_or_below_cap: replacements.variants.every((v) => v.baseline_total_minutes <= v.cap_minutes), unfilled_place_ratings: productionPlaces.length * PEOPLE.length, hard_closures_or_conflicts: ["Central Market and Troll Market are deliberately placed on Tuesday; moving Lancaster to Wednesday breaks both.", "Jefferson School closes at 13:00 Saturday, so the Monticello product must finish on time.", "The Icon Museum in Clinton is closed Wednesday and was rejected from the return day.", "Burnside buildings are not promised on the Monday holiday; only dawn-dusk grounds are core.", "No OSRM baseline contains live traffic; days 9 and 10 must use live ETAs and cannot absorb central-Bethlehem or outlet detours."], route_lock_status: "research-complete-bookings-pending" }
  };
  const geojson = { type: "FeatureCollection", name: ROUTE_SLUG, features: [
    ...days.flatMap((d) => d.drive.legs.map((leg) => ({ type: "Feature", id: leg.id, properties: { feature_kind: "drive_leg", route_id: ROUTE_ID, day: d.day, date: d.date, from: leg.from, to: leg.to, distance_miles: leg.distance_miles, baseline_minutes: leg.baseline_minutes, map_color: route.route.map_color }, geometry: leg.geometry }))),
    ...replacements.variants.filter((v) => v.geometry).map((v) => ({ type: "Feature", id: v.id, properties: { feature_kind: "replacement_drive_variant", route_id: ROUTE_ID, day: v.day, replacement_place_id: v.replacement_place_id, replaces_place_ids: v.replaces_place_ids, baseline_total_miles: v.baseline_total_miles, baseline_total_minutes: v.baseline_total_minutes, delta_minutes: v.delta_minutes, cap_status: v.cap_status, map_color: route.route.map_color }, geometry: v.geometry })),
    ...productionPlaces.map((r) => ({ type: "Feature", id: r.id, properties: { feature_kind: "place", route_id: ROUTE_ID, place_id: r.id, name: r.name, city: r.city, state: r.state, visit_date: r.visit_date, priority: r.priority, included_in_magic_score: r.included_in_magic_score }, geometry: { type: "Point", coordinates: r.coordinates } })),
    ...Object.entries(geometry.nodes).map(([id, node]) => ({ type: "Feature", id: `node-${id}`, properties: { feature_kind: "route_node", route_id: ROUTE_ID, node_id: id, name: node.name }, geometry: { type: "Point", coordinates: node.coordinates } }))
  ] };
  const decisions = {
    schema_version: "1.0.0", route_id: ROUTE_ID, locked_at: verifiedAt,
    accepted: [
      { decision: "Charlottesville is the southern endpoint", reason: "It is the farthest point that still permits a US-only return under the daily cap with one complete Saturday city program." },
      { decision: "Open with Wadsworth and Holy Land, then sleep in Danbury", reason: "This unusual art-and-folk-faith pairing yields a 207-minute OSRM baseline and positions the Monday coal program at 194 minutes." },
      { decision: "Stage return at Burnside Bethlehem and Fairfield Hills Newtown", reason: "Their exact coordinates split Frederick-to-Boston into 207, 207 and 198-minute OSRM baselines while adding meaningful destination stops." },
      { decision: "One predefined night out", reason: "Morgan Wade at the Jefferson is exact-date, regional and rock-forward without consuming another recovery night." }
    ],
    rejected: [
      { option: "Opus 40 to Poughkeepsie opening", reason: "Boston-Opus-Poughkeepsie produced roughly five hours baseline driving." },
      { option: "Old New-Gate Prison and Copper Mine on day one", reason: "The exact Boston-Old New-Gate-Danbury sequence produced about 241 minutes; sleeping farther east then broke Monday's coal route. It is a strong place but not honest for this itinerary." },
      { option: "Staunton/Blue Ridge Tunnel/Frontier Culture extension", reason: "It forced multiple return legs above 210 minutes." },
      { option: "Charlottesville to Emmitsburg shrines to Harrisburg", reason: "The Sunday sequence approached five hours baseline." },
      { option: "Harrisburg to Middletown or New Paltz return", reason: "Both versions produced consecutive 3.75-4.6 hour baselines." },
      { option: "Icon Museum in Clinton on October 14", reason: "The museum is currently Thursday-Sunday and closed Wednesday." },
      { option: "Woodbury Common on October 13", reason: "The outlet detour pushed the exact bed-to-bed baseline above the hard cap; it is not silently hidden in a schedule." },
      { option: "Central Bethlehem/SteelStacks on October 12", reason: "Moving the lodging node east breaks the next day's cap; Burnside preserves both days." }
    ],
    traffic_policy: "OSRM baselines contain no traffic. Check live ETAs before departure; attractions never justify exceeding 210 active driving minutes. On days 9-10 there are no add-on detours.",
    image_policy: "Three local images are stored per place with creator, license and source metadata. Contextual images are labeled; permission-required images, if any, are private-prototype only."
  };
  await Promise.all([
    writeFile(path.join(ROUTE_DIR, "place-seed.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, places: seedPlaces }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "sources.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, verified_at: verifiedAt, sources }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "places.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, places: productionPlaces }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "images.json"), `${JSON.stringify({ schema_version: "1.0.0", route_id: ROUTE_ID, image_policy: "Downloaded Wikimedia Commons derivatives with per-file attribution; contextual coverage is labeled and each selected asset receives visual review.", images }, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "route.json"), `${JSON.stringify(route, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "route.geojson"), `${JSON.stringify(geojson, null, 2)}\n`),
    writeFile(path.join(ROUTE_DIR, "route-decisions.json"), `${JSON.stringify(decisions, null, 2)}\n`)
  ]);
  console.log(`Built ${ROUTE_NAME}: ${productionPlaces.length} places, ${images.length} images, ${days.length} days.`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
